import {notFound} from "next/navigation";
import {canManageBusiness} from "@/lib/access";
import {requireWorkspace} from "@/lib/workspace";
import {WorkspaceNav} from "../WorkspaceNav";
import {archiveRentalItem,createRentalItem,updateRentalItem} from "./actions";

const money=(cents:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(cents/100);
function Fields({item,categories=[],availableUpsells=[],relatedIds=[]}:{item?:any;categories?:string[];availableUpsells?:any[];relatedIds?:string[]}){return <div className="rental-inventory-form-grid"><label>Rental name<input required name="name" maxLength={120} defaultValue={item?.name??""} placeholder="Castle bounce house"/></label><label>Category<input name="category" maxLength={80} list="rental-categories" defaultValue={item?.category??""} placeholder="Bounce houses"/><datalist id="rental-categories">{categories.map(category=><option value={category} key={category}/>)}</datalist></label><label>Daily price<input required name="price" type="number" min="0" max="100000" step="0.01" defaultValue={item?(item.daily_price_cents/100).toFixed(2):""}/></label><label>Stock quantity<input required name="stockQuantity" type="number" min="1" max="10000" defaultValue={item?.stock_quantity??1}/></label><label>Rental image<input name="image" type="file" accept="image/jpeg,image/png,image/webp"/></label><label className="wide">Description<textarea name="description" rows={3} maxLength={2000} defaultValue={item?.description??""} placeholder="Size, capacity, included accessories, setup requirements…"/></label><label className="wide">Offer these items as add-ons<select name="relatedItemIds" multiple size={Math.min(6,Math.max(2,availableUpsells.length))} defaultValue={relatedIds}>{availableUpsells.map(option=><option value={option.id} key={option.id}>{option.name} · {money(option.daily_price_cents)}</option>)}</select><small>{availableUpsells.length?"Hold Ctrl (Windows) or Command (Mac) to select multiple items. Customers will see these before completing the booking.":"Add another active rental item before configuring an upsell."}</small></label><label className="rental-check"><input name="allowQuantity" type="checkbox" defaultChecked={item?.allow_quantity??false}/><span><strong>Allow customers to choose a quantity</strong><small>Use for chairs, tables, linens, and other items with shared stock.</small></span></label><label className="rental-check"><input name="active" type="checkbox" defaultChecked={item?.active??true}/><span><strong>Available for online booking</strong><small>Inactive rentals remain in history but are hidden from customers.</small></span></label></div>}

export default async function RentalInventoryPage({params,searchParams}:{params:Promise<{businessSlug:string}>;searchParams:Promise<{success?:string;error?:string}>}){
 const {businessSlug}=await params,q=await searchParams,{supabase,business,role}=await requireWorkspace(businessSlug);
 if(business.industry_profile!=="party_rental")notFound();
 const {data:items,error}=await supabase.from("inventory_items").select("id,name,category,description,daily_price_cents,image_url,allow_quantity,stock_quantity,active,created_at").eq("business_id",business.id).order("active",{ascending:false}).order("category").order("created_at",{ascending:false});
 const {data:upsells}=await supabase.from("rental_item_upsells").select("source_item_id,suggested_item_id").eq("business_id",business.id);
 const canEdit=canManageBusiness(role),active=items?.filter(item=>item.active)??[],units=active.reduce((sum,item)=>sum+item.stock_quantity,0),categories=[...new Set((items??[]).map(item=>item.category).filter((value):value is string=>Boolean(value)))],upsellsByItem=new Map((items??[]).map(item=>[item.id,(upsells??[]).filter(row=>row.source_item_id===item.id).map(row=>row.suggested_item_id)]));
 return <main className="epic3-shell"><WorkspaceNav slug={businessSlug} name={business.name} industry={business.industry_profile}/><section className="epic3-content rental-inventory-page">
  <header className="employee-page-header"><div><nav><span>Assets</span><b>›</b><span>Rental Inventory</span></nav><h1>Rental inventory</h1><p>Manage the rentals customers can select and reserve from your public website.</p></div>{canEdit&&<details className="rental-create"><summary className="sv-button">＋ Add rental item</summary><form action={createRentalItem.bind(null,businessSlug)}><Fields categories={categories} availableUpsells={active}/><div><button className="sv-button">Add rental item</button></div></form></details>}</header>
  {q.success&&<div className="workspace-notice success">{q.success}</div>}{q.error&&<div className="workspace-notice error">{q.error}</div>}{error&&<div className="workspace-notice error">Rental inventory could not be loaded. Apply the rental inventory migration first.</div>}
  <section className="equipment-metrics"><article><span>Active rentals</span><strong>{active.length}</strong><small>Visible for online booking</small></article><article><span>Categories</span><strong>{categories.length}</strong><small>Customer catalog groups</small></article><article><span>Total units</span><strong>{units}</strong><small>Available inventory capacity</small></article><article><span>Inactive</span><strong>{items?.filter(item=>!item.active).length??0}</strong><small>Hidden from customers</small></article></section>
  <section className="rental-admin-grid">{items?.map(item=><article className={`workspace-panel${item.active?"":" inactive"}`} key={item.id}><div className="rental-admin-image">{item.image_url?<img src={item.image_url} alt={item.name}/>:<span>Photo coming soon</span>}</div><header><div><span>{item.category||"Other rentals"} · {item.active?"Active":"Inactive"}</span><h2>{item.name}</h2></div><strong>{money(item.daily_price_cents)}</strong></header><p>{item.description||"No description added."}</p><dl><div><dt>Stock</dt><dd>{item.stock_quantity}</dd></div><div><dt>Customer quantity</dt><dd>{item.allow_quantity?"Selectable":"One per booking"}</dd></div></dl>{canEdit&&<details><summary>Edit rental</summary><form action={updateRentalItem.bind(null,businessSlug,item.id)}><Fields item={item} categories={categories} availableUpsells={active.filter(option=>option.id!==item.id)} relatedIds={upsellsByItem.get(item.id)??[]}/><div className="rental-form-actions"><button className="sv-button">Save changes</button>{item.active&&<button className="text-button danger" formAction={archiveRentalItem.bind(null,businessSlug,item.id)}>Deactivate</button>}</div></form></details>}</article>)}{!items?.length&&!error&&<div className="dashboard-empty"><strong>No rental items yet</strong><p>Add your first bounce house, table, chair package, concession machine, or party add-on.</p></div>}</section>
 </section></main>;
}
