import {notFound} from "next/navigation";
import {canManageBusiness} from "@/lib/access";
import {requireWorkspace} from "@/lib/workspace";
import {WorkspaceNav} from "../WorkspaceNav";
import {getSupabaseAdmin} from "@/lib/supabaseAdmin";
import {RentalInventoryFileFields} from "@/components/RentalInventoryFileFields";
import {archiveRentalItem,createRentalCategory,createRentalItem,deleteRentalCategory,updateRentalCategory,updateRentalItem} from "./actions";

const money=(cents:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(cents/100);
type RentalCategory={id:string;name:string;sort_order:number};
function Fields({item,categories=[],availableUpsells=[],relatedIds=[],receiptUrl}:{item?:any;categories?:RentalCategory[];availableUpsells?:any[];relatedIds?:string[];receiptUrl?:string}){return <div className="rental-inventory-form-grid"><label>Rental name<input required name="name" maxLength={120} defaultValue={item?.name??""} placeholder="Castle bounce house"/></label><label>Category<select name="categoryId" defaultValue={item?.category_id??""}><option value="">Uncategorized</option>{categories.map(category=><option value={category.id} key={category.id}>{category.name}</option>)}</select><small>Use Manage categories below to add or rename groups.</small></label><label>Daily rental price<input required name="price" type="number" min="0" max="100000" step="0.01" defaultValue={item?(item.daily_price_cents/100).toFixed(2):""}/><small>What the customer pays to rent it.</small></label><label>Purchase cost<input name="purchaseCost" type="number" min="0" max="10000000" step="0.01" defaultValue={item?.purchase_cost_cents!=null?(item.purchase_cost_cents/100).toFixed(2):""} placeholder="0.00"/><small>Internal only. Never shown to customers.</small></label><label>Stock quantity<input required name="stockQuantity" type="number" min="1" max="10000" defaultValue={item?.stock_quantity??1}/></label><RentalInventoryFileFields receiptUrl={receiptUrl} receiptName={item?.purchase_receipt_name}/><label className="wide">Description<textarea name="description" rows={3} maxLength={2000} defaultValue={item?.description??""} placeholder="Size, capacity, included accessories, setup requirements…"/></label><label className="wide">Offer these items as add-ons<select name="relatedItemIds" multiple size={Math.min(6,Math.max(2,availableUpsells.length))} defaultValue={relatedIds}>{availableUpsells.map(option=><option value={option.id} key={option.id}>{option.name} · {money(option.daily_price_cents)}</option>)}</select><small>{availableUpsells.length?"Hold Ctrl (Windows) or Command (Mac) to select multiple items. Customers will see these before completing the booking.":"Add another active rental item before configuring an upsell."}</small></label><label className="rental-check"><input name="allowQuantity" type="checkbox" defaultChecked={item?.allow_quantity??false}/><span><strong>Allow customers to choose a quantity</strong><small>Use for chairs, tables, linens, and other items with shared stock.</small></span></label><label className="rental-check"><input name="active" type="checkbox" defaultChecked={item?.active??true}/><span><strong>Available for online booking</strong><small>Inactive rentals remain in history but are hidden from customers.</small></span></label></div>}

export default async function RentalInventoryPage({params,searchParams}:{params:Promise<{businessSlug:string}>;searchParams:Promise<{success?:string;error?:string;sort?:string;direction?:string}>}){
 const {businessSlug}=await params,q=await searchParams,{supabase,business,role}=await requireWorkspace(businessSlug);
 if(business.industry_profile!=="party_rental")notFound();
 const [{data:items,error},{data:upsells},{data:categories, error:categoryError}]=await Promise.all([
  supabase.from("inventory_items").select("id,name,category,category_id,description,daily_price_cents,purchase_cost_cents,purchase_receipt_path,purchase_receipt_name,image_url,allow_quantity,stock_quantity,active,created_at").eq("business_id",business.id).order("active",{ascending:false}).order("category").order("created_at",{ascending:false}),
  supabase.from("rental_item_upsells").select("source_item_id,suggested_item_id").eq("business_id",business.id),
  supabase.from("rental_inventory_categories").select("id,name,sort_order").eq("business_id",business.id).order("sort_order").order("name"),
 ]);
 const admin=getSupabaseAdmin(),receiptUrls=new Map<string,string>();
 if(admin)await Promise.all((items??[]).filter(item=>item.purchase_receipt_path).map(async item=>{const {data}=await admin.storage.from("rental-purchase-receipts").createSignedUrl(item.purchase_receipt_path!,900);if(data?.signedUrl)receiptUrls.set(item.id,data.signedUrl);}));
 const categoryRows=(categories??[]) as RentalCategory[],canEdit=canManageBusiness(role),active=items?.filter(item=>item.active)??[],units=active.reduce((sum,item)=>sum+item.stock_quantity,0),upsellsByItem=new Map((items??[]).map(item=>[item.id,(upsells??[]).filter(row=>row.source_item_id===item.id).map(row=>row.suggested_item_id)]));
 const sort=["name","category","price","stock","status","newest"].includes(q.sort??"")?q.sort!:"name",direction=q.direction==="desc"?"desc":"asc",sign=direction==="asc"?1:-1;
 const sortedItems=[...(items??[])].sort((a,b)=>{const values=(item:typeof a):Record<string,string|number>=>({name:item.name.toLowerCase(),category:(item.category||"Other rentals").toLowerCase(),price:item.daily_price_cents,stock:item.stock_quantity,status:item.active?1:0,newest:new Date(item.created_at).getTime()});const left=values(a)[sort],right=values(b)[sort];return (typeof left==="string"&&typeof right==="string"?left.localeCompare(right):Number(left)-Number(right))*sign;});
 return <main className="epic3-shell"><WorkspaceNav slug={businessSlug} name={business.name} industry={business.industry_profile}/><section className="epic3-content rental-inventory-page">
  <header className="employee-page-header"><div><nav><span>Assets</span><b>›</b><span>Rental Inventory</span></nav><h1>Rental inventory</h1><p>Manage the rentals customers can select and reserve from your public website.</p></div>{canEdit&&<details className="rental-create"><summary className="sv-button">＋ Add rental item</summary><form action={createRentalItem.bind(null,businessSlug)}><Fields categories={categoryRows} availableUpsells={active}/><div><button className="sv-button">Add rental item</button></div></form></details>}</header>
  {q.success&&<div className="workspace-notice success">{q.success}</div>}{q.error&&<div className="workspace-notice error">{q.error}</div>}{(error||categoryError)&&<div className="workspace-notice error">Rental inventory could not be loaded. Apply the latest rental inventory migrations first.</div>}
  <section className="equipment-metrics"><article><span>Active rentals</span><strong>{active.length}</strong><small>Visible for online booking</small></article><article><span>Categories</span><strong>{categoryRows.length}</strong><small>Customer catalog groups</small></article><article><span>Total units</span><strong>{units}</strong><small>Available inventory capacity</small></article><article><span>Inactive</span><strong>{items?.filter(item=>!item.active).length??0}</strong><small>Hidden from customers</small></article></section>
  <form className="rental-admin-sort" method="get"><strong>Sort inventory</strong><label><span>Sort by</span><select name="sort" defaultValue={sort}><option value="name">Rental name</option><option value="category">Category</option><option value="price">Rental price</option><option value="stock">Stock quantity</option><option value="status">Active status</option><option value="newest">Date added</option></select></label><label><span>Direction</span><select name="direction" defaultValue={direction}><option value="asc">Ascending</option><option value="desc">Descending</option></select></label><button className="sv-button">Apply sort</button></form>
  {canEdit&&<details className="workspace-panel rental-category-manager"><summary><strong>Manage categories</strong><span>Create, rename, reorder, or delete rental categories.</span></summary><form action={createRentalCategory.bind(null,businessSlug)} className="rental-category-create"><label>New category<input name="name" required maxLength={80}/></label><label>Sort order<input name="sortOrder" type="number" defaultValue={0}/></label><button className="sv-button">Add category</button></form><div className="rental-category-list">{categoryRows.map(category=>{const attached=(items??[]).filter(item=>item.category_id===category.id).length,replacements=categoryRows.filter(item=>item.id!==category.id);return <article key={category.id}><form action={updateRentalCategory.bind(null,businessSlug,category.id)}><label>Name<input name="name" required defaultValue={category.name}/></label><label>Sort<input name="sortOrder" type="number" defaultValue={category.sort_order}/></label><span>{attached} item{attached===1?"":"s"}</span><button className="text-button">Save</button></form><form action={deleteRentalCategory.bind(null,businessSlug,category.id)}><label>Move attached items to<select name="replacementCategoryId" required={attached>0} defaultValue=""><option value="">{attached?"Choose replacement":"No replacement needed"}</option>{replacements.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><button className="text-button danger" disabled={attached>0&&!replacements.length}>Delete category</button></form>{attached>0&&!replacements.length&&<small>Create another category before deleting this one.</small>}</article>})}{!categoryRows.length&&<p>No categories yet. Create one to organize your rental catalog.</p>}</div></details>}
  <section className="rental-admin-grid">{sortedItems.map(item=><article className={`workspace-panel${item.active?"":" inactive"}`} key={item.id}><div className="rental-admin-image">{item.image_url?<img src={item.image_url} alt={item.name}/>:<span>Photo coming soon</span>}</div><header><div><span>{item.category||"Other rentals"} · {item.active?"Active":"Inactive"}</span><h2>{item.name}</h2></div><strong>{money(item.daily_price_cents)}</strong></header><p>{item.description||"No description added."}</p><dl><div><dt>Stock</dt><dd>{item.stock_quantity}</dd></div><div><dt>Purchase cost</dt><dd>{item.purchase_cost_cents==null?"Not recorded":money(item.purchase_cost_cents)}</dd></div><div><dt>Customer quantity</dt><dd>{item.allow_quantity?"Selectable":"One per booking"}</dd></div><div><dt>Receipt</dt><dd>{receiptUrls.has(item.id)?<a href={receiptUrls.get(item.id)} target="_blank" rel="noreferrer">View receipt</a>:"Not uploaded"}</dd></div></dl>{canEdit&&<details><summary>Edit rental</summary><form action={updateRentalItem.bind(null,businessSlug,item.id)}><Fields item={item} categories={categoryRows} availableUpsells={active.filter(option=>option.id!==item.id)} relatedIds={upsellsByItem.get(item.id)??[]} receiptUrl={receiptUrls.get(item.id)}/><div className="rental-form-actions"><button className="sv-button">Save changes</button>{item.active&&<button className="text-button danger" formAction={archiveRentalItem.bind(null,businessSlug,item.id)}>Deactivate</button>}</div></form></details>}</article>)}{!items?.length&&!error&&<div className="dashboard-empty"><strong>No rental items yet</strong><p>Add your first bounce house, table, chair package, concession machine, or party add-on.</p></div>}</section>
 </section></main>;
}
