import Link from "next/link";
import { notFound } from "next/navigation";
import OfflinePaymentForm from "@/components/OfflinePaymentForm";
import InvoicePaymentActions from "@/components/InvoicePaymentActions";
import PrintButton from "@/components/PrintButton";
import CopyLinkButton from "@/components/CopyLinkButton";
import { CustomerActionIcon } from "@/components/CustomerActionIcon";
import { canManageCustomers } from "@/lib/access";
import { formatCents } from "@/lib/financial/priceBook";
import { requireWorkspace } from "@/lib/workspace";
import { WorkspaceNav } from "../../WorkspaceNav";
import { duplicateInvoice,recordOfflinePayment,refundInvoicePayment,resendInvoice,sendInvoice,voidInvoice,voidOfflinePayment } from "../actions";

export default async function InvoiceDetail({params,searchParams}:{params:Promise<{businessSlug:string;invoiceId:string}>;searchParams:Promise<{success?:string;error?:string;publicLink?:string}>}){
  const {businessSlug,invoiceId}=await params,q=await searchParams,{supabase,business,role}=await requireWorkspace(businessSlug);
  const [{data:invoice},{data:lines},{data:fees},{data:payments},{data:events}]=await Promise.all([
    supabase.from("invoices").select("*,customers!invoices_customer_fk(id,first_name,last_name,company_name,email),service_locations!invoices_location_fk(location_name,street_address,city,state,postal_code),jobs!invoices_job_fk(id,job_number,title),estimates!invoices_estimate_fk(id,estimate_number)").eq("id",invoiceId).eq("business_id",business.id).eq("is_deleted",false).maybeSingle(),
    supabase.from("invoice_line_items").select("*").eq("invoice_id",invoiceId).eq("business_id",business.id).order("sort_order"),
    supabase.from("invoice_fees").select("*").eq("invoice_id",invoiceId).eq("business_id",business.id).order("sort_order"),
    supabase.from("payments").select("id,amount_cents,refunded_amount_cents,currency,payment_method_type,provider,status,received_at,paid_at,offline_reference,offline_notes,recorded_by,void_reason,voided_at,provider_receipt_url,created_at").eq("invoice_id",invoiceId).eq("business_id",business.id).order("created_at",{ascending:false}),
    supabase.from("invoice_events").select("id,event_type,metadata,created_at").eq("invoice_id",invoiceId).eq("business_id",business.id).order("created_at",{ascending:false}),
  ]);
  if(!invoice)notFound();
  const paymentIds=(payments??[]).map(payment=>payment.id);
  const {data:refunds}=paymentIds.length?await supabase.from("payment_refunds")
    .select("id,payment_id,amount_cents,status,refund_method,reason,offline_reference,requested_by,requested_at,completed_at,failure_message")
    .eq("business_id",business.id).in("payment_id",paymentIds).order("requested_at",{ascending:false}):{data:[]};
  const userIds=[...new Set([...(payments??[]).map(payment=>payment.recorded_by),...(refunds??[]).map(refund=>refund.requested_by)].filter(Boolean) as string[])];
  const {data:actors}=userIds.length?await supabase.from("employees").select("auth_user_id,preferred_name").eq("business_id",business.id).in("auth_user_id",userIds):{data:[]};
  const actorById=new Map((actors??[]).map(actor=>[actor.auth_user_id,actor.preferred_name]));
  const customer=Array.isArray(invoice.customers)?invoice.customers[0]:invoice.customers;
  const location=Array.isArray(invoice.service_locations)?invoice.service_locations[0]:invoice.service_locations;
  const job=Array.isArray(invoice.jobs)?invoice.jobs[0]:invoice.jobs;
  const estimate=Array.isArray(invoice.estimates)?invoice.estimates[0]:invoice.estimates;
  const canEdit=canManageCustomers(role),canPay=canEdit&&invoice.balance_due_cents>0&&!["draft","void","refunded"].includes(invoice.status);
  const customerName=customer?.company_name||`${customer?.first_name??""} ${customer?.last_name??""}`.trim()||"No customer";
  const netPaid=Number(invoice.amount_paid_cents)-Number(invoice.amount_refunded_cents);
  const formatDate=(value:string|null)=>value?new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`)):"—";
  return <main className="epic3-shell"><WorkspaceNav slug={businessSlug} name={business.name} industry={business.industry_profile}/><section className="epic3-content customer-record-page invoice-record-page">
    <header className="customer-record-header"><div><small><Link href={`/app/${businessSlug}/invoices`}>Invoices</Link> › {invoice.invoice_number}</small><h1>{invoice.title} <span className={`estimate-status ${invoice.status}`}>{invoice.status.replaceAll("_"," ")}</span></h1><p>{customerName} · Issued {formatDate(invoice.issue_date)}</p></div><div className="crm-header-actions">{customer?.email&&<a className="sv-button sv-secondary" href={`mailto:${customer.email}`}>Email</a>}{canEdit&&invoice.status==="draft"&&<Link className="sv-button" href={`/app/${businessSlug}/invoices/${invoiceId}/edit`}>Edit invoice</Link>}<PrintButton/></div></header>
    {q.error&&<div className="workspace-notice error">{q.error}</div>}{q.success&&<div className="workspace-notice success">{q.success}</div>}
    {q.publicLink&&<div className="estimate-public-link"><div><strong>Customer invoice link</strong><span>This secure link is shown once. Copy it now for customer delivery.</span></div><CopyLinkButton url={q.publicLink} label="Copy invoice link"/></div>}
    <section className="customer-record-metrics redesigned invoice-record-metrics"><article className="invoice-metric-status"><div><i><CustomerActionIcon name="check"/></i><span><small>Status</small><strong>{invoice.status.replaceAll("_"," ")}</strong></span></div><p>Current invoice stage</p></article><article className="next-service"><div><i><CustomerActionIcon name="calendar"/></i><span><small>Issued</small><strong>{formatDate(invoice.issue_date)}</strong></span></div><p>Invoice date</p></article><article className="last-service"><div><i><CustomerActionIcon name="clock"/></i><span><small>Due date</small><strong>{formatDate(invoice.due_date)}</strong></span></div><p>Payment deadline</p></article><article className="spent"><div><i><CustomerActionIcon name="chart"/></i><span><small>Total</small><strong>{formatCents(invoice.grand_total_cents,invoice.currency)}</strong></span></div><p>Invoice total</p></article><article className="invoice-metric-paid"><div><i><CustomerActionIcon name="card"/></i><span><small>Paid</small><strong>{formatCents(netPaid,invoice.currency)}</strong></span></div><p>Net payments received</p></article><article className="balance"><div><i><CustomerActionIcon name="card"/></i><span><small>Balance due</small><strong>{formatCents(invoice.balance_due_cents,invoice.currency)}</strong></span></div><p>Outstanding amount</p></article></section>
    <nav className="customer-record-tabs"><span>Overview</span><a href="#payments">Payments <b>{payments?.length??0}</b></a><a href="#activity">Activity <b>{events?.length??0}</b></a>{customer?.id&&<Link href={`/app/${businessSlug}/customers/${customer.id}`}>Customer</Link>}{job&&<Link href={`/app/${businessSlug}/jobs/${job.id}`}>Job</Link>}{estimate&&<Link href={`/app/${businessSlug}/estimates/${estimate.id}`}>Estimate</Link>}</nav>
    <div className="customer-record-columns"><div className="customer-record-main invoice-record-main"><section className="workspace-panel invoice-document-card"><div className="panel-title"><div><h2>Invoice details</h2><span>{invoice.invoice_number}</span></div>{canEdit&&invoice.status==="draft"&&<Link href={`/app/${businessSlug}/invoices/${invoiceId}/edit`}>Edit</Link>}</div><div className="estimate-document-head"><div><strong>{customerName}</strong><span>{customer?.email}</span>{location&&<span>{location.location_name}: {location.street_address}, {location.city}, {location.state} {location.postal_code}</span>}</div><div><span>Issued: {invoice.issue_date||"Not issued"}</span><span>Due: {invoice.due_date||"No due date"}</span>{estimate&&<Link href={`/app/${businessSlug}/estimates/${estimate.id}`}>From estimate {estimate.estimate_number}</Link>}{job&&<Link href={`/app/${businessSlug}/jobs/${job.id}`}>From job #{job.job_number}</Link>}</div></div>
      <div className="estimate-document-lines"><div className="head"><span>Item</span><span>Qty</span><span>Price</span><span>Total</span></div>{lines?.map(line=><div key={line.id}><span><strong>{line.name_snapshot}</strong><small>{line.description_snapshot}</small></span><span>{line.quantity} {line.unit_type_snapshot}</span><span>{formatCents(line.unit_price_cents,invoice.currency)}</span><span>{formatCents(line.line_total_cents,invoice.currency)}</span></div>)}</div>
      <dl className="estimate-totals"><div><dt>Subtotal</dt><dd>{formatCents(invoice.subtotal_cents,invoice.currency)}</dd></div><div><dt>Discount</dt><dd>−{formatCents(invoice.discount_total_cents,invoice.currency)}</dd></div><div><dt>Tax</dt><dd>{formatCents(invoice.tax_total_cents,invoice.currency)}</dd></div>{fees?.map(fee=><div key={fee.id}><dt>{fee.name_snapshot}</dt><dd>{formatCents(fee.amount_cents,invoice.currency)}</dd></div>)}<div className="total"><dt>Total</dt><dd>{formatCents(invoice.grand_total_cents,invoice.currency)}</dd></div><div><dt>Paid</dt><dd>{formatCents(invoice.amount_paid_cents-invoice.amount_refunded_cents,invoice.currency)}</dd></div><div className="total"><dt>Balance due</dt><dd>{formatCents(invoice.balance_due_cents,invoice.currency)}</dd></div></dl>
      {invoice.customer_notes&&<div className="estimate-message"><h3>Customer note</h3><p>{invoice.customer_notes}</p></div>}
    </section></div><aside className="customer-record-aside invoice-record-aside">
      {canEdit&&<section className="workspace-panel customer-side-card invoice-record-actions"><div className="panel-title"><h2>Invoice actions</h2><span className={`estimate-status ${invoice.status}`}>{invoice.status.replaceAll("_"," ")}</span></div>{invoice.status==="draft"&&<form action={sendInvoice.bind(null,businessSlug,invoiceId)}><button className="sv-button">Send invoice</button></form>}{["sent","viewed","partially_paid","overdue"].includes(invoice.status)&&<form action={resendInvoice.bind(null,businessSlug,invoiceId)}><button className="sv-button sv-secondary">Resend invoice</button></form>}<form action={duplicateInvoice.bind(null,businessSlug,invoiceId)}><button className="sv-button sv-secondary">Duplicate invoice</button></form>{!["void","paid","refunded"].includes(invoice.status)&&<details><summary>Void invoice</summary><form action={voidInvoice.bind(null,businessSlug,invoiceId)}><input required name="reason" maxLength={500} placeholder="Void reason"/><button className="sv-button sv-danger">Void invoice</button></form></details>}</section>}
      {canPay&&<section className="workspace-panel customer-side-card invoice-offline-payment"><div className="panel-title"><h2>Record payment</h2><span>{formatCents(invoice.balance_due_cents,invoice.currency)} due</span></div><p>Use “Other / deposit application” when applying funds collected outside Servonas.</p><OfflinePaymentForm action={recordOfflinePayment.bind(null,businessSlug,invoiceId)} balance={(invoice.balance_due_cents/100).toFixed(2)}/></section>}
      <section className="workspace-panel customer-side-card" id="payments"><div className="panel-title"><h2>Payment history</h2><span>{payments?.length??0} payments</span></div><div className="estimate-event-list payment-ledger">{payments?.length?payments.map(payment=>{
        const paymentRefunds=(refunds??[]).filter(refund=>refund.payment_id===payment.id);
        const refundable=Math.max(0,Number(payment.amount_cents)-Number(payment.refunded_amount_cents));
        return <div key={payment.id}><strong>{formatCents(payment.amount_cents,payment.currency)} · {(payment.payment_method_type||payment.provider).replaceAll("_"," ")}</strong><span>{payment.status.replaceAll("_"," ")} · {new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short",timeZone:business.timezone}).format(new Date(payment.received_at||payment.paid_at||payment.created_at))}</span>{payment.recorded_by&&<small>Received by {actorById.get(payment.recorded_by)||"authorized team member"}</small>}{payment.offline_reference&&<small>Reference: {payment.offline_reference}</small>}{payment.offline_notes&&<small>{payment.offline_notes}</small>}{payment.provider_receipt_url&&<a href={payment.provider_receipt_url} target="_blank" rel="noreferrer">View Stripe receipt</a>}{payment.void_reason&&<small>Void reason: {payment.void_reason}</small>}
          {paymentRefunds.map(refund=><article className={`payment-refund ${refund.status}`} key={refund.id}><strong>Refund {formatCents(refund.amount_cents,payment.currency)} · {refund.status.replaceAll("_"," ")}</strong><span>{refund.refund_method.replaceAll("_"," ")} · {new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short",timeZone:business.timezone}).format(new Date(refund.completed_at||refund.requested_at))}</span><small>Reason: {refund.reason}</small>{refund.requested_by&&<small>Requested by {actorById.get(refund.requested_by)||"authorized team member"}</small>}{refund.offline_reference&&<small>Reference: {refund.offline_reference}</small>}{refund.failure_message&&<small>Failure: {refund.failure_message}</small>}</article>)}
          {canEdit&&<InvoicePaymentActions payment={{provider:payment.provider,status:payment.status,refundableCents:refundable,currency:payment.currency}} refundAction={refundInvoicePayment.bind(null,businessSlug,invoiceId,payment.id)} voidAction={payment.provider==="offline"?voidOfflinePayment.bind(null,businessSlug,invoiceId,payment.id):undefined}/>}
        </div>;
      }):<p>No payments recorded.</p>}</div></section>
      <section className="workspace-panel customer-side-card"><div className="panel-title"><h2>Internal notes</h2></div><p>{invoice.internal_notes||"No internal notes."}</p></section>
      <section className="workspace-panel customer-side-card" id="activity"><div className="panel-title"><h2>Activity</h2><span>{events?.length??0} events</span></div><div className="estimate-event-list">{events?.map(event=><div key={event.id}><strong>{event.event_type.replaceAll("_"," ")}</strong><span>{new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short",timeZone:business.timezone}).format(new Date(event.created_at))}</span></div>)}</div></section>
    </aside></div>
  </section></main>;
}
