import {cookies} from "next/headers";
import {NextResponse} from "next/server";
import {createSupabaseServerClient} from "@/lib/supabaseServer";
import {getSupabaseAdmin} from "@/lib/supabaseAdmin";
import {exchangeGoogleBusinessCode,listGoogleBusinessLocations} from "@/lib/googleBusinessProfile";

const destination=(slug:string,kind:"success"|"error",message:string)=>new URL(`/app/${encodeURIComponent(slug)}/settings/website?${kind}=${encodeURIComponent(message)}`,process.env.NEXT_PUBLIC_APP_URL||"https://servonas.com");
export async function GET(request:Request){
 const url=new URL(request.url),code=url.searchParams.get("code"),state=url.searchParams.get("state"),store=await cookies(),raw=store.get("servonas_google_business_oauth")?.value;store.delete("servonas_google_business_oauth");let saved:{state:string;businessSlug:string;businessId:string}|null=null;try{saved=raw?JSON.parse(raw):null;}catch{}
 if(!saved||!state||state!==saved.state||!code)return NextResponse.redirect(destination(saved?.businessSlug||"","error","Google authorization could not be verified."));
 const supabase=await createSupabaseServerClient(),{data:{user}}=await supabase.auth.getUser(),{data:membership}=user?await supabase.from("business_members").select("role").eq("business_id",saved.businessId).eq("user_id",user.id).maybeSingle():{data:null};if(!user||!membership||!["owner","admin"].includes(membership.role))return NextResponse.redirect(destination(saved.businessSlug,"error","Google authorization is not permitted for this workspace."));
 try{const token=await exchangeGoogleBusinessCode(code);if(!token.refresh_token)throw new Error("Google did not provide long-term access. Remove Servonas from Google account permissions and connect again.");const locations=await listGoogleBusinessLocations(token.access_token!),db=getSupabaseAdmin();if(!db)throw new Error("Google connection storage is unavailable.");const {data:business}=await db.from("businesses").select("name").eq("id",saved.businessId).maybeSingle(),wanted=business?.name.trim().toLowerCase(),matches=locations.filter(location=>location.title.trim().toLowerCase()===wanted),location=matches.length===1?matches[0]:locations.length===1?locations[0]:null;if(!location)throw new Error(locations.length?"Google returned multiple profiles and none uniquely matched this Servonas business name.":"No Google Business Profile was found for this account.");const {error}=await db.from("business_google_profile_connections").upsert({business_id:saved.businessId,connected_by:user.id,refresh_token:token.refresh_token,google_account_id:location.accountId,google_location_id:location.locationId,location_title:location.title,status:"connected",connected_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"business_id"});if(error)throw new Error("Google connection could not be saved. Apply the Google Business Profile migration.");return NextResponse.redirect(destination(saved.businessSlug,"success",`Google Business Profile connected: ${location.title}`));}catch(error){return NextResponse.redirect(destination(saved.businessSlug,"error",error instanceof Error?error.message:"Google Business Profile connection failed."));}
}
