import {getSupabaseAdmin} from "../supabaseAdmin.ts";
import {getSubaccountTwilioHttpClient} from "./twilioHttp.ts";
import {getSubaccountWebhookSecretResolver} from "./subaccountWebhookSecrets.ts";
import {resolveTenantOutboundSender} from "./tenantOutboundSender.ts";
import {calculateMessagingPeriod,nextMonth,shouldAdvanceMessageStatus,usageCanFinalize,utcBillingPeriod,type BillableUsage} from "./usageMath.ts";

type UsageCapture={businessId:string;accountSid:string;messageSid:string;direction:string;status:string;from?:string|null;to?:string|null;numSegments?:number|null;numMedia?:number|null;price?:number|string|null;priceUnit?:string|null;errorCode?:string|null;messagingServiceSid?:string|null;phoneNumberSid?:string|null;occurredAt?:string;sourceType?:string|null;sourceId?:string|null;providerDateCreated?:string|null;providerDateSent?:string|null;providerDateUpdated?:string|null;providerSyncedAt?:string|null};
type TwilioMessage={sid:string;account_sid:string;direction:string;status:string;from:string|null;to:string|null;num_segments:string|null;num_media:string|null;price:string|null;price_unit:string|null;error_code:number|string|null;messaging_service_sid:string|null;date_created:string|null;date_sent:string|null;date_updated:string|null};
const number=(value:unknown)=>value===null||value===undefined||value===""?null:Number.isFinite(Number(value))?Number(value):null;
const iso=(value:string|null|undefined)=>value&&!Number.isNaN(Date.parse(value))?new Date(value).toISOString():null;
const retryAt=(attempts:number)=>new Date(Date.now()+Math.min(86_400_000,Math.max(60_000,2**Math.min(attempts,10)*60_000))).toISOString();

async function accountForBusiness(businessId:string,accountSid:string){const db=getSupabaseAdmin();if(!db)return null;const {data}=await db.from("business_twilio_accounts").select("id,business_id,twilio_subaccount_sid").eq("business_id",businessId).eq("twilio_subaccount_sid",accountSid).eq("provisioning_status","active").maybeSingle();return data;}
async function phoneSid(businessId:string,direction:string,from?:string|null,to?:string|null){const db=getSupabaseAdmin();if(!db)return null;const numberValue=direction==="inbound"?to:from;if(!numberValue)return null;const {data}=await db.from("twilio_phone_numbers").select("twilio_phone_number_sid").eq("business_id",businessId).eq("phone_number_e164",numberValue).eq("status","active").maybeSingle();return data?.twilio_phone_number_sid??null;}

export async function recordTenantMessageUsage(input:UsageCapture){
 const db=getSupabaseAdmin();if(!db)throw new Error("Twilio usage storage is unavailable.");
 const account=await accountForBusiness(input.businessId,input.accountSid);if(!account)throw new Error("Tenant Twilio account is unavailable.");
 const occurred=input.occurredAt??new Date().toISOString(),segments=input.numSegments??null,media=input.numMedia??null,price=number(input.price),priceUnit=input.priceUnit?.toUpperCase()??null;
 const {data:existing}=await db.from("twilio_message_usage").select("id,message_status,num_segments,num_media,twilio_price,twilio_price_unit,usage_finalized_at,reconciliation_attempts,accepted_at,sent_at,delivered_at,failed_at,received_at").eq("twilio_account_sid",input.accountSid).eq("twilio_message_sid",input.messageSid).maybeSingle();
 const advances=shouldAdvanceMessageStatus(existing?.message_status,input.status),status=advances?input.status:existing?.message_status??input.status;
 const final=usageCanFinalize({status,numSegments:segments??existing?.num_segments??null,numMedia:media??existing?.num_media??null,price:price??number(existing?.twilio_price),priceUnit:priceUnit??existing?.twilio_price_unit??null});
 const values={business_id:input.businessId,business_twilio_account_id:account.id,twilio_account_sid:input.accountSid,twilio_message_sid:input.messageSid,direction:input.direction,channel:(media??existing?.num_media??0)>0?"mms":"sms",from_phone_e164:input.from??null,to_phone_e164:input.to??null,num_segments:segments,num_media:media,message_status:status,accepted_at:input.direction==="inbound"?null:existing?.accepted_at??iso(input.providerDateCreated)??occurred,sent_at:["sent","delivered","undelivered","read"].includes(status)?iso(input.providerDateSent)??existing?.sent_at??occurred:null,delivered_at:["delivered","read"].includes(status)?existing?.delivered_at??occurred:null,failed_at:["failed","undelivered"].includes(status)?existing?.failed_at??occurred:null,received_at:input.direction==="inbound"?existing?.received_at??iso(input.providerDateCreated)??occurred:null,provider_date_created:iso(input.providerDateCreated),provider_date_updated:iso(input.providerDateUpdated),twilio_price:price,twilio_price_unit:priceUnit,provider_error_code:advances?input.errorCode??null:null,messaging_service_sid:input.messagingServiceSid??null,phone_number_sid:input.phoneNumberSid??await phoneSid(input.businessId,input.direction,input.from,input.to),billing_period_start:utcBillingPeriod(occurred),source_type:input.sourceType??null,source_id:input.sourceId??null,usage_finalized_at:final?(existing?.usage_finalized_at??new Date().toISOString()):null,last_provider_sync_at:iso(input.providerSyncedAt),next_reconciliation_at:final?new Date("9999-12-31T00:00:00Z").toISOString():new Date().toISOString(),updated_at:new Date().toISOString()};
 if(existing){const {error}=await db.from("twilio_message_usage").update(Object.fromEntries(Object.entries(values).filter(([,value])=>value!==null))).eq("id",existing.id).eq("business_id",input.businessId);if(error)throw new Error("Twilio usage could not be updated.");return existing.id;}
 const {data,error}=await db.from("twilio_message_usage").insert(values).select("id").single();if(error){if(error.code==="23505")return recordTenantMessageUsage(input);throw new Error("Twilio usage could not be recorded.");}return data.id;
}

export async function recordTenantStatusCallback(input:{businessId:string;accountSid:string;messageSid:string;status:string;errorCode?:string|null}){
 return recordTenantMessageUsage({businessId:input.businessId,accountSid:input.accountSid,messageSid:input.messageSid,direction:"outbound-api",status:input.status,errorCode:input.errorCode??null,sourceType:"status_callback"});
}

export async function sendTenantTwilioMessage(input:{businessId:string;to:string;body:string;sourceType:string;sourceId:string}){
 const sender=await resolveTenantOutboundSender(input.businessId);if(!sender.configured||sender.mode!=="messaging_service"||!sender.accountSid||!sender.username||!sender.password||!sender.messagingServiceSid)throw new Error("Tenant Twilio sender is not active.");
 const origin=(process.env.NEXT_PUBLIC_SITE_URL||process.env.NEXT_PUBLIC_APP_URL||"https://servonas.com").replace(/\/$/,"");
 const response=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${sender.accountSid}/Messages.json`,{method:"POST",headers:{Authorization:`Basic ${Buffer.from(`${sender.username}:${sender.password}`).toString("base64")}`,"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({To:input.to,MessagingServiceSid:sender.messagingServiceSid,Body:input.body,StatusCallback:`${origin}/api/twilio/tenant-message-status`})});
 const message=await response.json() as Partial<TwilioMessage>&{message?:string};if(!response.ok||!message.sid)throw new Error("Twilio rejected the tenant message.");
 await recordTenantMessageUsage({businessId:input.businessId,accountSid:sender.accountSid,messageSid:message.sid,direction:message.direction??"outbound-api",status:message.status??"accepted",from:message.from,to:message.to??input.to,numSegments:number(message.num_segments),numMedia:number(message.num_media),price:message.price,priceUnit:message.price_unit,messagingServiceSid:message.messaging_service_sid??sender.messagingServiceSid,occurredAt:iso(message.date_sent)??new Date().toISOString(),sourceType:input.sourceType,sourceId:input.sourceId,providerDateCreated:message.date_created,providerDateSent:message.date_sent,providerDateUpdated:message.date_updated});return{sid:message.sid};
}

export async function reconcileTenantMessageUsage(limit=100){
 const db=getSupabaseAdmin();if(!db)return{processed:0,finalized:0,failed:0};const now=new Date().toISOString();
 const {data:rows}=await db.from("twilio_message_usage").select("id,business_id,twilio_account_sid,twilio_message_sid,reconciliation_attempts").is("usage_finalized_at",null).lte("next_reconciliation_at",now).order("created_at").limit(Math.min(Math.max(limit,1),500));let processed=0,finalized=0,failed=0;
 for(const row of rows??[]){processed++;try{const token=await getSubaccountWebhookSecretResolver().getSubaccountAuthToken({businessId:row.business_id,subaccountSid:row.twilio_account_sid});if(!token)throw new Error("credential_unavailable");const client=getSubaccountTwilioHttpClient(row.twilio_account_sid,token),message=await client.request<TwilioMessage>(`https://api.twilio.com/2010-04-01/Accounts/${encodeURIComponent(row.twilio_account_sid)}/Messages/${encodeURIComponent(row.twilio_message_sid)}.json`);await recordTenantMessageUsage({businessId:row.business_id,accountSid:row.twilio_account_sid,messageSid:row.twilio_message_sid,direction:message.direction,status:message.status,from:message.from,to:message.to,numSegments:number(message.num_segments),numMedia:number(message.num_media),price:message.price,priceUnit:message.price_unit,errorCode:message.error_code===null?null:String(message.error_code),messagingServiceSid:message.messaging_service_sid,occurredAt:iso(message.date_sent)??iso(message.date_created)??now,providerDateCreated:message.date_created,providerDateSent:message.date_sent,providerDateUpdated:message.date_updated,providerSyncedAt:now});const {data:after}=await db.from("twilio_message_usage").select("usage_finalized_at").eq("id",row.id).single();if(after?.usage_finalized_at)finalized++;else await db.from("twilio_message_usage").update({reconciliation_attempts:row.reconciliation_attempts+1,next_reconciliation_at:retryAt(row.reconciliation_attempts+1),last_provider_sync_at:now,updated_at:now}).eq("id",row.id);}catch{failed++;await db.from("twilio_message_usage").update({reconciliation_attempts:row.reconciliation_attempts+1,next_reconciliation_at:retryAt(row.reconciliation_attempts+1),last_provider_sync_at:now,updated_at:now}).eq("id",row.id);}}
 return{processed,finalized,failed};
}

async function planForBusiness(businessId:string){const db=getSupabaseAdmin();if(!db)throw new Error("Messaging billing storage is unavailable.");const {data:subscription}=await db.from("business_platform_subscriptions").select("stripe_price_id").eq("business_id",businessId).maybeSingle();if(subscription?.stripe_price_id){const {data:plan}=await db.from("messaging_usage_plan_configs").select("plan_key,included_outbound_sms_segments").eq("stripe_price_id",subscription.stripe_price_id).eq("active",true).maybeSingle();if(plan)return plan;}const {data:fallback}=await db.from("messaging_usage_plan_configs").select("plan_key,included_outbound_sms_segments").eq("plan_key","default").single();return fallback??{plan_key:"default",included_outbound_sms_segments:0};}
export async function getMessagingPeriodReport(businessId:string,periodStart:string){const db=getSupabaseAdmin();if(!db)throw new Error("Messaging billing storage is unavailable.");const {data:business}=await db.from("businesses").select("id,name").eq("id",businessId).eq("is_deleted",false).maybeSingle();if(!business)throw new Error("Business not found.");const plan=await planForBusiness(businessId),periodEnd=nextMonth(periodStart),[{data:rows,error},{data:billingPeriod}]=await Promise.all([db.from("twilio_message_usage").select("direction,channel,num_segments,usage_finalized_at,twilio_price,twilio_price_unit,message_status,twilio_message_sid,num_media,sent_at,delivered_at,received_at,provider_error_code,messaging_service_sid,phone_number_sid").eq("business_id",businessId).eq("billing_period_start",periodStart).order("created_at"),db.from("business_messaging_billing_periods").select("*").eq("business_id",businessId).eq("period_start",periodStart).maybeSingle()]);if(error)throw new Error("Messaging usage report is unavailable.");const totals=calculateMessagingPeriod((rows??[]) as BillableUsage[],Number(plan.included_outbound_sms_segments));return{business:{id:business.id,name:business.name},periodStart,periodEnd,planKey:plan.plan_key,...totals,billingPeriod:billingPeriod??null,messages:rows??[]};}
export async function calculateMessagingBillingPeriod(businessId:string,periodStart:string,finalize=false){const db=getSupabaseAdmin();if(!db)throw new Error("Messaging billing storage is unavailable.");const {data:existing}=await db.from("business_messaging_billing_periods").select("*").eq("business_id",businessId).eq("period_start",periodStart).maybeSingle();if(existing?.status==="finalized")return existing;const report=await getMessagingPeriodReport(businessId,periodStart),closed=report.periodEnd<=new Date().toISOString().slice(0,10),canFinalize=finalize&&closed&&report.unfinalizedMessageCount===0,now=new Date().toISOString(),values={business_id:businessId,period_start:periodStart,period_end:report.periodEnd,plan_key:report.planKey,included_units:report.includedUnits,billable_units:report.billableUnits,overage_units:report.overageUnits,provider_cost:report.providerCost,provider_cost_currency:report.providerCostCurrency,unfinalized_message_count:report.unfinalizedMessageCount,status:canFinalize?"finalized":"calculated",calculated_at:now,finalized_at:canFinalize?now:null,updated_at:now};if(existing){const {data,error}=await db.from("business_messaging_billing_periods").update(values).eq("id",existing.id).neq("status","finalized").select("*").maybeSingle();if(error)throw new Error("Messaging billing period could not be calculated.");if(data)return data;const {data:finalized}=await db.from("business_messaging_billing_periods").select("*").eq("id",existing.id).single();return finalized;}const {data,error}=await db.from("business_messaging_billing_periods").insert(values).select("*").single();if(error?.code==="23505")return calculateMessagingBillingPeriod(businessId,periodStart,finalize);if(error)throw new Error("Messaging billing period could not be calculated.");return data;}
export async function calculateClosedMessagingPeriods(){const db=getSupabaseAdmin();if(!db)return{processed:0,finalized:0};const current=utcBillingPeriod(new Date()),previousDate=new Date(`${current}T00:00:00Z`);previousDate.setUTCMonth(previousDate.getUTCMonth()-1);const period=previousDate.toISOString().slice(0,10),{data:accounts}=await db.from("business_twilio_accounts").select("business_id").eq("provisioning_status","active");let processed=0,finalized=0;for(const account of accounts??[]){const result=await calculateMessagingBillingPeriod(account.business_id,period,true);processed++;if(result.status==="finalized")finalized++;}return{processed,finalized};}
