import type {Metadata} from "next";
import Image from "next/image";
import Link from "next/link";
export const metadata:Metadata={title:"Free Car Detailing Website | Servonas",description:"We'll build your car detailing website for free. Get online booking, scheduling, customers, invoices, payments and more with Servonas.",keywords:["car detailing website design","auto detailing website","mobile detailing website","website for detailing business","car detailing web design","detailing business website","ceramic coating website"],alternates:{canonical:"/car-detailing-website"}};
const attributionKeys=["utm_source","utm_medium","utm_campaign","utm_content","utm_term","gclid","gbraid","wbraid"] as const;
const route=(base:string,params:Record<string,string|string[]|undefined>,source=false)=>{const query=new URLSearchParams(source?{source:"car-detailing-website"}:{});for(const key of attributionKeys){const raw=params[key],value=Array.isArray(raw)?raw[0]:raw;if(value)query.set(key,value.slice(0,500));}return `${base}${query.size?`?${query}`:""}`;};
const included=[["Professional detailing website","A polished site built around your packages, brand, and service area."],["Mobile-friendly design","A premium experience that looks sharp on every screen."],["Online booking","Let customers choose a service and request a convenient time."],["Service package selection","Present interior, exterior, coating, and maintenance packages clearly."],["Customer management","Keep vehicle owners, contact details, and history organized."],["Scheduling","Manage upcoming details from one calendar."],["Estimates and invoices","Price custom work and invoice completed appointments."],["Online payments","Accept secure card payments after connecting Stripe."],["Customer texting","Keep customers informed with Servonas messaging tools."],["Job management","Track every detail from booking through completion."]];
export default async function CarDetailingWebsite({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const params=await searchParams,signup=route("/signup",params,true),demo=route("/demo/car-detailing",params);return <main className="pcw-page detailing-landing">
 <section className="pcw-hero detailing-hero"><div className="sv-container pcw-hero-grid"><div className="pcw-hero-copy"><span className="sv-kicker">Websites for detailing businesses</span><h1>We&apos;ll Build Your Car Detailing Website. <span>Free.</span></h1><p>Get a professional website built for your detailing business, plus online booking, customers, scheduling, invoices, payments, and more.</p><div className="sv-actions"><Link className="sv-button pcw-primary" href={signup}>Build My Free Website →</Link><Link className="sv-button sv-secondary" href={demo}>View Example Website</Link></div><div className="pcw-hero-proof"><span>✓ Built for detailing businesses</span><span>✓ Mobile friendly</span><span>✓ No existing website needed</span><span>✓ Online booking included</span></div></div><div className="pcw-hero-visual"><div className="pcw-photo"><Image src="/images/car-detailing-professional-polishing.png" alt="Professional auto detailer polishing a glossy vehicle" fill priority sizes="(max-width: 900px) 100vw, 46vw"/></div><div className="pcw-site-preview"><span>YOUR NEW DETAILING WEBSITE</span><strong>Premium presentation. Easy booking.</strong><small>Showcase packages and turn visitors into appointments.</small></div><div className="pcw-free-badge"><b>FREE</b><span>pilot website build</span></div></div></div></section>
 <section className="pcw-pilot"><div className="sv-container"><span>★</span><div><h2>A limited Servonas pilot offer</h2><p>We&apos;re looking for a limited number of car detailing businesses to join the Servonas pilot. We&apos;ll build your website at no cost and give you access to the tools that help run your business.</p></div></div></section>
 <section className="sv-section pcw-included"><div className="sv-container"><header className="sv-heading"><span className="sv-kicker">More than a static website</span><h2>Everything your detailing business needs to get online and organized.</h2><p>Your website attracts the booking. Servonas helps manage everything that follows.</p></header><div className="pcw-included-grid">{included.map(([title,body],index)=><article key={title}><i>{String(index+1).padStart(2,"0")}</i><div><h3>{title}</h3><p>{body}</p></div></article>)}</div></div></section>
 <section className="pcw-how"><div className="sv-container"><header className="sv-heading"><span className="sv-kicker">How it works</span><h2>From your business details to booking cars in three steps.</h2></header><ol>{[["01","Tell Us About Your Detailing Business","Share the basics and choose packages like interior, exterior, ceramic coating, or paint correction."],["02","We Build Your Website","Servonas prepares a professional website using your business information and selected style."],["03","Start Booking Details","Customers can request a service while you manage the appointment, customer, job, invoice, and payment."]].map(([n,title,body])=><li key={n}><span>{n}</span><h3>{title}</h3><p>{body}</p></li>)}</ol></div></section>
 <section className="pcw-connected"><div className="sv-container pcw-connected-grid"><div><span className="sv-kicker">Website meets workflow</span><h2>Your Website Should Book Cars, Not Just Look Good</h2><p>Most traditional websites stop at showing information. A Servonas-powered detailing site connects service selection and booking to the business workflow you use every day.</p></div><div className="pcw-flow"><div><i>1</i><span><strong>Customer selects a package</strong><small>Interior, exterior, coating, correction, or maintenance</small></span></div><b>↓</b><div><i>2</i><span><strong>They request a date and time</strong><small>Contact and service details enter Servonas</small></span></div><b>↓</b><div><i>3</i><span><strong>You manage the detail</strong><small>Schedule, complete, invoice, and collect</small></span></div></div></div></section>
 <section className="pcw-demo-callout detailing-demo-callout"><div className="sv-container"><div className="pcw-demo-browser"><header><i/><i/><i/><span>apexautodetail.example</span></header><div><span>APEX AUTO DETAIL</span><h2>Your Car Deserves More Than a Wash</h2><p>See the premium website experience Servonas can create for a detailing business.</p></div></div><div><span className="sv-kicker">See what we can build for you</span><h2>Preview an example car detailing website built with Servonas.</h2><p>Explore its packages, transformation story, trust sections, and safe demonstration booking experience.</p><Link className="sv-button" href={demo}>View Example Website</Link></div></div></section>
 <section className="sv-section pcw-audience"><div className="sv-container"><header className="sv-heading"><span className="sv-kicker">Built for independent detailers</span><h2>Made for the way small detailing businesses actually book.</h2><p>Ideal for mobile detailers, owner-operated shops, ceramic coating businesses, paint correction specialists, and teams currently booking through texts, social media, or calls.</p></header><div><span>Mobile detailers</span><span>Owner-operated shops</span><span>Ceramic coating</span><span>Paint correction</span><span>New detailing businesses</span></div></div></section>
 <section className="pcw-faq"><div className="sv-container"><header className="sv-heading"><span className="sv-kicker">Frequently asked questions</span><h2>What to know before you start.</h2></header><div className="pcw-faq-list"><details><summary>Is the website really free?</summary><p>Servonas is currently offering website creation at no cost to selected detailing businesses participating in the limited pilot.</p></details><details><summary>Do I need an existing website?</summary><p>No. You can create your business presence through Servonas without an existing site.</p></details><details><summary>Can customers book detailing services online?</summary><p>Yes. You can enable Servonas online booking and choose the services and availability you want customers to see.</p></details><details><summary>Can I list different detailing packages?</summary><p>Yes. Existing Servonas service records can represent your detailing packages, descriptions, durations, and pricing.</p></details><details><summary>Can I use my own domain?</summary><p>Yes. Servonas supports connecting a domain you own using the supplied DNS records and automatic HTTPS after verification.</p></details><details><summary>What happens when someone books?</summary><p>The booking and customer information becomes available in Servonas so you can schedule the work, manage the customer, complete the job, invoice, and collect payment.</p></details><details><summary>Does this work for mobile detailers?</summary><p>Yes. You can define your service area, collect the customer&apos;s address, manage appointments, and use Servonas scheduling for mobile work.</p></details></div></div></section>
 <section className="home-final-cta pcw-final"><div className="sv-container"><div><span className="sv-kicker">Limited pilot availability</span><h2>Ready to Get Your Detailing Business Online?</h2><p>We&apos;ll build your website for free and give you the tools to manage bookings, customers, jobs, invoices and payments.</p></div><Link className="sv-button sv-light" href={signup}>Build My Free Website</Link></div></section>
 </main>}
