-- Servonas Epic 4: generalized jobs/work orders.
create extension if not exists "pgcrypto";

create table if not exists public.jobs (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  customer_id uuid references public.customers(id) on delete set null,
  job_number bigint generated by default as identity,
  title text not null,
  status text not null default 'draft' check (status in ('draft','pending','confirmed','in_progress','completed','canceled')),
  starts_at timestamptz,
  ends_at timestamptz,
  service_address text,
  description text,
  internal_notes text,
  subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
  tax_amount numeric(12,2) not null default 0 check (tax_amount >= 0),
  total_amount numeric(12,2) generated always as (subtotal + tax_amount) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  is_deleted boolean not null default false,
  check (ends_at is null or starts_at is null or ends_at >= starts_at)
);

create index if not exists jobs_business_start_idx on public.jobs(business_id, starts_at);
create index if not exists jobs_business_status_idx on public.jobs(business_id, status) where is_deleted = false;
create index if not exists jobs_customer_idx on public.jobs(customer_id);

create table if not exists public.job_status_history (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  job_id uuid not null references public.jobs(id) on delete cascade,
  from_status text,
  to_status text not null,
  changed_by uuid references auth.users(id) on delete set null,
  changed_at timestamptz not null default now()
);
create index if not exists job_status_history_job_idx on public.job_status_history(job_id, changed_at desc);

alter table public.jobs enable row level security;
alter table public.job_status_history enable row level security;

drop policy if exists "members can view jobs" on public.jobs;
create policy "members can view jobs" on public.jobs for select to authenticated
  using (public.is_business_member(business_id));

drop policy if exists "managers can create jobs" on public.jobs;
create policy "managers can create jobs" on public.jobs for insert to authenticated
  with check (public.has_business_role(business_id,array['owner','admin','manager']) and created_by=auth.uid());

drop policy if exists "managers can update jobs" on public.jobs;
create policy "managers can update jobs" on public.jobs for update to authenticated
  using (public.has_business_role(business_id,array['owner','admin','manager']))
  with check (public.has_business_role(business_id,array['owner','admin','manager']));

drop policy if exists "members can view job history" on public.job_status_history;
create policy "members can view job history" on public.job_status_history for select to authenticated
  using (public.is_business_member(business_id));

create or replace function public.log_job_changes() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  if tg_op='INSERT' then
    insert into public.business_activity(business_id,actor_user_id,action,entity_type,entity_id,summary)
    values(new.business_id,auth.uid(),'insert','job',new.id,'Job created: '||new.title);
    insert into public.job_status_history(business_id,job_id,from_status,to_status,changed_by)
    values(new.business_id,new.id,null,new.status,auth.uid());
  elsif tg_op='UPDATE' then
    if new.status is distinct from old.status then
      insert into public.job_status_history(business_id,job_id,from_status,to_status,changed_by)
      values(new.business_id,new.id,old.status,new.status,auth.uid());
    end if;
    insert into public.business_activity(business_id,actor_user_id,action,entity_type,entity_id,summary)
    values(new.business_id,auth.uid(),'update','job',new.id,
      case when new.is_deleted and not old.is_deleted then 'Job archived: '||new.title
           when new.status is distinct from old.status then 'Job status changed to '||replace(new.status,'_',' ')||': '||new.title
           else 'Job updated: '||new.title end);
  end if;
  return new;
end; $$;

drop trigger if exists jobs_activity_trigger on public.jobs;
create trigger jobs_activity_trigger after insert or update on public.jobs
for each row execute function public.log_job_changes();
