"use server";
import { redirect } from "next/navigation";
import { getSupabaseAdmin } from "@/lib/supabaseAdmin";
const text=(f:FormData,k:string)=>String(f.get(k)??"").trim();
export async function submitPublicBooking(publicSlug:string,formData:FormData){
 const supabase=getSupabaseAdmin();if(!supabase)redirect(`/book/${publicSlug}?error=Booking+is+temporarily+unavailable`);
 if(text(formData,"companyWebsite"))redirect(`/book/${publicSlug}?success=Thanks`); // honeypot
 const {data:settings}=await supabase.from("booking_settings").select("*,businesses(id,name,slug)").ilike("public_slug",publicSlug).eq("enabled",true).maybeSingle();if(!settings)redirect(`/book/${publicSlug}?error=This+booking+page+is+not+available`);
 const serviceId=text(formData,"serviceId"),startRaw=text(formData,"startsAt"),first=text(formData,"firstName"),last=text(formData,"lastName"),email=text(formData,"email").toLowerCase(),phone=text(formData,"phone");if(!serviceId||!startRaw||!first||(!email&&!phone))redirect(`/book/${publicSlug}?error=Complete+the+required+fields`);
 const {data:service}=await supabase.from("services").select("*").eq("id",serviceId).eq("business_id",settings.business_id).eq("active",true).eq("is_deleted",false).maybeSingle();if(!service)redirect(`/book/${publicSlug}?error=That+service+is+no+longer+available`);
 const start=new Date(startRaw);if(Number.isNaN(start.getTime()))redirect(`/book/${publicSlug}?error=Choose+a+valid+appointment+time`);const end=new Date(start.getTime()+(service.duration_minutes+settings.buffer_minutes)*60000);const now=Date.now();if(start.getTime()<now+settings.minimum_notice_hours*3600000||start.getTime()>now+settings.maximum_days_ahead*86400000)redirect(`/book/${publicSlug}?error=That+time+is+outside+the+booking+window`);
 const [datePart,timePart]=startRaw.split("T");const weekday=new Date(`${datePart}T12:00:00Z`).getUTCDay();const {data:opening}=await supabase.from("booking_availability").select("start_time,end_time").eq("business_id",settings.business_id).eq("weekday",weekday).eq("active",true).lte("start_time",timePart).gte("end_time",new Date(start.getTime()+service.duration_minutes*60000).toTimeString().slice(0,5)).maybeSingle();if(!opening)redirect(`/book/${publicSlug}?error=That+time+is+outside+the+business’s+available+hours`);
 const dayStart=new Date(`${datePart}T00:00:00`),dayEnd=new Date(`${datePart}T23:59:59`);const [{data:conflicts},{data:blackouts},{count:dayCount}]=await Promise.all([supabase.from("jobs").select("id").eq("business_id",settings.business_id).eq("is_deleted",false).not("status","eq","canceled").lt("starts_at",end.toISOString()).gt("ends_at",start.toISOString()).limit(1),supabase.from("booking_blackouts").select("id").eq("business_id",settings.business_id).lt("starts_at",end.toISOString()).gt("ends_at",start.toISOString()).limit(1),supabase.from("jobs").select("id",{count:"exact",head:true}).eq("business_id",settings.business_id).eq("is_deleted",false).not("status","eq","canceled").gte("starts_at",dayStart.toISOString()).lte("starts_at",dayEnd.toISOString())]);if(conflicts?.length||blackouts?.length||(settings.daily_appointment_limit&&Number(dayCount)>=settings.daily_appointment_limit))redirect(`/book/${publicSlug}?error=That+time+is+not+available.+Please+choose+another`);
 let customerId:string|undefined;if(email){const {data:existing}=await supabase.from("customers").select("id").eq("business_id",settings.business_id).ilike("email",email).eq("is_deleted",false).maybeSingle();customerId=existing?.id;}if(!customerId){const {data:customer,error}=await supabase.from("customers").insert({business_id:settings.business_id,first_name:first,last_name:last,email:email||null,phone:phone||null,notes:null}).select("id").single();if(error){console.error("Public customer creation failed",error);redirect(`/book/${publicSlug}?error=We+couldn’t+save+your+contact+information`)}customerId=customer.id;}else{await supabase.from("customers").update({first_name:first,last_name:last,phone:phone||null,updated_at:new Date().toISOString()}).eq("id",customerId);}
 const status=settings.auto_confirm?"confirmed":"pending";const {data:job,error:jobError}=await supabase.from("jobs").insert({business_id:settings.business_id,customer_id:customerId,service_id:service.id,title:service.name,status,starts_at:start.toISOString(),ends_at:new Date(start.getTime()+service.duration_minutes*60000).toISOString(),service_address:text(formData,"address")||null,description:[text(formData,"details"),...(settings.intake_questions??[]).map((q:string,i:number)=>{const a=text(formData,`question_${i}`);return a?`${q}: ${a}`:"";})].filter(Boolean).join("\n\n")||null,subtotal:service.price_amount||0,tax_amount:0,booking_source:"website"}).select("id").single();if(jobError){console.error("Public job creation failed",jobError);redirect(`/book/${publicSlug}?error=We+couldn’t+complete+your+booking`)}
 const requestKey=text(formData,"requestKey")||null;const {data:submission}=await supabase.from("public_booking_submissions").insert({business_id:settings.business_id,service_id:service.id,job_id:job.id,customer_id:customerId,request_key:requestKey,status:"accepted"}).select("id").single();if(submission)await supabase.from("jobs").update({public_booking_id:submission.id}).eq("id",job.id);
 redirect(`/book/${publicSlug}/success`);
}
