import Link from "next/link";
import {canManageCustomers} from "@/lib/access";
import {formatCents} from "@/lib/financial/priceBook";
import {receivableStatus,receivableSummary,type ReceivableRow} from "@/lib/financial/receivables";
import {requireWorkspace} from "@/lib/workspace";
import {WorkspaceNav} from "../../WorkspaceNav";
import {chargeBookingBalanceNow,rescheduleBookingBalance} from "./actions";

const dateLabel=(value:string|null)=>value?new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(value.length===10?`${value}T00:00:00Z`:value)):"—";
const money=(value:number)=>formatCents(value,"USD");
export default async function ReceivablesPage({params,searchParams}:{params:Promise<{businessSlug:string}>;searchParams:Promise<Record<string,string|undefined>>}){
 const {businessSlug}=await params,q=await searchParams,{supabase,business,role}=await requireWorkspace(businessSlug),editable=canManageCustomers(role);
 const [invoiceResult,bookingResult,customerResult,jobResult,paymentResult,attemptResult,methodResult]=await Promise.all([
  supabase.from("invoices").select("id,invoice_number,customer_id,job_id,status,grand_total_cents,amount_paid_cents,amount_refunded_cents,balance_due_cents,due_date,is_deleted").eq("business_id",business.id).eq("is_deleted",false).limit(2000),
  supabase.from("bookings").select("id,booking_number,customer_id,job_id,status,total_cents,amount_paid_cents,balance_due_cents,rental_starts_at,rental_ends_at,balance_charge_scheduled_for,final_payment_authorized_at,stripe_payment_method_id").eq("business_id",business.id).limit(2000),
  supabase.from("customers").select("id,first_name,last_name,company_name").eq("business_id",business.id).limit(3000),
  supabase.from("jobs").select("id,job_number,title,status,starts_at,ends_at").eq("business_id",business.id).eq("is_deleted",false).limit(3000),
  supabase.from("payments").select("id,invoice_id,booking_id,status,payment_method_type,failure_message,created_at").eq("business_id",business.id).order("created_at",{ascending:false}).limit(4000),
  supabase.from("payment_attempts").select("invoice_id,status,failure_reason,attempted_at").eq("business_id",business.id).order("attempted_at",{ascending:false}).limit(4000),
  supabase.from("customer_payment_methods").select("provider_payment_method_id,method_type,brand,last_four,status").eq("business_id",business.id).eq("status","active").limit(3000),
 ]);
 const errors=[invoiceResult.error,bookingResult.error,customerResult.error,jobResult.error,paymentResult.error,attemptResult.error,methodResult.error].filter(Boolean);
 if(errors.length)console.error("Receivables directory load failed",{businessId:business.id,codes:errors.map(error=>error?.code)});
 const customers=new Map((customerResult.data??[]).map((c:any)=>[c.id,c.company_name||`${c.first_name??""} ${c.last_name??""}`.trim()||"Customer"]));
 const jobs=new Map((jobResult.data??[]).map((j:any)=>[j.id,j]));
 const latestInvoicePayment=new Map<string,any>(),latestBookingPayment=new Map<string,any>(),latestAttempt=new Map<string,any>();
 const methods=new Map((methodResult.data??[]).map((method:any)=>[method.provider_payment_method_id,method.last_four?`${method.brand??method.method_type} •••• ${method.last_four}`:method.method_type]));
 for(const payment of paymentResult.data??[]){if(payment.invoice_id&&!latestInvoicePayment.has(payment.invoice_id))latestInvoicePayment.set(payment.invoice_id,payment);if(payment.booking_id&&!latestBookingPayment.has(payment.booking_id))latestBookingPayment.set(payment.booking_id,payment);}
 for(const attempt of attemptResult.data??[])if(!latestAttempt.has(attempt.invoice_id))latestAttempt.set(attempt.invoice_id,attempt);
 const invoicedJobs=new Set((invoiceResult.data??[]).filter((i:any)=>i.job_id&&!i.is_deleted&&i.status!=="void").map((i:any)=>i.job_id));
 const rows:ReceivableRow[]=[];
 for(const invoice of invoiceResult.data??[]){if(["draft","void","uncollectible","refunded"].includes(invoice.status))continue;const payment=latestInvoicePayment.get(invoice.id),attempt=latestAttempt.get(invoice.id),job=jobs.get(invoice.job_id);const remaining=Number(invoice.balance_due_cents??0);rows.push({id:invoice.id,source:"invoice",customer:customers.get(invoice.customer_id)??"Customer",customerId:invoice.customer_id,reference:`Invoice ${invoice.invoice_number}`,jobId:invoice.job_id,eventDate:job?.starts_at??null,totalCents:Number(invoice.grand_total_cents??0),paidCents:Number(invoice.amount_paid_cents??0)-Number(invoice.amount_refunded_cents??0),remainingCents:remaining,scheduledFor:invoice.due_date,paymentMethod:payment?.payment_method_type?String(payment.payment_method_type).replaceAll("_"," "):null,status:receivableStatus({remainingCents:remaining,scheduledFor:invoice.due_date,paymentStatus:attempt?.status??payment?.status,invoiceStatus:invoice.status}),failureMessage:attempt?.failure_reason??payment?.failure_message??null});}
 for(const booking of bookingResult.data??[]){if(invoicedJobs.has(booking.job_id)||["cancelled","expired","refunded","pending_payment"].includes(booking.status))continue;const payment=latestBookingPayment.get(booking.id),job=jobs.get(booking.job_id),remaining=Number(booking.balance_due_cents??0),scheduled=booking.balance_charge_scheduled_for??booking.rental_ends_at??booking.rental_starts_at??job?.ends_at??job?.starts_at??null;rows.push({id:booking.id,source:"booking",customer:customers.get(booking.customer_id)??"Customer",customerId:booking.customer_id,reference:`Booking #${booking.booking_number}`,jobId:booking.job_id,eventDate:booking.rental_starts_at??job?.starts_at??null,totalCents:Number(booking.total_cents??0),paidCents:Number(booking.amount_paid_cents??0),remainingCents:remaining,scheduledFor:scheduled,paymentMethod:methods.get(booking.stripe_payment_method_id)??(booking.stripe_payment_method_id?"Card on file":payment?.payment_method_type??null),status:receivableStatus({remainingCents:remaining,scheduledFor:scheduled,paymentStatus:payment?.status}),failureMessage:payment?.failure_message??null});}
 const filter=["upcoming","attention","paid","all"].includes(q.status??"")?q.status!:"upcoming",from=q.from??"",to=q.to??"";
 const visible=rows.filter(row=>(filter==="all"||(filter==="paid"?row.status==="paid":filter==="attention"?["past_due","failed"].includes(row.status):["scheduled","due","processing"].includes(row.status)))&&(!from||String(row.scheduledFor??row.eventDate??"").slice(0,10)>=from)&&(!to||String(row.scheduledFor??row.eventDate??"").slice(0,10)<=to)).sort((a,b)=>String(a.scheduledFor??"9999").localeCompare(String(b.scheduledFor??"9999")));
 const summary=receivableSummary(rows),base=`/app/${businessSlug}/invoices/receivables`;
 return <main className="epic3-shell"><WorkspaceNav slug={businessSlug} name={business.name} industry={business.industry_profile}/><section className="epic3-content employee-directory-page invoice-directory-page"><header className="employee-page-header"><div><nav aria-label="Breadcrumb"><span>Billing</span><b>›</b><span>Outstanding payments</span></nav><h1>Outstanding payments</h1><p>See scheduled balances and money customers still owe across bookings and invoices.</p></div><Link className="sv-button sv-secondary" href={`/app/${businessSlug}/invoices`}>Invoices</Link></header>
 {q.error&&<div className="workspace-notice error">{q.error}</div>}{q.success&&<div className="workspace-notice success">{q.success}</div>}{errors.length>0&&<div className="workspace-notice error">Some receivables could not be loaded. Apply the receivables migration if it is still pending.</div>}
 <section className="employee-stat-row invoice-stat-row" aria-label="Receivables summary"><article><span>Total outstanding</span><strong>{money(summary.outstanding)}</strong><small>All open balances</small></article><article><span>Scheduled next 7 days</span><strong>{money(summary.next7)}</strong><small>Authorized and due soon</small></article><article><span>Scheduled next 30 days</span><strong>{money(summary.next30)}</strong><small>Expected this month</small></article><article><span>Past due / failed</span><strong>{money(summary.pastDue)}</strong><small>Needs attention</small></article></section>
 <section className="employee-directory-shell invoice-directory-shell"><div className="employee-directory-main"><form className="employee-directory-toolbar invoice-directory-toolbar"><label><span>View</span><select name="status" defaultValue={filter}><option value="upcoming">Upcoming</option><option value="attention">Past due / failed</option><option value="paid">Paid</option><option value="all">All</option></select></label><label><span>From</span><input type="date" name="from" defaultValue={from}/></label><label><span>To</span><input type="date" name="to" defaultValue={to}/></label><button className="sv-button sv-secondary">Filters</button>{(filter!=="upcoming"||from||to)&&<Link className="jobs-clear-filters" href={base}>Clear</Link>}</form>
 <div className="invoice-table receivables-table" role="table" aria-label="Outstanding payments"><div className="invoice-table-head" role="row"><span>Customer / reference</span><span>Event</span><span>Total / paid</span><span>Remaining</span><span>Scheduled charge</span><span>Method / source</span><span>Status / actions</span></div>{visible.length?visible.map(row=><div role="row" key={`${row.source}-${row.id}`}><span role="cell"><strong>{row.customer}</strong><small>{row.reference}{row.jobId?` · Job #${jobs.get(row.jobId)?.job_number??""}`:""}</small></span><span role="cell">{dateLabel(row.eventDate)}</span><span role="cell"><strong>{money(row.totalCents)}</strong><small>{money(row.paidCents)} paid</small></span><span role="cell"><strong>{money(row.remainingCents)}</strong></span><span role="cell">{dateLabel(row.scheduledFor)}</span><span role="cell"><strong>{row.paymentMethod??"Not available"}</strong><small>{row.source==="booking"?"Online Booking":"Invoice"}</small></span><span role="cell"><b className={`estimate-status ${row.status}`}>{row.status.replaceAll("_"," ")}</b>{row.failureMessage&&<small>{row.failureMessage}</small>}<small><Link href={row.source==="invoice"?`/app/${businessSlug}/invoices/${row.id}`:row.jobId?`/app/${businessSlug}/jobs/${row.jobId}`:`/app/${businessSlug}/bookings`}>View {row.source}</Link></small>{editable&&row.source==="booking"&&row.remainingCents>0&&<details><summary>Payment actions</summary><form action={rescheduleBookingBalance.bind(null,businessSlug,row.id)}><input type="date" name="scheduledFor" required defaultValue={row.scheduledFor?.slice(0,10)}/><button className="text-button">Reschedule</button></form>{row.jobId&&jobs.get(row.jobId)?.status==="completed"&&<form action={chargeBookingBalanceNow.bind(null,businessSlug,row.id)}><button className="text-button">Charge now</button></form>}</details>}</span></div>):<div className="dashboard-empty"><strong>No matching payments.</strong><p>Try another status or date range.</p></div>}</div></div></section></section></main>;
}
