"use server";
import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {canManageBusiness} from "@/lib/access";
import {generateGoogleBusinessReviewReply,postGoogleBusinessProfileReviewReply} from "@/lib/googleBusinessProfile";
import {requireWorkspace} from "@/lib/workspace";

const base=(slug:string)=>`/app/${encodeURIComponent(slug)}/notifications`;
const message=(error:unknown)=>error instanceof Error?error.message:"Something went wrong.";
async function notification(slug:string,id:string){const context=await requireWorkspace(slug);const {data,error}=await context.supabase.from("business_notifications").select("*").eq("business_id",context.business.id).eq("id",id).maybeSingle();if(error||!data)throw new Error("This notification is no longer available.");return {...context,notification:data as {id:string;type:string;status:string;metadata:Record<string,unknown>}};}
export async function markNotificationRead(slug:string,id:string){const {supabase,business}=await notification(slug,id);await supabase.from("business_notifications").update({status:"read",read_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("business_id",business.id).eq("id",id).eq("status","unread");revalidatePath(base(slug));}
export async function markAllNotificationsRead(slug:string){const {supabase,business}=await requireWorkspace(slug);await supabase.from("business_notifications").update({status:"read",read_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("business_id",business.id).eq("status","unread");revalidatePath(base(slug));}
export async function dismissNotification(slug:string,id:string){const {supabase,business,notification:row}=await notification(slug,id);const issueId=typeof row.metadata?.issueId==="string"?row.metadata.issueId:null;const severity=typeof row.metadata?.severity==="string"?row.metadata.severity:null;const now=new Date().toISOString();if(row.type==="marketing_issue"&&issueId){if(severity==="critical"){await supabase.from("business_notifications").update({status:"read",read_at:now,updated_at:now,metadata:{...row.metadata,acknowledgedAt:now}}).eq("business_id",business.id).eq("id",id);revalidatePath(base(slug));redirect(`${base(slug)}?success=${encodeURIComponent("Issue acknowledged. It will stay visible until resolved.")}`);}await supabase.from("business_marketing_issues").update({status:"dismissed",dismissed_at:now,updated_at:now}).eq("business_id",business.id).eq("id",issueId);};await supabase.from("business_notifications").update({status:"dismissed",dismissed_at:now,updated_at:now}).eq("business_id",business.id).eq("id",id);revalidatePath(base(slug));}
export async function generateReviewReply(slug:string,id:string){try{const {supabase,business,role,notification:row}=await notification(slug,id);if(!canManageBusiness(role))throw new Error("Only owners and administrators can generate review replies.");const review=row.metadata,reply=await generateGoogleBusinessReviewReply({businessName:business.name,author:String(review.author||"Google customer"),rating:Number(review.rating||0),review:String(review.text||"")});await supabase.from("business_notifications").update({metadata:{...review,suggestedReply:reply},updated_at:new Date().toISOString()}).eq("business_id",business.id).eq("id",id);revalidatePath(base(slug));redirect(`${base(slug)}?success=${encodeURIComponent("Reply draft generated.")}`);}catch(error){redirect(`${base(slug)}?error=${encodeURIComponent(message(error))}`);}}
export async function postReviewReply(slug:string,id:string,data:FormData){try{const {supabase,business,role,notification:row}=await notification(slug,id);if(!canManageBusiness(role))throw new Error("Only owners and administrators can post review replies.");const review=row.metadata,reply=String(data.get("reply")||"").trim();if(!reply||reply.length>1500)throw new Error("Enter a reply up to 1,500 characters.");const reviewId=String(review.reviewId||"");if(!reviewId)throw new Error("Google review information is missing.");await postGoogleBusinessProfileReviewReply({businessId:business.id,reviewId,reply});await supabase.from("business_notifications").update({status:"resolved",resolved_at:new Date().toISOString(),updated_at:new Date().toISOString(),metadata:{...review,reply}}).eq("business_id",business.id).eq("id",id);revalidatePath(base(slug));redirect(`${base(slug)}?success=${encodeURIComponent("Reply posted to Google.")}`);}catch(error){redirect(`${base(slug)}?error=${encodeURIComponent(message(error))}`);}}
export async function saveNotificationPreferences(slug:string,data:FormData){const {supabase,business,user,role}=await requireWorkspace(slug);if(!canManageBusiness(role))redirect(`${base(slug)}?error=${encodeURIComponent("Only owners and administrators can change notification preferences.")}`);const row={business_id:business.id,google_reviews_enabled:data.get("googleReviews")==="on",marketing_enabled:data.get("marketing")==="on",payments_enabled:data.get("payments")==="on",updated_at:new Date().toISOString(),updated_by:user.id};await supabase.from("business_notification_preferences").upsert(row,{onConflict:"business_id"});revalidatePath(`/app/${encodeURIComponent(slug)}/settings/notifications`);redirect(`/app/${encodeURIComponent(slug)}/settings/notifications?success=${encodeURIComponent("Notification preferences saved.")}`);}
