import {notFound} from "next/navigation";
import type {Metadata} from "next";
import {getSupabaseAdmin} from "@/lib/supabaseAdmin";
import {matchesPublicRentalSlug} from "@/lib/publicRental";
import {hostedTenantRobots,publicSeoPlatformUrl,tenantCanonicalUrl,tenantMetadata} from "@/lib/publicTenantSeo";
import {RentalDetailLanding} from "@/components/RentalDetailLanding";
import {TenantLandingSchema} from "@/components/TenantPublicSchema";

const fields="id,name,category,category_id,description,daily_price_cents,image_url,length_ft,width_ft,height_ft,standard_rental_hours_override,inventory_item_specifications(label,value,icon,sort_order,is_public)";
async function load(siteSlug:string,slug:string){const db=getSupabaseAdmin();if(!db)return null;const {data:website}=await db.from("business_website_settings").select("business_id,custom_domain,domain_status").ilike("public_slug",siteSlug).eq("status","published").maybeSingle();if(!website)return null;const [{data:business},{data:items},{data:locations},{data:categoryPages}]=await Promise.all([db.from("businesses").select("name,phone,email").eq("id",website.business_id).maybeSingle(),db.from("inventory_items").select(fields).eq("business_id",website.business_id).eq("active",true),db.from("business_location_pages").select("slug,city,state").eq("business_id",website.business_id).eq("status","published").limit(6),db.from("category_website_pages").select("category_id,slug").eq("business_id",website.business_id).eq("status","published")]);const item=(items??[]).find(row=>matchesPublicRentalSlug(row,slug));if(!item||!business)return null;return{website,business,item:{...item,standardRentalHours:Number(item.standard_rental_hours_override??24),related:(items??[]).filter(row=>row.category_id===item.category_id&&row.id!==item.id).slice(0,4)},locations:locations??[],categoryUrl:(categoryPages??[]).find(row=>row.category_id===item.category_id)?.slug??null};}
export async function generateMetadata({params}:{params:Promise<{siteSlug:string;itemSlug:string}>}):Promise<Metadata>{const {siteSlug,itemSlug}=await params,data=await load(siteSlug,itemSlug);if(!data)return{};const fallback=`${publicSeoPlatformUrl}/sites/${encodeURIComponent(siteSlug)}`;return tenantMetadata({settings:data.website,fallbackBase:fallback,path:`/rentals/${itemSlug}`,title:`${data.item.name} Rental | ${data.business.name}`,description:data.item.description||`Rent ${data.item.name} from ${data.business.name}.`,index:hostedTenantRobots(data.website).index});}
export default async function HostedRentalPage({params}:{params:Promise<{siteSlug:string;itemSlug:string}>}){const {siteSlug,itemSlug}=await params,data=await load(siteSlug,itemSlug);if(!data)notFound();const fallback=`${publicSeoPlatformUrl}/sites/${encodeURIComponent(siteSlug)}`,url=tenantCanonicalUrl(data.website,`/rentals/${itemSlug}`,fallback);return <><TenantLandingSchema type="WebPage" name={data.item.name} url={url} homeUrl={tenantCanonicalUrl(data.website,"/",fallback)}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Product",name:data.item.name,description:data.item.description||undefined,image:data.item.image_url?[data.item.image_url]:undefined,offers:data.item.daily_price_cents>0?{"@type":"Offer",price:String(Number(data.item.daily_price_cents)/100),priceCurrency:"USD",url}:undefined}).replace(/</g,"\\u003c")}}/><RentalDetailLanding item={data.item} business={data.business} bookingUrl={`/book/${siteSlug}`} homeUrl={`/sites/${siteSlug}`} categoryUrl={data.categoryUrl?`/sites/${siteSlug}/${data.categoryUrl}`:null} locations={data.locations.map(page=>({...page,slug:`sites/${siteSlug}/${page.slug}`}))}/></>;}
