import Link from "next/link";
import {redirect} from "next/navigation";
import {createSupabaseServerClient} from "@/lib/supabaseServer";
import {isServonasPlatformAdmin} from "@/lib/platformAccess";
import {getAdminUsageReport} from "@/lib/admin/usageReporting";
import {setCustomerFeatureAccess} from "./actions";
const periodPattern=/^\d{4}-(0[1-9]|1[0-2])$/,number=(value:number)=>new Intl.NumberFormat("en-US").format(value),money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:4}).format(value);
function AccessForm({businessId,feature,enabled,period}:{businessId:string;feature:"ai"|"twilio";enabled:boolean;period:string}){return <form action={setCustomerFeatureAccess} className="admin-customer-access-form"><input type="hidden" name="businessId" value={businessId}/><input type="hidden" name="feature" value={feature}/><input type="hidden" name="enabled" value={String(!enabled)}/><input type="hidden" name="period" value={period}/><label><span className="sr-only">Internal reason</span><input name="reason" required minLength={5} placeholder="Internal reason"/></label><label><span className="sr-only">Confirmation</span><input name="confirmation" required pattern="CONFIRM" placeholder="Type CONFIRM"/></label><button className={`sv-button sv-small ${enabled?"sv-danger":""}`}>{enabled?"Remove access":"Add access"}</button></form>}
export default async function CustomerAdmin({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){const query=await searchParams,session=await createSupabaseServerClient(),{data:{user}}=await session.auth.getUser();if(!isServonasPlatformAdmin(user))redirect("/app");const period=periodPattern.test(query.period??"")?query.period!:new Date().toISOString().slice(0,7),report=await getAdminUsageReport(period);return <main className="admin-entitlements admin-customer-management"><header><div><span className="sv-kicker">Internal administration</span><h1>Customer access &amp; usage</h1><p>Manage paid AI and Twilio access and review provider usage for every Servonas business.</p></div><div className="crm-header-actions"><Link className="sv-button sv-secondary" href="/app/admin/twilio">Twilio setup</Link><Link className="sv-button sv-secondary" href="/app">Workspaces</Link></div></header>{query.error&&<div className="workspace-notice error">{query.error}</div>}{query.success&&<div className="workspace-notice success">{query.success}</div>}<section className="workspace-panel usage-period-panel"><form method="get"><label>Usage month<input type="month" name="period" defaultValue={period}/></label><button className="sv-button">View month</button></form><p>Removing access is reversible and does not delete provider resources or historical usage.</p></section><section className="admin-customer-list">{report.businesses.map(row=><article className="workspace-panel" key={row.id}><div className="panel-title"><div><span className="sv-kicker">{row.slug}</span><h2>{row.name}</h2></div><Link className="sv-button sv-secondary sv-small" href={`/app/${row.slug}`}>Open workspace</Link></div><div className="admin-customer-products"><section><div className="admin-product-title"><div><strong>AI Assistant</strong><small>{number(row.ai.requestCount)} requests · {number(row.ai.totalTokens)} tokens · {money(row.ai.cost)}</small></div><span className={`estimate-status ${row.access.ai?"active":"inactive"}`}>{row.access.ai?"Access on":"Off"}</span></div><AccessForm businessId={row.id} feature="ai" enabled={row.access.ai} period={period}/></section><section><div className="admin-product-title"><div><strong>Twilio</strong><small>{number(row.twilio.messageCount)} messages · {number(row.twilio.segments)} segments · {money(row.twilio.cost)}</small><small>{row.twilioStatus.hasSubaccount?`Subaccount ${row.twilioStatus.provisioning} · activation ${row.twilioStatus.activation}`:"No tenant subaccount"}</small></div><span className={`estimate-status ${row.access.twilio?"active":"inactive"}`}>{row.access.twilio?"Access on":"Off"}</span></div><AccessForm businessId={row.id} feature="twilio" enabled={row.access.twilio} period={period}/></section></div></article>)}</section></main>}
