import Link from "next/link";
import {canManageBusiness} from "@/lib/access";
import {requireWorkspace} from "@/lib/workspace";
import {WorkspaceNav} from "../../WorkspaceNav";
import {GoogleReviewsEditor} from "@/components/GoogleReviewsEditor";
import {WebsiteIcon} from "@/components/WebsiteIcon";
import {getVercelDomainStatus} from "@/lib/vercelDomains";
import {getSupabaseAdmin} from "@/lib/supabaseAdmin";
import {checkWebsiteDomain,disconnectGoogleBusinessProfile,saveWebsiteSettings,setWebsitePublished,updateWebsiteLeadStatus,uploadWebsiteLogo} from "./actions";

const label=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());
export default async function WebsiteDashboard({params,searchParams}:{params:Promise<{businessSlug:string}>;searchParams:Promise<Record<string,string|undefined>>}){
 const {businessSlug}=await params,q=await searchParams,{supabase,business,role}=await requireWorkspace(businessSlug),editable=canManageBusiness(role);
 const [{data:settings,error:settingsError},{data:booking},{data:services},{data:hours},{data:territories},{data:requests}]=await Promise.all([
  supabase.from("business_website_settings").select("*").eq("business_id",business.id).maybeSingle(),
  supabase.from("booking_settings").select("enabled,public_slug,logo_path,logo_url,brand_color").eq("business_id",business.id).maybeSingle(),
  supabase.from("services").select("id,name,description,active").eq("business_id",business.id).eq("is_deleted",false).eq("active",true).order("sort_order").order("name"),
  supabase.from("booking_availability").select("weekday,start_time,end_time").eq("business_id",business.id).eq("active",true).order("weekday"),
  supabase.from("workforce_territories").select("id,name").eq("business_id",business.id).eq("is_active",true).order("name"),
  supabase.from("website_service_requests").select("id,customer_id,service_id,customer_name,phone,email,service_address,description,preferred_at,lead_status,created_at,services(name)").eq("business_id",business.id).order("created_at",{ascending:false}).limit(20),
 ]);
 const {data:signedLogo}=booking?.logo_path?await supabase.storage.from("booking-branding").createSignedUrl(booking.logo_path,3600):{data:null};
 const admin=getSupabaseAdmin(),{data:googleConnection}=admin?await admin.from("business_google_profile_connections").select("location_title,status").eq("business_id",business.id).maybeSingle():{data:null};
 const logoUrl=signedLogo?.signedUrl??booking?.logo_url??null,publicSlug=settings?.public_slug??business.slug,status=settings?.status??"draft";
 const origin=(process.env.NEXT_PUBLIC_APP_URL??"https://servonas.com").replace(/\/$/,""),publicUrl=`${origin}/sites/${publicSlug}`;
 const domainInfo=settings?.custom_domain?await getVercelDomainStatus(settings.custom_domain).catch(()=>null):null;
 const connectedDomain=settings?.domain_status==="connected"&&settings.custom_domain?settings.custom_domain:null,displayUrl=connectedDomain?`https://${connectedDomain}`:publicUrl;
 const missing=[!business.phone&&"phone number",!business.email&&"email",!(services?.length)&&"services",!(hours?.length)&&"business hours"].filter(Boolean);
 return <main className="epic3-shell"><WorkspaceNav slug={businessSlug} name={business.name} industry={business.industry_profile}/><section className="epic3-content website-dashboard">
  <header className="website-dashboard-header"><div><span>Business presence</span><h1>Website</h1><p>Servonas already knows your business. Your professional website is almost done.</p></div><div><span className={`website-status ${status}`}><i/> {label(status)}</span><Link className="sv-button sv-secondary" href={`/app/${businessSlug}/settings/website/preview`} target="_blank"><WebsiteIcon name="eye"/>Preview Website</Link>{editable&&<form action={setWebsitePublished.bind(null,businessSlug)}><input type="hidden" name="publish" value={String(status!=="published")}/><button className="sv-button"><WebsiteIcon name="send"/>{status==="published"?"Unpublish Website":"Publish Website"}</button></form>}</div></header>
  {q.error&&<div className="workspace-notice error">{q.error}</div>}{q.success&&<div className="workspace-notice success">{q.success}</div>}{settingsError&&<div className="workspace-notice error">Apply the Website database migration before configuring this feature.</div>}
  <section className="website-overview-card"><div><span>{connectedDomain?"Custom website":"Your website"}</span><a href={connectedDomain||status==="published"?displayUrl:undefined} target="_blank" rel="noreferrer">{displayUrl}<WebsiteIcon name="external"/></a><small>{connectedDomain?"Connected with automatic HTTPS":status==="published"?"Live and available to customers":"Save your settings, preview, then publish when ready"}</small></div><dl><div><i><WebsiteIcon name="check"/></i><dt>Business data</dt><dd>{missing.length?`${missing.length} item${missing.length===1?"":"s"} missing`:"Ready"}</dd></div><div><i><WebsiteIcon name="calendar"/></i><dt>Services</dt><dd>{services?.length??0} live</dd></div><div><i><WebsiteIcon name="pin"/></i><dt>Service areas</dt><dd>{territories?.length??0}</dd></div><div><i><WebsiteIcon name="globe"/></i><dt>Online requests</dt><dd>{settings?.request_service_enabled===false?"Off":"Enabled"}</dd></div></dl></section>
  {missing.length>0&&<div className="website-inherited-notice"><strong>Complete your Servonas information</strong><p>The public site automatically updates from Business Settings, Services, Territories, and Online Booking. Missing now: {missing.join(", ")}.</p></div>}
  <form action={saveWebsiteSettings.bind(null,businessSlug)} className="website-settings-form">
   <section className="workspace-panel website-setting-section"><header><div><span>01</span><h2>{connectedDomain?"Website template":"Website address & template"}</h2><p>Choose one professional layout. No page builder required.</p></div></header>{connectedDomain?<input type="hidden" name="publicSlug" value={publicSlug}/>:<label>Servonas website URL<div className="website-slug-input"><span>{origin}/sites/</span><input required name="publicSlug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" defaultValue={publicSlug} disabled={!editable}/></div></label>}<fieldset className="website-template-grid"><legend>Template</legend>{[["modern","Modern","Clean, bright, and conversion focused"],["traditional","Traditional","Established, dependable, and familiar"],["bold","Bold","High contrast with strong calls to action"]].map(([key,name,description])=><label className={`website-template-card ${key}`} key={key}><input type="radio" name="template" value={key} defaultChecked={(settings?.template_key??"modern")===key} disabled={!editable}/><i><span/><span/><span/></i><strong>{name}</strong><small>{description}</small></label>)}</fieldset></section>
   <section className="workspace-panel website-setting-section"><header><div><span>02</span><h2>Brand</h2><p>Your business identity is shared with booking and business settings.</p></div></header><div className="website-brand-settings"><div className="website-logo-card">{logoUrl?<img src={logoUrl} alt={`${business.name} logo`}/>:<i>{business.name.slice(0,1)}</i>}<span><strong>Business logo</strong><small>{logoUrl?"Shared with your Servonas booking page":"Add a logo for the header and footer"}</small></span></div><label>Primary color<input type="color" name="primaryColor" defaultValue={settings?.primary_color??booking?.brand_color??business.primary_color??"#1769f5"} disabled={!editable}/></label><label>Secondary color<input type="color" name="secondaryColor" defaultValue={settings?.secondary_color??"#0b1733"} disabled={!editable}/></label></div></section>
   <section className="workspace-panel website-setting-section"><header><div><span>03</span><h2>Content</h2><p>Customize the message while business details remain synchronized with Servonas.</p></div></header><div className="website-form-grid"><label className="wide">Hero heading<input name="heroHeading" maxLength={180} defaultValue={settings?.hero_heading??`${business.name} keeps your home or business running smoothly.`} disabled={!editable}/></label><label className="wide">Hero subheading<textarea name="heroSubheading" maxLength={500} rows={3} defaultValue={settings?.hero_subheading??"Reliable local service, clear communication, and a team that is ready when you need help."} disabled={!editable}/></label><label className="wide">About your business<textarea name="aboutText" maxLength={4000} rows={5} defaultValue={settings?.about_text??`${business.name} is a local service business committed to dependable work and a straightforward customer experience.`} disabled={!editable}/></label><details className="website-advanced-content wide" open><summary>Website photos</summary><div className="website-photo-manager">{(settings?.photo_urls??[]).length>0&&<div className="website-photo-previews">{settings.photo_urls.map((url:string,index:number)=><img src={url} alt={`Website photo ${index+1}`} key={url}/>)}</div>}<label>Upload photos <small>JPG, PNG, WebP, GIF, or AVIF. Up to 6 at a time and 8MB each.</small><input name="websitePhotos" type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/avif" multiple disabled={!editable}/></label><label>Saved and externally hosted photos <small>One secure HTTPS image URL per line. Remove a line to remove that photo from the website.</small><textarea name="photoUrls" rows={5} defaultValue={(settings?.photo_urls??[]).join("\n")} disabled={!editable}/></label><small>The first photo is used in the hero. The second appears in About, and the remaining photos build the gallery.</small></div></details></div></section>
   <section className="website-live-data"><article><i><WebsiteIcon name="store"/></i><span>Business information</span><strong>{business.name}</strong><p>{business.phone||"Phone not added"}<br/>{business.email||"Email not added"}</p><Link href={`/app/${businessSlug}/settings`}>Edit business settings <WebsiteIcon name="arrow"/></Link></article><article><i><WebsiteIcon name="tools"/></i><span>Services</span><strong>{services?.length??0} published service{services?.length===1?"":"s"}</strong><p>{services?.slice(0,4).map(service=>service.name).join(" · ")||"No active services"}</p><Link href={`/app/${businessSlug}/price-book`}>Manage services <WebsiteIcon name="arrow"/></Link></article><article><i><WebsiteIcon name="clock"/></i><span>Hours &amp; areas</span><strong>{hours?.length??0} open days · {territories?.length??0} areas</strong><p>Changes automatically appear on the website.</p><Link href={`/app/${businessSlug}/booking`}>Manage hours <WebsiteIcon name="arrow"/></Link></article></section>
   <section className="workspace-panel website-setting-section"><header><div><span>04</span><h2>Online requests</h2><p>Turn website visitors into Servonas customers and trackable leads.</p></div></header><div className="website-toggle-list"><label><input type="checkbox" name="requestEnabled" defaultChecked={settings?.request_service_enabled??true} disabled={!editable}/><span><strong>Enable Request Service form</strong><small>Creates or matches a customer and records a website lead in Servonas.</small></span></label><label><input type="checkbox" name="bookingEnabled" defaultChecked={settings?.booking_enabled??false} disabled={!editable||!booking?.enabled}/><span><strong>Use Book Online as the primary button</strong><small>{booking?.enabled?"Links customers to your existing Servonas booking experience.":"Enable Online Booking before selecting this option."}</small></span></label></div></section>
   <section className="workspace-panel website-setting-section" id="domain"><header><div><span>05</span><h2>Custom domain</h2><p>Use a domain you already own. Your existing website will not change until you update its DNS.</p></div><b className={`domain-status ${settings?.domain_status??"not_connected"}`}>{label(settings?.domain_status??"not_connected")}</b></header><label>Domain name<input name="customDomain" placeholder="www.yourbusiness.com" defaultValue={settings?.custom_domain??""} disabled={!editable}/></label>{settings?.custom_domain&&<div className="website-dns-instructions"><strong>{settings.domain_status==="connected"?"Domain connected":"Connect your DNS"}</strong>{settings.domain_status==="connected"?(status==="published"?<p><a href={`https://${settings.custom_domain}`} target="_blank" rel="noreferrer">https://{settings.custom_domain}</a> now serves this Servonas website with automatic HTTPS.</p>:<p className="website-domain-warning">The domain is ready, but this website is still a draft. Select Publish Website at the top of the page before opening the domain.</p>):<><p>Add these records at the company where the domain is managed. DNS changes can take several minutes or, occasionally, up to 48 hours.</p>{domainInfo?.verification.map((record,index)=><div className="website-dns-record" key={`verify-${index}`}><b>{record.type}</b><span><small>Name</small><code>{record.domain}</code></span><span><small>Value</small><code>{record.value}</code></span></div>)}{domainInfo?.dnsRecords.map((record,index)=><div className="website-dns-record" key={`route-${index}`}><b>{record.type}</b><span><small>Name</small><code>{record.name}</code></span><span><small>Value</small><code>{record.value}</code></span></div>)}</>} {domainInfo&&!domainInfo.configured&&<p className="website-domain-warning">Custom-domain automation must be configured by Servonas before this domain can be connected.</p>}</div>}{editable&&<div className="website-domain-actions"><button className="sv-button sv-secondary" formAction={checkWebsiteDomain.bind(null,businessSlug)}>Check connection</button></div>}{editable&&!settings?.custom_domain&&<p className="website-domain-help">Enter the domain and select Check connection. Servonas will save the domain and show the required DNS records.</p>}</section>
   <section className="workspace-panel website-setting-section website-google-reviews"><header><div><span>06</span><h2>Google reviews</h2><p>Connect the live Google rating and optionally feature selected customer feedback.</p></div></header>{googleConnection?<div className="website-google-connected"><strong>✓ Google Business Profile connected</strong><span>{googleConnection.location_title||business.name}</span><small>Ratings and recent reviews synchronize automatically.</small><button className="text-button danger" formAction={disconnectGoogleBusinessProfile.bind(null,businessSlug)} formNoValidate>Disconnect Google</button></div>:editable&&<a className="sv-button" href={`/api/google-business/connect/${encodeURIComponent(businessSlug)}`}>Connect Google Business Profile</a>}<details><summary>Use Google Place ID instead</summary><label>Google Place ID<input name="googlePlaceId" placeholder="ChIJ..." defaultValue={settings?.google_place_id??""} disabled={!editable}/><small>Optional fallback for public Google Maps listings.</small></label></details><label>Google Business review page<input name="googleReviewUrl" type="url" placeholder="https://g.page/r/..." defaultValue={settings?.google_review_url??""} disabled={!editable}/><small>Used to link visitors back to the original reviews on Google.</small></label>{settings?.google_place_id&&!googleConnection&&<div className="website-google-connected"><strong>✓ Google rating connected by Place ID</strong><span>{settings.google_place_name||business.name}</span>{settings.google_place_address&&<small>{settings.google_place_address}</small>}</div>}<GoogleReviewsEditor reviews={Array.isArray(settings?.google_reviews)?settings.google_reviews:[]} disabled={!editable}/></section>
   {editable&&<footer className="website-save-bar"><i><WebsiteIcon name="shield"/></i><span>Business details, services, hours, and service areas stay synchronized automatically.</span><button className="sv-button"><WebsiteIcon name="save"/>Save Website</button></footer>}
  </form>
  {editable&&<section className="workspace-panel website-logo-upload"><div><h2>Logo upload</h2><p>Upload once and use the same logo for Website and Online Booking.</p></div><form action={uploadWebsiteLogo.bind(null,businessSlug)}><input required name="logo" type="file" accept="image/jpeg,image/png,image/webp"/><button className="sv-button sv-secondary"><WebsiteIcon name="upload"/>Upload Logo</button></form></section>}
  <section className="workspace-panel website-leads"><div className="panel-title"><div><span>Website leads</span><h2>Recent service requests</h2></div><b>{requests?.length??0}</b></div>{requests?.length?<div>{requests.map((request:any)=><article key={request.id}><header><div><strong>{request.customer_name}</strong><span>{new Date(request.created_at).toLocaleString()}</span></div><b className={`website-lead-status ${request.lead_status}`}>{label(request.lead_status)}</b></header><p>{Array.isArray(request.services)?request.services[0]?.name:request.services?.name??"Other service"} · {request.service_address}</p><blockquote>{request.description}</blockquote><div><a href={`tel:${request.phone}`}>{request.phone}</a>{request.email&&<a href={`mailto:${request.email}`}>{request.email}</a>}{request.customer_id&&<Link href={`/app/${businessSlug}/customers/${request.customer_id}`}>Open customer</Link>}<Link href={`/app/${businessSlug}/jobs?addJob=1${request.customer_id?`&customerId=${encodeURIComponent(request.customer_id)}`:""}`}>Create job</Link></div>{editable&&<form action={updateWebsiteLeadStatus.bind(null,businessSlug)}><input type="hidden" name="requestId" value={request.id}/><select name="status" defaultValue={request.lead_status}>{["new","contacted","qualified","booked","lost"].map(item=><option value={item} key={item}>{label(item)}</option>)}</select><button className="text-button">Update status</button></form>}</article>)}</div>:<div className="dashboard-empty"><strong>No website requests yet</strong><p>New Request Service submissions will appear here and create or match customer records automatically.</p></div>}</section>
 </section></main>;
}
