"use client";
import {useActionState,useMemo,useState} from "react";
import {createWorkspace,OnboardingState} from "@/app/onboarding/actions";
type Model="rentals"|"services"|"appointments"|"hybrid";
export default function OnboardingWizard({defaultEmail=""}:{defaultEmail?:string}){
 const [step,setStep]=useState(1),[state,action,pending]=useActionState(createWorkspace,{} as OnboardingState);
 const [data,setData]=useState({name:"",slug:"",email:defaultEmail,model:"rentals" as Model,inventory:true,staff:false,deposits:true,color:"#2563eb"});
 const clean=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
 const valid=useMemo(()=>data.name.trim().length>1&&data.slug.length>1&&data.email.includes("@"),[data]);
 return <form className="sv-wizard" action={action}><div className="sv-progress"><span style={{width:`${step*33.333}%`}}/></div><small>Step {step} of 3</small>
  <input type="hidden" name="name" value={data.name}/><input type="hidden" name="slug" value={data.slug}/><input type="hidden" name="email" value={data.email}/><input type="hidden" name="model" value={data.model}/><input type="hidden" name="color" value={data.color}/>
  {step===1&&<div><h2>Create your business</h2><p>This creates a secure workspace and makes you its owner.</p><label>Business name<input value={data.name} onChange={e=>setData({...data,name:e.target.value,slug:clean(e.target.value)})} placeholder="NRS Party Rentals"/></label><label>Workspace URL<div className="sv-input-prefix"><span>servonas.com/app/</span><input value={data.slug} onChange={e=>setData({...data,slug:clean(e.target.value)})} placeholder="nrs-party-rentals"/></div></label><label>Business email<input type="email" value={data.email} onChange={e=>setData({...data,email:e.target.value})}/></label></div>}
  {step===2&&<div><h2>What do you sell?</h2><p>Servonas will configure your initial workflows.</p><div className="sv-choice-grid">{([['rentals','Rentals','Reserve physical inventory'],['services','Services','Request or schedule jobs'],['appointments','Appointments','Book time or classes'],['hybrid','A mix','Combine time, work, and inventory']] as const).map(([v,t,d])=><button type="button" className={data.model===v?"active":""} onClick={()=>setData({...data,model:v})} key={v}><strong>{t}</strong><span>{d}</span></button>)}</div></div>}
  {step===3&&<div><h2>Choose your starting modules</h2><p>You can change these later.</p><label className="sv-check"><input name="inventory" type="checkbox" checked={data.inventory} onChange={e=>setData({...data,inventory:e.target.checked})}/><span><strong>Inventory or catalog</strong><small>Products, services, images, quantities, and availability</small></span></label><label className="sv-check"><input name="staff" type="checkbox" checked={data.staff} onChange={e=>setData({...data,staff:e.target.checked})}/><span><strong>Team scheduling</strong><small>Assign work and coordinate calendars</small></span></label><label className="sv-check"><input name="deposits" type="checkbox" checked={data.deposits} onChange={e=>setData({...data,deposits:e.target.checked})}/><span><strong>Payments and deposits</strong><small>Take secure payment during booking</small></span></label></div>}
  {state.error&&<p className="auth-error">{state.error}</p>}
  <div className="sv-wizard-actions">{step>1&&<button type="button" className="sv-button sv-secondary" onClick={()=>setStep(step-1)}>Back</button>}{step<3?<button type="button" className="sv-button" disabled={step===1&&!valid} onClick={()=>setStep(step+1)}>Continue</button>:<button className="sv-button" disabled={pending}>{pending?"Creating workspace…":"Create Workspace"}</button>}</div>
 </form>
}
