import {randomUUID} from "node:crypto";
import {zonedDateTimeToUtc} from "../bookingTime.ts";
import {canManageCustomers} from "../access.ts";
import {assistantTools,executeAssistantTool,type AssistantContext} from "./tools.ts";
import {getAssistantProvider,type AIProvider,type ProviderDecision} from "./provider.ts";
import {recordAssistantProviderUsage} from "./usage.ts";
import {clearCustomerChildConversationContext,clearSelectedCustomerConversationContext,pendingCustomerConversationContext,pendingSelectionFromContext,resolveCustomerCandidateAgainstTenant,selectCustomerConversationContext,type CustomerCandidate} from "./customerCandidateResolution.ts";
import {bindTrustedSelectedCustomer,bindTrustedSelectedInvoice,classifyInvoiceSendIntent,explicitCustomerSearchTerm,explicitlyChangesCustomer,requestsGlobalSchedule} from "./selectedCustomerContext.ts";
import {classifyBillingIntent} from "./billingIntent.ts";
import {classifySpokenConfirmation} from "./spokenConfirmation.ts";
import {classifyMarkInvoicePaidIntent,explicitInvoiceNumber} from "./markInvoicePaidIntent.ts";
import {assistantTrace,safeAssistantErrorCategory,type AssistantTraceSink} from "./debugTrace.ts";

export type ProcessAssistantInput={context:AssistantContext;conversationId?:string|null;channel:"web"|"mobile"|"voice"|"phone_call"|"sms";input:string;requestId?:string|null;provider?:AIProvider;trace?:AssistantTraceSink};
const dayRange=(offset:number,timeZone:string)=>{const target=new Date(Date.now()+offset*864e5),parts=new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(target),part=(t:string)=>parts.find(p=>p.type===t)?.value??"";const date=`${part("year")}-${part("month")}-${part("day")}`,start=zonedDateTimeToUtc(date,"00:00",timeZone);return{start:start.toISOString(),end:new Date(start.getTime()+864e5).toISOString()};};
function fallbackDecision(input:string,timeZone:string,selectedCustomerId?:string):ProviderDecision{const lower=input.toLowerCase();if(/who.*today|have today|schedule today/.test(lower))return{toolName:"getSchedule",arguments:dayRange(0,timeZone)};if(/tomorrow|who.*tomorrow/.test(lower)&&/who|schedule|appointment|have/.test(lower))return{toolName:"getSchedule",arguments:dayRange(1,timeZone)};if(/owe|outstanding|overdue/.test(lower))return{toolName:"getOutstandingInvoices",arguments:selectedCustomerId?{customerId:selectedCustomerId}:{}};const match=input.match(/(?:find|search for|look up)\s+(.+)/i);if(match)return{toolName:"searchCustomers",arguments:{term:match[1].replace(/[?.!]$/g,"")}};return{response:process.env.OPENAI_API_KEY?"I couldn't understand that request. Try including the customer, appointment, or invoice.":"Assistant AI is not configured yet. I can still answer “Who do I have today?”, “Who do I have tomorrow?”, “Find [customer]”, and “Who owes me money?”"};}
const mutationTools=new Set(["createCustomer","createAppointment","rescheduleAppointment","addJobNote","sendInvoice"]);
const audit=(context:AssistantContext,input:{actionRequestId?:string|null;actionType:string;entityType?:string|null;entityId?:string|null;before?:unknown;after?:unknown})=>context.supabase.rpc("record_ai_action_audit",{p_business_id:context.business.id,p_conversation_id:context.conversationId,p_action_request_id:input.actionRequestId??null,p_action_type:input.actionType,p_entity_type:input.entityType??"",p_entity_id:input.entityId??null,p_before:input.before??null,p_after:input.after??null,p_source:context.channel});
const customerName=(customer:any)=>customer.company_name||[customer.first_name,customer.last_name].filter(Boolean).join(" ")||"Customer";
const candidateList=(value:unknown):CustomerCandidate[]=>Array.isArray(value)?value.filter((candidate:any)=>candidate&&typeof candidate.id==="string"&&typeof candidate.displayName==="string").slice(0,10).map((candidate:any)=>({id:candidate.id,displayName:candidate.displayName,phoneLast4:typeof candidate.phoneLast4==="string"?candidate.phoneLast4:null,email:typeof candidate.email==="string"?candidate.email:null})):[];
const countWord=(count:number)=>({1:"one",2:"two",3:"three",4:"four",5:"five",6:"six",7:"seven",8:"eight",9:"nine",10:"ten"} as Record<number,string>)[count]??String(count);
const CONFIRMATION_TTL_MS=15*60*1000;
const selectionDebug=(event:string,details:Record<string,unknown>={})=>{if(process.env.ASSISTANT_SELECTION_DEBUG==="true")console.debug("Assistant pending selection",{event,...details});};
async function saveConversationContext(context:AssistantContext,conversationId:string,value:Record<string,unknown>){const {error}=await context.supabase.from("ai_conversations").update({context:value,updated_at:new Date().toISOString()}).eq("id",conversationId).eq("business_id",context.business.id).eq("user_id",context.user.id);if(error){console.error("Assistant conversation state save failed",{businessId:context.business.id,code:error.code});throw new Error("Assistant conversation state could not be saved. Please try again.");}}
async function invalidatePendingInvoiceActions(context:AssistantContext,conversationId:string){await context.supabase.from("ai_action_requests").update({status:"rejected",error:"Customer context changed.",updated_at:new Date().toISOString()}).eq("conversation_id",conversationId).eq("business_id",context.business.id).eq("user_id",context.user.id).eq("status","awaiting_confirmation").in("action_type",["markInvoicePaid"]);}

export async function processAssistantInput({context,conversationId,channel,input,requestId,provider=getAssistantProvider(),trace}:ProcessAssistantInput){
 const text=input.trim();if(!text||text.length>4000)throw new Error("Enter a message under 4,000 characters.");
 assistantTrace("request_received",{channel},trace);
 context.currentInput=text;context.requestId=typeof requestId==="string"&&/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(requestId)?requestId:randomUUID();
 let conversation:any=null;if(conversationId){const {data}=await context.supabase.from("ai_conversations").select("id,context").eq("id",conversationId).eq("business_id",context.business.id).eq("user_id",context.user.id).maybeSingle();conversation=data;}else{const {data}=await context.supabase.from("ai_conversations").select("id,context").eq("business_id",context.business.id).eq("user_id",context.user.id).eq("channel",channel).order("updated_at",{ascending:false}).limit(1).maybeSingle();conversation=data;}if(!conversation){const {data,error}=await context.supabase.from("ai_conversations").insert({business_id:context.business.id,user_id:context.user.id,channel,title:text.slice(0,80)}).select("id,context").single();if(error||!data)throw new Error("Assistant conversations are unavailable. Apply the latest database migration.");conversation=data;}
 context.conversationId=conversation.id;await context.supabase.from("ai_messages").insert({conversation_id:conversation.id,business_id:context.business.id,user_id:context.user.id,role:"user",content:text});
 if(channel==="voice"){
  const spokenIntent=classifySpokenConfirmation(text),{data:pendingActions}=await context.supabase.from("ai_action_requests").select("id,status,created_at,action_type,action_payload").eq("conversation_id",conversation.id).eq("business_id",context.business.id).eq("user_id",context.user.id).eq("status","awaiting_confirmation").order("created_at",{ascending:false}).limit(2),pendingRows=pendingActions??[];
  assistantTrace("confirmation_checked",{confirmationReceived:spokenIntent!=="none",pendingActionPresent:pendingRows.length>0},trace);
  if(spokenIntent!=="none"||pendingRows.length){let message:string,status:string|undefined,resolvedActionId:string|undefined;if(!pendingRows.length)message="There’s nothing waiting for confirmation.";else if(pendingRows.length!==1)message="I found more than one action waiting for confirmation. Please use the confirmation buttons.";else if(spokenIntent==="confirm"||spokenIntent==="reject"){assistantTrace("confirmation_received",{decision:spokenIntent},trace);const resolved=await resolveAssistantAction(context,pendingRows[0].id,spokenIntent,trace);message=resolved.message;status=resolved.status;resolvedActionId=pendingRows[0].id;}else{assistantTrace("execution_blocked_awaiting_confirmation",{},trace);message=`I still need a clear yes or no. ${await pendingActionReadback(context,pendingRows[0])}`;}await context.supabase.from("ai_messages").insert({conversation_id:conversation.id,business_id:context.business.id,user_id:context.user.id,role:"assistant",content:message});return{conversationId:conversation.id,message,confirmationMode:Boolean(pendingRows.length&&status===undefined),resolvedActionId,status};}
 }
 const persistedContext=(conversation.context&&typeof conversation.context==="object"?conversation.context:{}) as Record<string,unknown>;let activeConversationContext=persistedContext;const pending=pendingSelectionFromContext(persistedContext),customerSearchTerm=explicitCustomerSearchTerm(text),markPaidIntent=classifyMarkInvoicePaidIntent(text),globalSchedule=markPaidIntent!=="action"&&requestsGlobalSchedule(text),billingIntent=classifyBillingIntent(text),globalOutstanding=billingIntent==="outstanding_invoices_global",supersedesPending=Boolean(customerSearchTerm||markPaidIntent==="action"||globalSchedule||globalOutstanding),pendingCandidates=!supersedesPending&&pending?.type==="customer"?candidateList(pending.candidates):[];
 assistantTrace("intent_classified",{deterministicIntentDetected:Boolean(customerSearchTerm||markPaidIntent||globalSchedule||billingIntent),detectedIntent:markPaidIntent==="action"?"mark_invoice_paid":customerSearchTerm?"customer_search":globalSchedule?"global_schedule":billingIntent,billingIntent,markPaidIntent,selectedCustomerPresent:typeof persistedContext.selectedCustomerId==="string",selectedInvoicePresent:typeof persistedContext.selectedInvoiceId==="string",pendingSelectionPresent:Boolean(pending)},trace);
 selectionDebug("state_loaded",{selectedCustomerPresent:typeof persistedContext.selectedCustomerId==="string",selectedInvoicePresent:typeof persistedContext.selectedInvoiceId==="string",pendingSelectionType:pending?.type??null,pendingActionType:typeof persistedContext.pendingAction==="object"?"present":null,invoiceCandidatesPresent:Array.isArray(persistedContext.pendingInvoiceCandidates)||Array.isArray(persistedContext.invoiceCandidates),originatingIntentPresent:Boolean(pending?.originatingIntent),deterministicIntent:customerSearchTerm?"customer_search":globalSchedule?"global_schedule":classifyInvoiceSendIntent(text)==="read_only"?"invoice_activity":null});
 if((supersedesPending&&pending)||customerSearchTerm){if(pending)activeConversationContext=pendingCustomerConversationContext(activeConversationContext,[]);if(customerSearchTerm){activeConversationContext=clearCustomerChildConversationContext(activeConversationContext);await invalidatePendingInvoiceActions(context,conversation.id);}await saveConversationContext(context,conversation.id,activeConversationContext);selectionDebug("superseded",{entityType:pending?.type??"selected_invoice",currentIntent:customerSearchTerm?"customer_search":"global_schedule"});}
 if(pendingCandidates.length){selectionDebug("loaded",{entityType:pending?.type,candidateCount:pendingCandidates.length});const selection=await resolveCustomerCandidateAgainstTenant(text,pendingCandidates,async id=>{const {data}=await context.supabase.from("customers").select("id,first_name,last_name,company_name").eq("id",id).eq("business_id",context.business.id).eq("is_deleted",false).maybeSingle();return data?{id:data.id,displayName:customerName(data)}:null;});let selectionMessage:string,nextContext:Record<string,unknown>|null=null;if(selection.kind==="selected"){selectionMessage=`Got it — ${selection.candidate.displayName}.`;nextContext=selectCustomerConversationContext(persistedContext,selection.candidate.id);selectionDebug("resolved",{entityType:"customer",pendingCleared:true,orchestrationBypassed:true});}else if(selection.kind==="invalid_number"){selectionMessage=`I only found ${countWord(selection.count)} match${selection.count===1?"":"es"}. Which one did you mean?`;selectionDebug("invalid_number",{entityType:"customer",candidateCount:selection.count,orchestrationBypassed:true});}else if(selection.kind==="ambiguous"){selectionMessage="That matches more than one customer. Which numbered option did you mean?";selectionDebug("ambiguous",{entityType:"customer",candidateCount:selection.count,orchestrationBypassed:true});}else if(selection.kind==="stale"){selectionMessage="That customer is no longer available. Please search again.";nextContext=pendingCustomerConversationContext(persistedContext,[]);selectionDebug("stale",{entityType:"customer",pendingCleared:true,orchestrationBypassed:true});}else{selectionMessage=`Please choose one of the ${countWord(pendingCandidates.length)} existing matches by number or name.`;selectionDebug("unresolved",{entityType:"customer",candidateCount:pendingCandidates.length,orchestrationBypassed:true});}if(nextContext)await saveConversationContext(context,conversation.id,nextContext);await context.supabase.from("ai_messages").insert({conversation_id:conversation.id,business_id:context.business.id,user_id:context.user.id,role:"assistant",content:selectionMessage});return{conversationId:conversation.id,message:selectionMessage,...(selection.kind==="selected"?{selectedCustomerId:selection.candidate.id}:{})};}
 const persistedSelectedId=typeof persistedContext.selectedCustomerId==="string"?persistedContext.selectedCustomerId:null;
 let selectedCustomerId:string|undefined,selectedCustomerDisplayName:string|undefined;if(persistedSelectedId){const {data:selected}=await context.supabase.from("customers").select("id,first_name,last_name,company_name").eq("id",persistedSelectedId).eq("business_id",context.business.id).eq("is_deleted",false).maybeSingle();if(selected){selectedCustomerId=selected.id;selectedCustomerDisplayName=customerName(selected);context.trustedSelectedCustomerId=selected.id;}else{const cleared=clearSelectedCustomerConversationContext(persistedContext);activeConversationContext=cleared;await saveConversationContext(context,conversation.id,cleared);if(!explicitlyChangesCustomer(text)){const message="That selected customer is no longer available. Please search for the customer again.";await context.supabase.from("ai_messages").insert({conversation_id:conversation.id,business_id:context.business.id,user_id:context.user.id,role:"assistant",content:message});return{conversationId:conversation.id,message};}}}
 const persistedInvoiceId=typeof activeConversationContext.selectedInvoiceId==="string"?activeConversationContext.selectedInvoiceId:null;let selectedInvoiceId:string|undefined,selectedInvoiceNumber:string|undefined,selectedInvoiceWasStale=false;if(persistedInvoiceId){const {data:invoice}=await context.supabase.from("invoices").select("id,invoice_number,customer_id").eq("id",persistedInvoiceId).eq("business_id",context.business.id).eq("is_deleted",false).maybeSingle();if(invoice&&(!selectedCustomerId||invoice.customer_id===selectedCustomerId)){selectedInvoiceId=invoice.id;selectedInvoiceNumber=invoice.invoice_number;context.trustedSelectedInvoiceId=invoice.id;}else{selectedInvoiceWasStale=true;activeConversationContext={...activeConversationContext,selectedInvoiceId:null};await saveConversationContext(context,conversation.id,activeConversationContext);}}
 const {data:history}=await context.supabase.from("ai_messages").select("role,content").eq("conversation_id",conversation.id).in("role",["user","assistant"]).order("created_at",{ascending:true}).limit(20);
 const system=`You are Servonas Assistant for ${context.business.name}. Be concise.${channel==="voice"?" This request came from push-to-talk voice. Prefer a short, naturally spoken answer; avoid tables unless essential.":""} Use only registered tools. Never invent IDs or facts. Tenant timezone: ${context.business.timezone}. Current UTC: ${new Date().toISOString()}. ${selectedCustomerId?`A tenant-validated selected customer is active: ${selectedCustomerDisplayName}. Resolve this customer and pronouns to that customer. Do not search again.`:""} ${selectedInvoiceId?`A tenant-validated selected invoice is active: ${selectedInvoiceNumber}. Resolve “this invoice” and “that invoice” to it.`:""} Payment history means actual payment records; never substitute outstanding balances. Invoice activity must come from invoice/activity/delivery/payment records. If information is unavailable, say so honestly. Ask for clarification when identity, invoice, date, or exact required time is ambiguous. Never claim an action happened without a tool result.`;
 const activeSystem=`${system} ACTIVE STRUCTURED STATE (authoritative over transcript): customer=${selectedCustomerId?selectedCustomerDisplayName:"none"}; invoice=${selectedInvoiceId?selectedInvoiceNumber:"none"}; pending selection=${pendingSelectionFromContext(activeConversationContext)?.type??"none"}. Old transcript mentions do not reactivate cleared entity context.`;
 const invoiceSendIntent=classifyInvoiceSendIntent(text);let markPaidInvoiceId=selectedInvoiceId,markPaidMatchCount=0,invoiceResolution="none";if(markPaidIntent==="action"&&selectedInvoiceId)invoiceResolution="trusted_selected_invoice";if(markPaidIntent==="action"&&selectedInvoiceWasStale)invoiceResolution="stale";if(markPaidIntent==="action"&&!markPaidInvoiceId&&!selectedInvoiceWasStale){const number=explicitInvoiceNumber(text);let query=context.supabase.from("invoices").select("id,invoice_number").eq("business_id",context.business.id).eq("is_deleted",false).gt("balance_due_cents",0).limit(2);if(number)query=query.eq("invoice_number",number);else if(selectedCustomerId)query=query.eq("customer_id",selectedCustomerId);const {data:matches}=number||selectedCustomerId?await query:({data:[]} as {data:any[]});markPaidMatchCount=matches?.length??0;if(markPaidMatchCount===1){markPaidInvoiceId=matches![0].id;invoiceResolution="single_customer_invoice";}else if(markPaidMatchCount>1)invoiceResolution="ambiguous";}
 if(markPaidIntent==="action")assistantTrace("invoice_resolved",{result:invoiceResolution},trace);
 let decision:ProviderDecision;if(customerSearchTerm)decision={toolName:"searchCustomers",arguments:{term:customerSearchTerm}};else if(markPaidIntent==="action")decision=markPaidInvoiceId?{toolName:"markInvoicePaid",arguments:{invoiceId:markPaidInvoiceId}}:{response:selectedInvoiceWasStale?"That selected invoice is no longer available. Which invoice do you mean?":markPaidMatchCount>1?"I found more than one unpaid invoice for this customer. Which invoice do you mean?":"Which invoice do you want to mark paid?"};else if(markPaidIntent==="read_only")decision=selectedInvoiceId?{toolName:"getInvoiceActivity",arguments:{invoiceId:selectedInvoiceId}}:{response:"Which invoice do you mean?"};else if(globalSchedule)decision={toolName:"getSchedule",arguments:dayRange(/\btomorrow\b/i.test(text)?1:0,context.business.timezone)};else if(globalOutstanding)decision={toolName:"getOutstandingInvoices",arguments:{}};else if(billingIntent==="outstanding_invoices_customer"&&selectedCustomerId)decision={toolName:"getOutstandingInvoices",arguments:{customerId:selectedCustomerId}};else if(invoiceSendIntent==="read_only")decision=selectedInvoiceId?{toolName:"getInvoiceActivity",arguments:{invoiceId:selectedInvoiceId}}:{response:"Which invoice do you mean?"};else if(invoiceSendIntent==="explicit")decision=selectedInvoiceId?{toolName:"sendInvoice",arguments:{invoiceId:selectedInvoiceId}}:{response:"Which invoice do you want me to send?"};else try{decision=await provider.generateResponse({messages:(history??[]).map((m:any)=>({role:m.role as "user"|"assistant",content:m.content})),system:activeSystem,tools:assistantTools});}catch{decision=fallbackDecision(text,context.business.timezone,selectedCustomerId);}
 if(decision.usage)try{await recordAssistantProviderUsage({businessId:context.business.id,userId:context.user.id,conversationId:conversation.id,usage:decision.usage});}catch{console.error("AI provider usage recording failed",{businessId:context.business.id,provider:decision.usage.provider,model:decision.usage.model});}
 if(selectedCustomerId&&!globalOutstanding)decision=bindTrustedSelectedCustomer(text,decision,selectedCustomerId);
 if(selectedInvoiceId&&!globalOutstanding)decision=bindTrustedSelectedInvoice(text,decision,selectedInvoiceId);
 if(!("response" in decision)&&decision.toolName==="sendInvoice"){const sendIntent=classifyInvoiceSendIntent(text);if(sendIntent==="read_only")decision={toolName:"getInvoiceActivity",arguments:{invoiceId:selectedInvoiceId},usage:decision.usage};else if(sendIntent!=="explicit")decision={response:"Do you want to see when the invoice was sent, or resend it?",usage:decision.usage};}
 selectionDebug("decision",{finalTool:"response" in decision?null:decision.toolName,decisionSource:customerSearchTerm||globalSchedule||classifyInvoiceSendIntent(text)==="read_only"?"deterministic":"provider",selectedCustomerPresent:Boolean(selectedCustomerId),selectedInvoicePresent:Boolean(selectedInvoiceId),pendingSelectionType:pendingSelectionFromContext(activeConversationContext)?.type??null});
 assistantTrace("final_decision",{finalToolSelected:"response" in decision?null:decision.toolName,reason:markPaidIntent==="action"?"deterministic_mark_invoice_paid":"normal_routing",providerInvoked:!customerSearchTerm&&markPaidIntent===null&&!globalSchedule&&!globalOutstanding&&billingIntent!=="outstanding_invoices_customer"&&invoiceSendIntent===null},trace);
 let result:{message:string;data?:unknown;selectedCustomerId?:string;selectedInvoiceId?:string;actionRequest?:any};if("response" in decision)result={message:decision.response};else{if(selectedCustomerId&&!globalOutstanding&&!decision.arguments.customerId&&["getCustomer","getOutstandingInvoices","getPaymentHistory","createAppointment","searchInvoices"].includes(decision.toolName))decision.arguments.customerId=selectedCustomerId;if(selectedInvoiceId&&!globalOutstanding&&!decision.arguments.invoiceId&&["getPaymentHistory","getInvoiceActivity","sendInvoice","markInvoicePaid"].includes(decision.toolName))decision.arguments.invoiceId=selectedInvoiceId;assistantTrace("tool_invoked",{tool:decision.toolName,markInvoicePaidToolInvoked:decision.toolName==="markInvoicePaid"},trace);let toolResult;try{toolResult=await executeAssistantTool(decision.toolName,context,decision.arguments);}catch(error){assistantTrace("tool_failed",{tool:decision.toolName,errorCategory:safeAssistantErrorCategory(error)},trace);throw error;}if(toolResult.pendingAction){assistantTrace("pending_action_creation_attempted",{actionType:toolResult.pendingAction.actionType},trace);const idempotencyKey=randomUUID(),{data,error}=await context.supabase.from("ai_action_requests").insert({business_id:context.business.id,user_id:context.user.id,conversation_id:conversation.id,action_type:toolResult.pendingAction.actionType,action_payload:toolResult.pendingAction.payload,risk_level:"high",status:"awaiting_confirmation",requires_confirmation:true,idempotency_key:idempotencyKey}).select("id,status").single();if(error||!data){assistantTrace("pending_action_creation_failed",{errorCategory:"persistence_failed"},trace);throw new Error("I couldn't prepare that confirmation.");}assistantTrace("pending_action_created",{actionType:toolResult.pendingAction.actionType,status:data.status,confirmationResponseGenerated:true,executionBlockedAwaitingConfirmation:true},trace);result={message:toolResult.pendingAction.summary,actionRequest:{...data,summary:toolResult.pendingAction.summary}};}else{result=toolResult;if(mutationTools.has(decision.toolName)){await audit(context,{actionType:decision.toolName,after:{result:toolResult.data??null}});}}if(toolResult.selectedCustomerId||toolResult.selectedInvoiceId||toolResult.customerCandidates){let nextContext=activeConversationContext;if(toolResult.customerCandidates)nextContext=pendingCustomerConversationContext(nextContext,toolResult.customerCandidates,text);if(toolResult.selectedCustomerId)nextContext=selectCustomerConversationContext(nextContext,toolResult.selectedCustomerId);if(toolResult.selectedInvoiceId)nextContext={...nextContext,selectedInvoiceId:toolResult.selectedInvoiceId};await saveConversationContext(context,conversation.id,nextContext);}}
 await context.supabase.from("ai_messages").insert({conversation_id:conversation.id,business_id:context.business.id,user_id:context.user.id,role:"assistant",content:result.message,metadata:result.actionRequest?{actionRequest:result.actionRequest}:{}});return{conversationId:conversation.id,...result};
}

export async function resolveAssistantAction(context:AssistantContext,actionId:string,decision:"confirm"|"reject",trace?:AssistantTraceSink){
 assistantTrace("confirmation_resolution_started",{decision},trace);
 let actionQuery=context.supabase.from("ai_action_requests").select("*").eq("id",actionId).eq("business_id",context.business.id).eq("user_id",context.user.id);if(context.conversationId)actionQuery=actionQuery.eq("conversation_id",context.conversationId);const {data:action,error}=await actionQuery.maybeSingle();if(error||!action)throw new Error("That confirmation was not found.");if(action.status==="completed"||action.status==="rejected")return{status:action.status,message:action.status==="completed"?"That action was already completed.":"That action was canceled."};if(action.status!=="awaiting_confirmation")throw new Error("That action is no longer awaiting confirmation.");if(Date.now()-Date.parse(action.created_at)>CONFIRMATION_TTL_MS){await context.supabase.from("ai_action_requests").update({status:"rejected",error:"Confirmation expired.",updated_at:new Date().toISOString()}).eq("id",action.id).eq("status","awaiting_confirmation");throw new Error("That confirmation expired. Please request the action again.");}if(decision==="reject"){assistantTrace("confirmation_rejected",{actionType:action.action_type,status:"rejected"},trace);await context.supabase.from("ai_action_requests").update({status:"rejected",updated_at:new Date().toISOString()}).eq("id",action.id).eq("status","awaiting_confirmation");return{status:"rejected",message:"Canceled."};}
 if(action.action_type!=="markInvoicePaid")throw new Error("That action type cannot be confirmed.");if(!canManageCustomers(context.role))throw new Error("Your workspace role no longer allows financial actions.");const payload=action.action_payload as any,invoiceId=String(payload.invoiceId),amount=Number(payload.amountCents);assistantTrace("mutation_attempted",{actionType:action.action_type},trace);const claimed=await context.supabase.from("ai_action_requests").update({status:"executing",confirmed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",action.id).eq("status","awaiting_confirmation").select("id").maybeSingle();if(!claimed.data){const {data:latest}=await context.supabase.from("ai_action_requests").select("status,execution_result").eq("id",action.id).single();assistantTrace("mutation_not_claimed",{status:latest.status},trace);return{status:latest.status,message:latest.status==="completed"?"That action was already completed.":"That action is already processing."};}
 const before=await context.supabase.from("invoices").select("id,invoice_number,status,balance_due_cents").eq("id",invoiceId).eq("business_id",context.business.id).maybeSingle();if(!before.data||before.data.balance_due_cents!==amount){await context.supabase.from("ai_action_requests").update({status:"failed",error:"Invoice balance changed.",updated_at:new Date().toISOString()}).eq("id",action.id);throw new Error("The invoice balance changed. Please review it again.");}
 const {data:paymentId,error:rpcError}=await context.supabase.rpc("record_invoice_offline_payment",{p_business_id:context.business.id,p_invoice_id:invoiceId,p_amount_cents:amount,p_method:["cash","check","bank_transfer","external_card_terminal","other"].includes(payload.method)?payload.method:"other",p_received_at:new Date().toISOString(),p_reference:"Servonas Assistant",p_notes:"Confirmed through Servonas Assistant",p_idempotency_key:action.id});if(rpcError){assistantTrace("mutation_failed",{actionType:action.action_type,errorCategory:"payment_rpc_failed"},trace);await context.supabase.from("ai_action_requests").update({status:"failed",error:"Payment could not be recorded.",updated_at:new Date().toISOString()}).eq("id",action.id);throw new Error("I couldn't mark that invoice paid.");}
 const after=await context.supabase.from("invoices").select("id,invoice_number,status,balance_due_cents").eq("id",invoiceId).eq("business_id",context.business.id).single();await context.supabase.from("ai_action_requests").update({status:"completed",executed_at:new Date().toISOString(),execution_result:{paymentId,invoiceId},updated_at:new Date().toISOString()}).eq("id",action.id);context.conversationId=action.conversation_id;await audit(context,{actionRequestId:action.id,actionType:action.action_type,entityType:"invoice",entityId:invoiceId,before:before.data,after:after.data});assistantTrace("mutation_succeeded",{actionType:action.action_type,status:"completed"},trace);return{status:"completed",message:`Invoice ${after.data.invoice_number} is marked paid.`};
}

async function pendingActionReadback(context:AssistantContext,action:any){if(action.action_type!=="markInvoicePaid")return"Please use the confirmation card to review the action.";const payload=action.action_payload??{},invoiceId=String(payload.invoiceId??""),{data:invoice}=await context.supabase.from("invoices").select("invoice_number,currency,customers!invoices_customer_fk(first_name,last_name,company_name)").eq("id",invoiceId).eq("business_id",context.business.id).eq("is_deleted",false).maybeSingle();if(!invoice)return"The invoice is no longer available.";const customer=Array.isArray(invoice.customers)?invoice.customers[0]:invoice.customers,name=customerName(customer),amount=new Intl.NumberFormat("en-US",{style:"currency",currency:invoice.currency||"USD"}).format(Number(payload.amountCents||0)/100);return`Confirm marking invoice ${invoice.invoice_number} for ${name} paid (${amount})?`;}
