import {randomUUID} from "node:crypto";
import {zonedDateTimeToUtc} from "../bookingTime.ts";
import {canManageCustomers} from "../access.ts";
import {assistantTools,executeAssistantTool,type AssistantContext} from "./tools.ts";
import {getAssistantProvider,type AIProvider,type ProviderDecision} from "./provider.ts";

export type ProcessAssistantInput={context:AssistantContext;conversationId?:string|null;channel:"web"|"mobile"|"voice"|"phone_call"|"sms";input:string;provider?:AIProvider};
const dayRange=(offset:number,timeZone:string)=>{const target=new Date(Date.now()+offset*864e5),parts=new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(target),part=(t:string)=>parts.find(p=>p.type===t)?.value??"";const date=`${part("year")}-${part("month")}-${part("day")}`,start=zonedDateTimeToUtc(date,"00:00",timeZone);return{start:start.toISOString(),end:new Date(start.getTime()+864e5).toISOString()};};
function fallbackDecision(input:string,timeZone:string,selectedCustomerId?:string):ProviderDecision{const lower=input.toLowerCase();if(/who.*today|have today|schedule today/.test(lower))return{toolName:"getSchedule",arguments:dayRange(0,timeZone)};if(/tomorrow|who.*tomorrow/.test(lower)&&/who|schedule|appointment|have/.test(lower))return{toolName:"getSchedule",arguments:dayRange(1,timeZone)};if(/owe|outstanding|overdue/.test(lower))return{toolName:"getOutstandingInvoices",arguments:selectedCustomerId?{customerId:selectedCustomerId}:{}};const match=input.match(/(?:find|search for|look up)\s+(.+)/i);if(match)return{toolName:"searchCustomers",arguments:{term:match[1].replace(/[?.!]$/g,"")}};return{response:process.env.OPENAI_API_KEY?"I couldn't understand that request. Try including the customer, appointment, or invoice.":"Assistant AI is not configured yet. I can still answer “Who do I have today?”, “Who do I have tomorrow?”, “Find [customer]”, and “Who owes me money?”"};}
const mutationTools=new Set(["createCustomer","createAppointment","rescheduleAppointment","addJobNote"]);
const audit=(context:AssistantContext,input:{actionRequestId?:string|null;actionType:string;entityType?:string|null;entityId?:string|null;before?:unknown;after?:unknown})=>context.supabase.rpc("record_ai_action_audit",{p_business_id:context.business.id,p_conversation_id:context.conversationId,p_action_request_id:input.actionRequestId??null,p_action_type:input.actionType,p_entity_type:input.entityType??"",p_entity_id:input.entityId??null,p_before:input.before??null,p_after:input.after??null,p_source:context.channel});

export async function processAssistantInput({context,conversationId,channel,input,provider=getAssistantProvider()}:ProcessAssistantInput){
 const text=input.trim();if(!text||text.length>4000)throw new Error("Enter a message under 4,000 characters.");
 let conversation:any=null;if(conversationId){const {data}=await context.supabase.from("ai_conversations").select("id,context").eq("id",conversationId).eq("business_id",context.business.id).eq("user_id",context.user.id).maybeSingle();conversation=data;}if(!conversation){const {data,error}=await context.supabase.from("ai_conversations").insert({business_id:context.business.id,user_id:context.user.id,channel,title:text.slice(0,80)}).select("id,context").single();if(error||!data)throw new Error("Assistant conversations are unavailable. Apply the latest database migration.");conversation=data;}
 context.conversationId=conversation.id;await context.supabase.from("ai_messages").insert({conversation_id:conversation.id,business_id:context.business.id,user_id:context.user.id,role:"user",content:text});
 const {data:history}=await context.supabase.from("ai_messages").select("role,content").eq("conversation_id",conversation.id).in("role",["user","assistant"]).order("created_at",{ascending:true}).limit(20),selectedCustomerId=conversation.context?.selectedCustomerId as string|undefined;
 const system=`You are Servonas Assistant for ${context.business.name}. Be concise. Use only registered tools. Never invent IDs or facts. Tenant timezone: ${context.business.timezone}. Current UTC: ${new Date().toISOString()}. ${selectedCustomerId?`The selected customer ID is ${selectedCustomerId}; use it for clear conversational references.`:""} Ask for clarification when identity, invoice, date, or exact required time is ambiguous. Never claim an action happened without a tool result.`;
 let decision:ProviderDecision;try{decision=await provider.generateResponse({messages:(history??[]).map((m:any)=>({role:m.role as "user"|"assistant",content:m.content})),system,tools:assistantTools});}catch{decision=fallbackDecision(text,context.business.timezone,selectedCustomerId);}
 let result:{message:string;data?:unknown;selectedCustomerId?:string;actionRequest?:any};if("response" in decision)result={message:decision.response};else{if(selectedCustomerId&&!decision.arguments.customerId&&["getCustomer","getOutstandingInvoices","createAppointment"].includes(decision.toolName))decision.arguments.customerId=selectedCustomerId;const toolResult=await executeAssistantTool(decision.toolName,context,decision.arguments);if(toolResult.pendingAction){const idempotencyKey=randomUUID(),{data,error}=await context.supabase.from("ai_action_requests").insert({business_id:context.business.id,user_id:context.user.id,conversation_id:conversation.id,action_type:toolResult.pendingAction.actionType,action_payload:toolResult.pendingAction.payload,risk_level:"high",status:"awaiting_confirmation",requires_confirmation:true,idempotency_key:idempotencyKey}).select("id,status").single();if(error||!data)throw new Error("I couldn't prepare that confirmation.");result={message:toolResult.pendingAction.summary,actionRequest:{...data,summary:toolResult.pendingAction.summary}};}else{result=toolResult;if(mutationTools.has(decision.toolName)){await audit(context,{actionType:decision.toolName,after:{result:toolResult.data??null}});}}if(toolResult.selectedCustomerId){await context.supabase.from("ai_conversations").update({context:{...(conversation.context??{}),selectedCustomerId:toolResult.selectedCustomerId},updated_at:new Date().toISOString()}).eq("id",conversation.id).eq("business_id",context.business.id).eq("user_id",context.user.id);}}
 await context.supabase.from("ai_messages").insert({conversation_id:conversation.id,business_id:context.business.id,user_id:context.user.id,role:"assistant",content:result.message,metadata:result.actionRequest?{actionRequest:result.actionRequest}:{}});return{conversationId:conversation.id,...result};
}

export async function resolveAssistantAction(context:AssistantContext,actionId:string,decision:"confirm"|"reject"){
 const {data:action,error}=await context.supabase.from("ai_action_requests").select("*").eq("id",actionId).eq("business_id",context.business.id).eq("user_id",context.user.id).maybeSingle();if(error||!action)throw new Error("That confirmation was not found.");if(action.status==="completed"||action.status==="rejected")return{status:action.status,message:action.status==="completed"?"That action was already completed.":"That action was canceled."};if(action.status!=="awaiting_confirmation")throw new Error("That action is no longer awaiting confirmation.");if(decision==="reject"){await context.supabase.from("ai_action_requests").update({status:"rejected",updated_at:new Date().toISOString()}).eq("id",action.id).eq("status","awaiting_confirmation");return{status:"rejected",message:"Canceled."};}
 if(action.action_type!=="markInvoicePaid")throw new Error("That action type cannot be confirmed.");if(!canManageCustomers(context.role))throw new Error("Your workspace role no longer allows financial actions.");const payload=action.action_payload as any,invoiceId=String(payload.invoiceId),amount=Number(payload.amountCents);const claimed=await context.supabase.from("ai_action_requests").update({status:"executing",confirmed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",action.id).eq("status","awaiting_confirmation").select("id").maybeSingle();if(!claimed.data){const {data:latest}=await context.supabase.from("ai_action_requests").select("status,execution_result").eq("id",action.id).single();return{status:latest.status,message:latest.status==="completed"?"That action was already completed.":"That action is already processing."};}
 const before=await context.supabase.from("invoices").select("id,invoice_number,status,balance_due_cents").eq("id",invoiceId).eq("business_id",context.business.id).maybeSingle();if(!before.data||before.data.balance_due_cents!==amount){await context.supabase.from("ai_action_requests").update({status:"failed",error:"Invoice balance changed.",updated_at:new Date().toISOString()}).eq("id",action.id);throw new Error("The invoice balance changed. Please review it again.");}
 const {data:paymentId,error:rpcError}=await context.supabase.rpc("record_invoice_offline_payment",{p_business_id:context.business.id,p_invoice_id:invoiceId,p_amount_cents:amount,p_method:["cash","check","bank_transfer","external_card_terminal","other"].includes(payload.method)?payload.method:"other",p_received_at:new Date().toISOString(),p_reference:"Servonas Assistant",p_notes:"Confirmed through Servonas Assistant",p_idempotency_key:action.id});if(rpcError){await context.supabase.from("ai_action_requests").update({status:"failed",error:"Payment could not be recorded.",updated_at:new Date().toISOString()}).eq("id",action.id);throw new Error("I couldn't mark that invoice paid.");}
 const after=await context.supabase.from("invoices").select("id,invoice_number,status,balance_due_cents").eq("id",invoiceId).eq("business_id",context.business.id).single();await context.supabase.from("ai_action_requests").update({status:"completed",executed_at:new Date().toISOString(),execution_result:{paymentId,invoiceId},updated_at:new Date().toISOString()}).eq("id",action.id);context.conversationId=action.conversation_id;await audit(context,{actionRequestId:action.id,actionType:action.action_type,entityType:"invoice",entityId:invoiceId,before:before.data,after:after.data});return{status:"completed",message:`Invoice ${after.data.invoice_number} is marked paid.`};
}
