import {randomUUID} from "node:crypto";
import {canManageCustomers} from "../access.ts";
import {validateJobSchedule} from "../jobScheduling.ts";
import type {CustomerCandidate} from "./customerCandidateResolution.ts";

export type AssistantContext={supabase:any;business:{id:string;name:string;slug:string;timezone:string};user:{id:string};role:string;conversationId:string;channel:string;trustedSelectedCustomerId?:string};
export type ToolResult={message:string;data?:unknown;selectedCustomerId?:string;customerCandidates?:CustomerCandidate[];pendingAction?:{actionType:string;payload:Record<string,unknown>;summary:string;entityType?:string;entityId?:string}};
export type ToolDefinition={name:string;risk:"low"|"medium"|"high";description:string;parameters:Record<string,unknown>;execute:(context:AssistantContext,args:Record<string,unknown>)=>Promise<ToolResult>};

const uuid=(v:unknown)=>typeof v==="string"&&/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(v)?v:null;
const string=(v:unknown,max=500)=>typeof v==="string"&&v.trim()&&v.trim().length<=max?v.trim():null;
const integer=(v:unknown,min:number,max:number)=>Number.isInteger(v)&&Number(v)>=min&&Number(v)<=max?Number(v):null;
const money=(cents:number,currency="USD")=>new Intl.NumberFormat("en-US",{style:"currency",currency}).format(cents/100);
const customerName=(c:any)=>c.company_name||[c.first_name,c.last_name].filter(Boolean).join(" ")||"Customer";
const requireManager=(context:AssistantContext)=>{if(!canManageCustomers(context.role))throw new Error("Your workspace role does not allow this action.");};
const owned=async(context:AssistantContext,table:string,id:unknown,columns="*")=>{const entityId=uuid(id);if(!entityId)throw new Error("Choose a valid record.");const {data,error}=await context.supabase.from(table).select(columns).eq("id",entityId).eq("business_id",context.business.id).maybeSingle();if(error)throw new Error("I couldn't load that record.");if(!data)throw new Error("That record was not found in this workspace.");return data;};
const requireSelectedCustomerMatch=(context:AssistantContext,customerId:unknown)=>{if(context.trustedSelectedCustomerId&&customerId!==context.trustedSelectedCustomerId)throw new Error("That record does not belong to the selected customer.");};
const safeTerm=(v:unknown)=>string(v,100)?.replace(/[%_,()]/g," ").replace(/\s+/g," ")??null;

const searchCustomers:ToolDefinition={name:"searchCustomers",risk:"low",description:"Find customers by name, company, email, or phone.",parameters:{type:"object",properties:{term:{type:"string"}},required:["term"],additionalProperties:false},async execute(c,a){const term=safeTerm(a.term);if(!term)throw new Error("Enter a customer name or phone number.");const digits=term.replace(/\D/g,"");let q=c.supabase.from("customers").select("id,first_name,last_name,company_name,email,phone").eq("business_id",c.business.id).eq("is_deleted",false).limit(10);q=digits.length>=4?q.or(`phone.ilike.%${digits}%,first_name.ilike.%${term}%,last_name.ilike.%${term}%,company_name.ilike.%${term}%`):q.or(`first_name.ilike.%${term}%,last_name.ilike.%${term}%,company_name.ilike.%${term}%,email.ilike.%${term}%`);const {data,error}=await q;if(error)throw new Error("I couldn't search customers.");const rows=data??[],candidates:CustomerCandidate[]=rows.map((row:any)=>({id:row.id,displayName:customerName(row),phoneLast4:row.phone?.replace(/\D/g,"").slice(-4)||null,email:row.email||null}));if(!rows.length)return{message:`I couldn't find a customer matching “${term}”.`,data:[],customerCandidates:[]};if(rows.length===1){const row=rows[0];return{message:`I found ${customerName(row)}${row.phone?` — ${row.phone}`:""}.`,data:rows,selectedCustomerId:row.id,customerCandidates:[]};}return{message:`I found ${rows.length} matches:\n${rows.map((r:any,i:number)=>`${i+1}. ${customerName(r)}${r.phone?` — phone ending ${r.phone.replace(/\D/g,"").slice(-4)}`:""}`).join("\n")}\nWhich one?`,data:rows,customerCandidates:candidates};}};

const getCustomer:ToolDefinition={name:"getCustomer",risk:"low",description:"Get one customer's contact details, locations, recent jobs, upcoming appointments, and outstanding balance.",parameters:{type:"object",properties:{customerId:{type:"string"}},required:["customerId"],additionalProperties:false},async execute(c,a){const row=await owned(c,"customers",a.customerId,"id,first_name,last_name,company_name,email,phone,notes");const [{data:locations},{data:jobs},{data:invoices}]=await Promise.all([c.supabase.from("service_locations").select("id,location_name,street_address,city,state,postal_code").eq("business_id",c.business.id).eq("customer_id",row.id).eq("is_deleted",false).limit(5),c.supabase.from("jobs").select("id,job_number,title,status,starts_at,ends_at").eq("business_id",c.business.id).eq("customer_id",row.id).eq("is_deleted",false).order("starts_at",{ascending:false}).limit(10),c.supabase.from("invoices").select("id,invoice_number,status,balance_due_cents,currency,due_date").eq("business_id",c.business.id).eq("customer_id",row.id).eq("is_deleted",false).gt("balance_due_cents",0)]);const balance=(invoices??[]).reduce((n:number,i:any)=>n+Number(i.balance_due_cents||0),0),upcoming=(jobs??[]).filter((job:any)=>job.starts_at&&Date.parse(job.starts_at)>=Date.now()&&!['canceled','declined'].includes(job.status));return{message:`${customerName(row)}${balance?` owes ${money(balance,invoices?.[0]?.currency)} across ${invoices!.length} invoice${invoices!.length===1?"":"s"}`:" has no outstanding balance"}. ${upcoming.length?`${upcoming.length} upcoming appointment${upcoming.length===1?"":"s"}: ${upcoming.map((job:any)=>`${job.title} on ${new Intl.DateTimeFormat("en-US",{timeZone:c.business.timezone,dateStyle:"medium",timeStyle:"short"}).format(new Date(job.starts_at))}`).join(", ")}.`:"No upcoming appointments."}`,data:{customer:row,locations,jobs,invoices},selectedCustomerId:row.id};}};

const getSchedule:ToolDefinition={name:"getSchedule",risk:"low",description:"Get scheduled appointments in an ISO date range.",parameters:{type:"object",properties:{start:{type:"string"},end:{type:"string"},customerId:{type:"string"}},required:["start","end"],additionalProperties:false},async execute(c,a){const start=string(a.start,40),end=string(a.end,40);if(!start||!end||Number.isNaN(Date.parse(start))||Number.isNaN(Date.parse(end))||Date.parse(end)<=Date.parse(start)||Date.parse(end)-Date.parse(start)>31*864e5)throw new Error("Choose a schedule range of 31 days or less.");let query=c.supabase.from("jobs").select("id,job_number,title,status,starts_at,ends_at,customers!jobs_customer_tenant_fk(first_name,last_name,company_name)").eq("business_id",c.business.id).eq("is_deleted",false).gte("starts_at",start).lt("starts_at",end).not("status","in",'(canceled,declined)');if(a.customerId){const customerId=uuid(a.customerId);if(!customerId)throw new Error("Choose a valid customer.");query=query.eq("customer_id",customerId);}const {data,error}=await query.order("starts_at");if(error)throw new Error("I couldn't load the schedule.");const rows=data??[],format=(v:string)=>new Intl.DateTimeFormat("en-US",{timeZone:c.business.timezone,weekday:"short",hour:"numeric",minute:"2-digit"}).format(new Date(v));return{message:rows.length?`You have ${rows.length} appointment${rows.length===1?"":"s"}:\n${rows.map((j:any)=>`${format(j.starts_at)} — ${customerName(Array.isArray(j.customers)?j.customers[0]:j.customers)} — ${j.title}`).join("\n")}`:"You have no appointments in that time range.",data:rows};}};

const createCustomer:ToolDefinition={name:"createCustomer",risk:"medium",description:"Create a customer.",parameters:{type:"object",properties:{firstName:{type:"string"},lastName:{type:"string"},email:{type:"string"},phone:{type:"string"},notes:{type:"string"}},required:["firstName","email","phone"],additionalProperties:false},async execute(c,a){requireManager(c);const firstName=string(a.firstName,100),lastName=string(a.lastName,100),email=string(a.email,320),phone=string(a.phone,40);if(!firstName||!email||!/^\S+@\S+\.\S+$/.test(email)||!phone)throw new Error("A first name, valid email, and phone number are required.");const {data,error}=await c.supabase.from("customers").insert({business_id:c.business.id,first_name:firstName,last_name:lastName??"",email:email.toLowerCase(),phone,notes:string(a.notes,4000),is_active:true,created_by:c.user.id,updated_by:c.user.id}).select("id,first_name,last_name").single();if(error?.code==="23505")throw new Error("A customer with that email already exists.");if(error||!data)throw new Error("I couldn't create that customer.");return{message:`${customerName(data)} was created.`,data,selectedCustomerId:data.id};}};

const createAppointment:ToolDefinition={name:"createAppointment",risk:"medium",description:"Create a scheduled job appointment for a customer.",parameters:{type:"object",properties:{customerId:{type:"string"},title:{type:"string"},startsAt:{type:"string"},durationMinutes:{type:"integer"},serviceLocationId:{type:"string"},technicianId:{type:"string"}},required:["customerId","title","startsAt","durationMinutes"],additionalProperties:false},async execute(c,a){requireManager(c);const customer=await owned(c,"customers",a.customerId,"id,first_name,last_name,company_name"),title=string(a.title,200),duration=integer(a.durationMinutes,15,10080),starts=new Date(String(a.startsAt));if(!title||!duration||Number.isNaN(starts.getTime()))throw new Error("A title, exact start time, and valid duration are required.");const ends=new Date(starts.getTime()+duration*60000),locationId=a.serviceLocationId?uuid(a.serviceLocationId):null,techId=a.technicianId?uuid(a.technicianId):null;if(locationId){const l=await owned(c,"service_locations",locationId,"id,customer_id");if(l.customer_id!==customer.id)throw new Error("That location does not belong to the customer.");}const conflict=await validateJobSchedule({supabase:c.supabase,businessId:c.business.id,timeZone:c.business.timezone,startsAt:starts,endsAt:ends,arrivalWindowStart:null,arrivalWindowEnd:null,technicianId:techId,excludeJobId:undefined});if(conflict)throw new Error(conflict);const requestKey=randomUUID(),{data,error}=await c.supabase.from("jobs").insert({business_id:c.business.id,customer_id:customer.id,service_location_id:locationId,title,status:"scheduled",priority:"normal",schedule_commitment:"fixed",starts_at:starts.toISOString(),ends_at:ends.toISOString(),estimated_duration_minutes:duration,payment_status:"unpaid",booking_source:"assistant",request_key:requestKey,created_by:c.user.id,updated_by:c.user.id}).select("id,job_number,title,starts_at").single();if(error||!data)throw new Error("I couldn't create the appointment.");if(techId)await c.supabase.rpc("set_job_primary_technician",{p_job_id:data.id,p_technician_id:techId});return{message:`${customerName(customer)} is scheduled for ${new Intl.DateTimeFormat("en-US",{timeZone:c.business.timezone,weekday:"long",hour:"numeric",minute:"2-digit"}).format(starts)}.`,data};}};

const rescheduleAppointment:ToolDefinition={name:"rescheduleAppointment",risk:"medium",description:"Move an existing appointment to an exact new time.",parameters:{type:"object",properties:{jobId:{type:"string"},startsAt:{type:"string"},durationMinutes:{type:"integer"}},required:["jobId","startsAt"],additionalProperties:false},async execute(c,a){requireManager(c);const job=await owned(c,"jobs",a.jobId,"id,title,customer_id,starts_at,ends_at,assigned_technician_id,arrival_window_start,arrival_window_end");requireSelectedCustomerMatch(c,job.customer_id);const starts=new Date(String(a.startsAt)),oldDuration=Math.max(15,Math.round((Date.parse(job.ends_at)-Date.parse(job.starts_at))/60000)),duration=integer(a.durationMinutes,15,10080)??oldDuration;if(Number.isNaN(starts.getTime()))throw new Error("Choose an exact new appointment time.");const ends=new Date(starts.getTime()+duration*60000),conflict=await validateJobSchedule({supabase:c.supabase,businessId:c.business.id,timeZone:c.business.timezone,startsAt:starts,endsAt:ends,arrivalWindowStart:job.arrival_window_start?new Date(job.arrival_window_start):null,arrivalWindowEnd:job.arrival_window_end?new Date(job.arrival_window_end):null,technicianId:job.assigned_technician_id,excludeJobId:job.id});if(conflict)throw new Error(conflict);const {error}=await c.supabase.from("jobs").update({starts_at:starts.toISOString(),ends_at:ends.toISOString(),estimated_duration_minutes:duration,updated_by:c.user.id}).eq("id",job.id).eq("business_id",c.business.id);if(error)throw new Error("I couldn't move that appointment.");return{message:`${job.title} is moved to ${new Intl.DateTimeFormat("en-US",{timeZone:c.business.timezone,weekday:"long",hour:"numeric",minute:"2-digit"}).format(starts)}.`,data:{id:job.id}};}};

const searchInvoices:ToolDefinition={name:"searchInvoices",risk:"low",description:"Search invoices by invoice number, customer, or status.",parameters:{type:"object",properties:{term:{type:"string"},status:{type:"string"},customerId:{type:"string"}},additionalProperties:false},async execute(c,a){let q=c.supabase.from("invoices").select("id,invoice_number,status,grand_total_cents,balance_due_cents,currency,due_date,customers!invoices_customer_fk(first_name,last_name,company_name)").eq("business_id",c.business.id).eq("is_deleted",false).limit(20);if(a.customerId){const id=uuid(a.customerId);if(!id)throw new Error("Choose a valid customer.");q=q.eq("customer_id",id);}if(string(a.status,30))q=q.eq("status",String(a.status));if(safeTerm(a.term))q=q.ilike("invoice_number",`%${safeTerm(a.term)}%`);const {data,error}=await q;if(error)throw new Error("I couldn't search invoices.");const rows=data??[];return{message:rows.length?rows.map((i:any)=>`${i.invoice_number} — ${customerName(Array.isArray(i.customers)?i.customers[0]:i.customers)} — ${money(Number(i.balance_due_cents),i.currency)} due`).join("\n"):"I couldn't find a matching invoice.",data:rows};}};

const outstanding:ToolDefinition={name:"getOutstandingInvoices",risk:"low",description:"List unpaid or overdue invoices and totals.",parameters:{type:"object",properties:{customerId:{type:"string"}},additionalProperties:false},async execute(c,a){let q=c.supabase.from("invoices").select("id,invoice_number,status,balance_due_cents,currency,due_date,customer_id,customers!invoices_customer_fk(first_name,last_name,company_name)").eq("business_id",c.business.id).eq("is_deleted",false).gt("balance_due_cents",0).order("due_date");if(a.customerId){const id=uuid(a.customerId);if(!id)throw new Error("Choose a valid customer.");q=q.eq("customer_id",id);}const {data,error}=await q;if(error)throw new Error("I couldn't load outstanding invoices.");const rows=data??[],total=rows.reduce((n:number,i:any)=>n+Number(i.balance_due_cents),0);return{message:rows.length?`${rows.length} invoice${rows.length===1?"":"s"} outstanding — ${money(total,rows[0].currency)} total:\n${rows.map((i:any)=>`${i.invoice_number} — ${customerName(Array.isArray(i.customers)?i.customers[0]:i.customers)} — ${money(Number(i.balance_due_cents),i.currency)}`).join("\n")}`:"No outstanding invoices.",data:rows};}};

const markPaid:ToolDefinition={name:"markInvoicePaid",risk:"high",description:"Mark an invoice fully paid by recording an offline payment. Always requires confirmation.",parameters:{type:"object",properties:{invoiceId:{type:"string"},method:{type:"string"}},required:["invoiceId"],additionalProperties:false},async execute(c,a){requireManager(c);const invoice=await owned(c,"invoices",a.invoiceId,"id,invoice_number,status,balance_due_cents,currency,customer_id,customers!invoices_customer_fk(first_name,last_name,company_name)");requireSelectedCustomerMatch(c,invoice.customer_id);if(Number(invoice.balance_due_cents)<=0)throw new Error("That invoice is already paid.");const customer=Array.isArray(invoice.customers)?invoice.customers[0]:invoice.customers;return{message:"Confirmation required.",pendingAction:{actionType:"markInvoicePaid",payload:{invoiceId:invoice.id,amountCents:Number(invoice.balance_due_cents),method:string(a.method,30)??"other"},summary:`Mark invoice ${invoice.invoice_number} for ${customerName(customer)} paid (${money(Number(invoice.balance_due_cents),invoice.currency)})?`,entityType:"invoice",entityId:invoice.id}};}};

const addJobNote:ToolDefinition={name:"addJobNote",risk:"medium",description:"Add an internal note to a job.",parameters:{type:"object",properties:{jobId:{type:"string"},note:{type:"string"}},required:["jobId","note"],additionalProperties:false},async execute(c,a){requireManager(c);const job=await owned(c,"jobs",a.jobId,"id,title,customer_id");requireSelectedCustomerMatch(c,job.customer_id);const note=string(a.note,4000);if(!note)throw new Error("Enter a note.");const {data,error}=await c.supabase.from("job_notes").insert({business_id:c.business.id,job_id:job.id,body:note,note_type:"office",author_user_id:c.user.id,author_name:"Servonas Assistant"}).select("id").single();if(error||!data)throw new Error("I couldn't add that note.");return{message:`Note added to ${job.title}.`,data};}};

export const assistantTools=[searchCustomers,getCustomer,createCustomer,getSchedule,createAppointment,rescheduleAppointment,searchInvoices,markPaid,addJobNote,outstanding] as const;
export const assistantToolRegistry=new Map<string,ToolDefinition>(assistantTools.map(tool=>[tool.name,tool]));
export async function executeAssistantTool(name:string,context:AssistantContext,args:unknown){const tool=assistantToolRegistry.get(name);if(!tool)throw new Error("That Assistant action is not available.");if(!args||typeof args!=="object"||Array.isArray(args))throw new Error("The Assistant supplied invalid action details.");return tool.execute(context,args as Record<string,unknown>);}
