"use server";
import {revalidatePath} from "next/cache";
import {createSupabaseServerClient} from "@/lib/supabaseServer";
import {isServonasPlatformAdmin} from "@/lib/platformAccess";
import {getSupabaseAdmin} from "@/lib/supabaseAdmin";

async function admin(){const db=await createSupabaseServerClient(),{data:{user}}=await db.auth.getUser();if(!isServonasPlatformAdmin(user))return null;return{db,user:user!};}
const uuid=(value:string)=>/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(value);
export async function setPlatformFeature(input:{businessId:string;feature:"ai"|"twilio";enabled:boolean}){const context=await admin();if(!context)return{ok:false,error:"Platform administrator access is required."};if(!uuid(input.businessId))return{ok:false,error:"Invalid business."};const rpc=input.feature==="ai"?"admin_set_business_ai_assistant_access":"admin_set_business_twilio_access",{error}=await context.db.rpc(rpc,{p_business_id:input.businessId,p_enabled:input.enabled,p_changed_by:context.user.id,p_reason:"Changed from consolidated admin dashboard"});if(error){console.error("Admin feature toggle failed",{businessId:input.businessId,feature:input.feature,code:error.code});return{ok:false,error:"Access could not be changed."};}revalidatePath("/admin");return{ok:true};}
export async function setWebsiteManagement(input:{businessId:string;enabled:boolean;monthlyCostCents:number}){const context=await admin();if(!context)return{ok:false,error:"Platform administrator access is required."};if(!uuid(input.businessId)||!Number.isInteger(input.monthlyCostCents)||input.monthlyCostCents<0)return{ok:false,error:"Enter a valid monthly website cost."};const {error}=await context.db.rpc("admin_set_business_website_management",{p_business_id:input.businessId,p_enabled:input.enabled,p_monthly_cost_cents:input.monthlyCostCents});if(error){console.error("Website management toggle failed",{businessId:input.businessId,code:error.code});return{ok:false,error:"Website management could not be changed. Apply the admin dashboard migration."};}revalidatePath("/admin");return{ok:true};}
export async function setBusinessLifecycle(input:{businessId:string;active:boolean}){const context=await admin();if(!context)return{ok:false,error:"Platform administrator access is required."};if(!uuid(input.businessId))return{ok:false,error:"Invalid business."};const {error}=await context.db.rpc("admin_set_business_lifecycle",{p_business_id:input.businessId,p_active:input.active});if(error){console.error("Business lifecycle change failed",{businessId:input.businessId,code:error.code});return{ok:false,error:"Account access could not be changed. Apply the admin dashboard migration."};}revalidatePath("/admin");return{ok:true};}
export async function permanentlyDeleteBusiness(input:{businessId:string;businessName:string;confirmation:string}){const context=await admin();if(!context)return{ok:false,error:"Platform administrator access is required."};if(!uuid(input.businessId)||input.confirmation!=="DELETE")return{ok:false,error:"Permanent deletion was not confirmed."};const {error}=await context.db.rpc("admin_delete_business_permanently",{p_business_id:input.businessId,p_business_name:input.businessName,p_confirmation:input.confirmation});if(error){console.error("Permanent business deletion failed",{businessId:input.businessId,code:error.code,constraint:typeof error.details==="string"?error.details.match(/constraint \"([^\"]+)\"/)?.[1]??null:null});return{ok:false,error:error.code==="PGRST202"?"Apply the safe platform business deletion migration, then try again.":"The business could not be deleted. No partial database deletion was committed."};}revalidatePath("/admin");return{ok:true};}

const clean=(value:FormDataEntryValue|null,max:number)=>String(value??"").trim().replace(/\r\n/g,"\n").slice(0,max);
export async function sendPlatformEmailCampaign(data:FormData){
 const context=await admin();if(!context)return{ok:false,error:"Platform administrator access is required."};
 const subject=clean(data.get("subject"),160),body=clean(data.get("body"),5000),sendToken=String(data.get("sendToken")??"");
 if(data.get("confirm")!=="on")return{ok:false,error:"Confirm that you want to send this email to every eligible Servonas customer."};
 if(!subject||!body||!/^[0-9a-f-]{36}$/i.test(sendToken))return{ok:false,error:"Enter a subject and message before sending."};
 const db=getSupabaseAdmin();if(!db)return{ok:false,error:"Platform email delivery is unavailable."};
 const {data:existing}=await db.from("platform_email_campaigns").select("sent_count,skipped_count,failed_count").eq("send_token",sendToken).maybeSingle();
 if(existing)return{ok:true,sent:existing.sent_count,skipped:existing.skipped_count,failed:existing.failed_count};
 const {data:businesses,error:businessError}=await db.from("businesses").select("id,name,email").eq("is_deleted",false).not("email","is",null).limit(1000);
 if(businessError)return{ok:false,error:"Customer email addresses could not be loaded."};
 const candidates=(businesses??[]).map(business=>({...business,email:String(business.email??"").trim().toLowerCase()})).filter(row=>/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(row.email));
 const {data:optOuts}=candidates.length?await db.from("platform_email_opt_outs").select("email").in("email",candidates.map(row=>row.email)): {data:[]};
 const optedOut=new Set((optOuts??[]).map(row=>String(row.email).toLowerCase())),eligible=candidates.filter(row=>!optedOut.has(row.email));
 const {data:campaign,error:campaignError}=await db.from("platform_email_campaigns").insert({send_token:sendToken,subject,body,status:"sending",recipient_count:candidates.length,skipped_count:candidates.length-eligible.length,created_by:context.user.id}).select("id").single();
 if(campaignError||!campaign)return{ok:false,error:"The email campaign could not be saved. Apply the platform email migration."};
 if(eligible.length){const {error}=await db.from("platform_email_recipients").insert(eligible.map(row=>({campaign_id:campaign.id,business_id:row.id,business_name:row.name,recipient_email:row.email,status:"queued"})));if(error){await db.from("platform_email_campaigns").update({status:"failed",completed_at:new Date().toISOString()}).eq("id",campaign.id);return{ok:false,error:"The email recipients could not be saved."};}}
 const apiKey=process.env.RESEND_API_KEY?.trim(),configuredFrom=process.env.EMAIL_FROM?.trim();
 if(!apiKey||!configuredFrom){await db.from("platform_email_campaigns").update({status:"failed",failed_count:eligible.length,completed_at:new Date().toISOString()}).eq("id",campaign.id);return{ok:false,error:"Email delivery is not configured."};}
 const origin=(process.env.NEXT_PUBLIC_SITE_URL||process.env.NEXT_PUBLIC_APP_URL||"https://servonas.com").replace(/\/$/,""),sendingAddress=configuredFrom.match(/<\s*([^>]+)\s*>/)?.[1]?.trim()||configuredFrom,recipients=(await db.from("platform_email_recipients").select("id,recipient_email,business_name,tracking_token").eq("campaign_id",campaign.id)).data??[];
 let sent=0,failed=0;for(const recipient of recipients){const unsubscribeUrl=`${origin}/platform-unsubscribe/${recipient.tracking_token}`,html=`<div style="font-family:Arial,sans-serif;line-height:1.65;color:#172033"><p>${body.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\n/g,"<br/>")}</p><p style="margin-top:28px;color:#667085;font-size:12px">Sent by Servonas. <a href="${unsubscribeUrl}" style="color:#667085">Unsubscribe from platform announcements</a>.</p></div>`;try{const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({from:`Servonas <${sendingAddress}>`,to:[recipient.recipient_email],subject,text:`${body}\n\nUnsubscribe from Servonas platform announcements: ${unsubscribeUrl}`,html,headers:{"List-Unsubscribe":`<${unsubscribeUrl}>`}})}),result=await response.json() as {id?:string};if(!response.ok||!result.id)throw new Error("provider_rejected");await db.from("platform_email_recipients").update({status:"sent",provider_message_id:result.id,sent_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",recipient.id);sent++;}catch{await db.from("platform_email_recipients").update({status:"failed",error_message:"Email delivery failed.",updated_at:new Date().toISOString()}).eq("id",recipient.id);failed++;}}
 await db.from("platform_email_campaigns").update({status:failed?(sent?"partially_failed":"failed"):"sent",sent_count:sent,failed_count:failed,completed_at:new Date().toISOString()}).eq("id",campaign.id);revalidatePath("/admin");return{ok:true,sent,skipped:candidates.length-eligible.length,failed};
}
