"use server";
import {revalidatePath} from "next/cache";
import {createSupabaseServerClient} from "@/lib/supabaseServer";
import {isServonasPlatformAdmin} from "@/lib/platformAccess";

async function admin(){const db=await createSupabaseServerClient(),{data:{user}}=await db.auth.getUser();if(!isServonasPlatformAdmin(user))return null;return{db,user:user!};}
const uuid=(value:string)=>/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(value);
export async function setPlatformFeature(input:{businessId:string;feature:"ai"|"twilio";enabled:boolean}){const context=await admin();if(!context)return{ok:false,error:"Platform administrator access is required."};if(!uuid(input.businessId))return{ok:false,error:"Invalid business."};const rpc=input.feature==="ai"?"admin_set_business_ai_assistant_access":"admin_set_business_twilio_access",{error}=await context.db.rpc(rpc,{p_business_id:input.businessId,p_enabled:input.enabled,p_changed_by:context.user.id,p_reason:"Changed from consolidated admin dashboard"});if(error){console.error("Admin feature toggle failed",{businessId:input.businessId,feature:input.feature,code:error.code});return{ok:false,error:"Access could not be changed."};}revalidatePath("/admin");return{ok:true};}
export async function setWebsiteManagement(input:{businessId:string;enabled:boolean;monthlyCostCents:number}){const context=await admin();if(!context)return{ok:false,error:"Platform administrator access is required."};if(!uuid(input.businessId)||!Number.isInteger(input.monthlyCostCents)||input.monthlyCostCents<0)return{ok:false,error:"Enter a valid monthly website cost."};const {error}=await context.db.rpc("admin_set_business_website_management",{p_business_id:input.businessId,p_enabled:input.enabled,p_monthly_cost_cents:input.monthlyCostCents});if(error){console.error("Website management toggle failed",{businessId:input.businessId,code:error.code});return{ok:false,error:"Website management could not be changed. Apply the admin dashboard migration."};}revalidatePath("/admin");return{ok:true};}
export async function setBusinessLifecycle(input:{businessId:string;active:boolean}){const context=await admin();if(!context)return{ok:false,error:"Platform administrator access is required."};if(!uuid(input.businessId))return{ok:false,error:"Invalid business."};const {error}=await context.db.rpc("admin_set_business_lifecycle",{p_business_id:input.businessId,p_active:input.active});if(error){console.error("Business lifecycle change failed",{businessId:input.businessId,code:error.code});return{ok:false,error:"Account access could not be changed. Apply the admin dashboard migration."};}revalidatePath("/admin");return{ok:true};}
export async function permanentlyDeleteBusiness(input:{businessId:string;businessName:string;confirmation:string}){const context=await admin();if(!context)return{ok:false,error:"Platform administrator access is required."};if(!uuid(input.businessId)||input.confirmation!=="DELETE")return{ok:false,error:"Permanent deletion was not confirmed."};const {error}=await context.db.rpc("admin_delete_business_permanently",{p_business_id:input.businessId,p_business_name:input.businessName,p_confirmation:input.confirmation});if(error){console.error("Permanent business deletion failed",{businessId:input.businessId,code:error.code});return{ok:false,error:"The business could not be deleted. No partial database deletion was committed."};}revalidatePath("/admin");return{ok:true};}
