import Link from "next/link";
import {notFound} from "next/navigation";
import {canManageBusiness} from "@/lib/access";
import {requireWorkspace} from "@/lib/workspace";
import {WorkspaceNav} from "../../../../WorkspaceNav";
import {LocationPageEditor} from "@/components/LocationPageEditor";
import {publishLocationPage,regenerateLocationPage,saveLocationPage} from "../../../actions";

export default async function LocationPageEditorPage({params,searchParams}:{params:Promise<{businessSlug:string;pageId:string}>;searchParams:Promise<{success?:string;error?:string}>}){
 const {businessSlug,pageId}=await params,query=await searchParams,{supabase,business,role}=await requireWorkspace(businessSlug);if(!canManageBusiness(role))notFound();
 const [{data:page},{data:website}]=await Promise.all([supabase.from("business_location_pages").select("*").eq("business_id",business.id).eq("id",pageId).maybeSingle(),supabase.from("business_website_settings").select("public_slug,custom_domain,domain_status").eq("business_id",business.id).maybeSingle()]);if(!page)notFound();
 const base=website?.domain_status==="connected"&&website.custom_domain?`https://${String(website.custom_domain).replace(/^https?:\/\//,"").replace(/\/$/,"")}`:`${(process.env.NEXT_PUBLIC_APP_URL||"https://servonas.com").replace(/\/$/,"")}/sites/${encodeURIComponent(website?.public_slug||business.slug)}`,publicUrl=`${base}/${page.slug}`;
 return <main className="epic3-shell"><WorkspaceNav slug={businessSlug} name={business.name} industry={business.industry_profile}/><section className="epic3-content marketing-page local-seo-page"><header className="marketing-analytics-header"><div><span className="sv-kicker">Location page</span><h1>{page.city}{page.state?`, ${page.state}`:""}</h1><p>Edit the customer-facing words. Servonas handles the page setup and search details.</p></div><div className="location-page-header-actions"><Link className="sv-button sv-secondary" href={`/app/${businessSlug}/marketing/seo`}>Back to Local SEO</Link>{page.status==="published"&&<a className="sv-button sv-secondary" href={publicUrl} target="_blank" rel="noreferrer">View page</a>}</div></header>{query.error&&<div className="workspace-notice error">{query.error}</div>}{query.success&&<div className="workspace-notice success">{query.success}</div>}<section className="workspace-panel location-page-ready"><div><span className={`local-seo-badge ${page.status}`}>{page.status}</span><h2>Your {page.city} page is ready.</h2><p>Servonas wrote this for local customers using your actual services and business information.</p><ul><li>Written for {page.city} customers</li><li>Uses your actual services</li><li>Includes Google-friendly page information</li><li>Links customers to your booking or contact flow</li></ul></div><div className="local-seo-actions">{page.status!=="published"&&<form action={publishLocationPage.bind(null,businessSlug,pageId)}><button className="sv-button">Publish Page</button></form>}<form action={regenerateLocationPage.bind(null,businessSlug,pageId)}><button className="sv-button sv-secondary">Regenerate</button></form></div></section><LocationPageEditor page={page} saveAction={saveLocationPage.bind(null,businessSlug,pageId)}/></section></main>;
}
