import type {Metadata} from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata:Metadata={title:"Desert Shield Pest Control | Servonas Website Demo",description:"A fictional pest-control website example created to demonstrate Servonas website capabilities.",robots:{index:false,follow:true}};
const services=[["General Pest Control","Routine protection for the pests that do not belong in your home."],["Scorpion Control","Targeted exterior and entry-point treatments designed for desert homes."],["Termite Control","Thorough inspections and clear treatment recommendations."],["Rodent Control","Help identifying entry points and protecting your property."],["Mosquito Control","Seasonal outdoor treatments for more comfortable time outside."],["Commercial Pest Control","Practical service plans for local workplaces and properties."]];
const attributionKeys=["utm_source","utm_medium","utm_campaign","utm_content","utm_term","gclid","gbraid","wbraid"] as const;
export default async function PestControlDemo({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const params=await searchParams,query=new URLSearchParams({source:"pest-control-website",utm_content:"pest_demo"});for(const key of attributionKeys){const raw=params[key],value=Array.isArray(raw)?raw[0]:raw;if(value)query.set(key,value.slice(0,500));}return <main className="pest-demo">
 <aside className="pest-demo-banner"><span>This is an example website built with Servonas.</span><Link href={`/signup?${query}`}>Get One For My Business — Free</Link></aside>
 <header className="pest-demo-nav"><a href="#top" className="pest-demo-brand"><i>DS</i><span><strong>Desert Shield</strong><small>Pest Control</small></span></a><nav><a href="#services">Services</a><a href="#why">Why us</a><a href="#about">About</a><a href="#contact">Contact</a></nav><a className="pest-demo-button" href="#booking">Book Pest Control</a></header>
 <section className="pest-demo-hero" id="top"><div><span>LOCAL PEST PROTECTION · SOUTHWEST</span><h1>Protect Your Home From Unwanted Guests</h1><p>Reliable local pest control for ants, spiders, roaches, scorpions, rodents, and more.</p><div><a className="pest-demo-button" href="#booking">Book Pest Control</a><a className="pest-demo-secondary" href="#contact">Get a Free Quote</a></div><small>Fictional demonstration business · No real services are offered</small></div><div className="pest-demo-photo"><Image src="/images/pest-control-technician-spraying.png" alt="Pest control technician treating the outside of a home" fill priority sizes="(max-width: 900px) 100vw, 50vw"/><div><b>Local help, without the runaround.</b><span>Clear service options. Convenient scheduling.</span></div></div></section>
 <section className="pest-demo-trust"><span>✓ Local pest professionals</span><span>✓ Family-conscious treatments</span><span>✓ Convenient scheduling</span><span>✓ Clear pricing</span><span>✓ Fast response</span></section>
 <section className="pest-demo-section" id="services"><header><span>PEST CONTROL SERVICES</span><h2>Protection built around your property.</h2><p>Start with the service you need. A local professional can help determine the right next step.</p></header><div className="pest-demo-services">{services.map(([name,body],index)=><article key={name}><i>{String(index+1).padStart(2,"0")}</i><h3>{name}</h3><p>{body}</p><a href="#booking">Book this service →</a></article>)}</div></section>
 <section className="pest-demo-why" id="why"><div><span>WHY DESERT SHIELD</span><h2>Professional pest care that feels refreshingly straightforward.</h2><p>This fictional example shows how a local pest company can communicate trust, services, and next steps clearly.</p></div><ul><li><b>Local knowledge</b><span>Service designed around common Southwest pest concerns.</span></li><li><b>Thoughtful treatments</b><span>Clear explanations and property-conscious recommendations.</span></li><li><b>Easy communication</b><span>Convenient booking and helpful service updates.</span></li></ul></section>
 <section className="pest-demo-process"><header><span>HOW IT WORKS</span><h2>Three simple steps to a more comfortable home.</h2></header><ol><li><i>1</i><h3>Book online</h3><p>Choose a service and tell us what you are seeing.</p></li><li><i>2</i><h3>We treat your property</h3><p>A pest professional completes the recommended service.</p></li><li><i>3</i><h3>Enjoy your home</h3><p>Get clear follow-up information and ongoing options.</p></li></ol></section>
 <section className="pest-demo-reviews"><header><span>DEMONSTRATION REVIEWS</span><h2>What the customer experience could feel like.</h2><p>The examples below are fictional and shown only to demonstrate website design.</p></header><div>{[["Jamie R. — fictional","The booking process was simple and the service plan was explained clearly."],["Morgan T. — fictional","Professional communication from the first request through follow-up."],["Casey L. — fictional","The website made it easy to understand the services and choose a time."]].map(([name,quote])=><blockquote key={name}><b>★★★★★</b><p>“{quote}”</p><cite>{name}</cite></blockquote>)}</div></section>
 <section className="pest-demo-about" id="about"><div><span>ABOUT THIS EXAMPLE</span><h2>A local story customers can connect with.</h2><p>Desert Shield Pest Control is a fictional Southwest pest-control company created to show the kind of polished website Servonas can build. A real Servonas website uses the business&apos;s own story, services, branding, service areas, and contact details.</p></div><aside><strong>Serving communities throughout the East Valley and surrounding areas.</strong><span>Demo service area · Contact a real provider for availability</span></aside></section>
 <section className="pest-demo-booking" id="booking"><div><span>BOOK ONLINE</span><h2>Tell us how we can help.</h2><p>This safe demonstration form does not submit or create an appointment.</p></div><form><label>Service<select defaultValue=""><option value="" disabled>Choose a pest-control service</option>{services.map(([name])=><option key={name}>{name}</option>)}</select></label><label>Preferred day<input type="date"/></label><label>What are you seeing?<textarea rows={3} placeholder="Tell us about the pest issue"/></label><button type="button" className="pest-demo-button">Preview Booking</button><small>Demonstration only — no information is sent.</small></form></section>
 <footer className="pest-demo-footer" id="contact"><div><strong>Desert Shield Pest Control</strong><p>Fictional pest-control website demonstration.</p></div><div><b>Services</b><a href="#services">Residential pest control</a><a href="#services">Termite control</a><a href="#services">Rodent control</a></div><div><b>Contact</b><span>(555) 010-0248</span><span>hello@example.invalid</span></div><small>Powered by <Link href="/pest-control-website">Servonas</Link></small></footer>
 </main>}
