import {validateRentalPromo} from "@/lib/discounts";
import {calculateRentalCalendarDays,calculateRentalUnitPrice,resolveRentalPricingRules} from "@/lib/rentalPricing";
import {incrementalDepositCents} from "@/lib/bookingManage/stagedAmendments";
import type {RentalItemAddition} from "@/lib/bookingManage/addRentalItems";

type Db=any;
export async function previewBookingItemAmendment(db:Db,input:{businessId:string;bookingId:string;items:RentalItemAddition[]}){
 const {data:booking,error}=await db.from("bookings").select("id,business_id,customer_id,status,rental_starts_at,rental_ends_at,subtotal_cents,discount_cents,tax_cents,delivery_fee_cents,total_cents,amount_paid_cents,discount_code,discount_snapshot,booking_items(inventory_item_id,quantity,unit_price_cents,operator_charge_cents)").eq("id",input.bookingId).eq("business_id",input.businessId).maybeSingle();
 if(error||!booking||!["pending_payment","paid","confirmed"].includes(booking.status))throw new Error("This booking cannot be amended.");
 const ids=[...new Set(input.items.map(item=>item.inventoryItemId))];if(!ids.length||ids.length!==input.items.length)throw new Error("Choose one or more different rentals.");
 const [{data:settings},{data:items,error:itemError},{data:options,error:optionsError}]=await Promise.all([
  db.from("booking_settings").select("timezone,rental_deposit_percent,standard_rental_hours,allow_multi_day_rentals,additional_day_pricing_type,additional_day_discount_percent,additional_day_flat_rate_cents,max_rental_days").eq("business_id",input.businessId).maybeSingle(),
  db.from("inventory_items").select("id,name,image_url,daily_price_cents,allow_quantity,standard_rental_hours_override,allow_multi_day_override,additional_day_pricing_type_override,additional_day_discount_percent_override,additional_day_flat_rate_cents_override,max_rental_days_override").eq("business_id",input.businessId).in("id",ids).eq("active",true),
  db.from("inventory_item_booking_options").select("id,inventory_item_id,name,required,inventory_item_booking_option_choices(id,label,price_adjustment_cents)").eq("business_id",input.businessId).in("inventory_item_id",ids),
 ]);if(!settings||itemError||optionsError||!items||items.length!==ids.length)throw new Error("One or more selected rentals are unavailable.");
 const tz=settings.timezone??"America/Phoenix",date=(value:string)=>{const parts=new Intl.DateTimeFormat("en-US",{timeZone:tz,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date(value));const p=new Map(parts.map(x=>[x.type,x.value]));return `${p.get("year")}-${p.get("month")}-${p.get("day")}`;};
 const days=calculateRentalCalendarDays(date(booking.rental_starts_at),date(booking.rental_ends_at)),byId=new Map(items.map((item:any)=>[item.id,item]));
 const selected=new Map(input.items.map(item=>[item.inventoryItemId,item.options??[]]));
 const added=input.items.map(request=>{const item:any=byId.get(request.inventoryItemId);if(!item.allow_quantity&&Number(request.quantity)!==1)throw new Error(`${item.name} can only be added once.`);const configured=(options??[]).filter((option:any)=>option.inventory_item_id===item.id),requested=selected.get(item.id)??[];const snapshots:any[]=configured.flatMap((option:any)=>{const matches=requested.filter(value=>value.optionId===option.id);if(option.required&&matches.length!==1)throw new Error(`Choose ${option.name}.`);if(matches.length>1)throw new Error(`Choose only one ${option.name}.`);if(!matches.length)return [];const choice=(option.inventory_item_booking_option_choices??[]).find((value:any)=>value.id===matches[0].choiceId);if(!choice)throw new Error(`Choose a valid ${option.name}.`);return[{option_id:option.id,option_name:option.name,choice_id:choice.id,choice_label:choice.label,price_adjustment_cents:Number(choice.price_adjustment_cents)}];});if(requested.some(choice=>!configured.some((option:any)=>(option.inventory_item_booking_option_choices??[]).some((value:any)=>value.id===choice.choiceId))))throw new Error("Choose valid booking options.");const price=calculateRentalUnitPrice(Number(item.daily_price_cents),days,resolveRentalPricingRules({standardRentalHours:Number(settings.standard_rental_hours??24),allowMultiDay:Boolean(settings.allow_multi_day_rentals),additionalDayPricingType:settings.additional_day_pricing_type??"full_price",additionalDayDiscountPercent:Number(settings.additional_day_discount_percent??0),additionalDayFlatRateCents:settings.additional_day_flat_rate_cents==null?null:Number(settings.additional_day_flat_rate_cents),maxRentalDays:settings.max_rental_days==null?null:Number(settings.max_rental_days)},item));const optionAdjustmentCents=snapshots.reduce((sum:number,row:any)=>sum+row.price_adjustment_cents,0);return{id:item.id,name:item.name,imageUrl:item.image_url,quantity:Number(request.quantity),unitPriceCents:price.totalUnitPriceCents,optionAdjustmentCents,optionSelections:snapshots,lineTotalCents:(price.totalUnitPriceCents+optionAdjustmentCents)*Number(request.quantity)};});
 const existing=(booking.booking_items??[]).map((line:any)=>({id:line.inventory_item_id,quantity:Number(line.quantity),rentalUnitPriceCents:Number(line.unit_price_cents),unitPriceCents:Number(line.unit_price_cents)+Math.round(Number(line.operator_charge_cents??0)/Math.max(1,Number(line.quantity)))}));let discount=Number(booking.discount_cents??0),snapshot=booking.discount_snapshot??null;
 if(booking.discount_code){const promo=await validateRentalPromo(db,{businessId:input.businessId,customerId:booking.customer_id??undefined,code:booking.discount_code,items:[...existing,...added.map(item=>({id:item.id,quantity:item.quantity,rentalUnitPriceCents:item.unitPriceCents,unitPriceCents:item.unitPriceCents}))]});if(promo.ok){discount=promo.discountCents;snapshot=promo.snapshot;}else{discount=0;snapshot=null;}}
 const subtotal=Number(booking.subtotal_cents??0)+added.reduce((sum,item)=>sum+item.lineTotalCents,0),total=Math.max(0,subtotal-discount)+Number(booking.delivery_fee_cents??0)+Number(booking.tax_cents??0),paid=Number(booking.amount_paid_cents??0),dueNow=incrementalDepositCents({newTotalCents:total,amountPaidCents:paid,depositPercent:Number(settings.rental_deposit_percent??0)});
 return {booking,depositPercent:Number(settings.rental_deposit_percent??0),added,requestedItems:input.items,pricingSnapshot:{added,discount_snapshot:snapshot,discount_cents:discount},oldTotals:{subtotal_cents:Number(booking.subtotal_cents??0),discount_cents:Number(booking.discount_cents??0),tax_cents:Number(booking.tax_cents??0),total_cents:Number(booking.total_cents??0),balance_due_cents:Number(booking.balance_due_cents??0),balance_charge_scheduled_for:booking.balance_charge_scheduled_for??null},newTotals:{subtotal_cents:subtotal,discount_cents:discount,tax_cents:Number(booking.tax_cents??0),total_cents:total,balance_due_cents:total-paid},requiredPaymentCents:dueNow,remainingBalanceCents:total-paid-dueNow};
}
