import assert from "node:assert/strict";
import test from "node:test";
import {readFile} from "node:fs/promises";
const read=(path:string)=>readFile(new URL(`../${path}`,import.meta.url),"utf8");
test("unified customer admin is platform-admin only and shows both usage products",async()=>{const page=await read("app/app/admin/customers/page.tsx");assert.match(page,/isServonasPlatformAdmin/);assert.match(page,/AI Assistant/);assert.match(page,/Twilio/);assert.match(page,/row\.ai\.cost/);assert.match(page,/row\.twilio\.cost/);});
test("AI and Twilio access changes use atomic audited service-role RPCs",async()=>{const action=await read("app/app/admin/customers/actions.ts"),ai=await read("supabase/migrations/20260810000900_business_ai_assistant_access.sql"),twilio=await read("supabase/migrations/20260810001000_business_twilio_access.sql");assert.match(action,/admin_set_business_ai_assistant_access/);assert.match(action,/admin_set_business_twilio_access/);assert.match(ai,/business_ai_assistant_access_audit/);assert.match(twilio,/business_twilio_access_audit/);assert.match(twilio,/grant execute.+service_role/);});
test("existing active Twilio tenants retain access during migration",async()=>{const sql=await read("supabase/migrations/20260810001000_business_twilio_access.sql");assert.match(sql,/select business_id,true,now\(\) from public\.business_twilio_accounts/);assert.match(sql,/provisioning_status in\('active','provisioning'\)/);});
test("Twilio access blocks tenant routing and resource-creating admin operations",async()=>{const sender=await read("lib/twilio/tenantOutboundSender.ts"),subaccounts=await read("app/api/admin/twilio/subaccounts/route.ts"),activation=await read("app/api/admin/twilio/activation/[businessId]/route.ts"),search=await read("app/api/admin/twilio/phone-numbers/search/route.ts"),purchase=await read("app/api/admin/twilio/phone-numbers/purchase/route.ts");assert.match(sender,/isBusinessTwilioEnabled/);for(const source of[subaccounts,activation,search,purchase])assert.match(source,/requireBusinessTwilioEnabled/);});
test("disabling Twilio preserves legacy sender and does not delete provider resources",async()=>{const sender=await read("lib/twilio/tenantOutboundSender.ts"),migration=await read("supabase/migrations/20260810001000_business_twilio_access.sql");assert.match(sender,/if\(!await isBusinessTwilioEnabled\(businessId\)\)return fallback/);assert.match(sender,/mode:"legacy"/);assert.doesNotMatch(migration,/delete from public\.(business_twilio_accounts|twilio_phone_numbers|twilio_tenant_activations)/);});
