import assert from "node:assert/strict";
import test from "node:test";
import {readFile} from "node:fs/promises";
import {rootMeanSquare,VoiceActivityTracker,type VoiceActivityConfig} from "../lib/assistant/voiceActivity.ts";

const read=(path:string)=>readFile(new URL(`../${path}`,import.meta.url),"utf8");
const config:VoiceActivityConfig={calibrationMs:100,minimumSpeechMs:100,silenceMs:1500,noSpeechMs:5000,minimumThreshold:.025,noiseMultiplier:2.8};

test("silence before speech waits and background noise below the calibrated threshold is ignored",()=>{const tracker=new VoiceActivityTracker(0,config);assert.equal(tracker.sample(.01,20),"waiting");assert.equal(tracker.sample(.012,80),"waiting");assert.equal(tracker.sample(.02,500),"waiting");assert.equal(tracker.hasSpeech(),false);assert.ok(tracker.speechThreshold()>=.025);});
test("sustained meaningful audio marks speech as begun",()=>{const tracker=new VoiceActivityTracker(0,config);tracker.sample(.005,50);assert.equal(tracker.sample(.08,200),"waiting");assert.equal(tracker.sample(.08,310),"speech_started");assert.equal(tracker.hasSpeech(),true);});
test("a natural pause shorter than 1.5 seconds does not stop recording",()=>{const tracker=new VoiceActivityTracker(0,config);tracker.sample(.005,50);tracker.sample(.08,200);tracker.sample(.08,310);assert.equal(tracker.sample(.001,500),"silence");assert.equal(tracker.sample(.001,1800),"silence");assert.equal(tracker.sample(.08,1850),"speech");});
test("sustained silence after speech auto-stops",()=>{const tracker=new VoiceActivityTracker(0,config);tracker.sample(.005,50);tracker.sample(.08,200);tracker.sample(.08,310);tracker.sample(.001,500);assert.equal(tracker.sample(.001,2001),"auto_stop");});
test("no speech timeout never submits a phantom command",()=>{const tracker=new VoiceActivityTracker(0,config);tracker.sample(.005,50);assert.equal(tracker.sample(.005,5001),"no_speech");assert.equal(tracker.hasSpeech(),false);});
test("RMS audio level calculation is stable",()=>{assert.equal(rootMeanSquare(new Float32Array([0,0])),0);assert.ok(Math.abs(rootMeanSquare(new Float32Array([1,-1]))-1)<.00001);});

test("auto-stop and manual Stop converge on one MediaRecorder stop path",async()=>{const client=await read("app/app/[businessSlug]/assistant/AssistantClient.tsx");assert.match(client,/event==="auto_stop"/);assert.match(client,/function stopRecording\(\)/);assert.equal((client.match(/fetch\(`\/api\/assistant\/\$\{businessSlug\}\/voice\/transcribe`/g)??[]).length,1);assert.equal((client.match(/submitAssistant\(transcript,"voice",requestId\)/g)??[]).length,1);});
test("cancel, no-speech, and session-end paths discard audio",async()=>{const client=await read("app/app/[businessSlug]/assistant/AssistantClient.tsx");assert.match(client,/if\(wasCanceled\).*return/);assert.match(client,/stopWithoutSubmission\("I didn't hear anything\. Try again\."\)/);assert.match(client,/function endVoiceSession\(\).*canceled\.current=true/);assert.match(client,/transcriptionAbort\.current\?\.abort\(\)/);});
test("the 60-second recording ceiling remains in force",async()=>{const client=await read("app/app/[businessSlug]/assistant/AssistantClient.tsx");assert.match(client,/const MAX_RECORDING_MS=60_000/);assert.match(client,/recordingTimer\.current=setTimeout/);});

test("conversation mode explicitly starts, loops for second and third commands, ends, and can restart",async()=>{const client=await read("app/app/[businessSlug]/assistant/AssistantClient.tsx");assert.match(client,/function startVoiceSession\(\)/);assert.match(client,/sessionActiveRef\.current=true/);assert.match(client,/function scheduleNextCommand\(\)/);assert.match(client,/attemptConversationRestart/);assert.match(client,/await startRecording\(true\)/);assert.match(client,/speak\(body\.message,continueSession\?scheduleNextCommand:undefined\)/);assert.match(client,/if\(!speakResponses\|\|!ttsSupported\)\{onComplete\?\.\(\);return;\}/);assert.match(client,/function endVoiceSession\(\)/);assert.match(client,/sessionActiveRef\.current=false/);assert.match(client,/Start voice session/);assert.match(client,/End session/);});
test("conversation mode preserves the existing Assistant conversation and selected context",async()=>{const client=await read("app/app/[businessSlug]/assistant/AssistantClient.tsx"),route=await read("app/api/assistant/[businessSlug]/route.ts"),orchestrator=await read("lib/assistant/orchestrator.ts");assert.match(client,/conversationId,channel,requestId/);assert.match(route,/processAssistantInput/);assert.match(orchestrator,/selectedCustomerId/);assert.match(orchestrator,/selectedInvoiceId/);assert.doesNotMatch(client,/setConversationId\(null\)/);});
test("ending a voice session releases microphone and VAD resources without clearing conversation",async()=>{const client=await read("app/app/[businessSlug]/assistant/AssistantClient.tsx");assert.match(client,/cleanupVoiceActivity/);assert.match(client,/cancelAnimationFrame/);assert.match(client,/audioSource\.current\?\.disconnect/);assert.match(client,/audioContext\.current\?\.close/);assert.match(client,/getTracks\(\)\.forEach\(track=>track\.stop\(\)\)/);assert.doesNotMatch(client,/endVoiceSession\(\).*setMessages/);});
test("ending during a pending microphone permission request cannot start a stale recorder",async()=>{const client=await read("app/app/[businessSlug]/assistant/AssistantClient.tsx");assert.match(client,/recordingGeneration=useRef\(0\)/);assert.match(client,/const generation=\+\+recordingGeneration\.current/);assert.match(client,/generation!==recordingGeneration\.current/);assert.match(client,/endVoiceSession\(\).*recordingGeneration\.current\+=1/);});

test("conversation turn detaches the recorder and analyser during TTS while preserving the authorized stream",async()=>{const client=await read("app/app/[businessSlug]/assistant/AssistantClient.tsx");assert.match(client,/preserveSessionMedia=sessionActiveRef\.current&&!wasCanceled/);assert.match(client,/releaseRecorder\(preserveSessionMedia\)/);assert.match(client,/cleanupVoiceActivity\(preserveSessionMedia\)/);assert.match(client,/audioSource\.current\?\.disconnect/);assert.match(client,/analyser\.current\?\.disconnect/);assert.match(client,/if\(!preserveSessionMedia\)stopMicrophoneStream\(\)/);assert.match(client,/reusableStream=sessionActiveRef\.current&&stream\.current\?\.getAudioTracks\(\)\.some\(track=>track\.readyState==="live"\)/);});
test("TTS completion schedules and fires the 650 ms microphone restart",async()=>{const client=await read("app/app/[businessSlug]/assistant/AssistantClient.tsx");assert.match(client,/onEnd:finish/);assert.match(client,/NEXT_COMMAND_DELAY_MS=650/);assert.match(client,/resumeTimer\.current=setTimeout\(\(\)=>\{resumeTimer\.current=null;void attemptConversationRestart\(generation,0\);\},NEXT_COMMAND_DELAY_MS\)/);assert.match(client,/const restarted=await startRecording\(true\)/);});
test("TTS disabled resumes conversation mode after the displayed response",async()=>{const client=await read("app/app/[businessSlug]/assistant/AssistantClient.tsx");assert.match(client,/if\(!speakResponses\|\|!ttsSupported\)\{onComplete\?\.\(\);return;\}/);});
test("Safari missing speech callbacks use the bounded fallback and stale callbacks are ignored",async()=>{const client=await read("app/app/[businessSlug]/assistant/AssistantClient.tsx");assert.match(client,/speechPlaybackTimeoutMs\(message\)/);assert.match(client,/generation!==speechGeneration\.current/);assert.match(client,/tts\.stop\(\);finish\(\)/);});
test("Safari-style stale recorder state is cleared or deferred without creating duplicate microphone sessions",async()=>{const client=await read("app/app/[businessSlug]/assistant/AssistantClient.tsx");assert.match(client,/recorder\.current&&recorder\.current\.state!=="inactive"/);assert.match(client,/microphone_restart_deferred/);assert.match(client,/if\(recorder\.current\?\.state==="inactive"\)recorder\.current=null/);assert.match(client,/requestInFlight\.current\|\|recorder\.current\?\.state==="recording"/);});
test("blocked and failed restarts use bounded retries instead of silently stranding the session",async()=>{const client=await read("app/app/[businessSlug]/assistant/AssistantClient.tsx");assert.match(client,/const MAX_RESTART_ATTEMPTS=5/);assert.match(client,/function scheduleRestartRetry/);assert.match(client,/request_in_flight/);assert.match(client,/recorder_not_recording/);assert.match(client,/restarted&&recorder\.current\?\.state==="recording"/);assert.match(client,/Conversation Mode paused because the microphone could not restart/);});
test("ending the session invalidates a pending automatic restart",async()=>{const client=await read("app/app/[businessSlug]/assistant/AssistantClient.tsx");assert.match(client,/resumeGeneration=useRef\(0\)/);assert.match(client,/generation!==resumeGeneration\.current\|\|!sessionActiveRef\.current/);assert.match(client,/function endVoiceSession\(\).*clearResumeTimer\(\)/);});
test("manual Cancel pauses instead of causing an unintended automatic restart",async()=>{const client=await read("app/app/[businessSlug]/assistant/AssistantClient.tsx");assert.match(client,/function cancelRecording\(\)\{clearResumeTimer\(\)/);assert.match(client,/recording_canceled.*automaticRestart:false/);});
test("safe development diagnostics cover the complete resume attempt without transcript data",async()=>{const client=await read("app/app/[businessSlug]/assistant/AssistantClient.tsx");for(const event of ["resume_timer_scheduled","resume_timer_fired","microphone_restart_attempted","microphone_restart_succeeded","microphone_restart_failed"])assert.match(client,new RegExp(`["']${event}["']`));assert.match(client,/conversationSessionActive:sessionActiveRef\.current/);assert.doesNotMatch(client,/diagnostic\([^\n]*transcript/);});
test("Stop Speaking resumes only an explicitly active session",async()=>{const client=await read("app/app/[businessSlug]/assistant/AssistantClient.tsx");assert.match(client,/stopSpeaking\(true\)/);assert.match(client,/resumeSession&&sessionActiveRef\.current/);});

test("voice session pauses for existing high-risk confirmation and never auto-confirms",async()=>{const client=await read("app/app/[businessSlug]/assistant/AssistantClient.tsx"),orchestrator=await read("lib/assistant/orchestrator.ts");assert.match(client,/const continueSession=sessionActiveRef\.current&&!body\.actionRequest/);assert.match(client,/Confirmation required/);assert.doesNotMatch(client,/scheduleNextCommand\(\).*actionRequest/);assert.match(orchestrator,/requires_confirmation:true/);});
test("voice keeps request IDs, idempotency, and tenant security unchanged",async()=>{const client=await read("app/app/[businessSlug]/assistant/AssistantClient.tsx"),route=await read("app/api/assistant/[businessSlug]/route.ts"),orchestrator=await read("lib/assistant/orchestrator.ts");assert.match(client,/const requestId=crypto\.randomUUID\(\)/);assert.match(route,/requireWorkspace\(businessSlug\)/);assert.match(orchestrator,/context\.requestId/);assert.match(orchestrator,/idempotency/);});
test("Phase 2.25 introduces no Twilio or SMS dependency",async()=>{const source=(await Promise.all([read("app/app/[businessSlug]/assistant/AssistantClient.tsx"),read("lib/assistant/voiceActivity.ts")])).join("\n");assert.doesNotMatch(source,/twilio|sms/i);});
