import assert from "node:assert/strict";
import test from "node:test";
import {readFile} from "node:fs/promises";
const source=()=>readFile(new URL("../lib/assistant/tools.ts",import.meta.url),"utf8");

test("tool registry contains only the ten approved Phase 1 tools",async()=>{const code=await source();for(const name of ["addJobNote","createAppointment","createCustomer","getCustomer","getOutstandingInvoices","getSchedule","markInvoicePaid","rescheduleAppointment","searchCustomers","searchInvoices"])assert.match(code,new RegExp(`name:\"${name}\"`));assert.doesNotMatch(code,/name:\"runSql\"/);});
test("AI cannot call an unregistered tool",async()=>{const code=await source();assert.match(code,/if\(!tool\)throw new Error\("That Assistant action is not available/);});
test("invalid AI tool arguments are rejected",async()=>{const code=await source();assert.match(code,/if\(!args\|\|typeof args!==\"object\"\|\|Array\.isArray\(args\)\)/);assert.match(code,/if\(!term\)throw new Error\("Enter a customer/);});
test("customer lookup preserves a unique selected customer and ambiguity asks which",async()=>{const code=await source();assert.match(code,/rows\.length===1/);assert.match(code,/selectedCustomerId:row\.id/);assert.match(code,/Which one\?/);});
test("staff cannot use customer, scheduling, note, or financial mutations",async()=>{const code=await source();assert.match(code,/const requireManager=.*canManageCustomers/);for(const marker of ["createCustomer","createAppointment","rescheduleAppointment","markPaid","addJobNote"])assert.match(code,new RegExp(`const ${marker}[\\s\\S]{0,700}requireManager\\(c\\)`));});
test("markInvoicePaid creates confirmation instead of executing payment",async()=>{const code=await source();assert.match(code,/pendingAction:\{actionType:\"markInvoicePaid\"/);assert.doesNotMatch(code,/markPaid[\s\S]{0,1800}record_invoice_offline_payment/);});
test("tool source scopes customer and invoice access by trusted business ID",async()=>{const source=await readFile(new URL("../lib/assistant/tools.ts",import.meta.url),"utf8");assert.match(source,/\.eq\("business_id",context\.business\.id\)/);assert.doesNotMatch(source,/tenantId|userId from/);});
test("schedule tools validate ranges and mutations reuse conflict validation",async()=>{const source=await readFile(new URL("../lib/assistant/tools.ts",import.meta.url),"utf8");assert.match(source,/31\*864e5/);assert.match(source,/validateJobSchedule/);assert.match(source,/requestKey=randomUUID/);assert.match(source,/excludeJobId:job\.id/);});
test("invoice confirmation is claimed once and RPC uses action ID as idempotency key",async()=>{const source=await readFile(new URL("../lib/assistant/orchestrator.ts",import.meta.url),"utf8");assert.match(source,/\.eq\("status","awaiting_confirmation"\)/);assert.match(source,/p_idempotency_key:action\.id/);assert.match(source,/decision==="reject"/);assert.match(source,/status:"rejected"/);});
test("conversation context persists and restores selected customer",async()=>{const source=await readFile(new URL("../lib/assistant/orchestrator.ts",import.meta.url),"utf8");assert.match(source,/selectedCustomerId/);assert.match(source,/conversation\.context/);assert.match(source,/clear conversational references/);});
test("new AI tables have RLS and user plus tenant policies",async()=>{const sql=await readFile(new URL("../supabase/migrations/20260810000600_servonas_ai_assistant_phase_1.sql",import.meta.url),"utf8");for(const table of ["ai_conversations","ai_messages","ai_action_requests","ai_action_audit_log"])assert.match(sql,new RegExp(`alter table public\\.${table} enable row level security`));assert.match(sql,/user_id=auth\.uid\(\)/);assert.match(sql,/has_business_role\(business_id/);assert.match(sql,/revoke insert,update,delete on public\.ai_action_audit_log/);});
