import assert from "node:assert/strict";
import test from "node:test";
import {readFile} from "node:fs/promises";
import {bindTrustedSelectedCustomer,explicitlyChangesCustomer} from "../lib/assistant/selectedCustomerContext.ts";
import {clearSelectedCustomerConversationContext,resolveCustomerCandidateSelection,selectCustomerConversationContext,type CustomerCandidate} from "../lib/assistant/customerCandidateResolution.ts";

const first="11111111-1111-4111-8111-111111111111",second="22222222-2222-4222-8222-222222222222",invented="99999999-9999-4999-8999-999999999999";
const contextualPhrases=["this customer","what do they owe me?","does he owe me?","add a note for him","does she owe me?","add a note for her","their invoice","their appointment","his invoice","her invoice","do they have anything scheduled?"];

test("every natural follow-up binds to the trusted selected customer",()=>{for(const input of contextualPhrases){const result=bindTrustedSelectedCustomer(input,{toolName:"getOutstandingInvoices",arguments:{customerId:invented}},second);assert.ok("toolName" in result);assert.equal(result.arguments.customerId,second,input);}});
test("model-generated customer IDs cannot override trusted context",()=>{const result=bindTrustedSelectedCustomer("Does this customer owe me money?",{toolName:"getOutstandingInvoices",arguments:{customerId:invented}},second);assert.ok("toolName" in result);assert.equal(result.arguments.customerId,second);});
test("a model response cannot bypass a required selected-customer lookup",()=>{for(const input of ["Does this customer owe me?","Do they have appointments?"]){const result=bindTrustedSelectedCustomer(input,{response:"Please choose the customer again."},second);assert.ok("toolName" in result);assert.equal(result.arguments.customerId,second);assert.notEqual(result.toolName,"searchCustomers");}});
test("multiple consecutive tool calls retain the same selected customer",()=>{for(const input of ["Does this customer owe me?","Do they have appointments?","What is their phone number?"]){const result=bindTrustedSelectedCustomer(input,{toolName:"getCustomer",arguments:{}},second);assert.ok("toolName" in result);assert.equal(result.arguments.customerId,second);}});
test("an explicit new search is not rebound to the prior customer",()=>{assert.equal(explicitlyChangesCustomer("Find Jane Smith"),true);const decision={toolName:"searchCustomers",arguments:{term:"Jane Smith"}} as const;assert.deepEqual(bindTrustedSelectedCustomer("Find Jane Smith",decision,first),decision);});
test("selecting another customer replaces the active context",()=>{const one=selectCustomerConversationContext({},first),two=selectCustomerConversationContext(one,second);assert.equal(two.selectedCustomerId,second);});
test("stale selected context is safely cleared",()=>{const cleared=clearSelectedCustomerConversationContext({selectedCustomerId:second,pendingCustomerCandidates:[{id:second,displayName:"Test"}],other:"kept"});assert.equal(cleared.selectedCustomerId,undefined);assert.equal(cleared.pendingCustomerCandidates,undefined);assert.equal(cleared.other,"kept");});
test("production regression resolves candidate 2 then performs its invoice lookup directly",async()=>{const candidates:CustomerCandidate[]=[{id:first,displayName:"Matthew Bair"},{id:second,displayName:"Test Address"}],selection=resolveCustomerCandidateSelection("2",candidates);assert.equal(selection.kind,"selected");if(selection.kind!=="selected")return;const context=selectCustomerConversationContext({},selection.candidate.id),decision=bindTrustedSelectedCustomer("Does this customer owe me money?",{toolName:"searchCustomers",arguments:{term:"this customer"}},context.selectedCustomerId);assert.ok("toolName" in decision);assert.equal(decision.toolName,"getOutstandingInvoices");assert.equal(decision.arguments.customerId,second);
 const invoices=[{id:"invoice",invoice_number:"INV-2",balance_due_cents:2500,customer_id:second},{id:"other",invoice_number:"INV-1",balance_due_cents:1000,customer_id:first}],executed=invoices.filter(invoice=>invoice.customer_id===decision.arguments.customerId);assert.deepEqual(executed.map(invoice=>invoice.invoice_number),["INV-2"]);assert.equal(executed.some(invoice=>invoice.customer_id===first),false);});
test("stale and cross-tenant selected IDs are revalidated before tool orchestration",async()=>{const source=await readFile(new URL("../lib/assistant/orchestrator.ts",import.meta.url),"utf8");assert.match(source,/\.eq\("id",persistedSelectedId\)\.eq\("business_id",context\.business\.id\)\.eq\("is_deleted",false\)/);assert.match(source,/clearSelectedCustomerConversationContext/);});
test("job and invoice mutations enforce selected-customer ownership",async()=>{const source=await readFile(new URL("../lib/assistant/tools.ts",import.meta.url),"utf8");assert.match(source,/requireSelectedCustomerMatch\(c,job\.customer_id\)/);assert.match(source,/requireSelectedCustomerMatch\(c,invoice\.customer_id\)/);});
