import assert from "node:assert/strict";
import test from "node:test";
import {readFile} from "node:fs/promises";
import {classifySpokenConfirmation} from "../lib/assistant/spokenConfirmation.ts";

for(const phrase of ["yes","yep","yeah","correct","confirm","confirmed","go ahead","do it","proceed","sounds good","yes please"])test(`positive confirmation: ${phrase}`,()=>assert.equal(classifySpokenConfirmation(phrase),"confirm"));
for(const phrase of ["no","nope","cancel","cancel it","don't","do not","never mind","nevermind","stop","reject"])test(`negative confirmation: ${phrase}`,()=>assert.equal(classifySpokenConfirmation(phrase),"reject"));
for(const phrase of ["maybe","I think so","probably","sure, I guess","what happens if I do?","which invoice was that?","wait","yeah maybe"])test(`ambiguous confirmation does not execute: ${phrase}`,()=>assert.notEqual(classifySpokenConfirmation(phrase),"confirm"));

test("spoken confirmation is intercepted before normal Assistant routing",async()=>{const code=await readFile(new URL("../lib/assistant/orchestrator.ts",import.meta.url),"utf8"),confirmation=code.indexOf('if(channel==="voice")'),provider=code.indexOf("provider.generateResponse");assert.ok(confirmation>=0&&confirmation<provider);assert.match(code,/classifySpokenConfirmation\(text\)/);});
test("bare confirmation with no pending action executes nothing",async()=>{const code=await readFile(new URL("../lib/assistant/orchestrator.ts",import.meta.url),"utf8");assert.match(code,/if\(!pendingRows\.length\)message=.*nothing waiting for confirmation/);});
test("one authoritative pending action is tenant user and conversation scoped",async()=>{const code=await readFile(new URL("../lib/assistant/orchestrator.ts",import.meta.url),"utf8");assert.match(code,/\.eq\("conversation_id",conversation\.id\)\.eq\("business_id",context\.business\.id\)\.eq\("user_id",context\.user\.id\)\.eq\("status","awaiting_confirmation"\)/);assert.match(code,/pendingRows\.length!==1/);});
test("spoken and button confirmation share resolveAssistantAction",async()=>{const orchestrator=await readFile(new URL("../lib/assistant/orchestrator.ts",import.meta.url),"utf8"),route=await readFile(new URL("../app/api/assistant/[businessSlug]/actions/[actionId]/route.ts",import.meta.url),"utf8");assert.match(orchestrator,/await resolveAssistantAction\(context,pendingRows\[0\]\.id,spokenIntent\)/);assert.match(route,/await resolveAssistantAction/);});
test("confirmation expires after fifteen minutes and cannot execute",async()=>{const code=await readFile(new URL("../lib/assistant/orchestrator.ts",import.meta.url),"utf8");assert.match(code,/CONFIRMATION_TTL_MS=15\*60\*1000/);assert.match(code,/Confirmation expired/);assert.match(code,/status:"rejected"/);});
test("completed rejected wrong tenant wrong user and wrong conversation actions cannot be newly confirmed",async()=>{const code=await readFile(new URL("../lib/assistant/orchestrator.ts",import.meta.url),"utf8");assert.match(code,/\.eq\("id",actionId\)\.eq\("business_id",context\.business\.id\)\.eq\("user_id",context\.user\.id\)/);assert.match(code,/actionQuery=actionQuery\.eq\("conversation_id",context\.conversationId\)/);assert.match(code,/action\.status==="completed"\|\|action\.status==="rejected"/);assert.match(code,/action\.status!=="awaiting_confirmation"/);});
test("permission and idempotency are rechecked by the shared execution path",async()=>{const code=await readFile(new URL("../lib/assistant/orchestrator.ts",import.meta.url),"utf8");assert.match(code,/canManageCustomers\(context\.role\)/);assert.match(code,/\.update\(\{status:"executing"/);assert.match(code,/\.eq\("status","awaiting_confirmation"\)/);assert.match(code,/p_idempotency_key:action\.id/);});
test("TTS completes before confirmation microphone listening resumes",async()=>{const client=await readFile(new URL("../app/app/[businessSlug]/assistant/AssistantClient.tsx",import.meta.url),"utf8");assert.match(client,/speak\(body\.message,requestId,continueSession\?scheduleNextCommand:undefined\)/);assert.match(client,/onEnd:finish/);assert.match(client,/NEXT_COMMAND_DELAY_MS=650/);});
test("confirmation read-back uses the same server-audio TTS provider",async()=>{const client=await readFile(new URL("../app/app/[businessSlug]/assistant/AssistantClient.tsx",import.meta.url),"utf8"),provider=await readFile(new URL("../lib/assistant/textToSpeech.ts",import.meta.url),"utf8");assert.match(client,/speak\(body\.message/);assert.match(provider,/OpenAITextToSpeechProvider/);assert.equal((client.match(/new OpenAITextToSpeechProvider/g)??[]).length,1);});
test("ending a voice session cannot execute a pending action",async()=>{const client=await readFile(new URL("../app/app/[businessSlug]/assistant/AssistantClient.tsx",import.meta.url),"utf8");assert.match(client,/function endVoiceSession\(\).*sessionActiveRef\.current=false/);assert.doesNotMatch(client,/function endVoiceSession\(\).*resolveAssistantAction/);});
test("confirmation transcript remains visible and resolved card state is updated",async()=>{const client=await readFile(new URL("../app/app/[businessSlug]/assistant/AssistantClient.tsx",import.meta.url),"utf8");assert.match(client,/role:"user",content:transcript/);assert.match(client,/!body\.resolvedActionId\|\|action\.id!==body\.resolvedActionId/);});
