import assert from "node:assert/strict";
import test from "node:test";
import {readFile} from "node:fs/promises";
const read=(path:string)=>readFile(new URL(`../${path}`,import.meta.url),"utf8");
test("car-detailing landing page matches website search intent and preserves attribution",async()=>{const page=await read("app/car-detailing-website/page.tsx");assert.match(page,/Free Car Detailing Website \| Servonas/);assert.match(page,/We&apos;ll Build Your Car Detailing Website/);assert.match(page,/source:\"car-detailing-website\"/);assert.match(page,/View Example Website/);for(const key of ["utm_source","utm_medium","utm_campaign","utm_content","utm_term","gclid","gbraid","wbraid"])assert.match(page,new RegExp(key));});
test("detailing demo is public-facing fictional and cannot create bookings",async()=>{const page=await read("app/demo/car-detailing/page.tsx");assert.match(page,/Apex Auto Detail/);assert.match(page,/Fictional demonstration business/);assert.match(page,/button type="button"/);assert.match(page,/example\.invalid/);assert.doesNotMatch(page,/type="submit"|fetch\(|form action=/);});
test("shared website-first config handles pest control and car detailing",async()=>{const [config,onboarding,auth]=await Promise.all([read("lib/websiteFirstConfig.ts"),read("components/WebsiteFirstOnboarding.tsx"),read("app/auth/actions.ts")]);assert.match(config,/pest-control-website/);assert.match(config,/car-detailing-website/);assert.match(config,/Ceramic Coating/);assert.match(onboarding,/source:WebsiteFirstSource/);assert.match(onboarding,/Business setup/);assert.match(auth,/isWebsiteFirstSource/);});
test("migration persists detailing using canonical business service website and territory models",async()=>{const sql=await read("supabase/migrations/20260813000100_website_first_onboarding.sql");assert.match(sql,/car-detailing-website/);assert.match(sql,/'other'/);assert.match(sql,/'car_detailing'/);assert.match(sql,/insert into public\.services/);assert.match(sql,/business_website_settings/);assert.match(sql,/workforce_territories/);assert.match(sql,/enable row level security/);});
test("detailing page uses a project-local generated automotive asset",async()=>{const [landing,demo]=await Promise.all([read("app/car-detailing-website/page.tsx"),read("app/demo/car-detailing/page.tsx")]);assert.match(landing,/car-detailing-professional-polishing\.png/);assert.match(demo,/car-detailing-professional-polishing\.png/);});
