import test from "node:test";
import assert from "node:assert/strict";
import {calculateDiscount,type DiscountRule} from "../lib/discounts.ts";
import {discountTierLabel,parseDiscountTiers,selectDiscountTier,validateDiscountTiers,type DiscountTier} from "../lib/discountTiers.ts";
import {calculateFinancialDocument} from "../lib/financial/calculations.ts";
const tiers:DiscountTier[]=[{id:"low",minimum_subtotal_cents:17500,discount_type:"fixed",discount_value:5000},{id:"high",minimum_subtotal_cents:30000,discount_type:"fixed",discount_value:7500}];
const rule:DiscountRule={id:"discount",business_id:"tenant",code:"SAVE",name:"Rental savings",discount_type:"fixed",discount_value:1000,applies_to:"order",minimum_subtotal_cents:null,starts_at:null,expires_at:null,usage_limit:null,per_customer_limit:null,first_time_customer_only:false,is_active:true,tiers};
const evaluate=(cents:number,overrides:Partial<DiscountRule>={})=>calculateDiscount({...rule,...overrides},[{id:"rental",quantity:1,unitPriceCents:cents}],new Set());
test("below the first tier does not qualify",()=>{const result=evaluate(17499);assert.equal(result.ok,false);if(!result.ok)assert.match(result.error,/minimum rental subtotal/);});
for(const [subtotal,savings,tier] of [[17500,5000,"low"],[25000,5000,"low"],[30000,7500,"high"],[50000,7500,"high"]] as const)test(`subtotal ${subtotal} applies only tier ${tier}`,()=>{const result=evaluate(subtotal);assert.ok(result.ok);assert.equal(result.discountCents,savings);assert.equal(result.totalCents,subtotal-savings);assert.equal(result.snapshot.tier?.id,tier);});
test("removing rentals downgrades or removes the promotion",()=>{let cart=[{id:"rental",quantity:2,unitPriceCents:17500}];let result=calculateDiscount(rule,cart,new Set());assert.equal(result.ok&&result.discountCents,7500);cart[0].quantity=1;result=calculateDiscount(rule,cart,new Set());assert.equal(result.ok&&result.discountCents,5000);cart=[];assert.equal(calculateDiscount(rule,cart,new Set()).ok,false);});
test("display ordering does not change the highest qualifying threshold",()=>{assert.equal(selectDiscountTier([...tiers].reverse(),30000)?.id,"high");assert.equal(evaluate(30000,{tiers:[...tiers].reverse()}).ok,true);});
test("a discount can contain exactly one tier",()=>{const result=evaluate(20000,{tiers:[tiers[0]]});assert.equal(result.ok&&result.discountCents,5000);});
test("legacy empty or absent tiers preserve fixed/percentage and minimum behavior",()=>{const legacy=evaluate(20000,{tiers:undefined});assert.equal(legacy.ok&&legacy.discountCents,1000);const percentage=evaluate(20000,{tiers:[],discount_type:"percentage",discount_value:2000});assert.equal(percentage.ok&&percentage.discountCents,4000);assert.equal(evaluate(20000,{tiers:[],minimum_subtotal_cents:25000}).ok,false);});
test("tier thresholds supersede the legacy minimum",()=>{assert.equal(evaluate(17500,{minimum_subtotal_cents:50000}).ok,true);});
test("tiers support percentage discounts and cap fixed savings at eligible rentals",()=>{const percentage=evaluate(30000,{tiers:[{...tiers[0],discount_type:"percentage",discount_value:2000}]});assert.equal(percentage.ok&&percentage.discountCents,6000);const capped=evaluate(17500,{tiers:[{...tiers[0],discount_value:90000}]});assert.equal(capped.ok&&capped.discountCents,17500);});
test("qualification excludes operator fees, but legacy discounts keep their operator behavior",()=>{const items=[{id:"rental",quantity:1,unitPriceCents:35000,rentalUnitPriceCents:17000}];assert.equal(calculateDiscount(rule,items,new Set()).ok,false);const legacy=calculateDiscount({...rule,tiers:[],discount_type:"percentage",discount_value:2000},items,new Set());assert.equal(legacy.ok&&legacy.discountCents,7000);});
test("selected-item tiers qualify on all rentals and discount only eligible rentals",()=>{const result=calculateDiscount({...rule,applies_to:"selected_items"},[{id:"bounce",quantity:1,unitPriceCents:20000},{id:"chair",quantity:1,unitPriceCents:10000}],new Set(["chair"]));assert.ok(result.ok);assert.equal(result.snapshot.qualifyingSubtotalCents,30000);assert.equal(result.eligibleSubtotalCents,10000);assert.equal(result.discountCents,7500);});
test("snapshots keep promotion identity, chosen tier and savings after edits",()=>{const result=evaluate(30000);assert.ok(result.ok);const saved=JSON.parse(JSON.stringify(result.snapshot));const edited={...rule,tiers:tiers.map(tier=>({...tier,discount_value:100}))};calculateDiscount(edited,[{id:"rental",quantity:1,unitPriceCents:30000}],new Set());assert.equal(saved.tier.discount_value,7500);assert.equal(saved.discountId,"discount");assert.equal(saved.discountCents,7500);assert.equal(saved.tierLabel,"$75 off $300+");});
test("previews render the requested labels",()=>{assert.equal(discountTierLabel(tiers[0]),"$50 off $175+");assert.equal(discountTierLabel(tiers[1]),"$75 off $300+");assert.equal(discountTierLabel({...tiers[0],discount_type:"percentage",discount_value:1250}),"12.5% off $175+");});
test("conflicting thresholds, duplicate IDs and invalid values are rejected",()=>{for(const value of [[tiers[0],{...tiers[1],minimum_subtotal_cents:17500}],[tiers[0],{...tiers[1],id:"low"}],[{...tiers[0],discount_value:-1}],[{...tiers[0],discount_type:"percentage",discount_value:10001}],[{...tiers[0],minimum_subtotal_cents:1.5}],null])assert.ok(validateDiscountTiers(value));assert.throws(()=>parseDiscountTiers("bad json"));});
test("decreasing fixed and percentage values are rejected",()=>{assert.ok(validateDiscountTiers([tiers[0],{...tiers[1],discount_value:4900}]));assert.ok(validateDiscountTiers([{...tiers[0],discount_type:"percentage",discount_value:2000},{...tiers[1],discount_type:"percentage",discount_value:1000}]));});
test("mixed tier validation accounts for later percentage/fixed crossovers",()=>{assert.equal(validateDiscountTiers([tiers[0],{...tiers[1],discount_type:"percentage",discount_value:2000}]),null);assert.ok(validateDiscountTiers([tiers[0],{...tiers[1],discount_type:"percentage",discount_value:1000}]));assert.ok(validateDiscountTiers([{...tiers[0],discount_type:"percentage",discount_value:1000},tiers[1]]));assert.ok(validateDiscountTiers([tiers[0],{...tiers[1],discount_type:"percentage",discount_value:2000}],"selected_items"));});
test("invoice tax, delivery, deposit and Stripe amount use canonical discount savings",()=>{const promo=evaluate(30000);assert.ok(promo.ok);const invoice=calculateFinancialDocument({currency:"USD",lines:[{currency:"USD",quantity:"1",unitPriceCents:30000,taxable:true,taxRateBasisPoints:1000}],documentDiscount:{type:"fixed",value:promo.discountCents},feesCents:[2500],deposit:{type:"percentage",value:5000}});assert.equal(invoice.discountTotalCents,7500);assert.equal(invoice.grandTotalCents,27250);assert.equal(invoice.depositRequiredCents,13625);assert.equal(promo.snapshot.qualifyingSubtotalCents,30000);});
test("higher-tier validation never accepts worse savings at sampled eligible bases",()=>{
 for(const applies of ["order","selected_items"])for(const lowType of ["fixed","percentage"] as const)for(const highType of ["fixed","percentage"] as const)for(const low of [1,20,99])for(const high of [1,20,99]){
  const pair:DiscountTier[]=[{id:"a",minimum_subtotal_cents:50,discount_type:lowType,discount_value:lowType==="percentage"?low*100:low},{id:"b",minimum_subtotal_cents:100,discount_type:highType,discount_value:highType==="percentage"?high*100:high}];
  if(validateDiscountTiers(pair,applies))continue;
  const savings=(tier:DiscountTier,base:number)=>Math.min(base,tier.discount_type==="percentage"?Math.round(base*tier.discount_value/10000):tier.discount_value);
  for(let base=applies==="order"?100:0;base<=500;base++)assert.ok(savings(pair[1],base)>=savings(pair[0],base),JSON.stringify({pair,base,applies}));
 }
});
