import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("Google Business callback logs stage-by-stage diagnostics without secrets", async () => {
 const callback = await readFile(new URL("../app/api/google-business/callback/route.ts", import.meta.url), "utf8");
 assert.match(callback, /google_business_callback_started/);
 assert.match(callback, /google_business_callback_params_validated/);
 assert.match(callback, /google_business_state_validation_started/);
 assert.match(callback, /google_business_state_validation_completed/);
 assert.match(callback, /google_business_callback_workspace_resolution_started/);
 assert.match(callback, /google_business_callback_workspace_resolution_completed/);
 assert.match(callback, /google_business_oauth_config_validated/);
 assert.match(callback, /google_business_token_exchange_started/);
 assert.match(callback, /google_business_token_exchange_completed/);
 assert.match(callback, /google_business_token_exchange_failed/);
 assert.match(callback, /google_business_credentials_persist_started/);
 assert.match(callback, /google_business_credentials_persist_completed/);
 assert.match(callback, /google_business_account_discovery_started/);
 assert.match(callback, /google_business_account_discovery_completed/);
 assert.match(callback, /google_business_callback_completed/);
 assert.match(callback, /google_business_callback_failed/);
 assert.match(callback, /google_business_callback_redirected/);
 assert.match(callback, /state_not_found/);
 assert.match(callback, /state_mismatch/);
 assert.match(callback, /state_business_missing/);
 assert.match(callback, /missing_servonas_session/);
 assert.match(callback, /workspace_membership_missing/);
 assert.match(callback, /workspace_role_not_permitted/);
 assert.match(callback, /oauth_not_configured/);
 assert.match(callback, /exchangeGoogleBusinessCode\(code\)/);
 assert.match(callback, /googleBusinessCallbackId/);
 assert.match(callback, /redirectUriHost/);
 assert.doesNotMatch(callback, /authorizationCode:/);
 assert.doesNotMatch(callback, /accessToken:/);
 assert.doesNotMatch(callback, /refreshToken:/);
 assert.doesNotMatch(callback, /clientSecret:/);
});
