import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
const read=(path:string)=>readFile(new URL(`../${path}`,import.meta.url),"utf8");

test("consolidated admin is restricted and supports month YTD and prior year",async()=>{const page=await read("app/admin/page.tsx");assert.match(page,/isServonasPlatformAdmin/);assert.match(page,/redirect\("\/login\?next=\/admin"\)/);assert.match(page,/Year to date/);assert.match(page,/Prior year/);assert.match(page,/Platform usage &amp; spend/);});
test("admin dashboard links to the acquisition funnel report",async()=>{const page=await read("app/admin/page.tsx");assert.match(page,/href="\/app\/admin\/marketing\/acquisition"/);assert.match(page,/Acquisition Funnel/);});
test("customer grid hides disabled provider spend and exposes access toggles",async()=>{const [page,controls]=await Promise.all([read("app/admin/page.tsx"),read("app/admin/AdminCustomerControls.tsx")]);assert.match(page,/row\.access\.twilio\?/);assert.match(page,/row\.access\.ai\?/);assert.match(page,/Enable Twilio to show tenant spend/);assert.match(page,/Enable AI to show tenant spend/);assert.match(controls,/feature:"ai"\|"twilio"/);assert.match(controls,/Website management/);});
test("account lifecycle and deletion are audited platform-admin RPCs",async()=>{const [migration,actions]=await Promise.all([read("supabase/migrations/20260813000500_platform_admin_dashboard.sql"),read("app/admin/actions.ts")]);assert.match(migration,/public\.is_servonas_platform_admin\(\)/);assert.match(migration,/admin_set_business_lifecycle/);assert.match(migration,/admin_delete_business_permanently/);assert.match(migration,/p_confirmation<>'DELETE'/);assert.match(migration,/delete from public\.businesses where id=p_business_id/);assert.match(migration,/on delete cascade/);assert.match(actions,/No partial database deletion was committed/);});

test("permanent tenant erasure handles restrictive dependencies without weakening normal audit immutability",async()=>{const migration=await read("supabase/migrations/20260814000300_safe_platform_business_deletion.sql");assert.match(migration,/permanent_business_delete_authorized/);assert.match(migration,/current_setting\('servonas\.permanent_business_delete',true\)='on'/);assert.match(migration,/and public\.is_servonas_platform_admin\(\)/);assert.match(migration,/p_confirmation<>'DELETE'/);assert.match(migration,/platform_business_admin_events/);assert.match(migration,/exception when foreign_key_violation/);assert.match(migration,/delete from public\.businesses where id=p_business_id/);assert.match(migration,/c\.relname not in \('businesses','platform_business_admin_events'\)/);assert.doesNotMatch(migration,/disable trigger/i);});
test("website management cost is snapshotted by billing month",async()=>{const [migration,cron]=await Promise.all([read("supabase/migrations/20260813000500_platform_admin_dashboard.sql"),read("app/api/cron/financial/route.ts")]);assert.match(migration,/business_website_management_periods/);assert.match(migration,/monthly_cost_cents/);assert.match(cron,/Website management snapshot failed/);assert.match(cron,/business_id,billing_period_start/);});
test("legacy split admin pages redirect to the consolidated dashboard",async()=>{for(const path of["app/app/admin/ai/page.tsx","app/app/admin/twilio/page.tsx","app/app/admin/customers/page.tsx"]){assert.match(await read(path),/redirect\("\/admin"\)/);}});
