import assert from "node:assert/strict";
import test from "node:test";
import {createComplianceService,type ComplianceRepository} from "../lib/twilio/compliance.ts";
import {createPhoneNumberService,type PhoneNumberRepository} from "../lib/twilio/phoneNumbers.ts";
import {validTwilioSignature} from "../lib/twilioWebhook.ts";
import {createHmac} from "node:crypto";

const business="aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",account={id:"account-row",businessId:business,subaccountSid:`AC${"1".repeat(32)}`,friendlyName:"A",subaccountStatus:"active",provisioningStatus:"active" as const,provisioningError:null,lastSyncedAt:null};

test("Twilio signature validation includes exact URL and sorted form values",()=>{const url="https://servonas.com/api/twilio/inbound",p=new URLSearchParams({To:"+14805550123",From:"+14805550124",Body:"hello"});const payload=url+[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>k+v).join("");const sig=createHmac("sha1","token").update(payload).digest("base64");assert.equal(validTwilioSignature(url,p,sig,"token"),true);assert.equal(validTwilioSignature(url+"/",p,sig,"token"),false);});

test("compliance creation is tenant scoped, idempotent, and never persists registration ID",async()=>{let row:any=null,calls=0;const writes:Record<string,unknown>[]=[];const repository:ComplianceRepository={async get(id){return row?.business_id===id?row:null;},async insert(v){writes.push(v);row={id:"r",twilio_customer_profile_sid:null,twilio_end_user_sid:null,registration_type:"secondary_customer_profile",status:"draft",status_reason:null,twilio_error_code:null,twilio_error_message_sanitized:null,last_synced_at:null,...v};return row;},async update(_id,v){writes.push(v);Object.assign(row,v);return row;}};const provider={async getProfile(){return{sid:`BU${"2".repeat(32)}`,status:"twilio-approved"};},async createDraft(){calls++;return{sid:`BU${"2".repeat(32)}`,status:"draft"};}};const old=process.env.TWILIO_SECONDARY_CUSTOMER_PROFILE_POLICY_SID;process.env.TWILIO_SECONDARY_CUSTOMER_PROFILE_POLICY_SID=`RN${"3".repeat(32)}`;const service=createComplianceService({repository,provider,getAccount:async()=>account});const input={authorizedRepresentative:{firstName:"A",lastName:"B",email:"a@example.com",phone:"+14805550123",businessTitle:"Owner",jobPosition:"Owner"},business:{legalName:"A",customerType:"business",registrationIdType:"ein",registrationIdNumber:"12-3456789",industry:"services",companyType:"llc",websiteUrl:"https://example.com",regionsOfOperation:["US"],address:{street:"1 Main",city:"Gilbert",region:"AZ",postalCode:"85296",country:"US"}}};await service.getOrCreateBusinessComplianceRegistration(business,input);await service.getOrCreateBusinessComplianceRegistration(business,input);assert.equal(calls,1);assert.equal(JSON.stringify(writes).includes("12-3456789"),false);if(old===undefined)delete process.env.TWILIO_SECONDARY_CUSTOMER_PROFILE_POLICY_SID;else process.env.TWILIO_SECONDARY_CUSTOMER_PROFILE_POLICY_SID=old;});

test("number purchase reconciles provider state and repeated calls do not buy twice",async()=>{let row:any=null,purchases=0,owned:any=null;const repository:PhoneNumberRepository={async getPrimary(){return row?.twilio_phone_number_sid?row:null;},async getByNumber(){return row;},async claim(v){row={id:"n",twilio_phone_number_sid:null,...v};return row;},async mark(_id,v){Object.assign(row,v);return row;}};const provider={async search(){return[];},async findOwned(){return owned;},async purchase(_sid:string,phone:string){purchases++;owned={sid:`PN${"4".repeat(32)}`,phone_number:phone};return owned;}};const service=createPhoneNumberService({repository,provider,getAccount:async()=>account,getCompliance:async()=>({id:"c",businessId:business,twilioCustomerProfileSid:`BU${"2".repeat(32)}`,status:"approved",statusReason:null,errorCode:null,errorMessage:null,lastSyncedAt:null})});const first=await service.purchaseBusinessPhoneNumber(business,"+14805550123");const second=await service.purchaseBusinessPhoneNumber(business,"+14805550123");assert.equal(first.twilio_phone_number_sid,second.twilio_phone_number_sid);assert.equal(purchases,1);assert.equal(first.provisioning_status,"pending_webhook_security");});

test("number search and purchase are blocked before compliance approval",async()=>{const repository={} as PhoneNumberRepository,provider={} as any;const service=createPhoneNumberService({repository,provider,getAccount:async()=>account,getCompliance:async()=>null});await assert.rejects(service.searchBusinessPhoneNumbers(business,{areaCode:"480"}),/approved/);});
