import assert from "node:assert/strict";
import test from "node:test";
import {createHmac} from "node:crypto";
import {readFile} from "node:fs/promises";
import {resolveInboundWebhookSecurity} from "../lib/twilio/inboundWebhookSecurity.ts";
import {validTwilioSignature} from "../lib/twilioWebhook.ts";
import {createBusinessTwilioProvider,getParentTwilioClient,reconcileExistingBusinessTwilioSecret,TwilioRemediationError,type BusinessTwilioRepository,type StoredBusinessTwilioAccount} from "../lib/twilio/businessTwilioProvider.ts";

const a="aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",b="bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",sidA=`AC${"1".repeat(32)}`,sidB=`AC${"2".repeat(32)}`;
const secretStore=()=>{const values=new Map<string,string>();return{values,async storeSubaccountAuthToken(i:any){values.set(`${i.businessId}:${i.subaccountSid}`,i.authToken);return{status:"available" as const,version:1,updatedAt:"2026-08-10T00:00:00Z"};},async getSubaccountAuthToken(i:any){return values.get(`${i.businessId}:${i.subaccountSid}`)??null;},async deleteSubaccountAuthToken(i:any){values.delete(`${i.businessId}:${i.subaccountSid}`);},async rotateSubaccountAuthToken(i:any){values.set(`${i.businessId}:${i.subaccountSid}`,i.authToken);return{status:"available" as const,version:2,updatedAt:"2026-08-10T00:00:00Z"};}};};

test("tenant secret lookup is bound to both business and subaccount",async()=>{const secrets=secretStore();await secrets.storeSubaccountAuthToken({businessId:a,subaccountSid:sidA,authToken:"tenant-a-secret"});assert.equal(await secrets.getSubaccountAuthToken({businessId:a,subaccountSid:sidA}),"tenant-a-secret");assert.equal(await secrets.getSubaccountAuthToken({businessId:b,subaccountSid:sidA}),null);assert.equal(await secrets.getSubaccountAuthToken({businessId:a,subaccountSid:sidB}),null);});

test("unknown account and missing tenant secret fail closed while legacy parent remains valid",async()=>{const secrets=secretStore(),mappings={async find(accountSid:string,to:string){return accountSid===sidA&&to==="+14805550123"?{businessId:a,subaccountSid:sidA}:null;}};assert.equal(await resolveInboundWebhookSecurity({accountSid:sidB,to:"+14805550123",parentAccountSid:"ACparent",parentAuthToken:"parent"},{mappings,secrets}),null);assert.equal(await resolveInboundWebhookSecurity({accountSid:sidA,to:"+14805550123",parentAccountSid:"ACparent",parentAuthToken:"parent"},{mappings,secrets}),null);const legacy=await resolveInboundWebhookSecurity({accountSid:"ACparent",to:"+14805550123",parentAccountSid:"ACparent",parentAuthToken:"parent"},{mappings,secrets});assert.equal(legacy?.token,"parent");});

test("valid tenant signature succeeds and invalid signature is rejected",async()=>{const secrets=secretStore();await secrets.storeSubaccountAuthToken({businessId:a,subaccountSid:sidA,authToken:"tenant-secret"});const mappings={async find(){return{businessId:a,subaccountSid:sidA};}},security=await resolveInboundWebhookSecurity({accountSid:sidA,to:"+14805550123",parentAccountSid:"ACparent",parentAuthToken:"parent"},{mappings,secrets});const url="https://servonas.com/api/twilio/inbound",params=new URLSearchParams({AccountSid:sidA,To:"+14805550123",Body:"Hi"}),payload=url+[...params.entries()].sort(([x],[y])=>x.localeCompare(y)).map(([k,v])=>k+v).join(""),signature=createHmac("sha1",security!.token).update(payload).digest("base64");assert.equal(validTwilioSignature(url,params,signature,security!.token),true);assert.equal(validTwilioSignature(url,params,"invalid",security!.token),false);});

test("migration stores only an opaque Vault reference and no token column",async()=>{const sql=await readFile(new URL("../supabase/migrations/20260810000400_twilio_subaccount_vault_secrets.sql",import.meta.url),"utf8");assert.match(sql,/webhook_secret_id uuid/);assert.doesNotMatch(sql,/add column[^;]*(auth_token|credential_value|plaintext)/i);assert.match(sql,/vault\.create_secret/);});

test("existing-subaccount remediation fetches only and cannot create a duplicate",async()=>{let creates=0;const row={business_id:a,twilio_subaccount_sid:sidA} as StoredBusinessTwilioAccount,repository={async getAccount(){return row;}} as unknown as BusinessTwilioRepository,parentClient={async findSubaccountByFriendlyName(){return null;},async getSubaccount(){return{sid:sidA,friendly_name:"Copper State Bounce",status:"active",auth_token:"recovered-secret"};},async createSubaccount(){creates++;throw new Error("must not create");}},secrets=secretStore();const result=await reconcileExistingBusinessTwilioSecret({repository,parentClient,secretStore:secrets},a);assert.equal(result.subaccountSid,sidA);assert.equal(creates,0);assert.equal(await secrets.getSubaccountAuthToken({businessId:a,subaccountSid:sidA}),"recovered-secret");});

test("partial provisioning retry reconciles the existing subaccount instead of creating another",async()=>{let creates=0,finds=0,stores=0;const base={id:"r",business_id:a,twilio_subaccount_sid:null,twilio_subaccount_friendly_name:null,twilio_subaccount_status:null,provisioning_status:"failed",provisioning_error:null,created_at:new Date(0).toISOString(),updated_at:new Date(0).toISOString(),last_synced_at:null,webhook_secret_status:"missing",webhook_secret_version:0,webhook_secret_updated_at:null} as StoredBusinessTwilioAccount;const repository={async getBusiness(){return{id:a,name:"A"};},async getAccount(){return base;},async insertProvisioning(){return base;},async markProvisioning(){base.provisioning_status="provisioning";return base;},async markActive(_id:string,account:any){base.twilio_subaccount_sid=account.sid;base.provisioning_status="active";return base;},async markFailed(){base.provisioning_status="failed";},async markWebhookSecretError(){base.webhook_secret_status="error";}} as BusinessTwilioRepository;const parentClient={async findSubaccountByFriendlyName(name:string){finds++;return finds>1?{sid:sidA,friendly_name:name,status:"active",auth_token:"secret"}:null;},async getSubaccount(){throw new Error();},async createSubaccount(name:string){creates++;return{sid:sidA,friendly_name:name,status:"active",auth_token:"secret"};}};const secrets=secretStore(),original=secrets.storeSubaccountAuthToken;secrets.storeSubaccountAuthToken=async(i:any)=>{stores++;if(stores===1)throw new Error("vault unavailable");return original(i);};const provider=createBusinessTwilioProvider({repository,parentClient,secretStore:secrets});await assert.rejects(provider.createBusinessTwilioSubaccount(a));base.twilio_subaccount_sid=null;base.updated_at=new Date(0).toISOString();await provider.createBusinessTwilioSubaccount(a);assert.equal(creates,1);});

test("safe security diagnostic route never serializes or returns a credential",async()=>{const source=await readFile(new URL("../app/api/admin/twilio/subaccounts/[businessId]/security/route.ts",import.meta.url),"utf8");assert.doesNotMatch(source,/authToken\s*:/);assert.doesNotMatch(source,/token\s*:/);});

test("credential recovery uses parent Account SID and Auth Token instead of the API key",async()=>{const previous={...process.env},originalFetch=global.fetch;Object.assign(process.env,{TWILIO_ACCOUNT_SID:"ACparent",TWILIO_AUTH_TOKEN:"parent-token",TWILIO_API_KEY_SID:"SKmain",TWILIO_API_KEY_SECRET:"key-secret"});let authorization="";global.fetch=async(_input,init)=>{authorization=new Headers(init?.headers).get("authorization")??"";return new Response(JSON.stringify({sid:sidA,friendly_name:"A",status:"active",auth_token:"tenant-token"}),{status:200,headers:{"content-type":"application/json"}});};try{await getParentTwilioClient().getSubaccount(sidA);assert.equal(Buffer.from(authorization.slice(6),"base64").toString(),"ACparent:parent-token");}finally{global.fetch=originalFetch;process.env=previous;}});

test("Twilio recovery failure stops before Vault and reports a sanitized stage",async()=>{let vaultCalls=0;const repository={async getAccount(){return{twilio_subaccount_sid:sidA} as StoredBusinessTwilioAccount;}} as unknown as BusinessTwilioRepository,parentClient={async findSubaccountByFriendlyName(){return null;},async createSubaccount(){throw new Error();},async getSubaccount(){throw new TwilioRemediationError("twilio_recovery",401,20003);}},secrets={...secretStore(),async storeSubaccountAuthToken(){vaultCalls++;throw new Error();}};await assert.rejects(reconcileExistingBusinessTwilioSecret({repository,parentClient,secretStore:secrets},a),(error:any)=>error instanceof TwilioRemediationError&&error.stage==="twilio_recovery"&&error.providerStatus===401);assert.equal(vaultCalls,0);});

test("Vault failure is distinguishable without exposing the credential",async()=>{const repository={async getAccount(){return{twilio_subaccount_sid:sidA} as StoredBusinessTwilioAccount;}} as unknown as BusinessTwilioRepository,parentClient={async findSubaccountByFriendlyName(){return null;},async createSubaccount(){throw new Error();},async getSubaccount(){return{sid:sidA,friendly_name:"A",status:"active",auth_token:"tenant-token"};}},secrets={...secretStore(),async storeSubaccountAuthToken(){throw new Error("database detail must not escape");}};await assert.rejects(reconcileExistingBusinessTwilioSecret({repository,parentClient,secretStore:secrets},a),(error:any)=>error instanceof TwilioRemediationError&&error.stage==="vault_storage"&&!error.message.includes("database detail"));});
