import Link from "next/link";
import { notFound } from "next/navigation";
import { WorkspaceNav } from "../../WorkspaceNav";
import { requireWorkspace } from "@/lib/workspace";
import { canManageCustomers } from "@/lib/access";
import { addJobNote, addJobPhoto, archiveJob, assignJobTechnician, cancelJob, changeJobStatus, editJobNote, removeJobPhoto } from "../actions";
import { availableJobTransitions, type JobStatus } from "@/lib/jobStatusTransitions";
import {MissedCallTranscript} from "@/components/MissedCallTranscript";
import {CustomerActionIcon} from "@/components/CustomerActionIcon";

const relation = <T,>(value: T | T[] | null) => Array.isArray(value) ? value[0] ?? null : value;
const money = (value: number | null) => `$${Number(value ?? 0).toFixed(2)}`;
export default async function JobDetail({ params, searchParams }: { params: Promise<{ businessSlug: string; jobId: string }>; searchParams: Promise<Record<string, string | undefined>> }) {
  const { businessSlug, jobId } = await params;
  const query = await searchParams;
  const { supabase, business, role } = await requireWorkspace(businessSlug);
  const [{ data: job, error }, { data: history }, { data: notes }, { data: photoRows }, { data: technicians },{data:recoveryMessages}] = await Promise.all([
    supabase.from("jobs").select("*,customers!jobs_customer_tenant_fk(id,first_name,last_name,company_name,email,phone),service_locations!jobs_service_location_tenant_fk(id,location_name,street_address,unit,city,state,postal_code),services!jobs_service_tenant_fk(name)").eq("id", jobId).eq("business_id", business.id).eq("is_deleted", false).maybeSingle(),
    supabase.from("job_timeline_events").select("id,event_type,summary,actor_name,occurred_at,employees!job_timeline_actor_employee_fk(preferred_name)").eq("job_id", jobId).eq("business_id", business.id).order("occurred_at", { ascending: false }),
    supabase.from("job_notes").select("id,body,note_type,author_name,created_at,updated_at,employees!job_notes_author_employee_fk(preferred_name)").eq("job_id", jobId).eq("business_id", business.id).order("created_at", { ascending: false }),
    supabase.from("job_photos").select("id,storage_path,caption,photo_type,created_at").eq("job_id", jobId).eq("business_id", business.id).order("created_at", { ascending: false }),
    supabase.from("technician_directory").select("id,preferred_name,technician_status").eq("business_id", business.id).eq("is_active", true).eq("is_technician", true).eq("can_be_assigned_jobs", true).order("preferred_name"),
    supabase.from("missed_call_recovery_messages").select("id,direction,body,ai_generated,delivery_status,created_at").eq("business_id",business.id).eq("job_id",jobId).order("created_at"),
  ]);
  if (error) console.error("Job detail query failed", { code: error.code, businessId: business.id, jobId });
  if (!job) notFound();
  const customer = relation(job.customers), location = relation(job.service_locations), service = relation(job.services), technician = technicians?.find(item=>item.id===job.assigned_technician_id);
  const canEdit = canManageCustomers(role);
  const statusTransitions = availableJobTransitions(job.status as JobStatus);
  const dateTime = (value: string | null) => value ? new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: business.timezone }).format(new Date(value)) : "Not set";
  const photos = await Promise.all((photoRows ?? []).map(async (photo) => {
    const { data } = await supabase.storage.from("job-photos").createSignedUrl(photo.storage_path, 3600);
    return { ...photo, url: data?.signedUrl ?? null };
  }));
  return <main className="epic3-shell"><WorkspaceNav slug={businessSlug} name={business.name} industry={business.industry_profile}/><section className="epic3-content customer-record-page job-record-page">
    <header className="customer-record-header"><div><small><Link href={`/app/${businessSlug}/jobs`}>Jobs</Link> › Job #{job.job_number}</small><h1>{job.title} <span className={`job-status ${job.status}`}>{job.status.replaceAll("_", " ")}</span></h1><p>{service?.name||"Custom work"} · <span className={`job-priority ${job.priority}`}>{job.priority} priority</span>{job.is_return_visit&&<span className="return-visit-badge">Return visit</span>}</p></div><div className="crm-header-actions">{customer?.phone&&<a className="sv-button sv-secondary" href={`tel:${customer.phone}`}>Call</a>}{customer?.email&&<a className="sv-button sv-secondary" href={`mailto:${customer.email}`}>Email</a>}{canEdit&&<Link className="sv-button sv-secondary" href={`/app/${businessSlug}/invoices/new?jobId=${jobId}`}>Create invoice</Link>}{canEdit&&<Link className="sv-button" href={`/app/${businessSlug}/jobs/${jobId}/edit`}>Edit job</Link>}</div></header>
    {query.error && <div className="workspace-notice error">{query.error}</div>}{query.success && <div className="workspace-notice success">{query.success}</div>}

    <section className="customer-record-metrics redesigned job-record-metrics">
      <article className="job-metric-status"><div><i><CustomerActionIcon name="check"/></i><span><small>Status</small><strong>{job.status.replaceAll("_"," ")}</strong></span></div><p>Current job stage</p></article>
      <article className="next-service"><div><i><CustomerActionIcon name="calendar"/></i><span><small>Scheduled</small><strong>{dateTime(job.starts_at)}</strong></span></div><p>{job.schedule_commitment==="flexible"?"Flexible appointment":"Set appointment"}</p></article>
      <article className="last-service"><div><i><CustomerActionIcon name="clock"/></i><span><small>Duration</small><strong>{job.estimated_duration_minutes?`${job.estimated_duration_minutes} min`:"—"}</strong></span></div><p>Estimated service time</p></article>
      <article className="job-metric-technician"><div><i><CustomerActionIcon name="customer"/></i><span><small>Technician</small><strong>{technician?.preferred_name||"Unassigned"}</strong></span></div><p>Primary assignment</p></article>
      <article className="spent"><div><i><CustomerActionIcon name="chart"/></i><span><small>Job total</small><strong>{money(job.total_amount)}</strong></span></div><p>Service total</p></article>
      <article className="balance"><div><i><CustomerActionIcon name="card"/></i><span><small>Payment</small><strong>{job.payment_status.replaceAll("_"," ")}</strong></span></div><p>{job.booking_source||"Direct booking"}</p></article>
    </section>

    <nav className="customer-record-tabs"><span>Overview</span><a href="#notes">Notes <b>{notes?.length??0}</b></a><a href="#photos">Photos <b>{photos.length}</b></a><a href="#activity">Activity <b>{history?.length??0}</b></a>{customer&&<Link href={`/app/${businessSlug}/customers/${customer.id}`}>Customer</Link>}<Link href={`/app/${businessSlug}/invoices/new?jobId=${jobId}`}>Invoice</Link></nav>

    <div className="customer-record-columns"><div className="customer-record-main job-record-main">
     <div className="crm-detail-grid job-record-overview">
      <section className="workspace-panel job-summary"><div className="panel-title"><h2>Customer &amp; location</h2>{customer&&<Link href={`/app/${businessSlug}/customers/${customer.id}`}>View customer</Link>}</div><dl>
        <div><dt>Customer</dt><dd>{customer ? <Link href={`/app/${businessSlug}/customers/${customer.id}`}>{customer.company_name || `${customer.first_name} ${customer.last_name}`}</Link> : "Not assigned"}</dd></div>
        <div><dt>Phone</dt><dd>{customer?.phone ? <a href={`tel:${customer.phone}`}>{customer.phone}</a> : "Not set"}</dd></div><div><dt>Email</dt><dd>{customer?.email ? <a href={`mailto:${customer.email}`}>{customer.email}</a> : "Not set"}</dd></div>
        <div><dt>Location</dt><dd>{location ? <>{location.location_name}<br/><span>{[location.street_address, location.unit, location.city, location.state, location.postal_code].filter(Boolean).join(", ")}</span></> : job.service_address || "Not set"}</dd></div>
      </dl><h2>Work details</h2><dl><div><dt>Service</dt><dd>{service?.name || "Custom work"}</dd></div><div><dt>Visit type</dt><dd>{job.is_return_visit?"Return visit":"Original visit"}</dd></div>{job.is_return_visit&&<div><dt>Return reason</dt><dd>{job.return_visit_reason||"Not provided"}</dd></div>}{job.return_visit_for_job_id&&<div><dt>Original job</dt><dd><Link href={`/app/${businessSlug}/jobs/${job.return_visit_for_job_id}`}>View original job</Link></dd></div>}<div><dt>Description</dt><dd>{job.description || "No description"}</dd></div></dl>
      </section>
      <section className="workspace-panel job-summary"><div className="panel-title"><h2>Schedule &amp; billing</h2>{canEdit&&<Link href={`/app/${businessSlug}/jobs/${jobId}/edit`}>Edit</Link>}</div><dl><div><dt>Time commitment</dt><dd>{job.schedule_commitment==="flexible"?"Flexible during service day":"Set appointment time"}</dd></div><div><dt>Start</dt><dd>{dateTime(job.starts_at)}</dd></div><div><dt>End</dt><dd>{dateTime(job.ends_at)}</dd></div><div><dt>Arrival window</dt><dd>{job.arrival_window_start ? `${dateTime(job.arrival_window_start)} – ${dateTime(job.arrival_window_end)}` : "Not set"}</dd></div><div><dt>Duration</dt><dd>{job.estimated_duration_minutes ? `${job.estimated_duration_minutes} minutes` : "Not set"}</dd></div></dl>
        <h2>Price & payment</h2><dl><div><dt>Subtotal</dt><dd>{money(job.subtotal)}</dd></div><div><dt>Tax</dt><dd>{money(job.tax_amount)}</dd></div><div><dt>Discount</dt><dd>−{money(job.discount_amount)}</dd></div><div><dt>Total</dt><dd><strong>{money(job.total_amount)}</strong></dd></div><div><dt>Payment</dt><dd>{job.payment_status.replaceAll("_", " ")}</dd></div><div><dt>Source</dt><dd>{job.booking_source || "Unknown"}</dd></div></dl>
      </section>
     </div>
    <MissedCallTranscript messages={recoveryMessages??[]} timeZone={business.timezone}/>
    <section className="workspace-panel" id="notes"><div className="panel-title"><div><span className="sv-kicker">Communication</span><h2>Job notes</h2></div>{canEdit&&<form className="job-note-action" action={addJobNote.bind(null,businessSlug,jobId)}><select name="noteType" aria-label="Note visibility" defaultValue="internal"><option value="internal">Internal</option><option value="customer_visible">Customer visible</option></select><textarea required name="note" rows={2} maxLength={4000} placeholder="Add an office note…"/><button className="sv-button sv-secondary">Add note</button></form>}</div>{notes?.length?<div className="job-note-list">{notes.map((note)=><article key={note.id}><div><b>{note.note_type.replaceAll("_"," ")}</b><span>{relation(note.employees)?.preferred_name||note.author_name} · {dateTime(note.created_at)}{note.updated_at!==note.created_at?" · edited":""}</span></div><p>{note.body}</p>{canEdit&&<details><summary>Edit</summary><form action={editJobNote.bind(null,businessSlug,jobId)}><input type="hidden" name="noteId" value={note.id}/><select name="noteType" defaultValue={note.note_type}><option value="internal">Internal</option><option value="customer_visible">Customer visible</option></select><textarea required name="note" rows={3} maxLength={4000} defaultValue={note.body}/><button className="sv-button sv-secondary">Save note</button></form></details>}</article>)}</div>:<p>No notes recorded yet.</p>}</section>
    <section className="workspace-panel job-record-photos" id="photos"><div className="panel-title"><div><h2>Job photos</h2><p>Private job documentation. Links expire after one hour.</p></div>{canEdit&&<form action={addJobPhoto.bind(null,businessSlug,jobId)}><input required name="photo" type="file" accept="image/jpeg,image/png,image/webp,image/heic"/><select name="photoType" defaultValue="general" aria-label="Photo type"><option value="before">Before</option><option value="after">After</option><option value="general">General</option></select><input name="caption" maxLength={200} placeholder="Optional caption"/><button className="sv-button sv-secondary">Upload photo</button></form>}</div>{photos.length?<div className="job-photo-grid">{photos.map(photo=>photo.url&&<figure key={photo.id}><a href={photo.url} target="_blank" rel="noreferrer"><img src={photo.url} alt={photo.caption||`${photo.photo_type} job photo`}/></a><figcaption><b>{photo.photo_type}</b>{photo.caption&&<span>{photo.caption}</span>}{canEdit&&<form action={removeJobPhoto.bind(null,businessSlug,jobId)}><input type="hidden" name="photoId" value={photo.id}/><button className="text-button">Remove</button></form>}</figcaption></figure>)}</div>:<p>No photos uploaded.</p>}</section>
    </div><aside className="customer-record-aside job-record-aside">
     {canEdit?<section className="workspace-panel customer-side-card job-record-controls"><div className="panel-title"><h2>Job controls</h2><span className={`job-status ${job.status}`}>{job.status.replaceAll("_"," ")}</span></div><form action={assignJobTechnician.bind(null,businessSlug,jobId)}><label>Assigned technician<select name="technicianId" defaultValue={job.assigned_technician_id??""}><option value="">Unassigned</option>{technicians?.map(item=><option key={item.id} value={item.id} disabled={item.technician_status==="off_duty"}>{item.preferred_name}{item.technician_status==="off_duty"?" (off duty)":""}</option>)}</select></label><button className="sv-button sv-secondary">Save assignment</button></form>{statusTransitions.length>0&&<form action={changeJobStatus.bind(null,businessSlug,jobId)}><label>Next status<select name="status" defaultValue={statusTransitions[0]}>{statusTransitions.map(status=><option key={status} value={status}>{status.replaceAll("_"," ")}</option>)}</select></label><button className="sv-button">Update status</button></form>}{statusTransitions.includes("canceled")&&<details><summary>Cancel job</summary><form action={cancelJob.bind(null,businessSlug,jobId)}><label>Cancellation reason<input required name="cancellationReason" placeholder="Reason for cancellation"/></label><button className="sv-button sv-danger">Cancel job</button></form></details>}<form className="job-record-archive" action={archiveJob.bind(null,businessSlug,jobId)}><button className="text-button">Archive job</button></form></section>:<div className="workspace-notice">Your {role.replaceAll("_"," ")} role has read-only job access.</div>}
     <section className="workspace-panel customer-side-card" id="activity"><div className="panel-title"><h2>Recent activity</h2><span>{history?.length??0} events</span></div><div className="activity-list">{history?.length?history.slice(0,8).map(item=><article key={item.id}><div><strong>{item.summary}</strong><p>{relation(item.employees)?.preferred_name||item.actor_name}</p></div><span>{dateTime(item.occurred_at)}</span></article>):<p>No activity recorded yet.</p>}</div></section>
     <section className="workspace-panel customer-side-card"><div className="panel-title"><h2>Quick links</h2></div>{customer&&<Link className="employee-quick-action" href={`/app/${businessSlug}/customers/${customer.id}`}>Open customer</Link>}<Link className="employee-quick-action" href={`/app/${businessSlug}/invoices/new?jobId=${jobId}`}>Create invoice</Link><Link className="employee-quick-action" href={`/app/${businessSlug}/jobs`}>Back to jobs</Link></section>
    </aside></div>
  </section></main>;
}
