import Link from "next/link";
import { notFound } from "next/navigation";
import { WorkspaceNav } from "../../WorkspaceNav";
import { requireWorkspace } from "@/lib/workspace";
import { canManageCustomers } from "@/lib/access";
import { updateJob } from "../actions";
const statuses=["draft","pending","confirmed","in_progress","completed","canceled"];
const local=(value:string|null)=>value?new Date(new Date(value).getTime()-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16):"";
export default async function JobDetail({params,searchParams}:{params:Promise<{businessSlug:string;jobId:string}>;searchParams:Promise<Record<string,string|undefined>>}){
 const {businessSlug,jobId}=await params,q=await searchParams,{supabase,business,role}=await requireWorkspace(businessSlug);
 const [{data:job},{data:customers},{data:history}]=await Promise.all([supabase.from("jobs").select("*").eq("id",jobId).eq("business_id",business.id).eq("is_deleted",false).maybeSingle(),supabase.from("customers").select("id,first_name,last_name").eq("business_id",business.id).eq("is_deleted",false).order("last_name"),supabase.from("job_status_history").select("id,from_status,to_status,changed_at").eq("job_id",jobId).eq("business_id",business.id).order("changed_at",{ascending:false})]);
 if(!job) notFound(); const canEdit=canManageCustomers(role);
 return <main className="epic3-shell"><WorkspaceNav slug={businessSlug} name={business.name}/><section className="epic3-content"><header className="epic3-header"><div><small>Job #{job.job_number}</small><h1>{job.title}</h1><p><span className={`job-status ${job.status}`}>{job.status.replaceAll("_"," ")}</span></p></div><Link href={`/app/${businessSlug}/jobs`}>Back to jobs</Link></header>{q.error&&<div className="workspace-notice error">{q.error}</div>}{q.success&&<div className="workspace-notice success">{q.success}</div>}<div className="dashboard-grid"><section className="workspace-panel"><h2>Job details</h2><form action={updateJob.bind(null,businessSlug,jobId)} className="job-form"><label className="wide">Job title<input required name="title" defaultValue={job.title}/></label><label>Customer<select name="customerId" defaultValue={job.customer_id??""}><option value="">No customer selected</option>{(customers??[]).map(c=><option key={c.id} value={c.id}>{c.first_name} {c.last_name}</option>)}</select></label><label>Status<select name="status" defaultValue={job.status}>{statuses.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></label><label>Start<input name="startsAt" type="datetime-local" defaultValue={local(job.starts_at)}/></label><label>End<input name="endsAt" type="datetime-local" defaultValue={local(job.ends_at)}/></label><label className="wide">Service address<input name="serviceAddress" defaultValue={job.service_address??""}/></label><label>Subtotal<input name="subtotal" type="number" min="0" step="0.01" defaultValue={job.subtotal}/></label><label>Tax<input name="taxAmount" type="number" min="0" step="0.01" defaultValue={job.tax_amount}/></label><label className="wide">Description<textarea name="description" rows={4} defaultValue={job.description??""}/></label><label className="wide">Internal notes<textarea name="internalNotes" rows={4} defaultValue={job.internal_notes??""}/></label>{canEdit&&<button className="sv-button">Save job</button>}</form></section><section className="workspace-panel"><span className="sv-kicker">Total</span><div className="job-total">${Number(job.total_amount).toFixed(2)}</div><h2>Status history</h2><div className="activity-list">{history?.map(h=><article key={h.id}><strong>{h.from_status?`${h.from_status.replaceAll("_"," ")} → `:""}{h.to_status.replaceAll("_"," ")}</strong><span>{new Date(h.changed_at).toLocaleString()}</span></article>)}</div></section></div></section></main>;
}
