import {NextResponse} from "next/server";
import {createSupabaseServerClient} from "@/lib/supabaseServer";
import {requireTwilioPlatformAdmin,uuidPattern} from "@/lib/twilio/adminRoute";
import {activatePhase3,getPhase3Snapshot,type Phase3CampaignInput} from "@/lib/twilio/phase3Activation";
import {requireBusinessTwilioEnabled} from "@/lib/twilio/access";

export async function GET(_request:Request,{params}:{params:Promise<{businessId:string}>}){const unauthorized=await requireTwilioPlatformAdmin();if(unauthorized)return unauthorized;const {businessId}=await params;if(!uuidPattern.test(businessId))return NextResponse.json({error:"Invalid businessId"},{status:400});try{return NextResponse.json(await getPhase3Snapshot(businessId));}catch{return NextResponse.json({error:"Phase 3 status is unavailable."},{status:502});}}

export async function POST(request:Request,{params}:{params:Promise<{businessId:string}>}){const unauthorized=await requireTwilioPlatformAdmin();if(unauthorized)return unauthorized;const {businessId}=await params;if(!uuidPattern.test(businessId))return NextResponse.json({error:"Invalid businessId"},{status:400});let body:Partial<Phase3CampaignInput>&{confirmation?:string;acknowledgeCharges?:boolean};try{body=await request.json();}catch{return NextResponse.json({error:"A JSON request body is required."},{status:400});}const samples=Array.isArray(body.messageSamples)?body.messageSamples.filter(v=>typeof v==="string"&&v.trim()).slice(0,5):[];if(body.confirmation!=="ACTIVATE"||body.acknowledgeCharges!==true)return NextResponse.json({error:"Explicit activation and Twilio charge acknowledgement are required."},{status:400});if(!body.description?.trim()||!body.messageFlow?.trim()||!body.useCase?.trim()||samples.length<2)return NextResponse.json({error:"Campaign description, message flow, use case, and at least two message samples are required."},{status:400});const session=await createSupabaseServerClient(),{data:{user}}=await session.auth.getUser();try{await requireBusinessTwilioEnabled(businessId);return NextResponse.json({activation:await activatePhase3(businessId,{description:body.description.trim(),messageFlow:body.messageFlow.trim(),messageSamples:samples,useCase:body.useCase.trim(),hasEmbeddedLinks:Boolean(body.hasEmbeddedLinks),hasEmbeddedPhone:Boolean(body.hasEmbeddedPhone)},user!.id)});}catch(error){const blockers=error&&typeof error==="object"&&"blockers" in error&&Array.isArray(error.blockers)?error.blockers:undefined;return NextResponse.json({error:error instanceof Error?error.message:"Phase 3 activation failed.",...(blockers?{blockers}:{})},{status:blockers?409:502});}}
