import Link from "next/link";
import {canManageBusiness} from "@/lib/access";
import {requireWorkspace} from "@/lib/workspace";
import {WorkspaceNav} from "../../WorkspaceNav";
import {saveNotificationPreferences} from "../../notifications/actions";

export default async function NotificationSettings({params,searchParams}:{params:Promise<{businessSlug:string}>;searchParams:Promise<Record<string,string|undefined>>}){
 const {businessSlug}=await params,q=await searchParams,{supabase,business,role}=await requireWorkspace(businessSlug),canEdit=canManageBusiness(role),{data:preferences}=await supabase.from("business_notification_preferences").select("*").eq("business_id",business.id).maybeSingle();
 return <main className="epic3-shell"><WorkspaceNav slug={businessSlug} name={business.name} industry={business.industry_profile}/><section className="epic3-content notification-preferences"><header className="epic3-header"><div><span className="sv-kicker">Settings</span><h1>Notification preferences</h1><p>Choose which important updates appear in your Servonas notification center.</p></div><Link className="sv-button sv-secondary" href={`/app/${businessSlug}/notifications`}>View notifications</Link></header>{q.success&&<div className="workspace-notice success">{q.success}</div>}<form className="workspace-panel notification-preference-form" action={saveNotificationPreferences.bind(null,businessSlug)}><label><input type="checkbox" name="googleReviews" defaultChecked={preferences?.google_reviews_enabled??true} disabled={!canEdit}/><span><strong>Google reviews</strong><small>Show new Google review notifications that do not already have a business reply.</small></span></label><label><input type="checkbox" name="marketing" defaultChecked={preferences?.marketing_enabled??true} disabled={!canEdit}/><span><strong>Marketing</strong><small>Show Google Ads and other marketing issues as they are added to Servonas.</small></span></label><label><input type="checkbox" name="payments" defaultChecked={preferences?.payments_enabled??true} disabled={!canEdit}/><span><strong>Payments</strong><small>Show payment and billing alerts as they are added to Servonas.</small></span></label>{canEdit?<button className="sv-button">Save preferences</button>:<p className="workspace-notice">Only owners and administrators can change notification preferences.</p>}</form></section></main>;
}
