import Link from "next/link";
import {requireWorkspace} from "@/lib/workspace";
import {canManageCustomers} from "@/lib/access";
import {WorkspaceNav} from "../../WorkspaceNav";
import {mergeSmsDuplicate,updateMissedCallLeadStatus} from "./actions";

export default async function CustomerMessages({params,searchParams}:{params:Promise<{businessSlug:string}>;searchParams:Promise<Record<string,string|undefined>>}){
 const {businessSlug}=await params,q=await searchParams,{supabase,business,role}=await requireWorkspace(businessSlug),canEdit=canManageCustomers(role);
 const [{data:messages},{data:customers},{data:missedCallLeads},{data:recoveryMessages}]=await Promise.all([
  supabase.from("inbound_sms_messages").select("id,customer_id,from_phone_e164,body,classification,escalation_reasons,likely_spam,extracted_data,extracted_data_verified,auto_reply_status,provider_message_id,received_at,customers(first_name,last_name,company_name)").eq("business_id",business.id).order("received_at",{ascending:false}).limit(200),
  supabase.from("customers").select("id,first_name,last_name,company_name,phone,phone_normalized,created_at").eq("business_id",business.id).eq("is_deleted",false).not("phone_normalized","is",null).order("created_at"),
  supabase.from("missed_call_recovery_leads").select("id,customer_id,job_id,from_phone_e164,call_status,lead_status,conversation_status,customer_name,service_address,issue_summary,urgency,extracted_data_verified,created_at,customers(first_name,last_name,company_name),jobs(job_number,title)").eq("business_id",business.id).order("created_at",{ascending:false}).limit(100),
  supabase.from("missed_call_recovery_messages").select("id,lead_id,direction,body,ai_generated,delivery_status,created_at").eq("business_id",business.id).order("created_at").limit(1000),
 ]);
 const duplicateGroups=new Map<string,typeof customers>();
 for(const customer of customers??[]){const group=duplicateGroups.get(customer.phone_normalized!)??[];group.push(customer);duplicateGroups.set(customer.phone_normalized!,group);}
 const duplicates=[...duplicateGroups.entries()].filter(([,items])=>(items?.length??0)>1);
 const name=(value:any)=>{const customer=Array.isArray(value)?value[0]:value;return customer?.company_name||[customer?.first_name,customer?.last_name].filter(Boolean).join(" ")||"SMS lead";};
 return <main className="epic3-shell"><WorkspaceNav slug={businessSlug} name={business.name} industry={business.industry_profile}/><section className="epic3-content inbound-sms-page"><header className="epic3-header"><div><small><Link href={`/app/${businessSlug}/customers`}>Customers</Link> › Messages</small><h1>Inbound text messages</h1><p>Customer intake, consent events, escalations, spam review, and provider delivery evidence.</p></div><Link className="sv-button sv-secondary" href={`/app/${businessSlug}/settings#inbound-sms`}>SMS settings</Link></header>{q.error&&<div className="workspace-notice error">{q.error}</div>}{q.success&&<div className="workspace-notice success">{q.success}</div>}
  <section className="workspace-panel missed-call-board"><div className="panel-title"><div><h2>Missed Call Recovery</h2><span>{missedCallLeads?.length??0} recent leads</span></div><Link href={`/app/${businessSlug}/settings#missed-call-recovery`}>Recovery settings</Link></div><div className="missed-call-lead-list">{missedCallLeads?.map(lead=>{const transcript=(recoveryMessages??[]).filter(message=>message.lead_id===lead.id),job=Array.isArray(lead.jobs)?lead.jobs[0]:lead.jobs;return <article className={lead.urgency} key={lead.id}><header><div><Link href={`/app/${businessSlug}/customers/${lead.customer_id}`}>{lead.customer_name||name(lead.customers)}</Link><span>{lead.from_phone_e164} · {lead.call_status.replaceAll("-"," ")}</span></div><b>{lead.urgency} priority</b><time>{new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short",timeZone:business.timezone}).format(new Date(lead.created_at))}</time></header><p><strong>{lead.issue_summary||"Issue still being qualified"}</strong><br/>{lead.service_address||"Service address pending"}</p>{job&&<Link href={`/app/${businessSlug}/jobs/${lead.job_id}`}>Booked job #{job.job_number}: {job.title}</Link>}<form action={updateMissedCallLeadStatus.bind(null,businessSlug)}><input type="hidden" name="leadId" value={lead.id}/><label>Lead status<select name="leadStatus" defaultValue={lead.lead_status}><option value="new">New</option><option value="contacted">Contacted</option><option value="qualified">Qualified</option><option value="booked">Booked</option><option value="lost">Lost</option></select></label><button className="sv-button sv-secondary">Update</button></form><details><summary>Conversation · {transcript.length} messages</summary><div className="missed-call-transcript">{transcript.map(message=><div className={message.direction} key={message.id}><span>{message.direction}{message.ai_generated?" · AI":""}</span><p>{message.body}</p><small>{message.delivery_status} · {new Intl.DateTimeFormat("en-US",{dateStyle:"short",timeStyle:"short",timeZone:business.timezone}).format(new Date(message.created_at))}</small></div>)}</div></details></article>})}{!missedCallLeads?.length&&<div className="dashboard-empty"><strong>No missed-call leads yet.</strong><p>Enable recovery in settings and configure the Twilio voice status callback.</p></div>}</div></section>
  {duplicates.length>0&&<section className="workspace-panel"><div className="panel-title"><div><h2>Possible duplicate contacts</h2><span>Matched by standardized phone number</span></div><b>{duplicates.length}</b></div><div className="sms-duplicate-list">{duplicates.map(([phone,items])=><article key={phone}><div><strong>{phone}</strong><span>{items!.map(item=>name(item)).join(" · ")}</span></div>{canEdit&&<form action={mergeSmsDuplicate.bind(null,businessSlug)}><label>Merge<select name="sourceCustomerId" required defaultValue=""><option value="" disabled>Duplicate record</option>{items!.map(item=><option key={item.id} value={item.id}>{name(item)}</option>)}</select></label><span>into</span><label><select name="targetCustomerId" required defaultValue=""><option value="" disabled>Primary record</option>{items!.map(item=><option key={item.id} value={item.id}>{name(item)}</option>)}</select></label><button className="sv-button sv-secondary">Merge contact</button></form>}</article>)}</div></section>}
  <section className="workspace-panel"><div className="panel-title"><div><h2>Message inbox</h2><span>{messages?.length??0} recent messages</span></div></div><div className="inbound-sms-list">{messages?.map(message=><article className={message.classification} key={message.id}><header><div><Link href={`/app/${businessSlug}/customers/${message.customer_id}`}>{name(message.customers)}</Link><span>{message.from_phone_e164}</span></div><b>{message.classification.replaceAll("_"," ")}</b><time>{new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short",timeZone:business.timezone}).format(new Date(message.received_at))}</time></header><p>{message.body}</p>{message.escalation_reasons.length>0&&<div className="workspace-notice warning">Staff attention: {message.escalation_reasons.join(", ").replaceAll("_"," ")}</div>}{Object.keys(message.extracted_data??{}).length>0&&<small>Extracted information is <strong>{message.extracted_data_verified?"verified":"unconfirmed"}</strong>: {JSON.stringify(message.extracted_data)}</small>}<footer><span>Reply: {message.auto_reply_status.replaceAll("_"," ")}</span><span>Provider ID: {message.provider_message_id}</span></footer></article>)}{!messages?.length&&<div className="dashboard-empty"><strong>No inbound messages yet.</strong><p>Configure the designated number and Twilio webhook to begin receiving texts.</p></div>}</div></section>
 </section></main>;
}
