import type {Metadata} from "next";
import Image from "next/image";
import Link from "next/link";
export const metadata:Metadata={title:"Apex Auto Detail | Servonas Website Demo",description:"A fictional premium car-detailing website example created with Servonas.",robots:{index:false,follow:true}};
const packages=[["Interior Detail","Deep vacuuming, surfaces, windows, and careful interior finishing."],["Exterior Detail","Hand wash, wheels, tires, decontamination, and paint protection."],["Complete Detail","A thorough interior and exterior detail in one complete package."],["Ceramic Coating","Long-lasting gloss and paint protection with careful preparation."],["Paint Correction","Improve visible swirls, haze, and common paint imperfections."],["Maintenance Detail","Recurring care that keeps a vehicle consistently clean and protected."]];
const attributionKeys=["utm_source","utm_medium","utm_campaign","utm_content","utm_term","gclid","gbraid","wbraid"] as const;
export default async function CarDetailingDemo({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const params=await searchParams,query=new URLSearchParams({source:"car-detailing-website",utm_content:"car_detailing_demo"});for(const key of attributionKeys){const raw=params[key],value=Array.isArray(raw)?raw[0]:raw;if(value)query.set(key,value.slice(0,500));}return <main className="detail-demo">
 <aside className="detail-demo-banner"><span>This is an example detailing website built with Servonas.</span><Link href={`/signup?${query}`}>Get One For My Business — Free</Link></aside>
 <header className="detail-demo-nav"><a href="#top" className="detail-demo-brand"><i>A</i><span><strong>APEX</strong><small>AUTO DETAIL</small></span></a><nav><a href="#packages">Packages</a><a href="#results">Results</a><a href="#process">Process</a><a href="#booking">Book</a></nav><a className="detail-demo-button" href="#booking">Book a Detail</a></header>
 <section className="detail-demo-hero" id="top"><Image src="/images/car-detailing-professional-polishing.png" alt="Professional detailer polishing a premium vehicle" fill priority sizes="100vw"/><div className="detail-demo-overlay"/><div className="detail-demo-hero-copy"><span>PREMIUM MOBILE AUTO DETAILING</span><h1>Your Car Deserves More Than a Wash</h1><p>Professional mobile detailing, paint correction, and ceramic protection that makes your vehicle look its best.</p><div><a className="detail-demo-button" href="#booking">Book a Detail</a><a className="detail-demo-ghost" href="#packages">View Packages</a></div><small>Fictional demonstration business · No real services are offered</small></div></section>
 <section className="detail-demo-proof"><span>✦ Mobile convenience</span><span>✦ Professional-grade products</span><span>✦ Attention to detail</span><span>✦ Easy online booking</span><span>✦ Transparent packages</span></section>
 <section className="detail-demo-section" id="packages"><header><span>DETAILING PACKAGES</span><h2>Purpose-built care for every finish.</h2><p>From a refreshed interior to long-term ceramic protection, choose the level of care your vehicle needs.</p></header><div className="detail-demo-packages">{packages.map(([title,body],index)=><article key={title}><i>{String(index+1).padStart(2,"0")}</i><h3>{title}</h3><p>{body}</p><a href="#booking">Choose this package →</a></article>)}</div></section>
 <section className="detail-demo-results" id="results"><div><span>THE APEX DIFFERENCE</span><h2>See your vehicle in a new light.</h2><p>Professional detailing restores clarity, depth, and pride of ownership. This demonstration uses one original image with presentation treatments to illustrate how a real detailing website can tell a transformation story.</p><ul><li>Careful inspection before work begins</li><li>Package recommendations based on vehicle condition</li><li>Clear communication from booking through completion</li></ul></div><div className="detail-demo-comparison"><figure><Image src="/images/car-detailing-professional-polishing.png" alt="Vehicle before professional detailing presentation" fill sizes="(max-width: 900px) 100vw, 25vw"/><figcaption>BEFORE · DEMO</figcaption></figure><figure><Image src="/images/car-detailing-professional-polishing.png" alt="Glossy vehicle after professional detailing presentation" fill sizes="(max-width: 900px) 100vw, 25vw"/><figcaption>AFTER · DEMO</figcaption></figure></div></section>
 <section className="detail-demo-process" id="process"><header><span>HOW IT WORKS</span><h2>Premium results, without the runaround.</h2></header><ol>{[["1","Choose Your Package","Select the detail your vehicle needs."],["2","Pick a Time","Request a convenient appointment online."],["3","We Make It Shine","The detailing professional handles the rest."]].map(([n,title,body])=><li key={n}><i>{n}</i><h3>{title}</h3><p>{body}</p></li>)}</ol></section>
 <section className="detail-demo-reviews"><header><span>FICTIONAL DEMONSTRATION REVIEWS</span><h2>An experience worth talking about.</h2><p>These reviews are fictional and shown only to demonstrate website presentation.</p></header><div>{[["Taylor M. — fictional","The package was easy to understand and the online request took less than a minute."],["Jordan K. — fictional","Thoughtful communication and an incredibly polished presentation from start to finish."],["Alex R. — fictional","The mobile appointment made fitting a complete detail into my schedule simple."]].map(([name,quote])=><blockquote key={name}><b>★★★★★</b><p>“{quote}”</p><cite>{name}</cite></blockquote>)}</div></section>
 <section className="detail-demo-area"><span>MOBILE DETAILING</span><h2>Serving communities throughout the East Valley and surrounding areas.</h2><p>Generalized demonstration coverage · Real availability varies by business.</p></section>
 <section className="detail-demo-booking" id="booking"><div><span>BOOK YOUR DETAIL</span><h2>Choose the care your vehicle deserves.</h2><p>This polished demonstration form is read-only and never creates a real appointment.</p></div><form><label>Service package<select defaultValue=""><option disabled value="">Choose a package</option>{packages.map(([name])=><option key={name}>{name}</option>)}</select></label><label>Vehicle type<select defaultValue=""><option disabled value="">Choose a vehicle</option><option>Sedan</option><option>SUV / Crossover</option><option>Truck</option><option>Coupe</option></select></label><label>Preferred date<input type="date"/></label><label>Preferred time<input type="time" step="1800"/></label><label className="wide">Mobile service address<input placeholder="123 Example Street"/></label><button type="button" className="detail-demo-button">Preview Booking</button><small>Demonstration only — no information is sent.</small></form></section>
 <footer className="detail-demo-footer"><div><strong>APEX AUTO DETAIL</strong><p>Fictional premium detailing website demonstration.</p></div><div><b>Packages</b><a href="#packages">Interior detail</a><a href="#packages">Ceramic coating</a><a href="#packages">Paint correction</a></div><div><b>Contact</b><span>(555) 010-0327</span><span>hello@example.invalid</span><a href="#booking">Book a Detail</a></div><small>Powered by <Link href="/car-detailing-website">Servonas</Link></small></footer>
 </main>}
