import {notFound} from "next/navigation";
import type {Metadata} from "next";
import {getSupabaseAdmin} from "@/lib/supabaseAdmin";
import {loadPublishedBusinessWebsiteByDomain} from "@/lib/businessWebsite";
import {matchesPublicRentalSlug} from "@/lib/publicRental";
import {tenantMetadata,tenantCanonicalUrl} from "@/lib/publicTenantSeo";
import {RentalDetailLanding} from "@/components/RentalDetailLanding";
import {TenantLandingSchema} from "@/components/TenantPublicSchema";

const fields="id,name,category,category_id,description,daily_price_cents,image_url,length_ft,width_ft,height_ft,standard_rental_hours_override,inventory_item_specifications(label,value,icon,sort_order,is_public)";
async function load(domain:string,slug:string){const db=getSupabaseAdmin(),record=await loadPublishedBusinessWebsiteByDomain(domain);if(!db||record.kind!=="ok")return null;const [{data:items},{data:locations},{data:categoryPages}]=await Promise.all([db.from("inventory_items").select(fields).eq("business_id",record.settings.business_id).eq("active",true),db.from("business_location_pages").select("slug,city,state").eq("business_id",record.settings.business_id).eq("status","published").limit(6),db.from("category_website_pages").select("category_id,slug").eq("business_id",record.settings.business_id).eq("status","published")]);const item=(items??[]).find(row=>matchesPublicRentalSlug(row,slug));if(!item)return null;const related=(items??[]).filter(row=>row.category_id===item.category_id&&row.id!==item.id).slice(0,4),categoryUrl=(categoryPages??[]).find(row=>row.category_id===item.category_id)?.slug??null;return{record,item:{...item,standardRentalHours:Number(item.standard_rental_hours_override??24),related},locations:locations??[],categoryUrl};}
export async function generateMetadata({params}:{params:Promise<{domain:string;itemSlug:string}>}):Promise<Metadata>{const {domain,itemSlug}=await params,data=await load(domain,itemSlug);if(!data)return{};const local=data.locations[0]?.city?` in ${data.locations[0].city}`:"";return tenantMetadata({settings:data.record.settings,fallbackBase:`https://${domain}`,path:`/rentals/${itemSlug}`,title:`${data.item.name} Rental${local} | ${data.record.site.name}`,description:data.item.description||`Rent ${data.item.name}${local} from ${data.record.site.name}. Check availability online.`});}
export default async function RentalPage({params}:{params:Promise<{domain:string;itemSlug:string}>}){const {domain,itemSlug}=await params,data=await load(domain,itemSlug);if(!data)notFound();const url=tenantCanonicalUrl(data.record.settings,`/rentals/${itemSlug}`,`https://${domain}`);return <><TenantLandingSchema type="WebPage" name={data.item.name} url={url} homeUrl={tenantCanonicalUrl(data.record.settings,"/",`https://${domain}`)}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Product",name:data.item.name,description:data.item.description||undefined,image:data.item.image_url?[data.item.image_url]:undefined,offers:data.item.daily_price_cents>0?{"@type":"Offer",price:String(Number(data.item.daily_price_cents)/100),priceCurrency:"USD",url}:undefined}).replace(/</g,"\\u003c")}}/><RentalDetailLanding item={data.item} business={data.record.site} bookingUrl="/booking" homeUrl="/" categoryUrl={data.categoryUrl?`/${data.categoryUrl}`:null} locations={data.locations}/></>;}
