import Link from "next/link";
import {notFound} from "next/navigation";
import {addDays,dateInTimeZone,zonedDateTimeToUtc} from "@/lib/bookingTime";
import {hasIndustryCapability} from "@/lib/industryCapabilities";
import {eventQualifies,poolWeatherProvider} from "@/lib/weather/poolWeatherProvider";
import {requireWorkspace} from "@/lib/workspace";
import {WorkspaceNav} from "../../WorkspaceNav";
import {dismissPoolWeatherAlert,moveWeatherAffectedJobs} from "./actions";
const relation=<T,>(value:T|T[]|null)=>Array.isArray(value)?value[0]??null:value;
export default async function PoolWeather({params,searchParams}:{params:Promise<{businessSlug:string}>;searchParams:Promise<Record<string,string|undefined>>}){
 const {businessSlug}=await params,q=await searchParams,{supabase,business}=await requireWorkspace(businessSlug);if(!hasIndustryCapability(business.industry_profile,"poolWeatherScheduling"))notFound();
 const today=dateInTimeZone(new Date(),business.timezone),through=addDays(today,7),[{data:settings},{data:dismissed}]=await Promise.all([supabase.from("pool_service_settings").select("*").eq("business_id",business.id).maybeSingle(),supabase.from("pool_weather_alert_dismissals").select("event_key").eq("business_id",business.id)]);
 const rules=settings??{weather_alerts_enabled:false,wind_threshold_mph:30,rain_threshold_inches:1,heat_threshold_f:110,freeze_threshold_f:32};
 const dismissedKeys=new Set((dismissed??[]).map(item=>item.event_key));const events=rules.weather_alerts_enabled?(await poolWeatherProvider().forecast({startDate:today,endDate:through,areaLabel:business.city??business.state??"Service area"})).filter(event=>eventQualifies(event,rules)&&!dismissedKeys.has(event.id)):[];
 const start=zonedDateTimeToUtc(today,"00:00",business.timezone).toISOString(),end=zonedDateTimeToUtc(addDays(through,1),"00:00",business.timezone).toISOString();const {data:jobs}=await supabase.from("jobs").select("id,job_number,title,starts_at,ends_at,assigned_technician_id,customers!jobs_customer_tenant_fk(first_name,last_name,company_name),technician_profiles!jobs_technician_tenant_fk(preferred_name)").eq("business_id",business.id).eq("is_deleted",false).gte("starts_at",start).lt("starts_at",end).not("status","in",'("completed","canceled","declined")').order("starts_at");
 return <main className="epic3-shell"><WorkspaceNav slug={businessSlug} name={business.name}/><section className="epic3-content pool-weather-page"><header className="epic3-header"><div><small>Pool Service</small><h1>Weather Service Alerts</h1><p>Review weather-affected visits. Servonas never moves appointments without your approval.</p></div><Link className="sv-button sv-secondary" href={`/app/${businessSlug}/settings#pool-service-settings`}>Weather settings</Link></header>{q.error&&<div className="workspace-notice error">{q.error}</div>}{q.success&&<div className="workspace-notice success">{q.success}</div>}{!rules.weather_alerts_enabled&&<div className="workspace-notice">Weather Service Alerts are off. Enable them in Pool Service settings.</div>}
 {events.length?events.map(event=>{const eventDate=event.startsAt.slice(0,10),affected=(jobs??[]).filter(job=>job.starts_at&&dateInTimeZone(new Date(job.starts_at),business.timezone)===eventDate);return <section className="workspace-panel pool-weather-alert" key={event.id}><header><div><span>{event.type.replaceAll("_"," ")}</span><h2>{event.summary}</h2><p>{affected.length} pools are scheduled for service that day in {event.areaLabel}. Consider moving visits until after the event.</p></div><form action={dismissPoolWeatherAlert.bind(null,businessSlug)}><input type="hidden" name="eventKey" value={event.id}/><button className="text-button">Dismiss alert</button></form></header><form action={moveWeatherAffectedJobs.bind(null,businessSlug)}><div className="pool-weather-jobs">{affected.map(job=>{const customer=relation(job.customers),technician=relation(job.technician_profiles);return <label key={job.id}><input type="checkbox" name="jobId" value={job.id}/><span><strong>#{job.job_number} · {job.title}</strong><small>{customer?.company_name||`${customer?.first_name??""} ${customer?.last_name??""}`.trim()} · {technician?.preferred_name??"Unassigned"}</small></span></label>})}</div>{affected.length>0&&<footer><label>Move selected visits to<input required type="date" name="targetDate" min={eventDate} defaultValue={addDays(eventDate,1)}/></label><button className="sv-button">Move selected visits</button><small>Only this occurrence moves; the recurring series stays unchanged.</small></footer>}</form></section>}):rules.weather_alerts_enabled&&<div className="workspace-panel dashboard-empty"><strong>No qualifying weather alerts</strong><p>The configured provider has no events above your thresholds in the next seven days.</p></div>}
 </section></main>;
}
