"use client";
import {useEffect,useRef} from "react";
import {attributionFromSearch,type AcquisitionEvent,type AttributionValues} from "@/lib/acquisitionFunnel";
const storageKey="servonas.website-acquisition";
type Stored={sessionId:string;attribution:AttributionValues;landingUrl:string;referrer:string};
const state=():Stored=>{const raw=localStorage.getItem(storageKey);if(raw)try{const saved=JSON.parse(raw) as Stored;if(saved.sessionId)return saved;}catch{}const next={sessionId:crypto.randomUUID(),attribution:attributionFromSearch(new URLSearchParams(location.search)),landingUrl:location.href,referrer:document.referrer};localStorage.setItem(storageKey,JSON.stringify(next));return next;};
export function acquisitionSessionId(){return typeof window==="undefined"?"":state().sessionId;}
export function trackAcquisition(industry:string,event:AcquisitionEvent,metadata:Record<string,unknown>={}){if(typeof window==="undefined")return;const current=state();void fetch("/api/marketing/acquisition",{method:"POST",headers:{"content-type":"application/json"},keepalive:true,body:JSON.stringify({sessionId:current.sessionId,industry,event,path:`${location.pathname}${location.search}`,landingUrl:current.landingUrl,referrer:current.referrer,attribution:current.attribution,metadata})}).catch(()=>undefined);}
export function AcquisitionFunnelTracker({industry,event,metadata}:{industry:string;event:AcquisitionEvent;metadata?:Record<string,unknown>}){const sent=useRef(false);useEffect(()=>{if(sent.current)return;sent.current=true;trackAcquisition(industry,event,metadata);},[industry,event,metadata]);return null;}
export function AcquisitionBuilderLinkTracker({industry}:{industry:string}){useEffect(()=>{const handler=(event:MouseEvent)=>{const target=(event.target as Element|null)?.closest("a[data-acquisition-builder]");if(target)trackAcquisition(industry,"website_builder_started");};document.addEventListener("click",handler);return()=>document.removeEventListener("click",handler);},[industry]);return null;}
