"use client";
import {useEffect,useRef} from "react";
import {attributionFromSearch,type AcquisitionEvent,type AttributionValues} from "@/lib/acquisitionFunnel";
const storageKey=(industry:string)=>`servonas.website-acquisition.${industry}`;
const cookieKey=(industry:string)=>`servonas_acquisition_${industry}`;
type Stored={sessionId:string;attribution:AttributionValues;landingUrl:string;referrer:string};
const readCookie=(key:string)=>document.cookie.split("; ").find(item=>item.startsWith(`${key}=`))?.slice(key.length+1)??"";
const writeCookie=(key:string,value:string)=>{document.cookie=`${key}=${value}; Path=/; Max-Age=2592000; SameSite=Lax`;};
const state=(industry:string,initialSessionId?:string):Stored=>{const raw=localStorage.getItem(storageKey(industry));if(raw)try{const saved=JSON.parse(raw) as Stored;if(saved.sessionId)return saved;}catch{}const cookieSessionId=readCookie(cookieKey(industry)),sessionId=initialSessionId||cookieSessionId||crypto.randomUUID(),next={sessionId,attribution:attributionFromSearch(new URLSearchParams(location.search)),landingUrl:location.href,referrer:document.referrer};localStorage.setItem(storageKey(industry),JSON.stringify(next));writeCookie(cookieKey(industry),sessionId);return next;};
export function acquisitionSessionId(industry:string,initialSessionId?:string){return typeof window==="undefined"?"":state(industry,initialSessionId).sessionId;}
export function trackAcquisition(industry:string,event:AcquisitionEvent,metadata:Record<string,unknown>={},initialSessionId?:string){if(typeof window==="undefined")return;const current=state(industry,initialSessionId);void fetch("/api/marketing/acquisition",{method:"POST",headers:{"content-type":"application/json"},keepalive:true,body:JSON.stringify({sessionId:current.sessionId,industry,event,path:`${location.pathname}${location.search}`,landingUrl:current.landingUrl,referrer:current.referrer,attribution:current.attribution,metadata})}).catch(()=>undefined);}
export function AcquisitionFunnelTracker({industry,event,metadata,initialSessionId}:{industry:string;event:AcquisitionEvent;metadata?:Record<string,unknown>;initialSessionId?:string}){const sent=useRef(false);useEffect(()=>{if(sent.current)return;sent.current=true;trackAcquisition(industry,event,metadata,initialSessionId);},[industry,event,metadata,initialSessionId]);return null;}
export function AcquisitionBuilderLinkTracker({industry}:{industry:string}){useEffect(()=>{const handler=(event:MouseEvent)=>{const target=(event.target as Element|null)?.closest("a[data-acquisition-builder]");if(target)trackAcquisition(industry,"website_builder_started");};document.addEventListener("click",handler);return()=>document.removeEventListener("click",handler);},[industry]);return null;}
export function AcquisitionSignupLinkTracker({industry}:{industry:string}){useEffect(()=>{const handler=(event:MouseEvent)=>{const target=(event.target as Element|null)?.closest("a[data-acquisition-signup]");if(target)trackAcquisition(industry,"servonas_signup_started");};document.addEventListener("click",handler);return()=>document.removeEventListener("click",handler);},[industry]);return null;}
