import type {SupabaseClient} from '@supabase/supabase-js';
import {formatCents,marginPercent} from '@/lib/financial/priceBook';
import {finalizeRentalProfitability} from '@/app/app/[businessSlug]/jobs/profitabilityActions';
export async function BookingEquipmentProfitability({db,businessId,bookingId,slug,jobId,canEdit}:{db:SupabaseClient;businessId:string;bookingId:string;slug:string;jobId:string;canEdit:boolean}){
 const [{data:s,error},{data:booking},{data:allocations}]=await Promise.all([db.from('booking_profitability_snapshots').select('*').eq('business_id',businessId).eq('booking_id',bookingId).maybeSingle(),db.from('bookings').select('total_cents,tax_cents,refunded_cents').eq('business_id',businessId).eq('id',bookingId).maybeSingle(),db.from('booking_equipment_allocations').select('assumptions').eq('business_id',businessId).eq('booking_id',bookingId)]);
 if(error)return <section className="workspace-panel"><h2>Rental profitability</h2><p>Profitability data is unavailable.</p></section>;
 if(!s)return <section className="workspace-panel"><h2>Rental profitability</h2><p>Equipment allocations are captured when a paid rental is completed. Older completed bookings have no allocation snapshot.</p></section>;
 const originalRevenue=Number(s.revenue_cents),refund=Number(booking?.refunded_cents??0),total=Number(booking?.total_cents??0),netBeforeRefund=Math.max(total-Number(booking?.tax_cents??0),0),revenue=total>0?Math.max(netBeforeRefund-Math.round(refund*netBeforeRefund/total),0):originalRevenue,equipment=Number(s.equipment_allocation_cents),cost=Number(s.operating_cost_cents),profit=s.contribution_profit_cents==null?null:revenue-cost,estimatedCost=s.estimated_operating_cost_cents==null?null:Number(s.estimated_operating_cost_cents),estimatedProfit=estimatedCost==null?null:revenue-estimatedCost,excluded=(allocations??[]).filter(row=>row.assumptions?.enabled===false).length;
 const full=profit==null||!s.equipment_complete?null:profit-equipment;
 const margin=(costs:number)=>{const value=marginPercent(revenue,costs);return value==null?'—':`${value}%`;};
 return <section className="workspace-panel"><h2>Rental profitability</h2><p>Saved at completion. These internal allocations never create a cash expense or customer charge.</p><dl>
 <div><dt>Net booking revenue (excluding sales tax)</dt><dd>{formatCents(revenue)}</dd></div>
 <div><dt>{profit==null?'Estimated operating costs':'Operating Costs'}</dt><dd>{profit!=null?formatCents(cost):estimatedCost==null?'Incomplete — assumptions need review':formatCents(estimatedCost)}</dd></div>
 <div><dt>{profit==null?'Estimated Contribution Profit':'Contribution Profit'}</dt><dd>{profit!=null?`${formatCents(profit)} · ${margin(cost)} margin`:estimatedProfit==null?'Not available':`${formatCents(estimatedProfit)} · ${margin(estimatedCost!)} margin`}</dd></div>
 <div><dt>Allocated Equipment Cost</dt><dd>{s.equipment_complete?formatCents(equipment):'Incomplete assumptions at completion'}</dd></div>
 <div><dt>{profit==null?'Estimated Fully Loaded Profit':'Fully Loaded Profit'}</dt><dd>{profit==null?(estimatedProfit==null||!s.equipment_complete?'Not available':`${formatCents(estimatedProfit-equipment)} · ${margin(estimatedCost!+equipment)} margin`):(full==null?'Not available':`${formatCents(full)} · ${margin(cost+equipment)} margin`)}</dd></div></dl>
 {refund>0&&<p>Current profit reflects {formatCents(refund)} refunded. The original completion snapshot is preserved for audit.</p>}{excluded>0&&<p>Equipment allocation excludes {excluded} item{excluded===1?'':'s'} because tracking was off at completion.</p>}<small>Discounts are already included in the saved booking total. Equipment purchases are never a cash expense or customer charge.</small>
 {canEdit&&<form action={finalizeRentalProfitability.bind(null,slug,jobId,bookingId)} className="booking-settings-form"><p className="wide">{profit==null?'Confirm actual operating costs to replace estimates.':'Correct reviewed operating costs when needed; the prior values are retained in the audit history.'} Recorded invoice internal-cost estimate: {s.source_snapshot?.invoiceCostEstimateKnown?formatCents(Number(s.source_snapshot.invoiceCostEstimateCents)):'No cost estimate recorded'}. It is a reference only, not an added cost.</p>{[['labor','Labor'],['delivery','Delivery / vehicle costs'],['processingFees','Payment processing fees'],['other','Other variable costs']].map(([key,label])=><label key={key}>{label}<input name={key} required type="number" min="0" step="0.01" defaultValue={profit!=null?((Number(s.operating_costs?.[key]??0))/100).toFixed(2):''} placeholder="0.00"/></label>)}<label className="wide">Correction note <small>Optional</small><input name="reason" maxLength={1000} placeholder="Why these reviewed costs changed"/></label><label className="wide toggle-row"><input required name="confirmed" type="checkbox"/>I reviewed all operating costs. Equipment purchases are excluded.</label><button className="sv-button">{profit==null?'Confirm reviewed costs':'Save corrected costs'}</button></form>}
 </section>;
}
