"use client";

import {useMemo,useState} from "react";
import {applyBusinessHoursPreset,defaultBusinessHoursValues,detectBusinessHoursPreset,type BusinessHoursPreset,type BusinessHoursValue} from "@/lib/businessHoursEditor";

const dayNames=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
const displayOrder=[1,2,3,4,5,6,0];
const timeLabel=(value:string)=>{const [hour,minute]=value.split(":").map(Number),period=hour>=12?"PM":"AM",display=hour%12||12;return `${display}:${String(minute).padStart(2,"0")} ${period}`;};

export function BusinessHoursEditor({initialHours,fieldStyle="website",disabled=false,dayErrors}:{initialHours?:BusinessHoursValue[];fieldStyle?:"website"|"onboarding";disabled?:boolean;dayErrors?:Record<number,string>}){
 const normalized=initialHours?.length===7?initialHours:defaultBusinessHoursValues();
 const [rows,setRows]=useState(normalized),preset=useMemo(()=>detectBusinessHoursPreset(rows),[rows]);
 const change=(weekday:number,values:Partial<BusinessHoursValue>)=>setRows(current=>current.map(row=>row.weekday===weekday?{...row,...values}:row));
 const applyPreset=(next:BusinessHoursPreset)=>{if(next!=="custom")setRows(current=>applyBusinessHoursPreset(current,next));};
 const copy=(sourceDay:number,target:"weekdays"|"all"|number)=>{const source=rows.find(row=>row.weekday===sourceDay);if(!source)return;const targets=target==="weekdays"?[1,2,3,4,5]:target==="all"?[0,1,2,3,4,5,6]:[target];setRows(current=>current.map(row=>targets.includes(row.weekday)&&row.weekday!==sourceDay?{...row,open:source.open,start:source.start,end:source.end}:row));};
 const names=(weekday:number)=>fieldStyle==="website"?{open:`websiteDay_${weekday}`,start:`websiteStart_${weekday}`,end:`websiteEnd_${weekday}`}:{open:`open_${weekday}`,start:`start_${weekday}`,end:`end_${weekday}`};
 return <div className="business-hours-editor"><div className="business-hours-heading"><div><strong>Business hours</strong><span>Choose when customers can request service.</span></div><div className="business-hours-preset" role="group" aria-label="Quick setup"><span>Quick setup</span>{([{key:"weekdays",label:"Mon–Fri"},{key:"saturday",label:"Mon–Sat"},{key:"daily",label:"Every day"},{key:"custom",label:"Custom"}] as const).map(option=><button type="button" disabled={disabled||option.key==="custom"} aria-pressed={preset===option.key} className={preset===option.key?"active":""} onClick={()=>applyPreset(option.key)} key={option.key}>{option.label}</button>)}</div></div><div className="business-hours-list">{displayOrder.map(weekday=>{const row=rows.find(item=>item.weekday===weekday)!,fields=names(weekday);return <div className={`business-hours-row ${row.open?"open":"closed"}`} key={weekday}><strong className="business-hours-day">{dayNames[weekday]}</strong><label className="business-hours-toggle"><input type="checkbox" name={fields.open} checked={row.open} disabled={disabled} onChange={event=>change(weekday,{open:event.target.checked})}/><span aria-hidden="true"/><b>{row.open?"Open":"Closed"}</b></label>{row.open?<div className="business-hours-times"><label><span>Opening time</span><input aria-label={`${dayNames[weekday]} opening time`} type="time" name={fields.start} value={row.start} required disabled={disabled} onChange={event=>change(weekday,{start:event.target.value})}/></label><i>—</i><label><span>Closing time</span><input aria-label={`${dayNames[weekday]} closing time`} type="time" name={fields.end} value={row.end} required disabled={disabled} onChange={event=>change(weekday,{end:event.target.value})}/></label></div>:<span className="business-hours-closed-note">Not available for requests</span>}<details className="business-hours-copy"><summary aria-label={`Copy ${dayNames[weekday]} hours`}>Copy</summary><div><button type="button" onClick={()=>copy(weekday,"weekdays")}>All weekdays</button><button type="button" onClick={()=>copy(weekday,"all")}>All days</button>{displayOrder.filter(day=>day!==weekday).map(day=><button type="button" onClick={()=>copy(weekday,day)} key={day}>{dayNames[day].slice(0,3)}</button>)}</div></details>{dayErrors?.[weekday]&&<small className="field-error">{dayErrors[weekday]}</small>}<output className="business-hours-summary" aria-live="polite">{row.open?`${timeLabel(row.start)} – ${timeLabel(row.end)}`:"Closed"}</output></div>})}</div></div>;
}
