import Link from "next/link";
import {WebsiteRequestForm,type WebsiteRequestState} from "./WebsiteRequestForm";
import {EmbeddedBookingFrame} from "./EmbeddedBookingFrame";

export type BusinessSiteService={id:string;name:string;description:string|null;price_amount:number|null;price_label:string|null};
export type BusinessSiteData={
 name:string;phone:string|null;email:string|null;logoUrl:string|null;industryProfile:string|null;template:"modern"|"traditional"|"bold";primaryColor:string;secondaryColor:string;
 heroHeading:string;heroSubheading:string;aboutText:string;googleReviewUrl:string|null;googleReviews:{author:string;rating:number;text:string}[];photoUrls:string[];requestEnabled:boolean;bookingEnabled:boolean;bookingUrl:string|null;
 services:BusinessSiteService[];hours:{weekday:number;start:string;end:string}[];serviceAreas:string[];
};
const weekdays=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
const time=(value:string)=>{const [hour,minute]=value.slice(0,5).split(":").map(Number);return `${hour%12||12}:${String(minute).padStart(2,"0")} ${hour>=12?"PM":"AM"}`;};

export function BusinessWebsite({site,requestAction,preview=false}:{site:BusinessSiteData;requestAction?:(state:WebsiteRequestState,data:FormData)=>Promise<WebsiteRequestState>;preview?:boolean}){
 const isPartyRental=site.industryProfile==="party_rental";
 const reviewRating=site.googleReviews.length?site.googleReviews.reduce((sum,review)=>sum+review.rating,0)/site.googleReviews.length:null;
 const reviewRibbon=reviewRating?<>{site.googleReviewUrl?<a href={site.googleReviewUrl} target="_blank" rel="noreferrer" aria-label={`${reviewRating.toFixed(1)} out of 5 stars on Google`}>★ {reviewRating.toFixed(1)} Google rating</a>:<span aria-label={`${reviewRating.toFixed(1)} out of 5 stars`}>★ {reviewRating.toFixed(1)} customer rating</span>}</>:<span>✓ Responsive service</span>;
 const ctaHref=site.bookingEnabled&&site.bookingUrl?"#book-online":isPartyRental?"#contact":"#request-service",ctaLabel=site.bookingEnabled&&site.bookingUrl||isPartyRental?"Book Online":"Request Service";
 return <main className={`business-site template-${site.template}`} style={{"--site-primary":site.primaryColor,"--site-secondary":site.secondaryColor} as React.CSSProperties}>
  {preview&&<div className="business-site-preview-bar"><span>Preview mode — this is not the public website.</span><small>Close this tab to return to Servonas.</small></div>}
  <header className="business-site-header"><Link href="#top" className="business-site-brand">{site.logoUrl?<img src={site.logoUrl} alt={`${site.name} logo`}/>:<i>{site.name.slice(0,1)}</i>}<strong>{site.name}</strong></Link><nav>{!isPartyRental&&<a href="#services">Services</a>}<a href="#about">About</a><a href="#areas">Service Areas</a><a href="#contact">Contact</a></nav><div>{site.phone&&<a className="site-phone" href={`tel:${site.phone}`}>{site.phone}</a>}<a className="site-primary-button" href={ctaHref}>{ctaLabel}</a></div></header>
  <section className="business-site-hero" id="top"><div><span>Professional service. Local care.</span><h1>{site.heroHeading}</h1><p>{site.heroSubheading}</p><div><a className="site-primary-button" href={ctaHref}>{ctaLabel}</a>{site.phone&&<a className="site-secondary-button" href={`tel:${site.phone}`}>Call {site.phone}</a>}</div></div>{site.photoUrls[0]?<img src={site.photoUrls[0]} alt={`${site.name} service team`}/>:<aside><b>{site.name}</b><span>Trusted local service professionals</span></aside>}</section>
  <section className="business-site-trust">{reviewRibbon}<span>✓ Professional workmanship</span><span>✓ Local customer care</span></section>
  {!isPartyRental&&<section className="business-site-section" id="services"><header><span>What we do</span><h2>Services built around your needs</h2><p>Clear solutions from a local team you can count on.</p></header><div className="business-site-services">{site.services.length?site.services.map((service,index)=><article key={service.id}><i>{String(index+1).padStart(2,"0")}</i><h3>{service.name}</h3><p>{service.description||`Professional ${service.name.toLowerCase()} from the ${site.name} team.`}</p>{Number(service.price_amount)>0&&<small>{service.price_label==="starting_at"?"Starting at ":""}${Number(service.price_amount).toFixed(2)}</small>}<a href="#request-service">Request this service →</a></article>):["Repairs","Maintenance","New installations"].map((name,index)=><article key={name}><i>0{index+1}</i><h3>{name}</h3><p>Contact {site.name} to learn more about this service.</p></article>)}</div></section>}
  <section className="business-site-section business-site-areas" id="areas"><header><span>Where we work</span><h2>Proudly serving our local community</h2></header><div>{site.serviceAreas.length?site.serviceAreas.map(area=><span key={area}>{area}</span>):<span>Contact us to confirm service in your area</span>}</div></section>
  {site.photoUrls.length>2&&<section className="business-site-section business-site-gallery"><header><span>Our work</span><h2>Recent service highlights</h2></header><div>{site.photoUrls.slice(2).map((url,index)=><img src={url} alt={`${site.name} project ${index+1}`} key={url}/>)}</div></section>}
  {site.bookingEnabled&&site.bookingUrl&&<section className="business-site-booking" id="book-online"><header><span>Book online</span><h2>Reserve your date</h2></header><EmbeddedBookingFrame src={`${site.bookingUrl}${site.bookingUrl.includes("?")?"&":"?"}embed=1`} title={`Book online with ${site.name}`}/></section>}
  <section className="business-site-about" id="about"><div>{site.photoUrls[1]?<img src={site.photoUrls[1]} alt={`${site.name} at work`}/>:<aside>{site.name.slice(0,1)}</aside>}</div><div><span>About us</span><h2>Service you can feel confident calling</h2><p>{site.aboutText}</p><a className="site-primary-button" href={ctaHref}>{ctaLabel}</a></div></section>
  <section className={`business-site-reviews${site.googleReviews.length?" has-reviews":""}`}><div className="business-site-reviews-intro"><span>Customer reviews</span><h2>{site.googleReviews.length?"What our customers say":isPartyRental?"Ready to reserve your event rentals?":"Ready to work with a team that puts service first?"}</h2><p>{site.googleReviews.length?`Feedback shared by ${site.name} customers.`:isPartyRental?"Choose your date and book available rentals online.":`Contact ${site.name} today and tell us how we can help.`}</p>{site.googleReviewUrl&&<a className="site-secondary-button" href={site.googleReviewUrl} target="_blank" rel="noreferrer">See all reviews on Google</a>}</div>{site.googleReviews.length>0&&<div className="business-site-review-grid">{site.googleReviews.map((review,index)=><blockquote key={`${review.author}-${index}`}><div aria-label={`${review.rating} out of 5 stars`}>{"★".repeat(review.rating)}<span>{"★".repeat(5-review.rating)}</span></div><p>“{review.text}”</p><cite>{review.author}</cite></blockquote>)}</div>}{!site.googleReviews.length&&!site.googleReviewUrl&&<a className="site-secondary-button" href={ctaHref}>{ctaLabel}</a>}</section>
  {!isPartyRental&&<section className="business-site-contact" id="contact"><div><span>Get started</span><h2>Request service</h2><p>Tell us what you need. Your request goes directly into {site.name}&apos;s service system for follow-up.</p><dl>{site.phone&&<div><dt>Phone</dt><dd><a href={`tel:${site.phone}`}>{site.phone}</a></dd></div>}{site.email&&<div><dt>Email</dt><dd><a href={`mailto:${site.email}`}>{site.email}</a></dd></div>}<div><dt>Hours</dt><dd>{site.hours.length?site.hours.map(hour=><span key={hour.weekday}>{weekdays[hour.weekday]}: {time(hour.start)}–{time(hour.end)}</span>):<span>Call for availability</span>}</dd></div></dl></div><div id="request-service">{site.requestEnabled&&requestAction?<WebsiteRequestForm action={requestAction} services={site.services} businessName={site.name}/>:<div className="business-site-request-disabled"><strong>Contact {site.name}</strong><p>Online requests are not currently enabled. Please call or email the business directly.</p></div>}</div></section>}
  <footer className="business-site-footer" id={isPartyRental?"contact":undefined}><div><strong>{site.name}</strong><p>{site.aboutText.slice(0,180)}</p></div><div><b>Explore</b>{!isPartyRental&&<a href="#services">Services</a>}<a href="#about">About</a><a href="#areas">Service Areas</a>{isPartyRental&&site.bookingEnabled&&<a href="#book-online">Book Online</a>}</div><div><b>Contact</b>{site.phone&&<a href={`tel:${site.phone}`}>{site.phone}</a>}{site.email&&<a href={`mailto:${site.email}`}>{site.email}</a>}</div><small>Website powered by Servonas</small></footer>
 </main>;
}
