"use client";
import { useState } from "react";

type Template = { template_key: "confirmation"|"reminder"|"review"; display_name: string; body: string; enabled: boolean };
type Log = { id: string; template_key: string; to_phone: string; body: string; status: string; error_message: string|null; created_at: string; sent_at: string|null; bookings: { booking_number: number } | { booking_number: number }[] | null };
type BookingOption = { id: string; booking_number: number; customer_name: string };
const vars = ["{customerName}","{bookingNumber}","{eventDate}","{items}","{depositPaid}","{balanceDue}","{deliveryAddress}","{receiptLink}","{googleReviewLink}"];
export default function CommunicationsManager({ initialTemplates, initialLogs, bookings }: { initialTemplates: Template[]; initialLogs: Log[]; bookings: BookingOption[] }) {
  const [templates, setTemplates] = useState(initialTemplates); const [key, setKey] = useState(""); const [notice, setNotice] = useState(""); const [sending, setSending] = useState(false);
  async function save(template: Template) { setNotice(""); const r = await fetch("/api/admin/communications", { method:"PUT", headers:{"content-type":"application/json","x-admin-key":key}, body:JSON.stringify({templateKey:template.template_key,body:template.body,enabled:template.enabled})}); const j=await r.json(); setNotice(r.ok?`${template.display_name} saved.`:(j.error||"Could not save.")); }
  async function sendTest(formData: FormData) { setSending(true); setNotice(""); const r=await fetch("/api/admin/communications",{method:"POST",headers:{"content-type":"application/json","x-admin-key":key},body:JSON.stringify({bookingId:formData.get("bookingId"),templateKey:formData.get("templateKey")})}); const j=await r.json(); setNotice(r.ok?(j.stubbed?"Preview generated. No text message was sent.":"Text message sent."):(j.error||"Could not send.")); setSending(false); }
  return <div className="communications-manager">
    <label>Admin access key<input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="Required to save or send"/></label>
    <p className="muted">Available variables: {vars.join(" · ")}</p>
    <div className="template-grid">{templates.map((t,index)=><article className="template-card" key={t.template_key}><div className="template-heading"><h3>{t.display_name}</h3><label className="inline-toggle"><input type="checkbox" checked={t.enabled} onChange={e=>setTemplates(x=>x.map((a,i)=>i===index?{...a,enabled:e.target.checked}:a))}/> Enabled</label></div><textarea rows={7} value={t.body} onChange={e=>setTemplates(x=>x.map((a,i)=>i===index?{...a,body:e.target.value}:a))}/><button className="button small" type="button" onClick={()=>save(t)}>Save template</button></article>)}</div>
    <form action={sendTest} className="manual-sms-form"><h3>Generate a message preview</h3><p className="muted">SMS is currently in stub mode. This records the rendered message without sending or charging you.</p><select name="bookingId" required defaultValue=""><option value="" disabled>Select booking</option>{bookings.map(b=><option key={b.id} value={b.id}>#{b.booking_number} — {b.customer_name}</option>)}</select><select name="templateKey" defaultValue="confirmation"><option value="confirmation">Confirmation</option><option value="reminder">Reminder</option><option value="review">Review request</option></select><button className="button" disabled={sending}>{sending?"Generating…":"Generate preview"}</button></form>
    {notice&&<p className="notice">{notice}</p>}
    <div className="table-wrap"><table><thead><tr><th>Booking</th><th>Type</th><th>Phone</th><th>Status</th><th>Message</th><th>Time</th></tr></thead><tbody>{initialLogs.length===0?<tr><td colSpan={6}>No text messages yet.</td></tr>:initialLogs.map(log=>{const b=Array.isArray(log.bookings)?log.bookings[0]:log.bookings; return <tr key={log.id}><td>{b?`#${b.booking_number}`:"—"}</td><td>{log.template_key}</td><td>{log.to_phone}</td><td>{log.status}{log.error_message?<><br/><small>{log.error_message}</small></>:null}</td><td className="sms-body-cell">{log.body}</td><td>{new Date(log.sent_at||log.created_at).toLocaleString()}</td></tr>})}</tbody></table></div>
  </div>;
}
