"use client";
import {useState} from "react";

type TimeTier={upToMinutes:number;feeCents:number};
type Tier={upToMiles:number;feeCents:number};
type Settings={time_tiers?:TimeTier[]|null;maximum_drive_minutes?:number|null;enabled:boolean;origin_address_line1?:string|null;origin_address_line2?:string|null;origin_city?:string|null;origin_state?:string|null;origin_postal_code?:string|null;pricing_method?:string|null;free_radius_miles?:number|null;per_mile_rate_cents?:number|null;minimum_fee_cents?:number|null;maximum_distance_miles?:number|null;outside_area_action?:string|null;long_distance_fee_cents?:number|null;delivery_taxable?:boolean|null;tiers?:Tier[]|null};
const dollars=(cents:number)=>Number(cents||0)/100;

export function DeliverySettingsEditor({settings,disabled,action}:{settings:Settings;disabled:boolean;action:(formData:FormData)=>void}){
 const [method,setMethod]=useState(settings.pricing_method==="time_tiers"?"time_tiers":settings.pricing_method==="per_mile"?"per_mile":"distance_tiers");
 const [tiers,setTiers]=useState<Tier[]>(settings.tiers??[{upToMiles:30,feeCents:2500},{upToMiles:40,feeCents:5000},{upToMiles:50,feeCents:7500},{upToMiles:60,feeCents:10000}]);
 const [timeTiers,setTimeTiers]=useState<TimeTier[]>(settings.time_tiers??[{upToMinutes:20,feeCents:0},{upToMinutes:30,feeCents:2500}]);
 const updateTime=(index:number,key:keyof TimeTier,value:number)=>setTimeTiers(current=>current.map((tier,i)=>i===index?{...tier,[key]:value}:tier));
 const update=(index:number,key:keyof Tier,value:number)=>setTiers(current=>current.map((tier,i)=>i===index?{...tier,[key]:value}:tier));
 const move=(index:number,direction:-1|1)=>setTiers(current=>{const target=index+direction;if(target<0||target>=current.length)return current;const copy=[...current];[copy[index],copy[target]]=[copy[target],copy[index]];return copy;});
 return <form action={action} className="booking-settings-form delivery-settings-form">
  <input type="hidden" name="timeTiers" value={JSON.stringify(timeTiers)}/>
  <input type="hidden" name="tiers" value={JSON.stringify(tiers)}/>
  <label className="wide toggle-row"><input type="checkbox" name="enabled" defaultChecked={settings.enabled} disabled={disabled}/><span><b>Automatically calculate delivery or trip fees</b><small>Customers see their delivery price before they pay.</small></span></label>
  <fieldset className="wide delivery-origin"><legend>Business / starting address</legend><p>One-way driving distance and time start here. Changing it affects future bookings only.</p><label>Street address<input name="originAddressLine1" required defaultValue={settings.origin_address_line1??""} disabled={disabled}/></label><label>Suite or unit<input name="originAddressLine2" defaultValue={settings.origin_address_line2??""} disabled={disabled}/></label><label>City<input name="originCity" required defaultValue={settings.origin_city??""} disabled={disabled}/></label><label>State<input name="originState" required maxLength={2} defaultValue={settings.origin_state??""} disabled={disabled}/></label><label>ZIP code<input name="originPostalCode" required defaultValue={settings.origin_postal_code??""} disabled={disabled}/></label></fieldset>
  <label style={method==="time_tiers"?{display:"none"}:undefined}>Free delivery radius (miles)<input name="freeRadiusMiles" type="number" min="0" step="0.1" defaultValue={settings.free_radius_miles??20} disabled={disabled}/><small>Customers this close to your business won&apos;t pay a delivery fee.</small></label>
  <label>Pricing method<select name="pricingMethod" value={method} onChange={event=>setMethod(event.target.value)} disabled={disabled}><option value="time_tiers">Drive-time tiers</option><option value="distance_tiers">Distance tiers</option><option value="per_mile">Price per mile</option></select></label>
  <fieldset style={method!=="distance_tiers"?{display:"none"}:undefined} className="wide delivery-tiers"><legend>Distance prices</legend>{tiers.map((tier,index)=><div key={index}><span>Up to</span><input aria-label={`Tier ${index+1} miles`} type="number" min="0" step="0.1" value={tier.upToMiles} onChange={event=>update(index,"upToMiles",Number(event.target.value))} disabled={disabled}/><span>miles</span><label><span>Fee</span><input aria-label={`Tier ${index+1} fee`} type="number" min="0" step="0.01" value={dollars(tier.feeCents)} onChange={event=>update(index,"feeCents",Math.round(Number(event.target.value)*100))} disabled={disabled}/></label><button type="button" className="text-button" onClick={()=>move(index,-1)} disabled={disabled||index===0}>Up</button><button type="button" className="text-button" onClick={()=>move(index,1)} disabled={disabled||index===tiers.length-1}>Down</button><button type="button" className="text-button danger" onClick={()=>setTiers(current=>current.filter((_,i)=>i!==index))} disabled={disabled}>Remove</button></div>)}<button type="button" className="sv-button sv-secondary" onClick={()=>setTiers(current=>[...current,{upToMiles:(current.at(-1)?.upToMiles??0)+10,feeCents:0}])} disabled={disabled}>Add a tier</button></fieldset><div hidden={method!=="per_mile"}><label>Price per mile after free radius<input name="perMileRate" type="number" min="0" step="0.01" defaultValue={dollars(settings.per_mile_rate_cents??0)} disabled={disabled}/></label><label>Minimum delivery charge <small>Optional</small><input name="minimumFee" type="number" min="0" step="0.01" defaultValue={dollars(settings.minimum_fee_cents??0)} disabled={disabled}/></label></div>
  <fieldset style={method!=="time_tiers"?{display:"none"}:undefined} className="wide delivery-tiers"><legend>Drive-time prices</legend><p>One-way estimated driving time without live traffic. Each limit includes that minute; the first matching tier applies. Time and distance policies are saved separately.</p>{timeTiers.map((tier,index)=><div key={index}><span>Up to</span><input aria-label={`Time tier ${index+1} minutes`} type="number" min="0.1" step="0.1" value={tier.upToMinutes} onChange={event=>updateTime(index,"upToMinutes",Number(event.target.value))} disabled={disabled}/><span>minutes</span><label><span>Fee</span><input aria-label={`Time tier ${index+1} fee`} type="number" min="0" step="0.01" value={dollars(tier.feeCents)} onChange={event=>updateTime(index,"feeCents",Math.round(Number(event.target.value)*100))} disabled={disabled}/></label><button type="button" className="text-button danger" onClick={()=>setTimeTiers(current=>current.filter((_,i)=>i!==index))} disabled={disabled}>Remove</button></div>)}<button type="button" className="sv-button sv-secondary" onClick={()=>setTimeTiers(current=>[...current,{upToMinutes:(current.at(-1)?.upToMinutes??0)+10,feeCents:0}])} disabled={disabled}>Add time tier</button><label>Maximum drive time (minutes)<input name="maximumDriveMinutes" type="number" min="0.1" step="0.1" defaultValue={settings.maximum_drive_minutes??""} disabled={disabled}/><small>Optional. Beyond this limit, the outside-area policy applies. Addresses beyond your last tier otherwise require a quote.</small></label></fieldset>
  <label style={method==="time_tiers"?{display:"none"}:undefined}>Maximum service distance<input name="maximumDistanceMiles" type="number" min="0" step="0.1" defaultValue={settings.maximum_distance_miles===undefined?60:settings.maximum_distance_miles??""} disabled={disabled}/><small>Customers farther away won&apos;t be able to book normally.</small></label>
  <label>Outside the service area<select name="outsideAreaAction" defaultValue={settings.outside_area_action??"request_quote"} disabled={disabled}><option value="request_quote">Request a quote</option><option value="block">Do not allow online booking</option><option value="long_distance_fee">Allow with a long-distance fee</option></select></label>
  <label>Long-distance fee <small>Used only when selected above</small><input name="longDistanceFee" type="number" min="0" step="0.01" defaultValue={dollars(settings.long_distance_fee_cents??0)} disabled={disabled}/></label>
  <label className="toggle-row"><input name="deliveryTaxable" type="checkbox" defaultChecked={Boolean(settings.delivery_taxable)} disabled={disabled}/><span><b>Delivery fee is taxable</b><small>Delivery remains separate from item discounts.</small></span></label>
  {!disabled&&<button className="button">Save delivery policy</button>}
 </form>;
}
