"use client";
import {useState} from "react";
import {discountTierLabel,validateDiscountTiers,type DiscountTier} from "@/lib/discountTiers";
export function DiscountTiersEditor({initialTiers=[]}:{initialTiers?:DiscountTier[]}){
 const [tiers,setTiers]=useState(initialTiers);
 const update=(index:number,patch:Partial<DiscountTier>)=>setTiers(current=>current.map((tier,i)=>i===index?{...tier,...patch}:tier));
 const move=(index:number,direction:number)=>setTiers(current=>{const next=[...current];[next[index],next[index+direction]]=[next[index+direction],next[index]];return next;});
 const error=validateDiscountTiers(tiers);
 return <fieldset className="wide discount-item-picker"><legend>Discount tiers</legend><p>Add tiers to replace the single discount value and minimum subtotal. Only the highest qualifying threshold applies, regardless of display order. Qualification excludes taxes, delivery, and operator fees.</p><input type="hidden" name="discountTiers" value={JSON.stringify(tiers)}/>{tiers.map((tier,index)=><fieldset key={tier.id} style={{marginBlock:12,padding:12,border:"1px solid #dce2ea",borderRadius:8}}><legend>Tier {index+1}</legend><div className="discount-form-grid"><label>Minimum rental subtotal ($)<input required type="number" min="0" step="0.01" value={tier.minimum_subtotal_cents/100} onChange={event=>update(index,{minimum_subtotal_cents:Math.round(Number(event.target.value)*100)})}/></label><label>Discount type<select value={tier.discount_type} onChange={event=>update(index,{discount_type:event.target.value as DiscountTier["discount_type"]})}><option value="fixed">Fixed amount</option><option value="percentage">Percent</option></select></label><label>{tier.discount_type==="fixed"?"Amount ($)":"Percent (%)"}<input required type="number" min="0.01" max={tier.discount_type==="percentage"?100:21474836.47} step="0.01" value={tier.discount_value/100} onChange={event=>update(index,{discount_value:Math.round(Number(event.target.value)*100)})}/></label></div><p><strong>{discountTierLabel(tier)}</strong></p><button type="button" className="text-button" disabled={index===0} onClick={()=>move(index,-1)} aria-label={`Move tier ${index+1} up`}>Move up</button>{" "}<button type="button" className="text-button" disabled={index===tiers.length-1} onClick={()=>move(index,1)} aria-label={`Move tier ${index+1} down`}>Move down</button>{" "}<button type="button" className="text-button" onClick={()=>setTiers(current=>current.filter((_,i)=>i!==index))}>Remove tier {index+1}</button></fieldset>)}{error&&<p role="alert">{error}</p>}<button type="button" className="sv-button sv-secondary" disabled={tiers.length>=50} onClick={()=>setTiers(current=>[...current,{id:crypto.randomUUID(),minimum_subtotal_cents:current.length?Math.max(...current.map(tier=>tier.minimum_subtotal_cents))+12500:17500,discount_type:"fixed",discount_value:current.length?Math.max(...current.filter(tier=>tier.discount_type==="fixed").map(tier=>tier.discount_value),5000)+2500:5000}])}>Add tier</button></fieldset>;
}
