type Definition={id:string;qualification_type:string;name:string};
type Assignment={id:string;status:string;proficiency_level:string|null;credential_number:string|null;issuing_authority:string|null;issued_on:string|null;expires_on:string|null;notes:string|null;workforce_qualifications:Definition|Definition[]|null};
const relation=<T,>(value:T|T[]|null)=>Array.isArray(value)?value[0]??null:value;
export function EmployeeQualifications({assignments,definitions,canEdit,addAction,endAction}:{assignments:Assignment[];definitions:Definition[];canEdit:boolean;addAction:(formData:FormData)=>void|Promise<void>;endAction:(formData:FormData)=>void|Promise<void>}){
 const today=new Date().toISOString().slice(0,10);
 return <section className="workspace-panel employee-qualifications"><div className="panel-title"><div><span className="sv-kicker">Workforce readiness</span><h2>Skills and credentials</h2><p>Business-defined qualifications support dispatch matching without industry-specific assumptions.</p></div></div>
  <div className="qualification-list">{assignments.length?assignments.map(item=>{const definition=relation(item.workforce_qualifications);const expired=Boolean(item.expires_on&&item.expires_on<today);return <article key={item.id}><div><span className={`qualification-type ${definition?.qualification_type}`}>{definition?.qualification_type??"qualification"}</span><strong>{definition?.name??"Unknown qualification"}</strong><small>{item.proficiency_level||item.issuing_authority||item.credential_number||"No additional details"}{item.expires_on?` · ${expired?"Expired":"Expires"} ${item.expires_on}`:""}</small></div>{canEdit&&item.status==="active"&&<form action={endAction}><input type="hidden" name="assignmentId" value={item.id}/><button className="text-button danger">Remove</button></form>}</article>}):<div className="dashboard-empty"><strong>No skills or credentials recorded.</strong><p>Add only the qualifications this business actually uses.</p></div>}</div>
  {canEdit&&<form action={addAction} className="qualification-form"><label>Type<select name="qualificationType"><option value="skill">Skill</option><option value="certification">Certification</option><option value="license">License</option></select></label><label>Name<input name="name" required maxLength={150} list="qualification-options"/></label><datalist id="qualification-options">{definitions.map(item=><option key={item.id} value={item.name}/>)}</datalist><label>Level<input name="proficiencyLevel" maxLength={100} placeholder="Optional"/></label><label>Credential number<input name="credentialNumber" maxLength={150}/></label><label>Issuing authority<input name="issuingAuthority" maxLength={150}/></label><label>Issued<input name="issuedOn" type="date"/></label><label>Expires<input name="expiresOn" type="date"/></label><label className="qualification-notes">Notes<input name="notes" maxLength={2000}/></label><button className="sv-button">Add qualification</button></form>}
 </section>;
}
