type Territory={id:string;name:string;territory_type:string;postal_codes:string[];neighborhoods:string[];color?:string};
type Assignment={id:string;assignment_type:string;effective_from:string;effective_through:string|null;notes:string|null;workforce_territories:Territory|Territory[]|null};
const relation=<T,>(value:T|T[]|null)=>Array.isArray(value)?value[0]??null:value;
export function EmployeeTerritories({territories,assignments,canEdit,createAction,assignAction,endAction}:{territories:Territory[];assignments:Assignment[];canEdit:boolean;createAction:(data:FormData)=>void|Promise<void>;assignAction:(data:FormData)=>void|Promise<void>;endAction:(data:FormData)=>void|Promise<void>}){
 return <section className="workspace-panel employee-territories"><div className="panel-title"><div><span className="sv-kicker">Geographic coverage</span><h2>Territories</h2><p>Define primary, secondary, and temporary coverage for dispatch and future routing intelligence.</p></div></div>
  <div className="territory-assignment-list">{assignments.length?assignments.map(item=>{const territory=relation(item.workforce_territories);return <article key={item.id}><div><span className={`territory-kind ${item.assignment_type}`}>{item.assignment_type}</span><strong>{territory?.name??"Unknown territory"}</strong><small>{item.effective_from}{item.effective_through?` – ${item.effective_through}`:" onward"}{item.notes?` · ${item.notes}`:""}</small></div>{canEdit&&<form action={endAction}><input type="hidden" name="assignmentId" value={item.id}/><button className="text-button danger">End</button></form>}</article>}):<div className="dashboard-empty"><strong>No territory coverage assigned.</strong><p>This employee can still be scheduled manually.</p></div>}</div>
  {canEdit&&<div className="territory-management"><form action={assignAction} className="territory-assign-form"><label>Territory<select name="territoryId" required><option value="">Choose territory</option>{territories.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Coverage<select name="assignmentType" defaultValue="secondary"><option value="primary">Primary</option><option value="backup">Backup</option><option value="secondary">Additional</option><option value="temporary">Temporary</option></select></label><label>Starts<input name="effectiveFrom" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Ends<input name="effectiveThrough" type="date"/></label><label>Notes<input name="notes" maxLength={1000}/></label><button className="sv-button">Assign territory</button></form>
   <details><summary>Create a territory</summary><form action={createAction} className="territory-create-form"><label>Name<input name="name" required maxLength={150}/></label><label>Color<input name="color" type="color" defaultValue="#4F46E5"/></label><label>Type<select name="territoryType" defaultValue="mixed"><option value="mixed">Mixed</option><option value="postal_codes">ZIP / postal codes</option><option value="neighborhoods">Neighborhoods</option><option value="polygon">Polygon</option><option value="radius">Radius</option><option value="city_boundaries">City boundaries</option><option value="delivery_zone">Delivery zone</option><option value="service_area">Service area</option></select></label><label>Parent territory<select name="parentTerritoryId"><option value="">No parent</option>{territories.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>ZIP / postal codes<textarea name="postalCodes" placeholder="85234, 85296"/></label><label>Neighborhoods<textarea name="neighborhoods" placeholder="Downtown, North District"/></label><label>Cities<textarea name="cities" placeholder="Gilbert, Chandler"/></label><label>Radius center latitude<input name="radiusLatitude" type="number" min="-90" max="90" step="any"/></label><label>Radius center longitude<input name="radiusLongitude" type="number" min="-180" max="180" step="any"/></label><label>Radius miles<input name="radiusMiles" type="number" min=".1" max="500" step=".1"/></label><label>Description<textarea name="description" maxLength={2000}/></label><label>Notes<textarea name="notes" maxLength={4000}/></label><label className="territory-boundary">GeoJSON boundary (optional)<textarea name="boundaryGeojson" placeholder={'{"type":"Polygon","coordinates":[...]}'}/></label><button className="sv-button sv-secondary">Create territory</button></form></details>
  </div>}
 </section>;
}
