type Asset={id:string;asset_type:string;name:string;asset_number:string|null;serial_number:string|null;manufacturer:string|null;model:string|null;condition:string;status:string};
type Assignment={id:string;assigned_at:string;expected_return_at:string|null;assignment_condition:string|null;assignment_notes:string|null;workforce_assets:Asset|Asset[]|null};
const relation=<T,>(value:T|T[]|null)=>Array.isArray(value)?value[0]??null:value;
const label=(value:string)=>value.replaceAll("_"," ");
export function EmployeeAssets({assets,assignments,canEdit,createAction,assignAction,returnAction}:{assets:Asset[];assignments:Assignment[];canEdit:boolean;createAction:(data:FormData)=>void|Promise<void>;assignAction:(data:FormData)=>void|Promise<void>;returnAction:(data:FormData)=>void|Promise<void>}){
 return <section className="workspace-panel employee-assets"><div className="panel-title"><div><span className="sv-kicker">Custody and readiness</span><h2>Vehicles & equipment</h2><p>Track operational assets assigned to this employee without mixing them with rental inventory.</p></div></div>
  <div className="employee-asset-list">{assignments.length?assignments.map(item=>{const asset=relation(item.workforce_assets);return <article key={item.id}><div><span className="asset-type">{label(asset?.asset_type??"asset")}</span><strong>{asset?.name??"Unknown asset"}</strong><small>{[asset?.asset_number,asset?.manufacturer,asset?.model].filter(Boolean).join(" · ")||"No identifying details"} · {asset?.condition??item.assignment_condition??"condition unknown"}</small><small>Assigned {new Date(item.assigned_at).toLocaleDateString()}{item.expected_return_at?` · due ${new Date(item.expected_return_at).toLocaleDateString()}`:""}</small></div>{canEdit&&<form action={returnAction} className="asset-return-form"><input type="hidden" name="assignmentId" value={item.id}/><select name="returnCondition" defaultValue={asset?.condition??"good"} aria-label={`Return condition for ${asset?.name??"asset"}`}><option value="new">New</option><option value="good">Good</option><option value="fair">Fair</option><option value="poor">Poor</option><option value="out_of_service">Out of service</option></select><button className="text-button danger">Return</button></form>}</article>}):<div className="dashboard-empty"><strong>No assets assigned.</strong><p>Vehicles and equipment assigned to this employee will appear here.</p></div>}</div>
  {canEdit&&<div className="asset-management"><form action={assignAction} className="asset-assign-form"><label>Available asset<select name="assetId" required><option value="">Choose asset</option>{assets.map(asset=><option key={asset.id} value={asset.id}>{asset.name} · {label(asset.asset_type)}</option>)}</select></label><label>Expected return<input name="expectedReturnAt" type="datetime-local"/></label><label>Notes<input name="assignmentNotes" maxLength={2000}/></label><button className="sv-button">Assign asset</button></form>
   <details><summary>Add an asset</summary><form action={createAction} className="asset-create-form"><label>Name<input name="name" required maxLength={150}/></label><label>Type<select name="assetType" defaultValue="equipment"><option value="vehicle">Vehicle</option><option value="trailer">Trailer</option><option value="equipment">Equipment</option><option value="tablet">Tablet</option><option value="key">Key</option><option value="safety_equipment">Safety equipment</option><option value="other">Other</option></select></label><label>Asset number<input name="assetNumber" maxLength={150}/></label><label>Serial number<input name="serialNumber" maxLength={200}/></label><label>Manufacturer<input name="manufacturer" maxLength={150}/></label><label>Model<input name="model" maxLength={150}/></label><label>Year<input name="modelYear" type="number" min="1900" max="2200"/></label><label>License plate<input name="licensePlate" maxLength={50}/></label><label>VIN<input name="vin" maxLength={100}/></label><label>Condition<select name="condition" defaultValue="good"><option value="new">New</option><option value="good">Good</option><option value="fair">Fair</option><option value="poor">Poor</option><option value="out_of_service">Out of service</option></select></label><label className="asset-notes">Notes<textarea name="notes" maxLength={2000}/></label><button className="sv-button sv-secondary">Add asset</button></form></details>
  </div>}
 </section>;
}
