"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import type {LandscapePoint,LandscapeShape} from "@/lib/landscapingMeasurements";
type Location={id:string;customer_id:string;label:string;address:string;latitude:number|null;longitude:number|null};
type Maps={Map:new(node:HTMLElement,options:Record<string,unknown>)=>any;Polygon:new(options:Record<string,unknown>)=>any;Polyline:new(options:Record<string,unknown>)=>any;Marker:new(options:Record<string,unknown>)=>any;Geocoder:new()=>any;geometry:{spherical:{computeArea:(path:any[])=>number;computeLength:(path:any[])=>number}}};
const api=()=> (window as any).google?.maps as Maps|undefined;
async function load(key:string){if(api())return api()!;return new Promise<Maps>((resolve,reject)=>{const existing=document.querySelector<HTMLScriptElement>('script[src^="https://maps.googleapis.com/maps/api/js"]');if(existing){existing.addEventListener("load",()=>api()?resolve(api()!):reject(new Error("Map unavailable")),{once:true});return;}const script=document.createElement("script");script.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(key)}&libraries=geometry`;script.async=true;script.onload=()=>api()?resolve(api()!):reject(new Error("Map unavailable"));script.onerror=()=>reject(new Error("Map unavailable"));document.head.appendChild(script);});}
const colors={lawn:"#22c55e",bed:"#a855f7",hardscape:"#f59e0b",perimeter:"#2563eb"};
export function LandscapingMeasurementEditor({apiKey,customers,locations,action}:{apiKey?:string;customers:{id:string;name:string}[];locations:Location[];action:(data:FormData)=>void}){
 const node=useRef<HTMLDivElement>(null),map=useRef<any>(null),maps=useRef<Maps|null>(null),overlays=useRef<any[]>([]),draftOverlays=useRef<any[]>([]),draft=useRef<LandscapePoint[]>([]),drawingActive=useRef(false);
 const [customerId,setCustomer]=useState(""),[locationId,setLocation]=useState(""),[kind,setKind]=useState<LandscapeShape["kind"]>("lawn"),[drawing,setDrawing]=useState(false),[shapes,setShapes]=useState<LandscapeShape[]>([]),[message,setMessage]=useState("");
 const visible=locations.filter(row=>row.customer_id===customerId),selected=locations.find(row=>row.id===locationId);
 useEffect(()=>{const activeOverlays=overlays.current,activeDrafts=draftOverlays.current;if(!apiKey||!node.current){setMessage("Add NEXT_PUBLIC_GOOGLE_MAPS_API_KEY to use satellite measurements.");return;}load(apiKey).then(value=>{maps.current=value;map.current=new value.Map(node.current!,{center:{lat:33.4484,lng:-112.074},zoom:19,mapTypeId:"satellite",tilt:0,streetViewControl:false,mapTypeControl:true,fullscreenControl:true,draggableCursor:"grab"});map.current.addListener("click",(event:any)=>{if(!drawingActive.current||!event.latLng)return;const point={lat:event.latLng.lat(),lng:event.latLng.lng()};draft.current.push(point);const marker=new value.Marker({position:point,map:map.current,label:String(draft.current.length)});draftOverlays.current.push(marker);if(draft.current.length>1){const line=new value.Polyline({path:[...draft.current],map:map.current,strokeColor:colors[kind],strokeWeight:3});draftOverlays.current.push(line);}setMessage(`${draft.current.length} point${draft.current.length===1?"":"s"} added. Continue clicking, then finish the measurement.`);});}).catch(()=>setMessage("Satellite map could not load."));return()=>{activeOverlays.forEach(item=>item.setMap(null));activeDrafts.forEach(item=>item.setMap(null));};},[apiKey,kind]);
 useEffect(()=>{if(!selected||!map.current||!maps.current)return;if(selected.latitude!==null&&selected.longitude!==null){map.current.setCenter({lat:selected.latitude,lng:selected.longitude});map.current.setZoom(20);}else new maps.current.Geocoder().geocode({address:selected.address},(results:any[],status:string)=>{if(status==="OK"&&results?.[0]){map.current.setCenter(results[0].geometry.location);map.current.setZoom(20);}else setMessage("This address could not be located on the satellite map.");});},[selected]);
 const clearDraft=()=>{draftOverlays.current.forEach(item=>item.setMap(null));draftOverlays.current=[];draft.current=[];};
 const finish=()=>{const m=maps.current;if(!m)return;const min=kind==="perimeter"?2:3;if(draft.current.length<min){setMessage(`Add at least ${min} points.`);return;}const path=[...draft.current],area=kind==="perimeter"?0:m.geometry.spherical.computeArea(path)*10.7639104,length=kind==="perimeter"?m.geometry.spherical.computeLength(path)*3.2808399:0,shape:LandscapeShape={id:crypto.randomUUID(),kind,label:`${kind[0].toUpperCase()}${kind.slice(1)} ${shapes.filter(row=>row.kind===kind).length+1}`,points:path,areaSqFt:Math.round(area*10)/10,lengthFt:Math.round(length*10)/10};clearDraft();const overlay=kind==="perimeter"?new m.Polyline({path,map:map.current,strokeColor:colors[kind],strokeWeight:4}):new m.Polygon({paths:path,map:map.current,fillColor:colors[kind],fillOpacity:.3,strokeColor:colors[kind],strokeWeight:3});overlays.current.push(overlay);setShapes(current=>[...current,shape]);drawingActive.current=false;map.current?.setOptions({draggableCursor:"grab"});setDrawing(false);setMessage("Measurement added. Draw another area or save.");};
 const remove=(index:number)=>{overlays.current[index]?.setMap(null);overlays.current.splice(index,1);setShapes(current=>current.filter((_,i)=>i!==index));};
 const totals=useMemo(()=>({area:shapes.reduce((s,r)=>s+r.areaSqFt,0),length:shapes.reduce((s,r)=>s+r.lengthFt,0)}),[shapes]);
 return <form action={action} className="landscape-measurement-form"><input type="hidden" name="shapesJson" value={JSON.stringify(shapes)}/><div className="landscape-measurement-fields"><label>Measurement name<input name="name" required placeholder="Front and back yard"/></label><label>Customer<select name="customerId" required value={customerId} onChange={e=>{setCustomer(e.target.value);setLocation("");}}><option value="">Choose customer</option>{customers.map(row=><option value={row.id} key={row.id}>{row.name}</option>)}</select></label><label>Service location<select name="serviceLocationId" required value={locationId} onChange={e=>setLocation(e.target.value)}><option value="">Choose location</option>{visible.map(row=><option value={row.id} key={row.id}>{row.label}</option>)}</select></label></div><div className="landscape-map-toolbar"><label>Measure<select value={kind} disabled={drawing} onChange={e=>setKind(e.target.value as LandscapeShape["kind"])}><option value="lawn">Lawn area</option><option value="bed">Planting bed area</option><option value="hardscape">Hardscape area</option><option value="perimeter">Linear perimeter</option></select></label>{!drawing?<button type="button" onClick={()=>{clearDraft();drawingActive.current=true;map.current?.setOptions({draggableCursor:"crosshair"});setDrawing(true);setMessage("Tracing is on. Click points around the property boundary.");}} disabled={!locationId}>Start tracing</button>:<><button type="button" onClick={finish}>Finish measurement</button><button type="button" onClick={()=>{clearDraft();drawingActive.current=false;map.current?.setOptions({draggableCursor:"grab"});setDrawing(false);setMessage("Drawing canceled.");}}>Cancel</button></>}</div><div ref={node} className={`landscape-satellite-map${drawing?" tracing":""}`}/><p className="landscape-map-help">{message||"Choose a property, select a measurement type, and trace it on the satellite image."}</p><section className="landscape-measurement-summary"><header><div><span>Total measured area</span><strong>{totals.area.toLocaleString(undefined,{maximumFractionDigits:1})} sq ft</strong></div><div><span>Total measured perimeter</span><strong>{totals.length.toLocaleString(undefined,{maximumFractionDigits:1})} ft</strong></div></header>{shapes.map((shape,index)=><article key={shape.id}><i style={{background:colors[shape.kind]}}/><span><strong>{shape.label}</strong><small>{shape.areaSqFt?`${shape.areaSqFt.toLocaleString()} sq ft`:`${shape.lengthFt.toLocaleString()} linear ft`}</small></span><button type="button" onClick={()=>remove(index)}>Remove</button></article>)}{!shapes.length&&<p>No completed measurements yet.</p>}</section><div className="workspace-notice warning"><div><strong>Satellite measurement disclaimer</strong><p>Imagery can be outdated or distorted. Confirm important measurements on site before promising quantities or pricing.</p></div></div><button className="sv-button" disabled={!shapes.length}>Save and build estimate</button></form>;
}
