import {DomainRegistrantAddressFields} from "./DomainRegistrantAddressFields";
import {ManagedDomainStatusPoller} from "./ManagedDomainStatusPoller";
import {WebsiteIcon} from "./WebsiteIcon";
import {changeManagedDomainRequest,checkManagedDomainAvailability,purchaseManagedDomain} from "@/app/app/[businessSlug]/settings/website/actions";

type Order={status:string;customer_purchase_price:number|null;customer_renewal_price:number|null;currency:string|null;provider_order_id:string|null;availability_checked_at:string|null;last_error_category:string|null}|null;
const title=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());
const money=(value:number|null,currency="USD")=>value==null?"Pending":new Intl.NumberFormat("en-US",{style:"currency",currency}).format(Number(value));

export function ManagedDomainCustomerSetup({businessSlug,domain,status,order,editable,business,user,googleMapsApiKey}:{businessSlug:string;domain:string;status:string;order:Order;editable:boolean;business:{name:string;email?:string|null;phone?:string|null;address_line1?:string|null;address_line2?:string|null;city?:string|null;state?:string|null;postal_code?:string|null};user:{email?:string|null;user_metadata?:Record<string,unknown>};googleMapsApiKey?:string}){
 const activeStatus=order?.status??status,metadata=user.user_metadata??{},fullName=String(metadata.full_name??metadata.name??"").trim(),parts=fullName.split(/\s+/),firstName=String(metadata.first_name??parts[0]??""),lastName=String(metadata.last_name??parts.slice(1).join(" ")??"");
 const pending=["registration_pending","registered","connected"].includes(activeStatus);
 const canCheck=editable&&!pending&&!["available","premium_review","unavailable"].includes(activeStatus);
 return <div className="managed-domain-customer-setup">
  <input type="hidden" name="customDomain" value={pending?domain:""}/>
  <div className="website-managed-domain"><i><WebsiteIcon name={activeStatus==="connected"?"check":"globe"}/></i><span><small>Your custom domain</small><strong>{domain}</strong><p>{activeStatus==="connected"?"Your domain is connected and ready to use.":activeStatus==="available"?"This domain is available and ready for final registration.":activeStatus==="premium_review"?"This premium domain is not included in the free first-year offer.":activeStatus==="unavailable"?"This domain is unavailable. Choose a different address.":activeStatus==="failed"?"The registration needs attention. Nothing will be purchased again automatically.":pending?"Servonas is finishing registration and connection automatically.":"Check availability to continue."}</p></span><b className={`domain-status ${activeStatus}`}>{title(activeStatus)}</b></div>
  {order?.availability_checked_at&&<small className="managed-domain-checked">Availability checked {new Date(order.availability_checked_at).toLocaleString()}</small>}
  {canCheck&&<button className="sv-button sv-secondary" type="submit" formAction={checkManagedDomainAvailability.bind(null,businessSlug)} formNoValidate><WebsiteIcon name="globe"/>Check Availability →</button>}
  {(activeStatus==="premium_review"||activeStatus==="unavailable")&&<div className="website-domain-warning managed-domain-replace"><p>Choose another available standard domain.</p><label>New domain<input required name="newManagedDomain" placeholder="yourbusiness.com" autoCapitalize="none" autoCorrect="off"/></label><button className="sv-button sv-secondary" type="submit" formAction={changeManagedDomainRequest.bind(null,businessSlug)} formNoValidate>Use this domain instead</button></div>}
  {activeStatus==="available"&&order&&<section className="managed-domain-registration"><header><div><span>Almost done</span><h3>Who should own this domain?</h3><p>Domain registration requires owner contact information. We&apos;ll use the details below to register the domain to your business.</p></div><dl><div><dt>Due today</dt><dd>$0</dd></div><div><dt>Estimated renewal</dt><dd>{money(order.customer_renewal_price,order.currency??"USD")}/year</dd></div></dl></header><div className="managed-domain-registrant-grid"><label>First name<input required name="firstName" defaultValue={firstName}/></label><label>Last name<input required name="lastName" defaultValue={lastName}/></label><label>Business name<input name="companyName" defaultValue={business.name}/></label><label>Email<input required type="email" name="email" defaultValue={business.email??user.email??""}/></label><label>Phone<input required name="phone" defaultValue={business.phone??""} placeholder="(480) 555-1234"/></label><DomainRegistrantAddressFields apiKey={googleMapsApiKey} address1={business.address_line1} address2={business.address_line2} city={business.city} state={business.state} zip={business.postal_code}/></div><div className="managed-domain-terms"><label><input required type="checkbox" name="registrationTerms"/><span>I confirm this information is correct and authorize Servonas to register <strong>{domain}</strong> for my business.</span></label><label><input required type="checkbox" name="renewalTerms"/><span>I understand the first year is included and the current estimated renewal price is <strong>{money(order.customer_renewal_price,order.currency??"USD")}/year</strong>.</span></label></div>{editable&&<button className="sv-button" type="submit" formAction={purchaseManagedDomain.bind(null,businessSlug)}><WebsiteIcon name="globe"/>Register My Domain →</button>}</section>}
  {pending&&<ManagedDomainStatusPoller businessSlug={businessSlug} initialStatus={activeStatus}/>} 
 </div>;
}
