"use client";

import {useEffect} from "react";
import {trackMetaStandardEvent} from "./TenantMetaPixel";
import type {MechanicalBullLandingData} from "@/lib/mechanicalBullLanding";
import {mechanicalBullOperatorCopy} from "@/lib/mechanicalBullLanding";
import {TenantMainWebsiteLink} from "./TenantMainWebsiteLink";

const money=(cents:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(cents/100);

function track(slug:string,event:string){
 void fetch(`/api/public-booking/${encodeURIComponent(slug)}/analytics`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({event,sessionId:crypto.randomUUID(),metadata:{landing:"mechanical_bull"}})}).catch(()=>undefined);
}

export function MechanicalBullLanding({data,bookingUrl,websiteUrl=data.websiteUrl}:{data:MechanicalBullLandingData;bookingUrl:string;websiteUrl?:string}){
 const {item}=data;
 const scrollToBooking=(event:string)=>{track(data.bookingSlug,event);document.getElementById("bull-availability")?.scrollIntoView({behavior:"smooth",block:"start"});};
 useEffect(()=>{track(data.bookingSlug,"mechanical_bull_landing_view");trackMetaStandardEvent("ViewContent",{content_name:item.name,content_ids:[item.id],content_type:"product",value:item.dailyPriceCents>0?item.dailyPriceCents/100:undefined,currency:item.dailyPriceCents>0?"USD":undefined},{eventKey:`view-content:${data.bookingSlug}:${item.id}:mechanical-bull`,storage:"session"});},[data.bookingSlug,item.dailyPriceCents,item.id,item.name]);
 return <main className="mechanical-bull-landing" style={{"--bull-brand":data.brandColor} as React.CSSProperties}>
  <header className="mechanical-bull-nav"><a href={websiteUrl} className="mechanical-bull-brand" aria-label={`${data.businessName} main website`}>{data.businessName}</a><nav><a href="#details">The Bull</a><a href="#pricing">Pricing</a><a href="#areas">Service areas</a></nav>{data.phone&&<a className="mechanical-bull-call" href={`tel:${data.phone}`}>{data.phone}</a>}<button type="button" onClick={()=>scrollToBooking("mechanical_bull_check_availability")}>Check availability</button></header>
  <TenantMainWebsiteLink href={websiteUrl} businessName={data.businessName}/>
  <section className="mechanical-bull-hero" id="top"><div><span>Mechanical bull rental</span><h1>Mechanical Bull Rental in the Phoenix East Valley</h1><p>Bring the rodeo to your party, school, church, corporate event, or celebration with a mechanical bull from {data.businessName}.</p><div className="mechanical-bull-actions"><button type="button" onClick={()=>scrollToBooking("mechanical_bull_check_availability")}>Check Availability</button><a href="#pricing" onClick={()=>track(data.bookingSlug,"mechanical_bull_view_pricing")}>View Pricing</a></div></div><div className="mechanical-bull-hero-media">{item.imageUrl?<img src={item.imageUrl} alt={`${item.name} available from ${data.businessName}`}/>:<div><b>{item.name}</b><span>Check your date below</span></div>}</div></section>
  <section className="mechanical-bull-trust" aria-label="Rental highlights"><span>✓ Great for parties & events</span><span>✓ Live date availability</span><span>✓ Reserve online</span>{item.operatorMode!=="none"&&<span>✓ Operator option available</span>}</section>
  <section className="mechanical-bull-details" id="details"><div><span>Turn your event into a rodeo</span><h2>A high-energy centerpiece for your celebration.</h2><p>{item.description||`${item.name} gives guests a memorable attraction for events of all kinds.`}</p><p>It is a great fit for birthday parties, corporate events, school events, church events, community events, graduation parties, western-themed parties, adult parties, and large family gatherings.</p></div><aside id="pricing"><span>Mechanical Bull Rental</span><strong>{item.dailyPriceCents>0?money(item.dailyPriceCents):"Contact for price"}</strong>{item.dailyPriceCents>0&&<small>Up to {item.standardRentalHours}-hour rental</small>}{item.multiDayMessage&&<b>✓ {item.multiDayMessage}</b>}{item.operatorMode!=="none"&&<div><span>Operator</span><strong>{item.operatorHourlyRateCents>0?`${money(item.operatorHourlyRateCents)}/hour`:"Configured during booking"}</strong></div>}<button type="button" onClick={()=>scrollToBooking("mechanical_bull_check_availability")}>Check availability</button></aside></section>
  <section className="mechanical-bull-operator"><div><span>Want us to run the bull?</span><h2>Operator options, clearly shown before you book.</h2></div><p>{mechanicalBullOperatorCopy(item)}</p></section>
  <section className="mechanical-bull-included"><span>What your booking shows</span><div><article><b>01</b><h3>{item.name}</h3><p>The live rental item and its current pricing.</p></article><article><b>02</b><h3>Rental time</h3><p>Choose a date and time that works for your event.</p></article><article><b>03</b><h3>Availability</h3><p>See date-specific availability before reserving.</p></article>{item.operatorMode!=="none"&&<article><b>04</b><h3>Operator choice</h3><p>Review the current operator configuration while booking.</p></article>}</div></section>
  <section className="mechanical-bull-events"><header><span>Made for celebrations</span><h2>Bring the ride to the event.</h2></header><div>{["Birthday parties","Corporate events","School events","Church events","Western parties","Community events"].map((event,index)=><article key={event}><i>{String(index+1).padStart(2,"0")}</i><strong>{event}</strong></article>)}</div></section>
  <section className="mechanical-bull-availability" id="bull-availability"><header><span>Is the bull available for your date?</span><h2>Choose a date and check the Mechanical Bull.</h2><p>The booking calendar uses the current rental inventory, reserved times, blocked dates, business hours, and turnaround rules.</p></header><iframe src={bookingUrl} title={`Check ${item.name} availability`} onLoad={()=>track(data.bookingSlug,"mechanical_bull_booking_started")}/></section>
  <section className="mechanical-bull-areas" id="areas"><span>Mechanical bull rentals near you</span><h2>Serving the local East Valley.</h2><p>{data.serviceAreas.length?`Copper State Bounce’s configured service areas include ${data.serviceAreas.join(", ")}.`:`Check your event date and address during booking to confirm availability.`}</p><div>{data.serviceAreas.map(area=><span key={area}>{area}</span>)}</div></section>
  <section className="mechanical-bull-faq"><header><span>Questions</span><h2>Mechanical bull rental FAQ</h2></header><details><summary>How much does it cost to rent the mechanical bull?</summary><p>{item.dailyPriceCents>0?`${item.name} is currently ${money(item.dailyPriceCents)} for up to ${item.standardRentalHours} hours. Select your date and time to see the complete booking total.`:"Choose your date to view the current rental price."}</p></details><details><summary>Is an operator included?</summary><p>{mechanicalBullOperatorCopy(item)}</p></details><details><summary>How much space does the mechanical bull need?</summary><p>Contact Copper State Bounce before booking if you need equipment dimensions or site-planning details for your event.</p></details><details><summary>Can I rent it for a school, church, or corporate event?</summary><p>Choose your date and review availability for your event. Copper State Bounce can follow up on event-specific details.</p></details><details><summary>How do I check availability?</summary><p>Choose an event date and time in the booking section. The calendar will show the Mechanical Bull’s current availability for that selection.</p></details></section>
  <section className="mechanical-bull-final"><span>Ready to ride?</span><h2>Check your event date and reserve the Copper State Bounce mechanical bull today.</h2><button type="button" onClick={()=>scrollToBooking("mechanical_bull_check_availability")}>Check Availability</button></section>
 </main>;
}
