"use client";
import {useActionState,useState} from "react";
import Link from "next/link";
import {createGuidedWorkspace,OnboardingState} from "@/app/onboarding/actions";
const zones=["America/Phoenix","America/Los_Angeles","America/Denver","America/Chicago","America/New_York"];
export default function OnboardingWizard({defaultEmail=""}:{defaultEmail?:string}){
 const [step,setStep]=useState<1|2>(1),[state,action,pending]=useActionState(createGuidedWorkspace,{} as OnboardingState);
 const initial=state.values??{},[name,setName]=useState(initial.name??""),[slug,setSlug]=useState(initial.slug??"");
 const clean=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
 const error=(key:keyof NonNullable<OnboardingState["fieldErrors"]>)=>state.fieldErrors?.[key]&&<small className="field-error">{state.fieldErrors[key]}</small>;
 return <div className="onboarding-frame"><aside><span className="sv-kicker">Guided setup</span><h2>Ready in about 10–15 minutes</h2><ol>{["Welcome","Company","Business profile","Hours","First service","Ready to go"].map((label,index)=><li className={index+1===step?"active":index+1<step?"complete":""} key={label}><i>{index+1<step?"✓":index+1}</i><span>{label}</span></li>)}</ol><p>Your progress is saved after each completed step. You can safely return later.</p></aside>
  <section className="onboarding-card"><div className="onboarding-progress" aria-label={`Step ${step} of 6`}><span style={{width:`${step/6*100}%`}}/></div>
   {step===1?<div className="onboarding-welcome"><span className="sv-kicker">Step 1 of 6</span><h1>Welcome to Servonas</h1><p>Let’s configure the essentials your team needs to start operating. We’ll begin with your company, then set hours and create your first service.</p><div className="onboarding-promise"><strong>No payment method required</strong><span>Your active Pilot access is added automatically when the company workspace is created.</span></div><button className="sv-button" onClick={()=>setStep(2)}>Continue setup</button><Link href="/app">Resume later</Link></div>:
   <form action={action} className="onboarding-company-form"><header><span className="sv-kicker">Step 2 of 6</span><h1>Tell us about your company</h1><p>This information becomes the foundation for scheduling, customer communication, and local-time reporting.</p></header>
    {state.error&&<p className="auth-error" role="alert">{state.error}</p>}
    <fieldset><legend>Company identity</legend><label>Company name<input required name="name" value={name} onChange={event=>{setName(event.target.value);if(!slug)setSlug(clean(event.target.value));}} maxLength={200}/>{error("name")}</label><label>Customer-facing name<input required name="displayName" defaultValue={initial.displayName} maxLength={120}/>{error("displayName")}</label><label className="wide">Workspace URL<div className="sv-input-prefix"><span>servonas.com/app/</span><input required name="slug" value={slug} onChange={event=>setSlug(clean(event.target.value))}/></div>{error("slug")}</label></fieldset>
    <fieldset><legend>Business address</legend><label className="wide">Street address<input required name="addressLine1" autoComplete="street-address" defaultValue={initial.addressLine1}/>{error("addressLine1")}</label><label className="wide">Suite or unit <small>Optional</small><input name="addressLine2" defaultValue={initial.addressLine2}/></label><label>City<input required name="city" autoComplete="address-level2" defaultValue={initial.city}/></label><label>State or region<input required name="region" autoComplete="address-level1" defaultValue={initial.region}/></label><label>Postal code<input required name="postalCode" autoComplete="postal-code" defaultValue={initial.postalCode}/></label><label>Country<select name="country" defaultValue={initial.country??"US"}><option value="US">United States</option><option value="CA">Canada</option></select>{error("country")}</label></fieldset>
    <fieldset><legend>Contact and local time</legend><label>Business phone<input required name="phone" type="tel" autoComplete="tel" defaultValue={initial.phone}/>{error("phone")}</label><label>Business email<input required name="email" type="email" autoComplete="email" defaultValue={initial.email??defaultEmail}/>{error("email")}</label><label>Website <small>Optional</small><input name="website" type="url" placeholder="https://" defaultValue={initial.website}/>{error("website")}</label><label>Time zone<select required name="timezone" defaultValue={initial.timezone??"America/Phoenix"}>{zones.map(zone=><option key={zone}>{zone}</option>)}</select>{error("timezone")}</label></fieldset>
    <div className="onboarding-actions"><button type="button" className="sv-button sv-secondary" onClick={()=>setStep(1)}>Back</button><button className="sv-button" disabled={pending}>{pending?"Saving company…":"Save and continue"}</button></div></form>}
  </section></div>;
}
