"use client";
import {useActionState,useEffect,useRef,useState} from "react";
import Link from "next/link";
import {createGuidedWorkspace,OnboardingState} from "@/app/onboarding/actions";
import {parseGoogleAddressComponents,type GoogleAddressComponent} from "@/lib/googleAddressComponents";
const zones=["America/Phoenix","America/Los_Angeles","America/Denver","America/Chicago","America/New_York"];
export default function OnboardingWizard({defaultEmail="",defaultUserName="",googleMapsApiKey}:{defaultEmail?:string;defaultUserName?:string;googleMapsApiKey?:string}){
 const [step,setStep]=useState<1|2>(1),[state,action,pending]=useActionState(createGuidedWorkspace,{} as OnboardingState);
 const initial=state.values??{},[userName,setUserName]=useState(initial.userName??defaultUserName),[name,setName]=useState(initial.name??""),[slug,setSlug]=useState(initial.slug??""),[slugEdited,setSlugEdited]=useState(Boolean(initial.slug));
 const [placeId,setPlaceId]=useState(""),[address,setAddress]=useState(initial.addressLine1??""),[unit,setUnit]=useState(initial.addressLine2??"");
 const [city,setCity]=useState(initial.city??""),[region,setRegion]=useState(initial.region??""),[postalCode,setPostalCode]=useState(initial.postalCode??""),[country,setCountry]=useState(initial.country??"US");
 const [addressLookupError,setAddressLookupError]=useState(""),addressRef=useRef<HTMLInputElement>(null);
 const clean=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
 const error=(key:keyof NonNullable<OnboardingState["fieldErrors"]>)=>state.fieldErrors?.[key]&&<small className="field-error">{state.fieldErrors[key]}</small>;
 useEffect(()=>{if(state.error||state.values)setStep(2);},[state.error,state.values]);
 useEffect(()=>{
  if(step!==2||!googleMapsApiKey||!addressRef.current)return;
  let attempts=0,timer:ReturnType<typeof setTimeout>|undefined;
  const initialize=()=>{
   const maps=(window as typeof window&{google?:{maps?:{places?:{Autocomplete:new(input:HTMLInputElement,options:object)=>{addListener:(name:string,callback:()=>void)=>void;getPlace:()=>{place_id?:string;formatted_address?:string;address_components?:GoogleAddressComponent[]}}}}}}).google?.maps;
   if(!maps?.places||!addressRef.current){if(++attempts<20)timer=setTimeout(initialize,150);else setAddressLookupError("Google address suggestions could not be loaded.");return;}
   const autocomplete=new maps.places.Autocomplete(addressRef.current,{types:["address"],fields:["place_id","formatted_address","address_components"]});
   autocomplete.addListener("place_changed",()=>{const place=autocomplete.getPlace();if(!place.place_id||!place.formatted_address){setAddressLookupError("Choose a complete address from Google’s suggestions.");return;}
    const parsed=parseGoogleAddressComponents(place.address_components,place.formatted_address);setPlaceId(place.place_id);setAddress(parsed.streetAddress);setUnit(parsed.unit);setCity(parsed.city);setRegion(parsed.state);setPostalCode(parsed.postalCode);setCountry(parsed.country);setAddressLookupError("");});
  };
  if((window as typeof window&{google?:{maps?:{places?:unknown}}}).google?.maps?.places)initialize();else{const existing=document.querySelector<HTMLScriptElement>('script[data-servonas-google-places="true"]');if(existing)existing.addEventListener("load",initialize,{once:true});else{const script=document.createElement("script");script.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(googleMapsApiKey)}&libraries=places`;script.async=true;script.defer=true;script.dataset.servonasGooglePlaces="true";script.addEventListener("load",initialize,{once:true});script.addEventListener("error",()=>setAddressLookupError("Google address suggestions could not be loaded."),{once:true});document.head.appendChild(script);}}
  return()=>{if(timer)clearTimeout(timer);};
 },[googleMapsApiKey,step]);
 return <div className="onboarding-frame"><aside><span className="sv-kicker">Guided setup</span><h2>Ready in about 10–15 minutes</h2><ol>{["Welcome","Company","Business profile","Hours","First service","Ready to go"].map((label,index)=><li className={index+1===step?"active":index+1<step?"complete":""} key={label}><i>{index+1<step?"✓":index+1}</i><span>{label}</span></li>)}</ol><p>Your progress is saved after each completed step. You can safely return later.</p></aside>
  <section className="onboarding-card"><div className="onboarding-progress" aria-label={`Step ${step} of 6`}><span style={{width:`${step/6*100}%`}}/></div>
   {step===1?<div className="onboarding-welcome"><span className="sv-kicker">Step 1 of 6</span><h1>Welcome to Servonas</h1><p>Let’s configure the essentials your team needs to start operating. We’ll begin with your company, then set hours and create your first service.</p><label className="onboarding-name-field">What is your name?<input required autoFocus autoComplete="name" value={userName} onChange={event=>setUserName(event.target.value)} maxLength={100} placeholder="Your full name"/></label><div className="onboarding-promise"><strong>Everything you need to get started</strong><span>Finish the essentials and start using your workspace right away.</span></div><button className="sv-button" disabled={userName.trim().length<2} onClick={()=>setStep(2)}>Start setup now</button><Link href="/app">Resume later</Link></div>:
   <form action={action} className="onboarding-company-form"><input type="hidden" name="userName" value={userName}/><header><span className="sv-kicker">Step 2 of 6</span><h1>Tell us about your company</h1><p>This information becomes the foundation for scheduling, customer communication, and local-time reporting.</p></header>
    {state.error&&<p className="auth-error" role="alert">{state.error}</p>}
    <fieldset><legend>Company identity</legend><label>Company name<input required name="name" value={name} onChange={event=>{setName(event.target.value);if(!slugEdited)setSlug(clean(event.target.value));}} maxLength={200}/>{error("name")}</label><label>Customer-facing name<input required name="displayName" defaultValue={initial.displayName} maxLength={120}/>{error("displayName")}</label><label className="wide">Workspace URL<div className="sv-input-prefix"><span>servonas.com/app/</span><input required name="slug" value={slug} onChange={event=>{setSlugEdited(true);setSlug(clean(event.target.value));}}/></div>{error("slug")}</label></fieldset>
    <fieldset><legend>Business address</legend><input type="hidden" name="googlePlaceId" value={placeId}/><label className="wide">Street address<input ref={addressRef} required name="addressLine1" autoComplete="off" value={address} onChange={event=>{setAddress(event.target.value);setPlaceId("");}} placeholder={googleMapsApiKey?"Start typing and choose a Google suggestion":""}/>{error("addressLine1")}{addressLookupError&&<small className="field-error">{addressLookupError}</small>}<small>{googleMapsApiKey?"Choose an address from Google to fill the structured fields.":"Google address suggestions are not configured."}</small></label><label className="wide">Suite or unit <small>Optional</small><input name="addressLine2" value={unit} onChange={event=>setUnit(event.target.value)}/></label><label>City<input required name="city" autoComplete="address-level2" value={city} onChange={event=>{setCity(event.target.value);setPlaceId("");}}/></label><label>State or region<input required name="region" autoComplete="address-level1" value={region} onChange={event=>{setRegion(event.target.value);setPlaceId("");}}/></label><label>Postal code<input required name="postalCode" autoComplete="postal-code" value={postalCode} onChange={event=>{setPostalCode(event.target.value);setPlaceId("");}}/></label><label>Country<select name="country" value={country} onChange={event=>{setCountry(event.target.value);setPlaceId("");}}><option value="US">United States</option><option value="CA">Canada</option></select>{error("country")}</label></fieldset>
    <fieldset><legend>Contact and local time</legend><label>Business phone<input required name="phone" type="tel" autoComplete="tel" defaultValue={initial.phone}/>{error("phone")}</label><label>Business email<input required name="email" type="email" autoComplete="email" defaultValue={initial.email??defaultEmail}/>{error("email")}</label><label>Website <small>Optional</small><input name="website" type="url" placeholder="https://" defaultValue={initial.website}/>{error("website")}</label><label>Time zone<select required name="timezone" defaultValue={initial.timezone??"America/Phoenix"}>{zones.map(zone=><option key={zone}>{zone}</option>)}</select>{error("timezone")}</label></fieldset>
    <div className="onboarding-actions"><button type="button" className="sv-button sv-secondary" onClick={()=>setStep(1)}>Back</button><button className="sv-button" disabled={pending}>{pending?"Saving company…":"Save and continue"}</button></div></form>}
  </section></div>;
}
