"use client";
import {useActionState,useState} from "react";
import Link from "next/link";
import {saveBusinessHours,type BusinessHoursState} from "@/app/onboarding/actions";
import {defaultBusinessHours,type DayHours} from "@/lib/onboardingHours";
const names=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
export default function OnboardingBusinessHours({businessSlug,timezone,initialHours}:{businessSlug:string;timezone:string;initialHours?:DayHours[]}){
 const [state,action,pending]=useActionState(saveBusinessHours.bind(null,businessSlug),{} as BusinessHoursState),[rows,setRows]=useState(initialHours?.length===7?initialHours:defaultBusinessHours());
 const change=(weekday:number,values:Partial<DayHours>)=>setRows(current=>current.map(row=>row.weekday===weekday?{...row,...values}:row));
 const copyWeekdays=()=>{const source=rows.find(row=>row.weekday===1)??rows[0];setRows(current=>current.map(row=>row.weekday>=1&&row.weekday<=5?{...row,open:true,start:source.start,end:source.end}:row));};
 return <div className="onboarding-frame"><aside><span className="sv-kicker">Guided setup</span><h2>Set the rhythm of your week</h2><ol>{["Welcome","Company","Business profile","Hours","First service","Ready to go"].map((label,index)=><li className={index===3?"active":index<3?"complete":""} key={label}><i>{index<3?"✓":index+1}</i><span>{label}</span></li>)}</ol><p>These hours power public availability and scheduling. You can add exceptions and technician-specific availability later.</p></aside><section className="onboarding-card"><div className="onboarding-progress" aria-label="Step 4 of 6"><span style={{width:"66.67%"}}/></div><form action={action} className="onboarding-hours-form"><header><span className="sv-kicker">Step 4 of 6</span><h1>When are you open?</h1><p>All times are displayed in <strong>{timezone}</strong>. Database timestamps remain UTC.</p></header>{state.error&&<p className="auth-error" role="alert">{state.error}</p>}<div className="hours-toolbar"><button type="button" className="sv-button sv-secondary" onClick={copyWeekdays}>Copy Monday to weekdays</button></div><div className="onboarding-hours-list">{rows.map(row=><div className={row.open?"open":"closed"} key={row.weekday}><label className="hours-day"><input type="checkbox" name={`open_${row.weekday}`} checked={row.open} onChange={event=>change(row.weekday,{open:event.target.checked})}/><strong>{names[row.weekday]}</strong><span>{row.open?"Open":"Closed"}</span></label><label>Opens<input disabled={!row.open} required={row.open} type="time" name={`start_${row.weekday}`} value={row.start} onChange={event=>change(row.weekday,{start:event.target.value})}/></label><label>Closes<input disabled={!row.open} required={row.open} type="time" name={`end_${row.weekday}`} value={row.end} onChange={event=>change(row.weekday,{end:event.target.value})}/></label>{state.dayErrors?.[row.weekday]&&<small className="field-error">{state.dayErrors[row.weekday]}</small>}</div>)}</div><div className="onboarding-actions"><Link className="sv-button sv-secondary" href="/app">Resume later</Link><button className="sv-button" disabled={pending}>{pending?"Saving hours…":"Save and continue"}</button></div></form></section></div>;
}
