import Link from "next/link";
import {completeOnboarding} from "@/app/onboarding/actions";
import {calculateReadiness,type ReadinessFacts} from "@/lib/onboardingReadiness";
import OnboardingSubscriptionBilling from "./OnboardingSubscriptionBilling";
export default function OnboardingReadinessReview({businessSlug,businessName,facts,teamStatus,error,subscriptionBillingEnabled=false,trialEndsAt,timeZone}:{businessSlug:string;businessName:string;facts:ReadinessFacts;teamStatus:string;error?:string;subscriptionBillingEnabled?:boolean;trialEndsAt?:string;timeZone:string}){
 const readiness=calculateReadiness(facts);
 return <div className="onboarding-frame"><aside><span className="sv-kicker">Guided setup</span><h2>You’re almost ready</h2><ol>{["Welcome","Company","Business profile","Hours","First service","Ready to go"].map((label,index)=><li className={index===5?"active":"complete"} key={label}><i>{index<5?"✓":6}</i><span>{label}</span></li>)}</ol><p>Employee and customer imports are the next phase, but they do not block your Pilot workspace.</p></aside><section className="onboarding-card"><div className="onboarding-progress" aria-label="Step 6 of 6"><span style={{width:"100%"}}/></div><div className="onboarding-readiness"><header><span className="sv-kicker">Step 6 of 6</span><h1>{businessName} is ready for review</h1><p>Servonas verified this checklist from the company’s saved records.</p></header>{error&&<p className="auth-error" role="alert">{error}</p>}<div className="readiness-score"><strong>{readiness.percentage}%</strong><span>{readiness.ready?"Ready for Pilot go-live":"Setup needs attention"}</span></div>
  <section><h2>Go-Live checklist</h2><div className="readiness-groups"><article><span>Company</span><strong>{facts.company?"✓":"!"} Company information</strong></article><article><span>Operations</span><strong>{facts.businessProfile?"✓":"!"} Business profile</strong><strong>{facts.businessHours?"✓":"!"} Business hours</strong></article><article><span>Services</span><strong>{facts.firstService?"✓":"!"} First service</strong></article><article><span>Access</span><strong>{facts.pilotAccess?"✓":"!"} Pilot Access Active</strong></article></div></section>
  <div className="pilot-access-card"><strong>Pilot access is active.</strong><p>No payment method is required during the Servonas pilot.</p></div>
  <section><h2>Upcoming steps</h2><div className="readiness-next"><article><strong>Team setup · {teamStatus.replaceAll("_"," ")}</strong><p>Add your workforce, review roles, and send invitations when ready.</p><Link href={`/app/${businessSlug}/team`}>Add employees →</Link><br/><Link href={`/app/${businessSlug}/team/imports`}>Import employees →</Link></article><article><strong>Customer migration</strong><p>Bring customer and service-location history into Servonas when you are ready.</p><Link href={`/app/${businessSlug}/customers`}>Continue to customers →</Link></article></div><small>These are recommended and do not block go-live.</small></section>
  {subscriptionBillingEnabled&&trialEndsAt&&<OnboardingSubscriptionBilling businessSlug={businessSlug} trialEndsAt={trialEndsAt} timeZone={timeZone}/>}
  <div className="onboarding-actions"><Link className="sv-button sv-secondary" href="/app">Resume later</Link><form action={completeOnboarding.bind(null,businessSlug)}><button className="sv-button" disabled={!readiness.ready}>{subscriptionBillingEnabled?"Skip billing for now":"Complete setup and enter Servonas"}</button></form></div></div></section></div>;
}
