"use client";
import {useActionState} from "react";
import Link from "next/link";
import {createFirstService,type FirstServiceState} from "@/app/onboarding/actions";
export default function OnboardingFirstService({businessSlug,defaults}:{businessSlug:string;defaults:{service_name?:string;duration_minutes?:number;recurring_allowed?:boolean}}){
 const [state,action,pending]=useActionState(createFirstService.bind(null,businessSlug),{} as FirstServiceState),values=state.values??{};
 return <div className="onboarding-frame"><aside><span className="sv-kicker">Guided setup</span><h2>Create something customers can book</h2><ol>{["Welcome","Company","Business profile","Hours","First service","Ready to go"].map((label,index)=><li className={index===4?"active":index<4?"complete":""} key={label}><i>{index<4?"✓":index+1}</i><span>{label}</span></li>)}</ol><p>This uses the same live service catalog as booking, jobs, estimates, and invoices.</p></aside><section className="onboarding-card"><div className="onboarding-progress" aria-label="Step 5 of 6"><span style={{width:"83.33%"}}/></div><form action={action} className="onboarding-service-form"><header><span className="sv-kicker">Step 5 of 6</span><h1>Create your first service</h1><p>We suggested a starting point from your industry profile. Everything remains editable.</p></header>{state.error&&<p className="auth-error" role="alert">{state.error}</p>}
  <label>Service name<input required name="name" maxLength={150} defaultValue={String(values.name??defaults.service_name??"Service call")}/>{state.fieldErrors?.name&&<small className="field-error">{state.fieldErrors.name}</small>}</label>
  <label className="wide">Description <small>Optional</small><textarea name="description" maxLength={2000} defaultValue={String(values.description??"")}/>{state.fieldErrors?.description&&<small className="field-error">{state.fieldErrors.description}</small>}</label>
  <label>Default duration<input required name="durationMinutes" type="number" min="15" max="1440" step="15" defaultValue={Number(values.durationMinutes??defaults.duration_minutes??60)}/>{state.fieldErrors?.durationMinutes&&<small className="field-error">{state.fieldErrors.durationMinutes}</small>}</label>
  <label>Default price <small>Optional</small><div className="onboarding-money-input"><span>$</span><input name="price" inputMode="decimal" placeholder="Quote" defaultValue={String(values.price??"")}/></div>{state.fieldErrors?.price&&<small className="field-error">{state.fieldErrors.price}</small>}</label>
  <label className="wide">Required skills <small>Optional, separated by commas</small><input name="requiredSkills" defaultValue={values.requiredSkills?.join(", ")??""} placeholder="EPA certification, Diagnostics"/>{state.fieldErrors?.requiredSkills&&<small className="field-error">{state.fieldErrors.requiredSkills}</small>}</label>
  <label className="onboarding-check"><input type="checkbox" name="recurringAllowed" defaultChecked={Boolean(values.recurringAllowed??defaults.recurring_allowed)}/><span><strong>Recurring service is available</strong><small>Customers may receive this service on a repeating schedule.</small></span></label>
  <label className="onboarding-check"><input type="checkbox" name="active" defaultChecked={values.active??true}/><span><strong>Make this service active</strong><small>It will be available to operational workflows immediately.</small></span></label>
  <div className="onboarding-actions"><Link className="sv-button sv-secondary" href="/app">Resume later</Link><button className="sv-button" disabled={pending}>{pending?"Creating service…":"Create service and review"}</button></div></form></section></div>;
}
