"use client";

import {useEffect,useMemo,useRef,useState} from "react";
import {parseGoogleAddressComponents,type GoogleAddressComponent} from "@/lib/googleAddressComponents";

type Item={id:string;name:string;category:string|null;description:string|null;daily_price_cents:number;image_url:string|null;allow_quantity:boolean;stock_quantity:number};
type Capacity=Record<string,Record<string,number>>;
const money=(cents:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(cents/100);
const iso=(year:number,month:number,day:number)=>`${year}-${String(month+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`;

export default function PartyRentalBookingClient({businessSlug,businessName,inventory,capacityByItem,relatedItems={},standardDurationMinutes=240,depositPercent=25,onlinePaymentsReady:stripeReady=false,googleMapsApiKey}:{businessSlug:string;businessName:string;inventory:Item[];capacityByItem:Capacity;relatedItems?:Record<string,string[]>;standardDurationMinutes?:number;depositPercent?:number;onlinePaymentsReady?:boolean;googleMapsApiKey?:string}){
 const [viewDate,setViewDate]=useState(()=>{const d=new Date();d.setDate(1);return d});
 const [date,setDate]=useState(""),[startTime,setStartTime]=useState(""),[endTime,setEndTime]=useState("");
 const [quantities,setQuantities]=useState<Record<string,number>>({}),[search,setSearch]=useState(""),[category,setCategory]=useState("All rentals"),[submitting,setSubmitting]=useState(false),[invoiceLaterConfirmation,setInvoiceLaterConfirmation]=useState<string|null>(null);
 const [upsell,setUpsell]=useState<Item|null>(null),pendingBooking=useRef<FormData|null>(null),dismissedUpsells=useRef(new Set<string>());
 const [,setAddressError]=useState("");
 const calendarRef=useRef<HTMLDivElement>(null);
 const confirmationRef=useRef<HTMLElement>(null);
 const addressRef=useRef<HTMLInputElement>(null);
 const cityRef=useRef<HTMLInputElement>(null),zipRef=useRef<HTMLInputElement>(null);
 const selected=inventory.filter(item=>(quantities[item.id]??0)>0);
 const available=(item:Item,value=date)=>value?(capacityByItem[item.id]?.[value]??item.stock_quantity):item.stock_quantity;
 const categories=useMemo(()=>["All rentals",...new Set(inventory.map(item=>item.category||"Other rentals"))],[inventory]);
 const visible=useMemo(()=>inventory.filter(item=>(category==="All rentals"||(item.category||"Other rentals")===category)&&`${item.name} ${item.description??""}`.toLowerCase().includes(search.trim().toLowerCase())),[category,inventory,search]);
 const safeDepositPercent=Math.min(100,Math.max(0,depositPercent)),onlinePaymentsReady=stripeReady&&safeDepositPercent>0;
 const total=selected.reduce((sum,item)=>sum+item.daily_price_cents*(quantities[item.id]??0),0),deposit=Math.round(total*safeDepositPercent/100);
 const year=viewDate.getFullYear(),month=viewDate.getMonth(),first=new Date(year,month,1).getDay(),count=new Date(year,month+1,0).getDate();
 const currentMonth=new Date();currentMonth.setDate(1);currentMonth.setHours(0,0,0,0);
 const pretty=date?new Date(`${date}T12:00:00`).toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric",year:"numeric"}):"";
 const timeOptions=useMemo(()=>Array.from({length:48},(_,index)=>{const minutes=index*30,hour=Math.floor(minutes/60),minute=minutes%60,value=`${String(hour).padStart(2,"0")}:${String(minute).padStart(2,"0")}`,label=`${hour%12||12}:${String(minute).padStart(2,"0")} ${hour>=12?"PM":"AM"}`;return {value,label};}),[]);
 useEffect(()=>{const listener=(event:MessageEvent)=>{if(event.data?.type==="servonas:focus-calendar"){calendarRef.current?.focus({preventScroll:true});calendarRef.current?.scrollIntoView({behavior:"smooth",block:"start"});}};window.addEventListener("message",listener);return()=>window.removeEventListener("message",listener)},[]);
 useEffect(()=>{if(!invoiceLaterConfirmation)return;const frame=requestAnimationFrame(()=>{confirmationRef.current?.focus({preventScroll:true});confirmationRef.current?.scrollIntoView({behavior:"smooth",block:"center"});if(window.parent!==window)window.parent.postMessage({type:"servonas:booking-confirmed"},"*");});return()=>cancelAnimationFrame(frame);},[invoiceLaterConfirmation]);
 useEffect(()=>{if(!googleMapsApiKey)return;addressRef.current=document.querySelector<HTMLInputElement>('.rental-checkout input[name="address"]');cityRef.current=document.querySelector<HTMLInputElement>('.rental-checkout input[name="city"]');zipRef.current=document.querySelector<HTMLInputElement>('.rental-checkout input[name="zipCode"]');if(!addressRef.current)return;const hidden=document.createElement("input");hidden.type="hidden";hidden.name="googlePlaceId";addressRef.current.form?.appendChild(hidden);let attempts=0,timer:ReturnType<typeof setTimeout>|undefined;const clearSelection=()=>{hidden.value="";};const initialize=()=>{const places=(window as typeof window&{google?:{maps?:{places?:{Autocomplete:new(input:HTMLInputElement,options:object)=>{addListener:(name:string,callback:()=>void)=>void;getPlace:()=>{place_id?:string;formatted_address?:string;address_components?:GoogleAddressComponent[]}}}}}}).google?.maps?.places;if(!places||!addressRef.current){if(++attempts<20)timer=setTimeout(initialize,150);else setAddressError("Google address suggestions could not be loaded. Please refresh and try again.");return;}const autocomplete=new places.Autocomplete(addressRef.current,{types:["address"],fields:["place_id","formatted_address","address_components"]});setAddressError("");addressRef.current.addEventListener("input",clearSelection);autocomplete.addListener("place_changed",()=>{const place=autocomplete.getPlace();if(!place.place_id||!place.formatted_address)return;const parsed=parseGoogleAddressComponents(place.address_components,place.formatted_address);hidden.value=place.place_id;if(addressRef.current)addressRef.current.value=parsed.streetAddress||place.formatted_address;if(cityRef.current)cityRef.current.value=parsed.city;if(zipRef.current)zipRef.current.value=parsed.postalCode;setAddressError("");});};if((window as typeof window&{google?:{maps?:{places?:unknown}}}).google?.maps?.places)initialize();else{const existing=document.querySelector<HTMLScriptElement>('script[data-servonas-google-places="true"]');if(existing)existing.addEventListener("load",initialize,{once:true});else{const script=document.createElement("script");script.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(googleMapsApiKey)}&libraries=places`;script.async=true;script.defer=true;script.dataset.servonasGooglePlaces="true";script.addEventListener("load",initialize,{once:true});script.addEventListener("error",()=>setAddressError("Google address suggestions could not be loaded. Please refresh and try again."),{once:true});document.head.appendChild(script);}}return()=>{hidden.remove();addressRef.current?.removeEventListener("input",clearSelection);if(timer)clearTimeout(timer);};},[googleMapsApiKey]);
 function chooseStart(value:string){setStartTime(value);if(!value){setEndTime("");return;}const [hour,minute]=value.split(":").map(Number),end=Math.min(hour*60+minute+standardDurationMinutes,23*60+30);setEndTime(`${String(Math.floor(end/60)).padStart(2,"0")}:${String(end%60).padStart(2,"0")}`);}
 function setQuantity(item:Item,value:number){const max=item.allow_quantity?available(item):1;setQuantities(current=>({...current,[item.id]:Math.max(0,Math.min(value,max))}));}
 function chooseDate(value:string){setDate(value);setQuantities(current=>{const next:Record<string,number>={};for(const [id,qty] of Object.entries(current)){const item=inventory.find(row=>row.id===id);if(!item)continue;const safe=Math.min(qty,available(item,value));if(safe>0)next[id]=safe;}return next;});}
 async function completeBooking(data:FormData){if(!date||!startTime||!endTime)return alert("Choose the rental date and event time first.");if(!selected.length)return alert("Add at least one rental to your cart.");setSubmitting(true);try{const response=await fetch("/api/checkout",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...Object.fromEntries(data),businessSlug,rentalDate:date,startTime,endTime,items:selected.map(item=>({inventoryItemId:item.id,quantity:quantities[item.id]}))})});const result=await response.json();if(!response.ok)throw new Error(result.error||"The reservation could not be started.");if(result.paymentMode==="invoice_later"){setInvoiceLaterConfirmation(result.bookingNumber);setSubmitting(false);return;}if(window.top&&window.top!==window)window.top.location.assign(result.url);else window.location.assign(result.url)}catch(error){alert(error instanceof Error?error.message:"The reservation could not be started.");setSubmitting(false)}}
 function submit(data:FormData){const selectedIds=new Set(selected.map(item=>item.id));const suggestion=selected.flatMap(item=>relatedItems[item.id]??[]).map(id=>inventory.find(item=>item.id===id)).find((item):item is Item=>Boolean(item&&!selectedIds.has(item.id)&&!dismissedUpsells.current.has(item.id)&&available(item)>0));if(!suggestion)return completeBooking(data);pendingBooking.current=data;setUpsell(suggestion);}
 if(invoiceLaterConfirmation)return <section ref={confirmationRef} className="form-card rental-checkout booking-success" role="status" tabIndex={-1} aria-labelledby="rental-confirmation-title"><div className="success-check" aria-hidden="true">✓</div><small>Confirmation #{invoiceLaterConfirmation}</small><h2 id="rental-confirmation-title">Your reservation is confirmed</h2><p>{businessName} will send an invoice separately. No online payment was required to complete this booking.</p></section>;
 return <div className="party-rental-booking">
  {upsell&&<div className="rental-upsell-backdrop" role="presentation"><section className="rental-upsell-dialog" role="dialog" aria-modal="true" aria-labelledby="rental-upsell-title">{upsell.image_url&&<img src={upsell.image_url} alt=""/>}<span className="eyebrow">Suggested add-on</span><h2 id="rental-upsell-title">Add {upsell.name} for {money(upsell.daily_price_cents)}?</h2>{upsell.description&&<p>{upsell.description}</p>}<div><button type="button" className="button" onClick={()=>{setQuantity(upsell,1);dismissedUpsells.current.add(upsell.id);pendingBooking.current=null;setUpsell(null);}}>Add to cart</button><button type="button" className="button secondary" onClick={()=>{const data=pendingBooking.current;dismissedUpsells.current.add(upsell.id);pendingBooking.current=null;setUpsell(null);if(data)void completeBooking(data);}}>No thanks, continue booking</button></div></section></div>}
  <section className="rental-booking-step"><span className="eyebrow">Step 1 · Select date &amp; time</span><h2>When is your event?</h2><p>Choose your event date and times. We’ll only show rentals available for that date.</p>
   <div className="calendar" ref={calendarRef} tabIndex={-1}><div className="calendar-head"><button type="button" disabled={viewDate<=currentMonth} aria-label="Previous month" onClick={()=>setViewDate(new Date(year,month-1,1))}>‹</button><h3>{viewDate.toLocaleDateString("en-US",{month:"long",year:"numeric"})}</h3><button type="button" aria-label="Next month" onClick={()=>setViewDate(new Date(year,month+1,1))}>›</button></div><div className="weekdays">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(day=><span key={day}>{day}</span>)}</div><div className="days">{Array.from({length:first},(_,i)=><button className="day blank" disabled key={i}/>)}{Array.from({length:count},(_,i)=>{const day=i+1,value=iso(year,month,day),past=new Date(`${value}T23:59:59`)<new Date();return <button type="button" className={`day${past?" past":""}${date===value?" selected":""}`} disabled={past} aria-disabled={past} aria-label={`${value}${past?", unavailable because this date has passed":""}`} onClick={()=>chooseDate(value)} key={value}>{day}</button>})}</div></div>
   <div className="rental-time-row"><label>Event start time<select value={startTime} onChange={e=>chooseStart(e.target.value)} required><option value="">Choose start time</option>{timeOptions.filter((_,index)=>index*30+standardDurationMinutes<=23*60+30).map(option=><option value={option.value} key={option.value}>{option.label}</option>)}</select></label><label>Event end time<select value={endTime} onChange={e=>setEndTime(e.target.value)} required><option value="">Choose end time</option>{timeOptions.filter(option=>!startTime||option.value>startTime).map(option=><option value={option.value} key={option.value}>{option.label}</option>)}</select></label></div>
  </section>
  <section className={`booking-items-section ${date&&startTime&&endTime?"":"rental-step-disabled"}`}><div className="catalog-heading"><div><span className="eyebrow">Step 2 · Available rentals</span><h2>{date?`Rentals available ${pretty}`:"Choose a date and time above"}</h2><p>Add as many available items as you need.</p></div><div className="catalog-count">{selected.reduce((n,item)=>n+(quantities[item.id]??0),0)} in cart</div></div>
   <div className="rental-category-filter" aria-label="Rental categories">{categories.map(name=><button type="button" className={category===name?"active":""} aria-pressed={category===name} onClick={()=>setCategory(name)} key={name}>{name}</button>)}</div><label className="catalog-search"><span>Search rentals</span><input type="search" placeholder="Tables, chairs, bounce house…" value={search} onChange={e=>setSearch(e.target.value)}/></label>
   <div className="inventory-gallery">{visible.map(item=>{const qty=quantities[item.id]??0,max=available(item),unavailable=max===0;return <article className={`inventory-card ${qty?"selected":""} ${unavailable?"unavailable":""}`} key={item.id}><div className="inventory-media">{item.image_url?<img src={item.image_url} alt={item.name}/>:<div className="inventory-image-placeholder">Photo coming soon</div>}{unavailable&&<span className="unavailable-badge">Unavailable</span>}</div><div className="inventory-card-body"><span className="rental-card-category">{item.category||"Other rentals"}</span><div className="inventory-card-head"><h3>{item.name}</h3><strong className="catalog-price">{money(item.daily_price_cents)}{item.allow_quantity?" each":""}</strong></div>{item.description&&<p>{item.description}</p>}{item.allow_quantity?<div className="quantity-picker"><button type="button" onClick={()=>setQuantity(item,qty-1)} disabled={!qty}>−</button><div><strong>{qty}</strong><span>{max} available</span></div><button type="button" onClick={()=>setQuantity(item,qty+1)} disabled={qty>=max}>+</button></div>:<button type="button" className={`catalog-add-button ${qty?"selected":""}`} disabled={unavailable} onClick={()=>setQuantity(item,qty?0:1)}>{qty?"✓ Added to cart":"Add to cart"}</button>}</div></article>})}{!visible.length&&<div className="empty-catalog"><h3>No rentals in this category</h3><p>Choose another category or clear your search.</p></div>}</div>
  </section>
  <form action={submit} className="form-card rental-checkout"><span className="eyebrow">Step 3 · Book</span><h2>Complete your reservation</h2><div className="selected-summary">{selected.map(item=><div className="summary-line" key={item.id}><span>{item.name} × {quantities[item.id]}</span><strong>{money(item.daily_price_cents*quantities[item.id])}</strong></div>)}<div className="summary-total"><span>Rental total</span><strong>{money(total)}</strong></div>{onlinePaymentsReady?<div className="summary-line"><span>{safeDepositPercent}% deposit due now</span><strong>{money(deposit)}</strong></div>:<div className="summary-line"><span>Payment</span><strong>Invoice will be sent later</strong></div>}</div><div className="form-grid"><label>First name<input name="firstName" required/></label><label>Last name<input name="lastName" required/></label><label>Email<input name="email" type="email" required/></label><label>Phone<input name="phone" type="tel" required/></label></div><label>Delivery address<input name="address" required/></label><div className="form-grid"><label>City<input name="city" required/></label><label>ZIP code<input name="zipCode" required/></label></div><label>Event notes<textarea name="notes" rows={3}/></label><label><span><input className="inline-checkbox" type="checkbox" name="agreementAccepted" value="true" required/> I agree to the rental agreement and safety rules.</span></label>{onlinePaymentsReady&&<label><span><input className="inline-checkbox" type="checkbox" name="depositAccepted" value="true" required/> I understand the deposit policy.</span></label>}<button className="button" disabled={submitting||!date||!startTime||!endTime||!selected.length}>{submitting?(onlinePaymentsReady?"Opening secure checkout…":"Booking…"):(onlinePaymentsReady?`Book and pay ${money(deposit)} deposit`:"Book now · Invoice later")}</button><small>{onlinePaymentsReady?`Your reservation is securely processed for ${businessName} through Servonas.`:`Your booking will be completed now and ${businessName} will send the invoice later.`}</small></form>
 </div>
}
