import {poolChemistryFields} from "@/lib/poolService";
type Log=Record<string,unknown>|null;
export function PoolVisitForm({log,enabledFields,chemicals,checklist,completedTasks,chemicalRows,action}:{log:Log;enabledFields:string[];chemicals:{id:string;name:string;default_unit:string|null}[];checklist:{id:string;label:string}[];completedTasks:Set<string>;chemicalRows:{chemical_name:string;amount:number;unit:string;estimated_cost_cents:number|null}[];action:(data:FormData)=>void|Promise<void>}){
 return <section className="tech-section pool-visit"><span className="sv-kicker">Pool Service</span><h2>Chemistry &amp; service log</h2><p>Record what you measured and completed. Readings are optional; save a draft anytime.</p><form action={action} className="pool-visit-form">
  <details open><summary>Water chemistry</summary><div className="pool-reading-grid">{poolChemistryFields.filter(([key])=>enabledFields.includes(key)).map(([key,label])=><label key={key}>{label}<input inputMode="decimal" name={key} type="number" step="any" defaultValue={String(log?.[key]??"")}/></label>)}</div><label>Visit notes<textarea name="notes" rows={3} maxLength={4000} defaultValue={String(log?.notes??"")}/></label></details>
  <details open><summary>Service checklist</summary><div className="pool-visit-checklist">{checklist.map(item=><label key={item.id}><input name="completedTask" value={item.id.startsWith("default-")?`label:${item.label}`:item.id} type="checkbox" defaultChecked={completedTasks.has(item.id)}/><span>{item.label}</span></label>)}</div></details>
  <details><summary>Chemicals added</summary><div className="pool-chemical-entry">{Array.from({length:Math.max(3,chemicalRows.length)},(_,index)=>{const row=chemicalRows[index],matched=chemicals.find(item=>item.name===row?.chemical_name);return <fieldset key={index}><label>Chemical<select name="chemicalId" defaultValue={row?(matched?(matched.id.startsWith("default-")?`name:${matched.name}`:matched.id):"custom"):""}><option value="">None</option>{chemicals.map(item=><option key={item.id} value={item.id.startsWith("default-")?`name:${item.name}`:item.id}>{item.name}</option>)}<option value="custom">Other/custom</option></select></label><label>Custom name<input name="chemicalCustom" defaultValue={row&&!matched?row.chemical_name:""}/></label><label>Amount<input inputMode="decimal" name="chemicalAmount" type="number" min="0" step="any" defaultValue={row?.amount??""}/></label><label>Unit<input name="chemicalUnit" placeholder="oz, lb, gal" defaultValue={row?.unit??""}/></label><label>Est. cost ($)<input inputMode="decimal" name="chemicalCost" type="number" min="0" step=".01" defaultValue={row?.estimated_cost_cents!=null?(row.estimated_cost_cents/100).toFixed(2):""}/></label></fieldset>})}</div></details>
  <div className="pool-visit-actions"><button className="sv-button sv-secondary" name="submission" value="draft">Save draft</button><button className="sv-button" name="submission" value="completed">Complete service log</button></div>
 </form></section>;
}
