import {poolChemistryFields} from "@/lib/poolService";
type Settings={enabled_chemistry_fields:string[];weather_alerts_enabled:boolean;wind_threshold_mph:number;rain_threshold_inches:number;heat_threshold_f:number;freeze_threshold_f:number}|null;
type Range={field_key:string;minimum_value:number|null;maximum_value:number|null;consecutive_visits:number};
export function PoolServiceSettings({settings,ranges,chemicals,checklist,action}:{settings:Settings;ranges:Range[];chemicals:string[];checklist:string[];action:(data:FormData)=>void|Promise<void>}){
 const enabled=new Set(settings?.enabled_chemistry_fields??poolChemistryFields.map(([key])=>key)),range=new Map(ranges.map(item=>[item.field_key,item]));
 return <section className="settings-summary-card pool-settings" id="pool-service-settings"><header className="settings-section-header"><div><span>Pool Service</span><h2>Pool chemistry &amp; weather</h2><p>Choose the readings, visit tasks, chemicals, acceptable ranges, and weather conditions used by your pool team.</p></div><span className="customer-record-status active">Pool only</span></header><form action={action} className="pool-settings-form">
  <fieldset><legend>Chemistry readings</legend><p>Technicians can leave any enabled reading blank.</p><div className="pool-setting-checks">{poolChemistryFields.map(([key,label])=><label key={key}><input type="checkbox" name="chemistryFields" value={key} defaultChecked={enabled.has(key)}/><span>{label}</span></label>)}</div></fieldset>
  <fieldset><legend>Acceptable ranges</legend><p>Consecutive out-of-range readings create Pool Health alerts.</p><div className="pool-range-grid">{poolChemistryFields.map(([key,label])=>{const value=range.get(key);return <div key={key}><strong>{label}</strong><label>Minimum<input name={`${key}Min`} type="number" step="any" defaultValue={value?.minimum_value??""}/></label><label>Maximum<input name={`${key}Max`} type="number" step="any" defaultValue={value?.maximum_value??""}/></label><label>Visits<input name={`${key}Visits`} type="number" min="1" max="10" defaultValue={value?.consecutive_visits??2}/></label></div>})}</div></fieldset>
  <div className="pool-settings-columns"><label>Chemical list <small>One per line</small><textarea name="chemicals" rows={10} defaultValue={chemicals.join("\n")}/></label><label>Service checklist <small>One task per line</small><textarea name="checklist" rows={10} defaultValue={checklist.join("\n")}/></label></div>
  <fieldset><legend>Weather Service Alerts</legend><label className="settings-check"><input name="weatherEnabled" type="checkbox" defaultChecked={settings?.weather_alerts_enabled}/>Enable weather-aware scheduling alerts</label><div className="pool-weather-rules"><label>Wind exceeds (mph)<input name="windThreshold" type="number" min="0" step=".1" defaultValue={settings?.wind_threshold_mph??30}/></label><label>Rainfall exceeds (inches)<input name="rainThreshold" type="number" min="0" step=".1" defaultValue={settings?.rain_threshold_inches??1}/></label><label>Temperature exceeds (°F)<input name="heatThreshold" type="number" step=".1" defaultValue={settings?.heat_threshold_f??110}/></label><label>Temperature falls below (°F)<input name="freezeThreshold" type="number" step=".1" defaultValue={settings?.freeze_threshold_f??32}/></label></div><p>Weather alerts require approval before jobs move. A one-time move never changes the recurring pattern.</p></fieldset>
  <button className="sv-button">Save Pool Service settings</button>
 </form></section>;
}
