import {formatBusinessDate} from "@/lib/bookingTime";
import {chemicalCostSpike,poolChemistryFields,poolHealthAlerts,poolTrend,steadilyDecreasing} from "@/lib/poolService";
type Log=Record<string,unknown>&{id:string;job_id:string;completed_at:string|null;notes:string|null;employees?:{preferred_name:string}|{preferred_name:string}[]|null};
type Chemical={pool_service_log_id:string;chemical_name:string;amount:number;unit:string;estimated_cost_cents:number|null};
type Task={pool_service_log_id:string;task_label:string;completed:boolean};
type Photo={job_id:string;url:string|null;photo_type:string;caption:string|null};
type Range={field_key:string;minimum_value:number|null;maximum_value:number|null;consecutive_visits:number};
const relation=<T,>(value:T|T[]|null|undefined)=>Array.isArray(value)?value[0]??null:value??null;
export function PoolServiceHistory({logs,chemicals,tasks,photos,ranges,timezone}:{logs:Log[];chemicals:Chemical[];tasks:Task[];photos:Photo[];ranges:Range[];timezone:string}){
 const completed=logs.filter(log=>log.status==="completed"),alerts=poolHealthAlerts(completed as Parameters<typeof poolHealthAlerts>[0],ranges),monthlyCost=chemicals.reduce((sum,item)=>sum+Number(item.estimated_cost_cents??0),0)/Math.max(1,new Set(completed.map(log=>log.completed_at?.slice(0,7)).filter(Boolean)).size),visitCost=(logId:string)=>chemicals.filter(item=>item.pool_service_log_id===logId).reduce((sum,item)=>sum+Number(item.estimated_cost_cents??0),0),saltDeclining=steadilyDecreasing(completed.map(log=>log.salt_ppm==null?null:Number(log.salt_ppm))),costSpike=completed.length>3&&chemicalCostSpike(visitCost(completed[0].id),completed.slice(1,6).map(log=>visitCost(log.id)));
 return <section className="workspace-panel pool-history" id="pool-history"><div className="panel-title"><div><span className="sv-kicker">Pool Service</span><h2>Pool History</h2><p>{completed.length} completed visits · Estimated monthly chemical cost ${(monthlyCost/100).toFixed(2)}</p></div></div>
  {(alerts.length>0||saltDeclining||costSpike)&&<div className="pool-health-alerts"><strong>Pool Health alerts</strong>{alerts.map(alert=><p key={`${alert.field}-${alert.direction}`}>{poolChemistryFields.find(([key])=>key===alert.field)?.[1]??alert.field} has been {alert.direction} for {alert.visits} consecutive visits.</p>)}{saltDeclining&&<p>Salt has steadily decreased across the last three visits.</p>}{costSpike&&<p>Chemical cost for the latest visit is more than 50% above the recent average.</p>}</div>}
  {completed.length?<div className="pool-history-list">{completed.map((log,index)=>{const prior=completed[index+1],logChemicals=chemicals.filter(item=>item.pool_service_log_id===log.id),logTasks=tasks.filter(item=>item.pool_service_log_id===log.id&&item.completed),logPhotos=photos.filter(item=>item.job_id===log.job_id);return <details key={log.id} open={index===0}><summary><span>{formatBusinessDate(log.completed_at!,timezone)}</span><strong>{relation(log.employees)?.preferred_name??"Technician"}</strong><small>{logChemicals.length} chemicals · {logTasks.length} tasks · {logPhotos.length} photos</small></summary><div className="pool-history-reading-grid">{poolChemistryFields.flatMap(([key,label])=>{const value=log[key],trend=poolTrend(value==null?null:Number(value),prior?.[key]==null?null:Number(prior[key]));return value==null?[]:[<div key={key}><span>{label}</span><strong>{String(value)} {trend==="up"?"↑":trend==="down"?"↓":"→"}</strong></div>]})}</div>{logChemicals.length>0&&<div><h3>Chemicals added</h3><ul>{logChemicals.map((item,i)=><li key={i}>{item.chemical_name}: {item.amount} {item.unit}{item.estimated_cost_cents!=null?` · $${(item.estimated_cost_cents/100).toFixed(2)}`:""}</li>)}</ul></div>}{logTasks.length>0&&<div><h3>Checklist completed</h3><p>{logTasks.map(item=>item.task_label).join(" · ")}</p></div>}{logPhotos.length>0&&<div className="pool-history-photos">{logPhotos.map((photo,i)=>photo.url&&<a key={i} href={photo.url} target="_blank" rel="noreferrer"><img src={photo.url} alt={photo.caption??`${photo.photo_type} pool service photo`}/></a>)}</div>}{log.notes&&<div><h3>Notes</h3><p>{log.notes}</p></div>}</details>})}</div>:<div className="dashboard-empty"><strong>No pool service history yet</strong><p>Completed technician pool logs will appear here.</p></div>}
 </section>;
}
