import Link from "next/link";
import {promotionStatus} from "@/lib/promotions";
const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(value/100);
export function PromotionLanding({promotion,business,items,baseBookingUrl,websiteUrl}:{promotion:any;business:any;items:any[];baseBookingUrl:string;websiteUrl:string}){
 const status=promotionStatus({...promotion,...promotion.discounts},Number(promotion.redemption_count??0)),sold=status==="sold_out"||status==="expired",discount=promotion.discounts;
 const offer=discount.discount_type==="percentage"?`${discount.discount_value/100}% off`:money(discount.discount_value)+" off",remaining=discount.usage_limit==null?null:Math.max(0,Number(discount.usage_limit)-Number(promotion.redemption_count??0));
 const returnTo=`${websiteUrl.replace(/\/$/,"")}/${promotion.slug}`;
 const url=`${baseBookingUrl}?promotion=${encodeURIComponent(discount.code)}&promotionId=${encodeURIComponent(promotion.id)}&returnTo=${encodeURIComponent(returnTo)}`;
 const discountedPrice=(price:number)=>discount.discount_type==="percentage"?Math.max(0,Math.round(price*(1-discount.discount_value/10_000))):Math.max(0,price-discount.discount_value);
 return <main className="promotion-landing" style={{"--promotion-brand":business.primaryColor??business.primary_color??"#e8ab29"} as React.CSSProperties}>
  <header className="promotion-landing-header"><Link href={websiteUrl} className="promotion-brand" aria-label={`${business.name} main website`}>{business.logoUrl?<img src={business.logoUrl} alt={`${business.name} logo`}/>:<i>{business.name.slice(0,1)}</i>}<strong>{business.name}</strong></Link><a className="promotion-website-link" href={websiteUrl}>View full website</a></header>
  <section className="promotion-hero"><div><small>Limited-time offer</small><h1>{sold?"This offer has ended.":promotion.headline}</h1>{!sold&&remaining!=null&&<strong className="promotion-remaining">Only {remaining} discounted booking{remaining===1?"":"s"} available</strong>}<p>{sold?"View the full website to browse current rental options.":"Choose your event date and we’ll show you which eligible rentals are available."}</p>{!sold&&<Link className="promotion-primary-cta" href={url} data-promotion-event="promotion_primary_cta_clicked">Claim {offer} — Check My Date</Link>}<div className="promotion-trust" aria-label="Why book with this business"><span>Local rental company</span><span>Delivery options shown at checkout</span><span>Secure online booking</span></div></div></section>
  {!sold&&<section className="promotion-rentals" id="eligible-rentals"><header><div><small>Eligible rentals</small><h2>Included in this offer</h2></div><b>{offer}</b></header><div className="promotion-rental-grid">{items.map(item=>{const now=discountedPrice(Number(item.daily_price_cents));return <article className="promotion-rental-card" key={item.id}><div className="promotion-rental-image">{item.image_url?<img src={item.image_url} alt={item.name}/>:<span>{item.name.slice(0,1)}</span>}</div><div><small><b>{offer}</b></small><h3>{item.name}</h3><p className="promotion-price"><del>{money(item.daily_price_cents)}</del><strong>{money(now)}</strong><span> per day</span></p><Link href={`${url}&item=${item.id}`} data-promotion-event="promotion_item_selected" data-inventory-item-id={item.id}>See If It’s Available</Link></div></article>})}</div>{!items.length&&<p className="promotion-empty">No rentals are currently eligible for this offer.</p>}</section>}
  <details className="promotion-details"><summary>Offer details</summary><p>{promotion.terms||"Discount applies only to eligible rentals. Taxes, delivery, setup, and unrelated add-ons are excluded unless stated otherwise."}</p>{promotion.status==="active"&&remaining!=null&&<p><b>{remaining}</b> promotional spots remaining.</p>}</details>
 </main>;
}
