import {calculateDiscount} from "@/lib/discounts";
import {discountTierLabel,type DiscountTier} from "@/lib/discountTiers";
import Link from "next/link";
import {promotionStatus} from "@/lib/promotions";
import {PromotionStickyCta} from "@/components/PromotionStickyCta";
const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(value/100);
export function PromotionLanding({promotion,business,items,baseBookingUrl,websiteUrl}:{promotion:any;business:any;items:any[];baseBookingUrl:string;websiteUrl:string}){
 const status=promotionStatus({...promotion,...promotion.discounts},Number(promotion.redemption_count??0)),sold=status==="sold_out"||status==="expired",discount=promotion.discounts;
 const offer=discount.tiers?.length?discount.tiers.map((tier:DiscountTier)=>discountTierLabel(tier)).join(" · "):discount.discount_type==="percentage"?`${discount.discount_value/100}% off`:money(discount.discount_value)+" off",remaining=discount.usage_limit==null?null:Math.max(0,Number(discount.usage_limit)-Number(promotion.redemption_count??0));
 const returnTo=`${websiteUrl.replace(/\/$/,"")}/${promotion.slug}`;
 const url=`${baseBookingUrl}?promotion=${encodeURIComponent(discount.code)}&promotionId=${encodeURIComponent(promotion.id)}&returnTo=${encodeURIComponent(returnTo)}`;
 const discountedPrice=(price:number)=>{const result=calculateDiscount({...discount,applies_to:"order"},[{id:"preview",quantity:1,unitPriceCents:price}],new Set());return result.ok?result.totalCents:price;};
 const isCopperStateCampaign=promotion.slug==="fall-party-special";
 const offerLabel=isCopperStateCampaign?"$50 off rentals $175+ · $75 off rentals $300+":offer;
 const isAddon=(item:any)=>/(chair|table|cord|extension|speaker|cooler|concession|generator|light|add-on|addon)/i.test(`${item.name??""} ${item.category??""}`);
 const popularItems=isCopperStateCampaign?items.filter((item)=>!isAddon(item)).slice(0,6):items;
 const addonItems=isCopperStateCampaign?items.filter(isAddon):[];
 return <main className="promotion-landing" style={{"--promotion-brand":business.primaryColor??business.primary_color??"#e8ab29"} as React.CSSProperties}>
  <header className="promotion-landing-header"><Link href={websiteUrl} className="promotion-brand" aria-label={`${business.name} main website`}>{business.logoUrl?<img src={business.logoUrl} alt={`${business.name} logo`}/>:<i>{business.name.slice(0,1)}</i>}<strong>{business.name}</strong></Link><a className="promotion-website-link" href={websiteUrl}>View full website</a></header>
  <section className={`promotion-hero${isCopperStateCampaign?" promotion-hero-copper-state":""}`}><div><small>{isCopperStateCampaign?"Copper State Bounce special":"Limited-time offer"}</small><h1>{sold?"This offer has ended.":isCopperStateCampaign?"Save Up to $75 on Your Party Rental 🎉":promotion.headline}</h1>{!sold&&isCopperStateCampaign?<><p className="promotion-offer-line">{offerLabel}</p><strong className="promotion-book-by">Book by Sept. 30 — your event can be later.</strong></>:null}{!sold&&!isCopperStateCampaign&&remaining!=null&&<strong className="promotion-remaining">Only {remaining} discounted booking{remaining===1?"":"s"} available</strong>}<p>{sold?"View the full website to browse current rental options.":isCopperStateCampaign?"Pick your date and see what’s available.":"Choose your event date and we’ll show you which eligible rentals are available."}</p>{!sold&&items.length>0&&<Link className="promotion-primary-cta" href={url} data-promotion-event="promotion_primary_cta_clicked">{isCopperStateCampaign?"Check My Date":/* Claim {offer} — Check My Date */`Claim ${offer} — Check My Date`}</Link>}{!sold&&!items.length&&<p role="status">This offer is temporarily unavailable. <Link href={websiteUrl}>Browse our website for current rentals.</Link></p>}<div className="promotion-trust" aria-label="Why book with this business">{isCopperStateCampaign?<><span>Local East Valley rental company</span><span>Secure online booking</span><span>Delivery available</span></>:<><span>Local rental company</span><span>Delivery options shown at checkout</span><span>Secure online booking</span></>}</div></div></section>
  {!sold&&<section className="promotion-rentals" id="eligible-rentals"><header><div><small>{isCopperStateCampaign?"Popular rentals":"Eligible rentals"}</small><h2>{isCopperStateCampaign?"Popular Rentals":"Included in this offer"}</h2></div><b>{isCopperStateCampaign?offerLabel:offer}</b></header><div className="promotion-rental-grid">{popularItems.map(item=>{const now=discountedPrice(Number(item.daily_price_cents));const qualifies=Number(item.daily_price_cents)>=17500;return <article className="promotion-rental-card" key={item.id}><div className="promotion-rental-image">{item.image_url?<img src={item.image_url} alt={item.name}/>:<span>{item.name.slice(0,1)}</span>}</div><div><small>{qualifies&&<b>{offer}</b>}</small><h3>{item.name}</h3><p className="promotion-price">{now<Number(item.daily_price_cents)&&<del>{money(item.daily_price_cents)}</del>}<strong>{money(now)}</strong><span> per day</span></p><Link href={`${url}&item=${item.id}`} data-promotion-event="promotion_item_selected" data-inventory-item-id={item.id}>Check Availability</Link></div></article>})}</div>{isCopperStateCampaign&&items.length>popularItems.length&&<Link className="promotion-see-all" href={url} data-booking-cta="true">See All Rentals</Link>}{isCopperStateCampaign&&addonItems.length>0&&<><h3 className="promotion-addon-heading">Party Add-ons</h3><div className="promotion-rental-grid promotion-addon-grid">{addonItems.map(item=><article className="promotion-rental-card" key={item.id}><div className="promotion-rental-image">{item.image_url?<img src={item.image_url} alt={item.name}/>:<span>{item.name.slice(0,1)}</span>}</div><div><small></small><h3>{item.name}</h3><p className="promotion-price"><strong>{money(Number(item.daily_price_cents))}</strong><span> per day</span></p><Link href={`${url}&item=${item.id}`} data-promotion-event="promotion_item_selected" data-inventory-item-id={item.id}>Check Availability</Link></div></article>)}</div></>}{!items.length&&<p className="promotion-empty">No rentals are currently eligible for this offer.</p>}</section>}
  {isCopperStateCampaign&&!sold&&<PromotionStickyCta href={url}/>}
  <details className="promotion-details"><summary>Offer details</summary><p>{promotion.terms||"Discount applies only to eligible rentals. Taxes, delivery, setup, and unrelated add-ons are excluded unless stated otherwise."}</p>{promotion.status==="active"&&remaining!=null&&<p><b>{remaining}</b> promotional spots remaining.</p>}</details>
 </main>;
}
