"use client";

import {useState, useTransition} from "react";
import {useRouter} from "next/navigation";
import {cancelReconciliationBooking,documentReconciliationException} from "@/app/app/[businessSlug]/financials/reconciliation/actions";
import {cancellationReasons} from "@/lib/financial/reconciliationResolution";

type History={id:string;action:string;reason:string;note:string|null;created_at:string};
export function ReconciliationResolution({slug,bookingId,invoiceId,differenceCents,issues,history}:{slug:string;bookingId:string;invoiceId?:string|null;differenceCents:number;issues:string[];history:History[]}){
 const [open,setOpen]=useState(false),[pending,startTransition]=useTransition(),[error,setError]=useState(""); const router=useRouter();
 const close=()=>{if(!pending)setOpen(false);};
 const cancel=(isTest:boolean,form:FormData)=>startTransition(async()=>{setError("");const result=await cancelReconciliationBooking(slug,{bookingId,reason:String(form.get("reason")||""),note:String(form.get("note")||""),issueType:issues.join(","),isTest});if(!result.ok){setError(result.error??"Unable to complete this action.");return;}close();router.refresh();});
 const document=(form:FormData)=>startTransition(async()=>{setError("");const result=await documentReconciliationException(slug,{bookingId,invoiceId,differenceCents,issueType:issues.join(","),reason:String(form.get("exceptionReason")||""),note:String(form.get("exceptionNote")||"")});if(!result.ok){setError(result.error??"Unable to complete this action.");return;}router.refresh();});
 return <><button type="button" className="text-button" onClick={()=>setOpen(true)}>Resolve</button>{open&&<div className="reconciliation-resolution-backdrop" role="presentation" onMouseDown={close}><section className="reconciliation-resolution" role="dialog" aria-modal="true" aria-label="Resolve reconciliation issue" onMouseDown={event=>event.stopPropagation()}><header><div><h2>Resolve reconciliation issue</h2><p>{issues.length?issues.join(" · "):"Review this booking before taking action."}</p></div><button type="button" aria-label="Close" onClick={close}>×</button></header>{error&&<p className="workspace-notice error">{error}</p>}<details open><summary>Cancel booking</summary><p>Removes only the unpaid future balance. Existing successful payments and refunds remain in history.</p><form action={form=>cancel(false,form)}><label>Reason<select name="reason" defaultValue="customer_canceled">{cancellationReasons.map(reason=><option key={reason} value={reason}>{reason.replaceAll("_"," ")}</option>)}</select></label><label>Note <textarea name="note" maxLength={2000}/></label><button className="sv-button sv-danger" disabled={pending}>Cancel booking</button></form></details><details><summary>Cancel as test booking</summary><p>Marks this historical booking as a test and removes its unpaid future balance.</p><form action={form=>cancel(true,form)}><input type="hidden" name="reason" value="test_booking"/><label>Note <textarea name="note" maxLength={2000}/></label><button className="sv-button sv-danger" disabled={pending}>Cancel as test</button></form></details>{invoiceId&&<details><summary>Invoice and manual payment</summary><p>Use the existing invoice lifecycle for these actions so its ledger and communication rules remain authoritative.</p><a className="sv-button sv-secondary" href={`/app/${slug}/invoices/${invoiceId}`}>Open invoice</a></details>}<details><summary>Document exception</summary><p>This records the explanation and leaves all financial values unchanged.</p><form action={document}><label>Reason <input required name="exceptionReason" maxLength={500}/></label><label>Note <textarea required name="exceptionNote" maxLength={4000}/></label><button className="sv-button" disabled={pending}>Document exception</button></form></details><details><summary>Stripe repair</summary><p>Stripe repair service not yet enabled. Stripe payments can only be applied by the existing idempotent webhook path.</p></details>{history.length>0&&<section className="reconciliation-resolution-history"><h3>Resolution history</h3>{history.map(item=><p key={item.id}><strong>{item.action.replaceAll("_"," ")}</strong> · {item.reason}<small>{new Date(item.created_at).toLocaleString()}{item.note?` · ${item.note}`:""}</small></p>)}</section>}</section></div>}</>;
}
