"use client";
import {useEffect,useRef,useState} from "react";
import {createPortal} from "react-dom";
import {useRouter} from "next/navigation";
import {rentalMoney as money,rentalPriceLabel,type RentalPriceDisplay} from "@/lib/rentalPriceDisplay";
type Rule={id:string;rule_type:"day_of_week"|"date_range"|"specific_date";name:string|null;day_of_week:number|null;start_date:string|null;end_date:string|null;fixed_price_cents:number;active:boolean;updated_at?:string};
const days=[[1,"Monday"],[2,"Tuesday"],[3,"Wednesday"],[4,"Thursday"],[5,"Friday"],[6,"Saturday"],[0,"Sunday"]] as const;
const friendlyDate=(date:string)=>new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(`${date}T12:00:00Z`));
export function RentalDatePricingEditor({slug,itemId}:{slug:string;itemId:string}){
 const [open,setOpen]=useState(false);
 return <details className="date-pricing-editor" onToggle={e=>setOpen(e.currentTarget.open)}><summary>Custom date pricing &amp; price preview</summary>{open&&<PricingPanel slug={slug} itemId={itemId}/>}</details>;
}
function PricingPanel({slug,itemId}:{slug:string;itemId:string}){
 const url=`/api/rental-pricing/${encodeURIComponent(slug)}/${encodeURIComponent(itemId)}`,router=useRouter();
 const [rules,setRules]=useState<Rule[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const [draft,setDraft]=useState<Partial<Rule>|null>(null),[modalError,setModalError]=useState("");
 const dialog=useRef<HTMLDialogElement>(null),opener=useRef<HTMLElement|null>(null);
 const [date,setDate]=useState(""),[endDate,setEndDate]=useState(""),[preview,setPreview]=useState<RentalPriceDisplay|null>(null),[previewError,setPreviewError]=useState(""),[previewLoading,setPreviewLoading]=useState(false),[previewAttempt,setPreviewAttempt]=useState(0);
 async function request(method="GET",body?:unknown){const response=await fetch(url,{method,cache:"no-store",...(body?{headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Pricing could not be loaded.");return data;}
 async function load(){setLoading(true);setError("");try{setRules(await request());}catch(e){setError(e instanceof Error?e.message:"Could not load pricing.");}finally{setLoading(false);}}
 useEffect(()=>{let alive=true;fetch(url,{cache:"no-store"}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error||"Could not load pricing.");if(alive)setRules(data);}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[url]);
 useEffect(()=>{if(draft){dialog.current?.showModal();}else opener.current?.focus();},[draft]);
 useEffect(()=>{
  setPreview(null);setPreviewError("");if(!date){setPreviewLoading(false);return;}
  const controller=new AbortController();setPreviewLoading(true);
  fetch(`${url}?${new URLSearchParams({date,endDate:endDate||date})}`,{signal:controller.signal,cache:"no-store"}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error||"Could not preview price.");if(!controller.signal.aborted)setPreview(data);}).catch(e=>{if(!controller.signal.aborted)setPreviewError(e.message);}).finally(()=>{if(!controller.signal.aborted)setPreviewLoading(false);});
  return()=>controller.abort();
 },[date,endDate,url,previewAttempt]);
 async function mutate(method:string,body:unknown){
  setBusy(true);setError("");setNotice("");
  try{const result=await request(method,body);const id=(body as {id?:string}).id;setRules(current=>method==="DELETE"?current.filter(rule=>rule.id!==id):[...current.filter(rule=>rule.id!==result.id),result]);setNotice(method==="DELETE"?"Custom price removed. Other pricing still applies.":"Custom price saved.");setPreviewAttempt(n=>n+1);router.refresh();return true;}
  catch(e){const message=e instanceof Error?e.message:"Could not save pricing.";setError(message);setModalError(message);return false;}finally{setBusy(false);}
 }
 function edit(value:Partial<Rule>){opener.current=document.activeElement as HTMLElement;setModalError("");setDraft(value);}
 const active=rules.filter(rule=>rule.active);
 return <div className="date-pricing-panel" aria-busy={loading||busy}>
  <p>Custom prices save separately. Save changes to the standard price before previewing it.</p>
  {loading?<p role="status">Loading prices…</p>:<>
   {!active.length&&<div className="date-pricing-empty"><strong>No custom date pricing yet.</strong><p>Add weekend, seasonal, or specific-date pricing while keeping your standard price as the fallback.</p><button type="button" className="sv-button sv-secondary" onClick={()=>edit({rule_type:"date_range"})}>Add pricing rule</button></div>}
   <section><h3>Day-of-week pricing</h3><div className="date-pricing-weekdays">{days.map(([day,label])=>{const rule=active.find(row=>row.rule_type==="day_of_week"&&row.day_of_week===day);return <WeekdayRow key={`${day}:${rule?.id??""}:${rule?.updated_at??""}`} label={label} rule={rule} disabled={busy} save={(cents)=>mutate(rule?"PATCH":"POST",{...rule,rule_type:"day_of_week",day_of_week:day,fixed_price_cents:cents,active:true})} remove={()=>rule?mutate("DELETE",{id:rule.id}):Promise.resolve(true)}/>;})}</div></section>
   {(["date_range","specific_date"] as const).map(type=><section key={type}><h3>{type==="date_range"?"Special pricing":"Specific date overrides"}</h3>{type==="specific_date"&&<p>Specific-date pricing overrides weekday and special-date pricing.</p>}<div className="date-pricing-rules">{active.filter(rule=>rule.rule_type===type).map(rule=><article key={rule.id}><div><strong>{rule.name||friendlyDate(rule.start_date!)}</strong><span>{friendlyDate(rule.start_date!)}{type==="date_range"?` – ${friendlyDate(rule.end_date!)}`:""}</span><b>{money(rule.fixed_price_cents)}</b></div><div><button type="button" className="text-button" disabled={busy} onClick={()=>edit(rule)} aria-label={`Edit ${rule.name||rule.start_date}`}>Edit</button><button type="button" className="text-button danger" disabled={busy} onClick={()=>void mutate("DELETE",{id:rule.id})} aria-label={`Delete ${rule.name||rule.start_date}`}>Delete</button></div></article>)}</div><button type="button" className="sv-button sv-secondary" disabled={busy} onClick={()=>edit({rule_type:type})}>{type==="date_range"?"+ Add special pricing":"+ Add date override"}</button></section>)}
  </>}
  {error&&<div role="alert"><p>{error}</p>{!rules.length&&<button type="button" className="text-button" onClick={()=>void load()}>Retry loading prices</button>}</div>}{notice&&<p role="status">{notice}</p>}{busy&&<p role="status">Saving pricing…</p>}
  <details><summary>How pricing is chosen</summary><ol><li>Specific date price</li><li>Special date-range price</li><li>Day-of-week price</li><li>Standard price</li></ol><p>Only one date price applies. Multi-day pricing uses the starting date’s price.</p></details>
  <section><h3>Price preview</h3><div className="date-pricing-date-fields"><label>Rental date<input type="date" value={date} onChange={e=>{setDate(e.target.value);setEndDate("");}}/></label><label>Last rental day (optional)<input type="date" min={date} value={endDate} onChange={e=>setEndDate(e.target.value)}/></label></div>{previewLoading&&<p role="status">Resolving price…</p>}{previewError&&<div role="alert"><p>{previewError}</p><button type="button" className="text-button" onClick={()=>setPreviewAttempt(n=>n+1)}>Retry preview</button></div>}{preview&&<div aria-live="polite"><strong>{new Intl.DateTimeFormat("en-US",{dateStyle:"full",timeZone:"UTC"}).format(new Date(`${preview.rentalDate}T12:00:00Z`))}</strong><dl className="date-pricing-breakdown"><div><dt>Standard price</dt><dd>{money(preview.originalBasePriceCents)}</dd></div><div><dt>Applied pricing</dt><dd>{rentalPriceLabel(preview)}</dd></div><div><dt>Date-adjusted price</dt><dd>{money(preview.dateAdjustedBasePriceCents)}</dd></div>{preview.rentalDays>1&&<div><dt>Multi-day adjustment</dt><dd>+{money(preview.multiDayAdjustmentCents??0)}</dd></div>}<div><dt>Final rental price</dt><dd><strong>{money(preview.finalRentalPriceCents)}</strong></dd></div></dl></div>}</section>
  {draft&&createPortal(<dialog ref={dialog} className="date-pricing-dialog" aria-labelledby={`pricing-dialog-${itemId}`} onCancel={e=>{e.preventDefault();if(!busy)setDraft(null);}}><form onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget),start=String(form.get("start")),saved=await mutate(draft.id?"PATCH":"POST",{...draft,name:String(form.get("name"))||null,start_date:start,end_date:draft.rule_type==="specific_date"?start:String(form.get("end")),day_of_week:null,fixed_price_cents:Math.round(Number(form.get("price"))*100),active:true});if(saved)setDraft(null);}}><h2 id={`pricing-dialog-${itemId}`}>{draft.rule_type==="specific_date"?"Specific date price":"Special pricing"}</h2><label>{draft.rule_type==="specific_date"?"Label (optional)":"Name"}<input autoFocus name="name" maxLength={120} defaultValue={draft.name??""} required={draft.rule_type==="date_range"}/></label><label>{draft.rule_type==="specific_date"?"Date":"Start date"}<input name="start" type="date" required defaultValue={draft.start_date??""}/></label>{draft.rule_type==="date_range"&&<label>End date<input name="end" type="date" required defaultValue={draft.end_date??""}/></label>}<label>Price ($)<input name="price" inputMode="decimal" type="number" required min="0" step="0.01" defaultValue={draft.fixed_price_cents==null?"":draft.fixed_price_cents/100}/></label>{modalError&&<p role="alert">{modalError}</p>}<div className="date-pricing-actions"><button type="button" className="sv-button sv-secondary" disabled={busy} onClick={()=>setDraft(null)}>Cancel</button><button className="sv-button" disabled={busy}>{busy?"Saving…":"Save price"}</button></div></form></dialog>,document.body)}
 </div>;
}
function WeekdayRow({label,rule,disabled,save,remove}:{label:string;rule?:Rule;disabled:boolean;save:(cents:number)=>Promise<boolean>;remove:()=>Promise<boolean>}){
 const [custom,setCustom]=useState(Boolean(rule)),[price,setPrice]=useState(rule?String(rule.fixed_price_cents/100):""),[error,setError]=useState("");
 async function persist(){if(price===""||!Number.isFinite(Number(price))||Number(price)<0){setError("Enter a valid price.");return;}setError("");await save(Math.round(Number(price)*100));}
 return <div className="date-pricing-weekday"><strong>{label}</strong><label><span className="sr-only">{label} pricing</span><select value={custom?"custom":"standard"} disabled={disabled} onChange={async e=>{if(e.target.value==="standard"){if(await remove())setCustom(false);}else setCustom(true);}}><option value="standard">Use standard price</option><option value="custom">Custom price</option></select></label>{custom&&<><label><span>{label} price ($)</span><input type="number" min="0" step="0.01" inputMode="decimal" value={price} disabled={disabled} onChange={e=>setPrice(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void persist();}}}/></label><button type="button" className="sv-button sv-secondary" disabled={disabled} onClick={()=>void persist()}>Save {label}</button></>}{error&&<p role="alert">{error}</p>}</div>;
}
