"use client";

import {StripeTaxCodeInput} from "@/components/StripeTaxCodeInput";
import {resolveRentalStripeTaxCode} from "@/lib/stripeTaxCodes";

type Category={id:string;name:string;tax_code?:string|null};
type Item={id:string;name:string;category_id?:string|null;tax_code?:string|null};
type Action=(formData:FormData)=>void|Promise<void>;

export function RentalTaxCodeManager({categories,items,businessDefaultTaxCode,bulkAction,categoryAction}:{categories:Category[];items:Item[];businessDefaultTaxCode?:string|null;bulkAction:Action;categoryAction:Action}){
 const categoryById=new Map(categories.map(category=>[category.id,category]));
 return <details className="workspace-panel rental-category-manager"><summary><strong>Rental Stripe Tax codes</strong><span>Rental items inherit: item override → category override → business default.</span></summary><p>Set the business default in Settings → Billing → Sales tax. Delivery, fees, and discounts are configured separately and never inherit a rental code.</p><section className="rental-category-list">{categories.map(category=><article key={category.id}><form action={categoryAction}><input type="hidden" name="categoryId" value={category.id}/><strong>{category.name}</strong><StripeTaxCodeInput name="taxCode" defaultValue={category.tax_code} label="Category override" listId={`category-tax-codes-${category.id}`}/><button className="text-button">Save category override</button></form></article>)}</section><form action={bulkAction} className="rental-category-create"><h3>Bulk item override</h3><label>Apply to<select name="scope" defaultValue="all"><option value="all">All rental items</option><option value="category">All items in one category</option><option value="selected">Selected items</option></select></label><label>Category <small>Used only for the category option</small><select name="categoryId" defaultValue=""><option value="">Choose a category</option>{categories.map(category=><option value={category.id} key={category.id}>{category.name}</option>)}</select></label><StripeTaxCodeInput name="taxCode" label="Explicit item override" listId="bulk-rental-tax-codes"/><label className="wide">Selected items <small>Used only for the selected-items option</small><select name="itemIds" multiple size={Math.min(8,Math.max(3,items.length))}>{items.map(item=>{const category=categoryById.get(item.category_id??"");const effective=resolveRentalStripeTaxCode({itemTaxCode:item.tax_code,categoryTaxCode:category?.tax_code,businessDefaultTaxCode});return <option key={item.id} value={item.id}>{`${item.name} — ${effective.taxCode??"No inherited code"}`}</option>})}</select></label><button className="sv-button">Apply item override</button></form><div className="rental-category-list">{items.map(item=>{const category=categoryById.get(item.category_id??"");const effective=resolveRentalStripeTaxCode({itemTaxCode:item.tax_code,categoryTaxCode:category?.tax_code,businessDefaultTaxCode});return <p key={item.id}><strong>{item.name}</strong> · {effective.taxCode??"No Stripe Tax code configured"} <small>({effective.source??"none"})</small></p>})}</div></details>;
}
