"use client";
import {useState} from "react";
type Settings=Record<string,any>;
export function RentalProfitabilitySettings({settings,action}:{settings:Settings|null;action:(data:FormData)=>void|Promise<void>}){
 const [labor,setLabor]=useState(settings?.labor_method??""),[delivery,setDelivery]=useState(settings?.delivery_method??"");
 return <section className="workspace-panel"><header><h2>Operating cost assumptions</h2><p>Used for future completed rentals. Leave a category unconfigured when it is unknown; Servonas will show incomplete profitability instead of assuming $0.</p></header><form action={action} className="booking-settings-form"><label>Labor method<select name="laborMethod" value={labor} onChange={event=>setLabor(event.target.value)}><option value="">Not configured</option><option value="fixed">Fixed per booking</option><option value="hourly">Hourly using the job’s scheduled duration</option></select></label>{labor==="fixed"&&<label>Labor cost per booking<input required name="laborFixed" type="number" min="0" step="0.01" defaultValue={settings?.labor_fixed_cents==null?"":(Number(settings.labor_fixed_cents)/100).toFixed(2)}/></label>}{labor==="hourly"&&<label>Hourly labor cost<input required name="laborHourly" type="number" min="0" step="0.01" defaultValue={settings?.labor_hourly_cents==null?"":(Number(settings.labor_hourly_cents)/100).toFixed(2)}/></label>}
 <label>Delivery / vehicle method<select name="deliveryMethod" value={delivery} onChange={event=>setDelivery(event.target.value)}><option value="">Not configured</option><option value="fixed">Fixed per booking</option><option value="per_mile">Per delivery mile</option><option value="per_drive_hour">Per estimated drive hour</option></select></label>{delivery==="fixed"&&<label>Delivery cost per booking<input required name="deliveryFixed" type="number" min="0" step="0.01" defaultValue={settings?.delivery_fixed_cents==null?"":(Number(settings.delivery_fixed_cents)/100).toFixed(2)}/></label>}{delivery==="per_mile"&&<label>Delivery cost per mile<input required name="deliveryPerMile" type="number" min="0" step="0.01" defaultValue={settings?.delivery_per_mile_cents==null?"":(Number(settings.delivery_per_mile_cents)/100).toFixed(2)}/></label>}{delivery==="per_drive_hour"&&<label>Delivery cost per driving hour<input required name="deliveryPerDriveHour" type="number" min="0" step="0.01" defaultValue={settings?.delivery_per_drive_hour_cents==null?"":(Number(settings.delivery_per_drive_hour_cents)/100).toFixed(2)}/></label>}
 <label>Processing percentage<input required name="processingPercent" type="number" min="0" max="100" step="0.01" defaultValue={settings?.processing_percent_basis_points==null?"":(Number(settings.processing_percent_basis_points)/100).toFixed(2)} placeholder="2.90"/></label><label>Processing fixed fee<input required name="processingFixed" type="number" min="0" step="0.01" defaultValue={settings?.processing_fixed_cents==null?"":(Number(settings.processing_fixed_cents)/100).toFixed(2)} placeholder="0.30"/></label><label>Other variable cost per booking<input name="otherFixed" type="number" min="0" step="0.01" defaultValue={settings?.other_fixed_cents==null?"":(Number(settings.other_fixed_cents)/100).toFixed(2)} placeholder="Leave blank if unknown"/></label><p className="wide">Stripe fees are estimates here unless a booking has a reliably linked actual fee. Explicitly enter 0.00 only when that cost is genuinely zero.</p><button className="sv-button">Save operating cost assumptions</button></form></section>;
}
