"use client";
import {useMemo,useState} from "react";
import {ManagementDrawer} from "./ManagementDrawer";
import {CustomerActionIcon} from "./CustomerActionIcon";
import {cadenceLabel,previewOccurrences,type RecurrenceUnit} from "@/lib/servicePlanRecurrence";

type Option={id:string;name:string};
export function ServicePlanDrawer({customerName,locations,services,employees,action,menuItem=false}:{customerName:string;locations:Option[];services:Option[];employees:Option[];action:(formData:FormData)=>void|Promise<void>;menuItem?:boolean}){
 const [open,setOpen]=useState(false),[initial,setInitial]=useState(false),[unit,setUnit]=useState<RecurrenceUnit>("month"),[interval,setInterval]=useState(1),[first,setFirst]=useState("");
 const preview=useMemo(()=>first?previewOccurrences(first,interval,unit,4):[],[first,interval,unit]);
 const preset=(value:string)=>{const [amount,nextUnit]=value.split(":");setInterval(Number(amount));setUnit(nextUnit as RecurrenceUnit);};
 return <><button className={menuItem?"customer-action-item":"sv-button"} type="button" onClick={()=>setOpen(true)}>{menuItem?<><i className="customer-action-icon recurring"><CustomerActionIcon name="repeat"/></i><span><strong>Add service plan <em>Recurring</em></strong><small>Set up recurring service</small></span><b aria-hidden="true">›</b></>:<>＋ Add service plan</>}</button>
 <ManagementDrawer open={open} title="Add service plan" onDirty={()=>{}} onClose={()=>setOpen(false)}>
  <form action={action} className="quick-employee-form service-plan-form">
   <fieldset><legend>Basic information</legend><label>Plan name<input name="name" required placeholder="General Pest Control"/></label><label>Customer<input value={customerName} readOnly/></label><label>Service location<select name="serviceLocationId" required defaultValue=""><option value="" disabled>Choose location</option>{locations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Service type<select name="serviceId" required defaultValue=""><option value="" disabled>Choose service</option>{services.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="quick-form-grid"><label>Start date<input name="startDate" type="date" required/></label><label>End date <small>Optional</small><input name="endDate" type="date"/></label><label>Duration (minutes)<input name="durationMinutes" type="number" min="1" max="10080" defaultValue="60" required/></label><label>Default technician<select name="employeeId" defaultValue=""><option value="">Unassigned</option>{employees.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div></fieldset>
   <fieldset><legend>Initial service</legend><label className="drawer-check"><input type="checkbox" name="initialServiceRequired" checked={initial} onChange={event=>setInitial(event.target.checked)}/>Initial service required</label>{initial&&<div className="quick-form-grid"><label>Initial date<input name="initialServiceDate" type="date" required/></label><label>Initial price<input name="initialServicePrice" type="number" min="0" step=".01" defaultValue="0"/></label><label>Duration (minutes)<input name="initialServiceDuration" type="number" min="1" max="10080" defaultValue="90"/></label><label className="wide">Description<textarea name="initialServiceDescription" rows={2}/></label></div>}</fieldset>
   <fieldset><legend>Recurring cadence</legend><label>Common cadence<select onChange={event=>preset(event.target.value)} defaultValue="1:month"><option value="1:week">Weekly</option><option value="2:week">Every 2 weeks</option><option value="4:week">Every 4 weeks</option><option value="1:month">Monthly</option><option value="2:month">Every 2 months</option><option value="3:month">Quarterly</option><option value="6:month">Every 6 months</option><option value="1:year">Annually</option></select></label><div className="service-plan-cadence"><span>Repeat every</span><input name="intervalValue" type="number" min="1" max="120" value={interval} onChange={event=>setInterval(Number(event.target.value))}/><select name="intervalUnit" value={unit} onChange={event=>setUnit(event.target.value as RecurrenceUnit)}><option value="day">days</option><option value="week">weeks</option><option value="month">months</option><option value="year">years</option></select></div><label>First recurring service date<input name="firstRecurringDate" type="date" required value={first} onChange={event=>setFirst(event.target.value)}/></label>{preview.length>0&&<div className="recurrence-preview"><strong>{cadenceLabel(interval,unit)}</strong><span>Next occurrences: {preview.join(" · ")}</span></div>}</fieldset>
   <fieldset><legend>Pricing and scheduling</legend><div className="quick-form-grid"><label>Price per visit<input name="recurringPrice" type="number" min="0" step=".01" defaultValue="0" required/></label><label>Preferred time<select name="preferredTimeWindow" defaultValue="no_preference"><option value="no_preference">No preference</option><option value="morning">Morning</option><option value="afternoon">Afternoon</option><option value="08:00-10:00">8:00 AM–10:00 AM</option><option value="10:00-12:00">10:00 AM–12:00 PM</option></select></label></div><label className="drawer-check"><input type="checkbox" name="taxable"/>Taxable</label><p>Billing rule: Bill after each completed service</p></fieldset>
   <footer><button type="button" className="sv-button sv-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="sv-button">Create service plan</button></footer>
  </form>
 </ManagementDrawer></>;
}
