"use client";

import {useState} from "react";
import {ManagementDrawer} from "./ManagementDrawer";
import {CustomerActionIcon} from "./CustomerActionIcon";
import {formatEmployeeNumber,type EmployeeNumbering} from "@/lib/employeeNumbering";

type Action=(formData:FormData)=>void|Promise<void>;
type NoArgAction=()=>void|Promise<void>;
type Row=Record<string,any>;
type DrawerName="business"|"routing"|"numbering"|"payments"|null;

function EditButton({onClick,disabled=false}:{onClick:()=>void;disabled?:boolean}){
 return <button type="button" className="settings-edit-button" onClick={onClick} disabled={disabled}>Edit</button>;
}
function SectionHeader({icon,title,description,onEdit,editable}:{icon:"briefcase"|"location"|"customer"|"card";title:string;description:string;onEdit:()=>void;editable:boolean}){
 return <header className="settings-section-header"><i><CustomerActionIcon name={icon}/></i><div><h2>{title}</h2><p>{description}</p></div>{editable&&<EditButton onClick={onEdit}/>}<span aria-hidden="true">⌄</span></header>;
}
const modeLabel=(mode:string|undefined)=>({office:"Main office",custom:"Custom address",first_job:"First job",last_job:"Last job",none:"None"}[mode??""]??"Not configured");

export function SettingsDashboard({section,business,timezone,editable,canDelete,entitlement,endpointDefaults,technicians,endpointOverrides,routingPolicy,numbering,payment,invoicePaymentOptions,businessAction,routingAction,endpointAction,numberingAction,connectStripeAction,refreshStripeAction,disconnectStripeAction,invoicePaymentOptionsAction,deleteWorkspaceAction}:{
 section:"general"|"operations"|"billing"|"employees";
 business:Row;timezone:string;editable:boolean;canDelete:boolean;entitlement:Row;endpointDefaults:Row|null;technicians:Row[];endpointOverrides:Row[];routingPolicy:Row|null;numbering:EmployeeNumbering;payment:Row;invoicePaymentOptions:Row|null;
 businessAction:Action;routingAction:Action;endpointAction:Action;numberingAction:Action;connectStripeAction:NoArgAction;refreshStripeAction:NoArgAction;disconnectStripeAction:Action;invoicePaymentOptionsAction:Action;deleteWorkspaceAction:Action;
}){
 const [drawer,setDrawer]=useState<DrawerName>(null);
 const [prefix,setPrefix]=useState(numbering.prefix),[next,setNext]=useState(numbering.nextNumber),[digits,setDigits]=useState(numbering.minimumDigits);
 const close=()=>setDrawer(null);
 const started=entitlement.startsAt?new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeZone:timezone}).format(new Date(entitlement.startsAt)):"Not available";
 const ends=entitlement.endsAt?new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeZone:timezone}).format(new Date(entitlement.endsAt)):"No scheduled end date";
 const address=[business.address_line1,business.city,business.state,business.postal_code].filter(Boolean).join(", ")||"Not provided";
 return <>
  <header className="settings-page-header"><span>Workspace configuration</span><h1>{{general:"General settings",operations:"Operations settings",billing:"Billing settings",employees:"Employee settings"}[section]}</h1><p>{{general:"Manage business information and workspace access.",operations:"Configure routing, dispatch, and field-work defaults.",billing:"Manage payment collection and customer invoice methods.",employees:"Configure employee records and numbering defaults."}[section]}</p></header>

  {section==="general"&&<section className="settings-access-card">
   <div className="settings-access-title"><div><span>Plan &amp; access</span><h2>{entitlement.name}</h2><p>{entitlement.key==="pilot"?"Your business currently has Servonas Pilot access. No payment method is required during the pilot.":"Your current access controls available workspace capabilities."}</p></div><b className={`estimate-status ${entitlement.status}`}>{String(entitlement.status).replaceAll("_"," ")}</b></div>
   <dl><div><i><CustomerActionIcon name="calendar"/></i><span><dt>Started</dt><dd>{started}</dd></span></div><div><i><CustomerActionIcon name="clock"/></i><span><dt>Ends</dt><dd>{ends}</dd></span></div><div><i><CustomerActionIcon name="briefcase"/></i><span><dt>Billing required</dt><dd>No</dd></span></div></dl>
   <details><summary>Included capabilities</summary><div className="settings-capabilities">{entitlement.capabilities.map((item:string)=><span key={item}>{item.replaceAll("_"," ")}</span>)}</div></details>
   <p className="settings-support-copy">Questions about access? Contact Servonas support. Your workspace data is preserved if access changes.</p>
  </section>}

  {section==="general"&&<section className="settings-summary-card">
   <SectionHeader icon="briefcase" title="Business information" description="Manage your basic business details and contact information." onEdit={()=>setDrawer("business")} editable={editable}/>
   <dl className="settings-business-summary">
    <div><dt>Business name</dt><dd>{business.name}</dd></div><div><dt>Business email</dt><dd>{business.email||"Not provided"}</dd></div>
    <div><dt>Phone</dt><dd>{business.phone||"Not provided"}</dd></div><div><dt>Website</dt><dd>{business.website_url||"—"}</dd></div>
    <div><dt>Time zone</dt><dd>{business.timezone}</dd></div><div><dt>Brand color</dt><dd><i className="settings-color-dot" style={{background:business.primary_color??"#2563eb"}}/> {business.primary_color??"#2563eb"}</dd></div>
    <div><dt>Address</dt><dd>{address}</dd></div><div><dt>Default tax rate</dt><dd>{Number(business.tax_rate??0)}%</dd></div>
   </dl>
  </section>}

  {section==="general"&&canDelete&&<section className="settings-danger-zone" id="delete-workspace">
   <div><span>Servonas administration · Danger zone</span><h2>Delete workspace</h2><p>Remove <strong>{business.name}</strong> from Servonas, disable its public pages, disconnect Stripe, and cancel its Servonas subscription. Only confirmed Servonas administrators can perform this action, and it cannot be undone from the app.</p></div>
   <details><summary>Delete this workspace</summary><form action={deleteWorkspaceAction} onSubmit={event=>{if(!window.confirm(`Permanently delete the ${business.name} workspace?`))event.preventDefault();}}><label>Type <strong>{business.name}</strong> to confirm<input required name="confirmation" autoComplete="off"/></label><label className="settings-danger-confirm"><input required type="checkbox" name="acknowledge"/>I understand this removes the workspace for every team member.</label><button className="sv-button sv-danger">Delete workspace</button></form></details>
  </section>}

  {section==="operations"&&<section className="settings-summary-card">
   <SectionHeader icon="location" title="Dispatch routing defaults" description="Set home locations and planning/notification defaults." onEdit={()=>setDrawer("routing")} editable={editable}/>
   <div className="settings-routing-summary"><div><h3>Route locations</h3><p><b>Default start</b>{modeLabel(endpointDefaults?.start_mode)}</p><p><b>Office</b>{endpointDefaults?.office_address||business.address_line1||"Not configured"}</p><p><b>Default end</b>{modeLabel(endpointDefaults?.end_mode)}</p></div>
    <div><h3>Planning &amp; notification defaults</h3><p><b>Automatic dispatch</b>{routingPolicy?.auto_dispatch_all_jobs?"All assigned jobs":"Recurring plans only"}</p><p><b>Fallback service duration</b>{routingPolicy?.default_service_duration_minutes??60} min</p><p><b>Protect imminent jobs within</b>{routingPolicy?.imminent_job_lock_minutes??60} min</p>
     <ul><li className={routingPolicy?.scheduled_window_notifications_enabled?"enabled":""}>Prepare scheduled arrival-window notifications</li><li className={routingPolicy?.proximity_eta_notifications_enabled?"enabled":""}>Prepare confidence-gated proximity ETA notifications</li><li className={routingPolicy?.en_route_notifications_enabled?"enabled":""}>Prepare en-route notifications</li></ul>
    </div><div><h3>Notifications</h3><p>Notifications use customer preferences and remain in provider stub mode until delivery is configured. Route ETAs are estimates, not live GPS tracking.</p></div></div>
  </section>}

  {section==="employees"&&<section className="settings-summary-card" id="employee-numbering">
   <SectionHeader icon="customer" title="Employee numbering" description="Control how employee numbers are assigned." onEdit={()=>setDrawer("numbering")} editable={editable}/>
   <dl className="settings-numbering-summary"><div><dt>Auto-assign numbers</dt><dd className={numbering.autoAssignEnabled?"enabled":""}>{numbering.autoAssignEnabled?"✓ Enabled":"Disabled"}</dd></div><div><dt>Prefix</dt><dd>{numbering.prefix||"None"}</dd></div><div><dt>Starting number</dt><dd>{numbering.startingNumber}</dd></div><div><dt>Minimum digits</dt><dd>{numbering.minimumDigits}</dd></div><div><dt>Next number</dt><dd>{formatEmployeeNumber(numbering.prefix,numbering.nextNumber,numbering.minimumDigits)}</dd></div><div><dt>Manual override</dt><dd>{numbering.allowManualOverride?"Allowed":"Not allowed"}</dd></div></dl>
  </section>}

  {section==="billing"&&<section className="settings-summary-card" id="payments">
   <SectionHeader icon="card" title="Payments" description="Connect a tenant-specific Express account for invoice payments and payouts." onEdit={()=>setDrawer("payments")} editable={editable}/>
   <div className="settings-payment-summary"><div><b>Stripe Connect</b><span className={`estimate-status ${payment.ready?"paid":payment.onboarding_status||"draft"}`}>{payment.ready?"Ready":String(payment.onboarding_status||"Not connected").replaceAll("_"," ")}</span></div><p>{payment.ready?"Stripe is ready for payment collection and payouts.":"Payment collection is unavailable until Stripe onboarding is complete."}</p></div>
  </section>}
  <p className="settings-security-note">♙ Your workspace data is secure and only visible to authorized users.</p>

  <ManagementDrawer open={drawer==="business"} title="Edit business information" subtitle="Update the details used across your workspace." onDirty={()=>{}} onClose={close} size="wide">
   <form action={businessAction} className="settings-drawer-form"><label>Business name<input required name="name" defaultValue={business.name}/></label><label>Business email<input name="email" type="email" defaultValue={business.email??""}/></label><label>Phone<input name="phone" defaultValue={business.phone??""}/></label><label>Website<input name="websiteUrl" type="url" defaultValue={business.website_url??""}/></label><label>Time zone<select name="timezone" defaultValue={business.timezone??"America/Phoenix"}><option>America/Phoenix</option><option>America/Denver</option><option>America/Chicago</option><option>America/New_York</option><option>America/Los_Angeles</option></select></label><label>Brand color<input name="primaryColor" type="color" defaultValue={business.primary_color??"#2563eb"}/></label><label className="wide">Address<input name="addressLine1" defaultValue={business.address_line1??""}/></label><label>City<input name="city" defaultValue={business.city??""}/></label><label>State<input name="state" defaultValue={business.state??""}/></label><label>Postal code<input name="postalCode" defaultValue={business.postal_code??""}/></label><label>Default tax rate (%)<input name="taxRate" type="number" min="0" max="100" step=".01" defaultValue={business.tax_rate??0}/></label><footer><button type="button" className="sv-button sv-secondary" onClick={close}>Cancel</button><button className="sv-button">Save business information</button></footer></form>
  </ManagementDrawer>

  <ManagementDrawer open={drawer==="routing"} title="Edit dispatch routing defaults" subtitle="Manage business and technician route endpoints, planning, and notifications." onDirty={()=>{}} onClose={close} size="wide">
   <div className="settings-routing-drawer">
    <form action={routingAction} className="settings-drawer-form"><h3>Planning and notifications</h3><label className="settings-check wide settings-auto-dispatch"><input name="autoDispatchAllJobs" type="checkbox" defaultChecked={routingPolicy?.auto_dispatch_all_jobs??false}/><span><strong>Automatically dispatch all assigned jobs</strong><small>On the appointment day, move both recurring and one-time jobs from scheduled or confirmed to dispatched. Unassigned jobs remain scheduled for office review.</small></span></label><label>Fallback service duration (minutes)<input required name="defaultDuration" type="number" min="1" max="1440" defaultValue={routingPolicy?.default_service_duration_minutes??60}/></label><label>Protect imminent jobs within (minutes)<input required name="lockMinutes" type="number" min="0" max="1440" defaultValue={routingPolicy?.imminent_job_lock_minutes??60}/></label><label className="settings-check wide"><input name="scheduledWindowNotifications" type="checkbox" defaultChecked={routingPolicy?.scheduled_window_notifications_enabled??false}/>Prepare scheduled arrival-window notifications</label><label className="settings-check wide"><input name="proximityEtaNotifications" type="checkbox" defaultChecked={routingPolicy?.proximity_eta_notifications_enabled??false}/>Prepare confidence-gated proximity ETA notifications</label><label className="settings-check wide"><input name="enRouteNotifications" type="checkbox" defaultChecked={routingPolicy?.en_route_notifications_enabled??false}/>Prepare en-route notifications</label><button className="sv-button">Save planning defaults</button></form>
    <form action={endpointAction} className="settings-drawer-form"><h3>Business route locations</h3><label>Default start<select name="startMode" defaultValue={endpointDefaults?.start_mode??"first_job"}><option value="office">Main office</option><option value="custom">Custom address</option><option value="first_job">First job</option><option value="none">No origin</option></select></label><label>Default end<select name="endMode" defaultValue={endpointDefaults?.end_mode??"last_job"}><option value="office">Main office</option><option value="custom">Custom address</option><option value="last_job">Last job</option><option value="none">No destination</option></select></label><label>Office label<input name="officeLabel" defaultValue={endpointDefaults?.office_label??"Main office"}/></label><label>Office address<input name="officeAddress" defaultValue={endpointDefaults?.office_address??business.address_line1??""}/></label><label>Verified latitude<input name="officeLatitude" type="number" step="any" defaultValue={endpointDefaults?.office_latitude??""}/></label><label>Verified longitude<input name="officeLongitude" type="number" step="any" defaultValue={endpointDefaults?.office_longitude??""}/></label><label>Custom start address<input name="customStartAddress" defaultValue={endpointDefaults?.custom_start_address??""}/></label><label>Custom start label<input name="customStartLabel" defaultValue={endpointDefaults?.custom_start_label??""}/></label><label>Custom start latitude<input name="customStartLatitude" type="number" step="any" defaultValue={endpointDefaults?.custom_start_latitude??""}/></label><label>Custom start longitude<input name="customStartLongitude" type="number" step="any" defaultValue={endpointDefaults?.custom_start_longitude??""}/></label><label>Custom end address<input name="customEndAddress" defaultValue={endpointDefaults?.custom_end_address??""}/></label><label>Custom end label<input name="customEndLabel" defaultValue={endpointDefaults?.custom_end_label??""}/></label><label>Custom end latitude<input name="customEndLatitude" type="number" step="any" defaultValue={endpointDefaults?.custom_end_latitude??""}/></label><label>Custom end longitude<input name="customEndLongitude" type="number" step="any" defaultValue={endpointDefaults?.custom_end_longitude??""}/></label><button className="sv-button">Save route locations</button></form>
    {technicians.length>0&&<details className="settings-technician-overrides"><summary>Technician route overrides</summary>{technicians.map(technician=>{const value=endpointOverrides.find(item=>item.technician_id===technician.id);return <form action={endpointAction} className="settings-drawer-form" key={technician.id}><h3>{technician.preferred_name}</h3><input type="hidden" name="technicianId" value={technician.id}/><label>Start override<select name="startMode" defaultValue={value?.start_mode??"inherit"}><option value="inherit">Business default</option><option value="office">Main office</option><option value="home">Technician home</option><option value="custom">Custom address</option><option value="first_job">First job</option><option value="none">No origin</option></select></label><label>End override<select name="endMode" defaultValue={value?.end_mode??"inherit"}><option value="inherit">Business default</option><option value="office">Main office</option><option value="home">Technician home</option><option value="custom">Custom address</option><option value="last_job">Last job</option><option value="none">No destination</option></select></label><label>Private display label<input name="homeLabel" defaultValue={value?.home_label??"Technician home"}/></label><label>Private home address<input name="homeAddress" autoComplete="off" defaultValue={value?.home_address??""}/></label><label>Verified latitude<input name="homeLatitude" type="number" step="any" defaultValue={value?.home_latitude??""}/></label><label>Verified longitude<input name="homeLongitude" type="number" step="any" defaultValue={value?.home_longitude??""}/></label><label>Custom start address<input name="customStartAddress" defaultValue={value?.custom_start_address??""}/></label><label>Custom start label<input name="customStartLabel" defaultValue={value?.custom_start_label??""}/></label><label>Custom start latitude<input name="customStartLatitude" type="number" step="any" defaultValue={value?.custom_start_latitude??""}/></label><label>Custom start longitude<input name="customStartLongitude" type="number" step="any" defaultValue={value?.custom_start_longitude??""}/></label><label>Custom end address<input name="customEndAddress" defaultValue={value?.custom_end_address??""}/></label><label>Custom end label<input name="customEndLabel" defaultValue={value?.custom_end_label??""}/></label><label>Custom end latitude<input name="customEndLatitude" type="number" step="any" defaultValue={value?.custom_end_latitude??""}/></label><label>Custom end longitude<input name="customEndLongitude" type="number" step="any" defaultValue={value?.custom_end_longitude??""}/></label><button className="sv-button">Save override</button></form>})}</details>}
   </div>
  </ManagementDrawer>

  <ManagementDrawer open={drawer==="numbering"} title="Edit employee numbering" subtitle="Control how future employee numbers are assigned." onDirty={()=>{}} onClose={close}>
   <form action={numberingAction} className="settings-drawer-form single" onSubmit={event=>{if(next!==numbering.nextNumber&&!window.confirm("Changing the next number affects future employees only. Existing employee numbers will not change."))event.preventDefault();}}><div className="number-preview wide"><span>Preview</span><strong>{formatEmployeeNumber(prefix,next,digits)}</strong></div><label className="settings-check wide"><input type="checkbox" name="autoAssignEnabled" defaultChecked={numbering.autoAssignEnabled}/>Automatically assign employee numbers</label><label>Prefix <small>Optional</small><input name="prefix" value={prefix} onChange={event=>setPrefix(event.target.value)} maxLength={10} pattern="[A-Za-z0-9_-]*"/></label><label>Starting number<input required name="startingNumber" type="number" min="1" step="1" defaultValue={numbering.startingNumber}/></label><label>Minimum digits<input required name="minimumDigits" type="number" min="1" max="10" step="1" value={digits} onChange={event=>setDigits(Number(event.target.value))}/></label><label>Next employee number<input required name="nextNumber" type="number" min="1" step="1" value={next} onChange={event=>setNext(Number(event.target.value))}/></label><label className="settings-check wide"><input type="checkbox" name="allowManualOverride" defaultChecked={numbering.allowManualOverride}/>Allow authorized users to enter a custom number</label><footer><button type="button" className="sv-button sv-secondary" onClick={close}>Cancel</button><button className="sv-button">Save employee numbering</button></footer></form>
  </ManagementDrawer>

  <ManagementDrawer open={drawer==="payments"} title="Manage payments" subtitle="Connect and maintain your Stripe Express account." onDirty={()=>{}} onClose={close}>
   <div className="settings-payment-drawer">{payment.error&&<div className="workspace-notice error">Stripe account status could not be loaded.</div>}<div className="settings-payment-state"><b>Stripe Connect</b><span className={`estimate-status ${payment.ready?"paid":payment.onboarding_status||"draft"}`}>{payment.ready?"Ready":String(payment.onboarding_status||"Not connected").replaceAll("_"," ")}</span></div>
    {!payment.provider_account_id?<><p>Payment collection is unavailable until Stripe onboarding is complete.</p><form action={connectStripeAction}><button className="sv-button">Connect Stripe</button></form></>:<><dl><div><dt>Charges</dt><dd>{payment.charges_enabled?"Enabled":"Unavailable"}</dd></div><div><dt>Payouts</dt><dd>{payment.payouts_enabled?"Enabled":"Unavailable"}</dd></div><div><dt>Details submitted</dt><dd>{payment.details_submitted?"Yes":"No"}</dd></div><div><dt>Last sync</dt><dd>{payment.last_provider_sync_at?new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short",timeZone:timezone}).format(new Date(payment.last_provider_sync_at)):"Never"}</dd></div></dl>{payment.restrictions?.length>0&&<div className="workspace-notice error"><strong>Requirements due</strong><ul>{[...new Set(payment.restrictions as string[])].map(item=><li key={item}>{item.replaceAll("."," → ").replaceAll("_"," ")}</li>)}</ul></div>}<div className="settings-payment-actions"><form action={connectStripeAction}><button className="sv-button">{payment.ready?"Update Stripe details":"Resume onboarding"}</button></form><form action={refreshStripeAction}><button className="sv-button sv-secondary">Refresh status</button></form></div><details className="payment-disconnect"><summary>Disconnect Stripe</summary><form action={disconnectStripeAction}><label>Type DISCONNECT<input required name="confirmation" pattern="DISCONNECT" autoComplete="off"/></label><button className="sv-button sv-danger">Disconnect Stripe</button></form></details></>}
    <form action={invoicePaymentOptionsAction} className="settings-drawer-form single"><h3>Customer invoice payment options</h3><p className="wide">Only enabled methods appear on public invoices. Card payments also require a completed Stripe connection.</p><label className="settings-check wide"><input name="acceptOnlineCard" type="checkbox" defaultChecked={invoicePaymentOptions?.accept_online_card??true}/>Credit and debit cards through Stripe</label><label className="settings-check wide"><input name="acceptCash" type="checkbox" defaultChecked={invoicePaymentOptions?.accept_cash??false}/>Cash</label><label className="settings-check wide"><input name="acceptCheck" type="checkbox" defaultChecked={invoicePaymentOptions?.accept_check??false}/>Check</label><label className="wide">Make checks payable to<input name="checkPayableTo" defaultValue={invoicePaymentOptions?.check_payable_to??business.name}/></label><label className="settings-check wide"><input name="acceptPayByPhone" type="checkbox" defaultChecked={invoicePaymentOptions?.accept_pay_by_phone??false}/>Pay by phone</label><label className="wide">Payment phone number<input name="paymentPhone" type="tel" defaultValue={invoicePaymentOptions?.payment_phone??business.phone??""}/></label><button className="sv-button">Save invoice payment options</button></form>
   </div>
  </ManagementDrawer>
 </>;
}
