import Image from "next/image";
import Link from "next/link";
import type {WebsiteFirstSource} from "@/lib/websiteFirstConfig";
import {MarketingLandingAttribution} from "@/components/MarketingLandingAttribution";

const attributionKeys=["utm_source","utm_medium","utm_campaign","utm_content","utm_term","gclid","gbraid","wbraid"] as const;
type Params=Record<string,string|string[]|undefined>;
type LandingPhoto={src:string;alt:string};
export type WebsiteIndustryLandingConfig={source:WebsiteFirstSource;name:string;plural:string;eyebrow:string;headline:string;description:string;image?:string;imageAlt?:string;demoPath:string;services:string[];audiences:string[];accentClass:string;photos?:LandingPhoto[]};
const href=(base:string,params:Params,source?:WebsiteFirstSource)=>{const query=new URLSearchParams(source?{source}:{});for(const key of attributionKeys){const raw=params[key],value=Array.isArray(raw)?raw[0]:raw;if(value)query.set(key,value.slice(0,500));}return `${base}${query.size?`?${query}`:""}`;};

export function WebsiteIndustryLanding({config,params}:{config:WebsiteIndustryLandingConfig;params:Params}){
 const signup=href("/signup",params,config.source),demo=href(config.demoPath,params);
 const included=[["Professional website",`A polished website built around your ${config.name.toLowerCase()} services and brand.`],["Mobile-friendly design","A fast, modern experience across phones, tablets, and desktops."],["Online booking","Let customers request service and choose a convenient time."],["Customer management","Keep customer details, service locations, and history organized."],["Scheduling","Manage appointments, assignments, and upcoming work."],["Estimates and invoices","Price work and invoice completed jobs."],["Online payments","Accept secure card payments after connecting Stripe."],["Customer communication","Keep customers informed with email and texting tools."],["Job management","Track work from the first request through completion."]];
 return <main className={`pcw-page industry-website-landing ${config.accentClass}`}><MarketingLandingAttribution source={config.source}/>
  <section className="pcw-hero industry-landing-hero"><div className="sv-container pcw-hero-grid"><div className="pcw-hero-copy"><span className="sv-kicker">{config.eyebrow}</span><h1>We&apos;ll Build Your {config.name} Website. <span>Free.</span></h1><p>{config.description}</p><div className="sv-actions"><Link className="sv-button pcw-primary" data-acquisition-builder href={signup}>Build My Free Website →</Link><Link className="sv-button sv-secondary" href={demo}>View Example Website</Link></div><div className="pcw-hero-proof"><span>✓ First-year domain included</span><span>✓ Built for {config.plural.toLowerCase()}</span><span>✓ Mobile friendly</span><span>✓ Online requests included</span></div></div><div className="pcw-hero-visual">{config.image?<div className={`pcw-photo${config.photos?.length?" ken-burns":""}`}><Image src={config.image} alt={config.imageAlt??`${config.name} professional at work`} fill priority sizes="(max-width: 900px) 100vw, 46vw"/></div>:<div className="industry-landing-mark" aria-hidden="true"><i>{config.name==="HVAC"?"❄":"◆"}</i><strong>{config.name}</strong><span>Professional local service</span></div>}{config.photos?.length?<div className="industry-photo-grid" aria-label={`${config.name} photo gallery`}>{config.photos.slice(0,2).map((photo,index)=><figure className={`industry-photo-card ${index===0?"ken-burns-slow":"ken-burns-fast"}`} key={photo.src}><Image src={photo.src} alt={photo.alt} fill sizes="(max-width: 900px) 44vw, 20vw"/></figure>)}</div>:null}<div className="pcw-site-preview"><span>YOUR NEW {config.name.toUpperCase()} WEBSITE</span><strong>{config.headline}</strong><small>Website and business tools connected from day one.</small></div><div className="pcw-free-badge"><b>FREE</b><span>pilot website build</span></div></div></div></section>
  <section className="pcw-pilot"><div className="sv-container"><span>★</span><div><h2>A limited Servonas pilot offer</h2><p>We&apos;ll build your website and cover one standard domain registration for the first year. Premium domains are not included, and renewal after the first year is the business owner&apos;s responsibility.</p></div></div></section>
  <section className="sv-section pcw-included"><div className="sv-container"><header className="sv-heading"><span className="sv-kicker">More than a website</span><h2>Everything your {config.name.toLowerCase()} business needs to get online and organized.</h2><p>Your website brings in the request. Servonas helps you manage what happens next.</p></header><div className="pcw-included-grid">{included.map(([title,body],index)=><article key={title}><i>{String(index+1).padStart(2,"0")}</i><div><h3>{title}</h3><p>{body}</p></div></article>)}</div></div></section>
  <section className="pcw-how"><div className="sv-container"><header className="sv-heading"><span className="sv-kicker">How it works</span><h2>From business details to taking requests in three steps.</h2></header><ol>{[["01","Tell Us About Your Business",`Share your contact details, service area, and the ${config.name.toLowerCase()} services you offer.`],["02","Build and Preview Your Website","Choose a style, add your branding, review the real website, and request or connect a domain."],["03","Publish and Manage the Work","Turn website visitors into customers, jobs, appointments, invoices, and payments in Servonas."]].map(([number,title,body])=><li key={number}><span>{number}</span><h3>{title}</h3><p>{body}</p></li>)}</ol></div></section>
  <section className="pcw-connected"><div className="sv-container pcw-connected-grid"><div><span className="sv-kicker">Website meets operations</span><h2>Your Website Should Do More Than Look Good</h2><p>A Servonas-powered website connects customer requests to the workflow behind your business. Customer and service details stay together instead of being re-entered across disconnected tools.</p></div><div className="pcw-flow"><div><i>1</i><span><strong>Customer requests service</strong><small>From your branded website</small></span></div><b>↓</b><div><i>2</i><span><strong>Details enter Servonas</strong><small>Customer, location, and requested service stay connected</small></span></div><b>↓</b><div><i>3</i><span><strong>You manage the job</strong><small>Schedule, complete, invoice, and collect</small></span></div></div></div></section>
  <section className="pcw-demo-callout industry-demo-callout"><div className="sv-container"><div className="pcw-demo-browser"><header><i/><i/><i/><span>yourbusiness.example</span></header><div><span>YOUR {config.name.toUpperCase()} BUSINESS</span><h2>{config.headline}</h2><p>See the polished, mobile-friendly experience Servonas can create.</p></div></div><div><span className="sv-kicker">See what we can build</span><h2>Preview an example {config.name.toLowerCase()} website.</h2><p>Explore its service presentation, trust sections, local service areas, and safe request experience.</p><Link className="sv-button" href={demo}>View Example Website</Link></div></div></section>
  <section className="sv-section pcw-audience"><div className="sv-container"><header className="sv-heading"><span className="sv-kicker">Built for local service businesses</span><h2>A simpler online foundation for your company.</h2><p>Especially useful for owner-operators and growing teams booking work through calls, texts, social media, spreadsheets, or disconnected apps.</p></header><div>{config.audiences.map(item=><span key={item}>{item}</span>)}</div></div></section>
  <section className="pcw-faq"><div className="sv-container"><header className="sv-heading"><span className="sv-kicker">Frequently asked questions</span><h2>What to know before you start.</h2></header><div className="pcw-faq-list"><details><summary>Is the website really free?</summary><p>Servonas is offering website creation at no cost to selected businesses participating in the limited pilot.</p></details><details><summary>Do I need an existing website?</summary><p>No. You can start with a Servonas website address and connect or request your own domain during setup.</p></details><details><summary>Can customers request service online?</summary><p>Yes. Your website can collect customer, service, location, and scheduling information directly into Servonas.</p></details><details><summary>Can I use my own domain?</summary><p>Yes. Connect a domain you already own, or request an available standard domain through Servonas. One standard first-year registration is included for qualifying pilot businesses.</p></details><details><summary>What happens after the first year?</summary><p>You&apos;ll see the estimated annual renewal price before requesting a domain. Renewal after the included first year is the business owner&apos;s responsibility.</p></details></div></div></section>
  <section className="home-final-cta pcw-final"><div className="sv-container"><div><span className="sv-kicker">Limited pilot availability</span><h2>Ready to Get Your {config.name} Business Online?</h2><p>We&apos;ll build your website and give you the tools to manage the work it creates.</p></div><Link className="sv-button sv-light" data-acquisition-builder href={signup}>Build My Free Website</Link></div></section>
  <section className="pcw-domain-terms"><div className="sv-container"><details><summary>Is the domain included?</summary><p>Yes. For qualifying pilot businesses, Servonas will cover one standard domain registration for the first year. Premium domains are not included, and renewal after the first year is the business owner&apos;s responsibility.</p></details></div></section>
 </main>;
}
