"use client";

import {useState} from "react";

type DomainChoice="need_domain"|"existing_domain";

export function WebsiteFirstDomainChoice({slug,initialChoice="need_domain",initialDomain=""}:{slug:string;initialChoice?:string;initialDomain?:string}){
 const [choice,setChoice]=useState<DomainChoice>(initialChoice==="existing_domain"?"existing_domain":"need_domain");
 return <fieldset className="wide website-first-domain"><legend>Choose your website address</legend><p>We&apos;ll cover one standard domain for your first year as part of the Servonas pilot.</p><div className="website-first-domain-options"><label className={choice==="need_domain"?"selected":""}><input type="radio" name="domainPreference" value="need_domain" checked={choice==="need_domain"} onChange={()=>setChoice("need_domain")}/><i aria-hidden="true">{choice==="need_domain"?"✓":""}</i><span><strong>I want Servonas to get my domain <b>Included</b></strong><small>We&apos;ll cover one standard domain for your first year and help get it connected.</small></span></label><label className={choice==="existing_domain"?"selected":""}><input type="radio" name="domainPreference" value="existing_domain" checked={choice==="existing_domain"} onChange={()=>setChoice("existing_domain")}/><i aria-hidden="true">{choice==="existing_domain"?"✓":""}</i><span><strong>I already own a domain</strong><small>We&apos;ll help you connect your existing domain to your Servonas website.</small></span></label></div><label className="website-first-domain-name">{choice==="need_domain"?"What domain would you like?":"Your domain"}<input required name="domainName" defaultValue={initialDomain} placeholder={choice==="need_domain"?"desertshieldpest.com":"examplepestcontrol.com"} autoCapitalize="none"/><small>{choice==="need_domain"?"We'll confirm availability before registering it.":"We'll walk you through connecting it after your website is ready."}</small></label>{choice==="need_domain"&&slug&&<div className="website-first-temporary-url"><span>Your website can go live while we handle your request</span><strong>servonas.com/sites/{slug}</strong><small>One standard first-year registration is included. Premium domains are not included; renewal after the first year is your responsibility.</small></div>}</fieldset>;
}
