import Link from "next/link";
import {requireWorkspace} from "@/lib/workspace";
import {WorkspaceNav} from "../WorkspaceNav";
export default async function CallsPage({params,searchParams}:{params:Promise<{businessSlug:string}>;searchParams:Promise<{filter?:string}>}){
 const {businessSlug}=await params,{filter="all"}=await searchParams,{supabase,business}=await requireWorkspace(businessSlug);
 let query=supabase.from("voice_calls").select("id,direction,status,from_number,to_number,started_at,duration_seconds,was_missed,customers(id,first_name,last_name,company_name),employees!voice_calls_business_id_answered_by_employee_id_fkey(preferred_name)").eq("business_id",business.id).order("started_at",{ascending:false}).limit(100);
 if(filter==="missed")query=query.eq("was_missed",true);if(filter==="voicemail")query=query.not("recording_sid","is",null);
 const {data:calls,error}=await query;if(error)console.error("Voice calls unavailable",{businessId:business.id,code:error.code});
 return <main className="epic3-shell"><WorkspaceNav slug={businessSlug} name={business.name} industry={business.industry_profile}/><section className="epic3-content"><header className="settings-page-header"><span>Customer communications</span><h1>Calls</h1><p>Inbound and outbound business-phone activity.</p></header><nav className="customer-record-tabs"><Link href={`/app/${businessSlug}/calls`}>All</Link><Link href={`/app/${businessSlug}/calls?filter=missed`}>Missed</Link><Link href={`/app/${businessSlug}/calls?filter=voicemail`}>Voicemail</Link></nav><section className="workspace-panel"><div className="inbound-sms-list">{calls?.map((call:any)=>{const customer=Array.isArray(call.customers)?call.customers[0]:call.customers,employee=Array.isArray(call.employees)?call.employees[0]:call.employees,name=customer?(customer.company_name||`${customer.first_name??""} ${customer.last_name??""}`.trim()):call.direction==="inbound"?call.from_number:call.to_number;return <article key={call.id}><header><div><strong>{call.direction==="inbound"?"Incoming":"Outgoing"} call · {name||"Unknown caller"}</strong><span>{call.status}{call.was_missed?" · missed":""}{employee?.preferred_name?` · answered by ${employee.preferred_name}`:""}</span></div><time>{new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short",timeZone:business.timezone}).format(new Date(call.started_at))}</time></header><p>{call.duration_seconds?`${call.duration_seconds}s`:`${call.from_number} → ${call.to_number}`}</p>{customer?.id&&<footer><Link href={`/app/${businessSlug}/customers/${customer.id}`}>Open customer</Link></footer>}</article>})}{!calls?.length&&<div className="dashboard-empty"><strong>No calls yet.</strong><p>Configure a voice-capable Twilio number and inbound routing in Communication settings.</p></div>}</div></section></section></main>;
}
