import Link from "next/link";
import {requireWorkspace} from "@/lib/workspace";

const names=["landing_page_view","check_availability_clicked","availability_date_selected","booking_started","customer_info_entered","checkout_started","booking_completed"] as const;
const labels:Record<(typeof names)[number],string>={landing_page_view:"Landing visits",check_availability_clicked:"Check availability",availability_date_selected:"Dates selected",booking_started:"Bookings started",customer_info_entered:"Customer info entered",checkout_started:"Checkout started",booking_completed:"Bookings completed"};
const pct=(value:number,total:number)=>total?`${Math.round(value/total*100)}%`:"—";
const money=(cents:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(cents/100);

export default async function BookingFunnelPage({params,searchParams}:{params:Promise<{businessSlug:string}>;searchParams:Promise<{from?:string;to?:string;source?:string}>}){
 const {businessSlug}=await params,q=await searchParams,{supabase,business}=await requireWorkspace(businessSlug),to=q.to&&/^\d{4}-\d{2}-\d{2}$/.test(q.to)?q.to:new Date().toISOString().slice(0,10),from=q.from&&/^\d{4}-\d{2}-\d{2}$/.test(q.from)?q.from:`${to.slice(0,8)}01`,source=q.source||"all";
 let query=supabase.from("booking_funnel_events").select("event_name,booking_total_cents,metadata,booking_attribution_sessions!inner(utm_source,gclid,gbraid,wbraid)").eq("business_id",business.id).gte("occurred_at",`${from}T00:00:00Z`).lte("occurred_at",`${to}T23:59:59Z`);
 if(source==="google")query=query.or("gclid.not.is.null,gbraid.not.is.null,wbraid.not.is.null,utm_source.ilike.google",{foreignTable:"booking_attribution_sessions"});
 const {data,error}=await query;
 const events=data??[],count=Object.fromEntries(names.map(name=>[name,events.filter(row=>row.event_name===name).length])) as Record<(typeof names)[number],number>,revenue=events.filter(row=>row.event_name==="booking_completed").reduce((sum,row)=>sum+Number(row.booking_total_cents??0),0);
 return <main className="epic3-shell"><section className="epic3-content"><header className="page-header"><div><span className="sv-kicker">Marketing</span><h1>Booking funnel</h1><p>First-touch website and booking attribution for {business.name}.</p></div><Link className="sv-button sv-secondary" href={`/app/${businessSlug}/marketing/discounts`}>Discounts</Link></header><form className="workspace-panel quick-form-grid" method="get"><label>From<input type="date" name="from" defaultValue={from}/></label><label>To<input type="date" name="to" defaultValue={to}/></label><label>Source<select name="source" defaultValue={source}><option value="all">All traffic</option><option value="google">Google Ads attributed</option></select></label><button className="sv-button">Update report</button></form>{error?<div className="workspace-notice error">Apply the booking funnel attribution migration to view this report.</div>:<><section className="dashboard-stats">{names.map(name=><article className="workspace-panel" key={name}><span>{labels[name]}</span><strong>{count[name]}</strong></article>)}<article className="workspace-panel"><span>Attributed revenue</span><strong>{money(revenue)}</strong></article></section><section className="workspace-panel"><h2>Conversion rates</h2><div className="quick-form-grid"><p>Landing → availability <strong>{pct(count.check_availability_clicked,count.landing_page_view)}</strong></p><p>Availability → started <strong>{pct(count.booking_started,count.check_availability_clicked)}</strong></p><p>Started → completed <strong>{pct(count.booking_completed,count.booking_started)}</strong></p><p>Landing → completed <strong>{pct(count.booking_completed,count.landing_page_view)}</strong></p></div><p className="muted">Google Ads means attributed sessions with a Google click ID or Google UTM source. It is not an imported Google Ads click count.</p></section></>}</section></main>;
}
