import type {SupabaseClient} from "@supabase/supabase-js";
import {attributionKeys,attributionFromSearch,validSessionId,type AttributionValues} from "@/lib/bookingFunnel";

export {attributionKeys,attributionFromSearch,validSessionId};
export type AcquisitionEvent="marketing_landing_view"|"website_builder_started"|"website_builder_step1_started"|"website_builder_step1_completed"|"website_builder_validation_error"|"domain_option_selected"|"domain_availability_checked"|"domain_available"|"domain_unavailable"|"website_builder_style_viewed"|"website_builder_style_selected"|"website_preview_generation_started"|"website_preview_generated"|"website_preview_generation_failed"|"website_preview_viewed"|"website_creation_celebration_shown"|"servonas_signup_completed"|"business_created"|"website_published";
export const acquisitionEvents=new Set<AcquisitionEvent>(["marketing_landing_view","website_builder_started","website_builder_step1_started","website_builder_step1_completed","website_builder_validation_error","domain_option_selected","domain_availability_checked","domain_available","domain_unavailable","website_builder_style_viewed","website_builder_style_selected","website_preview_generation_started","website_preview_generated","website_preview_generation_failed","website_preview_viewed","website_creation_celebration_shown","servonas_signup_completed","business_created","website_published"]);
export type {AttributionValues};
export const safeAcquisitionMetadata=(value:unknown)=>{if(!value||typeof value!=="object"||Array.isArray(value))return {};const out:Record<string,string|number|boolean>={};for(const [key,item] of Object.entries(value as Record<string,unknown>)){if(!/^[a-z][a-z0-9_]{0,60}$/i.test(key))continue;if(typeof item==="string")out[key]=item.trim().slice(0,120);else if(typeof item==="number"&&Number.isFinite(item))out[key]=item;else if(typeof item==="boolean")out[key]=item;}return out;};
export async function linkAcquisitionSession(db:SupabaseClient,input:{sessionId?:string;industry:string;userId?:string|null;businessId?:string|null;event?:AcquisitionEvent}){if(!validSessionId(input.sessionId))return;const now=new Date().toISOString();const {error}=await db.from("website_acquisition_sessions").update({user_id:input.userId??null,business_id:input.businessId??null,last_seen_at:now,updated_at:now}).eq("id",input.sessionId).eq("industry",input.industry);if(error)return; if(input.event)await db.from("website_acquisition_events").insert({acquisition_session_id:input.sessionId,industry:input.industry,user_id:input.userId??null,business_id:input.businessId??null,event_name:input.event,event_key:`${input.sessionId}:${input.event}:${input.businessId??input.userId??"anonymous"}`});}
