import {getSupabaseAdmin} from "@/lib/supabaseAdmin";

const base=()=> (process.env.NEXT_PUBLIC_APP_URL||"https://servonas.com").replace(/\/$/,"");
export const googleSearchConsoleRedirectUri=()=>`${base()}/api/google-search-console/callback`;
const credentials=()=>({clientId:process.env.GOOGLE_SEARCH_CONSOLE_CLIENT_ID?.trim()||process.env.GOOGLE_BUSINESS_CLIENT_ID?.trim(),clientSecret:process.env.GOOGLE_SEARCH_CONSOLE_CLIENT_SECRET?.trim()||process.env.GOOGLE_BUSINESS_CLIENT_SECRET?.trim()});

export async function exchangeSearchConsoleCode(code:string){const {clientId,clientSecret}=credentials();if(!clientId||!clientSecret)throw new Error("Google Search Console OAuth is not configured.");const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({code,client_id:clientId,client_secret:clientSecret,redirect_uri:googleSearchConsoleRedirectUri(),grant_type:"authorization_code"})});const body=await response.json() as {refresh_token?:string;access_token?:string;error?:string};if(!response.ok||!body.refresh_token)throw new Error(body.error||"Google did not provide Search Console access.");return body;}
export async function listSearchConsoleProperties(accessToken:string){const response=await fetch("https://www.googleapis.com/webmasters/v3/sites",{headers:{authorization:`Bearer ${accessToken}`}});if(!response.ok)throw new Error("Search Console properties could not be loaded.");const body=await response.json() as {siteEntry?:Array<{siteUrl:string;permissionLevel:string}>};return body.siteEntry??[];}
export async function saveSearchConsoleConnection(input:{businessId:string;refreshToken:string;connectedBy:string}){const db=getSupabaseAdmin();if(!db)throw new Error("Search Console storage is unavailable.");const {error}=await db.from("business_google_search_console_connections").upsert({business_id:input.businessId,refresh_token:input.refreshToken,connected_by:input.connectedBy,status:"property_selection_required",updated_at:new Date().toISOString()},{onConflict:"business_id"});if(error)throw new Error("Search Console connection could not be saved.");}
