import {getSupabaseAdmin} from "@/lib/supabaseAdmin";

const base=()=> (process.env.NEXT_PUBLIC_APP_URL||"https://servonas.com").replace(/\/$/,"");
export const googleSearchConsoleRedirectUri=()=>`${base()}/api/google-search-console/callback`;
const credentials=()=>({clientId:process.env.GOOGLE_SEARCH_CONSOLE_CLIENT_ID?.trim()||process.env.GOOGLE_BUSINESS_CLIENT_ID?.trim(),clientSecret:process.env.GOOGLE_SEARCH_CONSOLE_CLIENT_SECRET?.trim()||process.env.GOOGLE_BUSINESS_CLIENT_SECRET?.trim()});

export async function exchangeSearchConsoleCode(code:string){const {clientId,clientSecret}=credentials();if(!clientId||!clientSecret)throw new Error("Google Search Console OAuth is not configured.");const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({code,client_id:clientId,client_secret:clientSecret,redirect_uri:googleSearchConsoleRedirectUri(),grant_type:"authorization_code"})});const body=await response.json() as {refresh_token?:string;access_token?:string;error?:string};if(!response.ok||!body.refresh_token)throw new Error(body.error||"Google did not provide Search Console access.");return body;}
export async function listSearchConsoleProperties(accessToken:string){const response=await fetch("https://www.googleapis.com/webmasters/v3/sites",{headers:{authorization:`Bearer ${accessToken}`}});if(!response.ok)throw new Error("Search Console properties could not be loaded.");const body=await response.json() as {siteEntry?:Array<{siteUrl:string;permissionLevel:string}>};return body.siteEntry??[];}
export async function saveSearchConsoleConnection(input:{businessId:string;refreshToken:string;connectedBy:string}){const db=getSupabaseAdmin();if(!db)throw new Error("Search Console storage is unavailable.");const {error}=await db.from("business_google_search_console_connections").upsert({business_id:input.businessId,refresh_token:input.refreshToken,connected_by:input.connectedBy,status:"property_selection_required",updated_at:new Date().toISOString()},{onConflict:"business_id"});if(error)throw new Error("Search Console connection could not be saved.");}

export const normalizeSearchConsoleUrl=(value:string)=>{try{if(value.startsWith("sc-domain:"))return value.toLowerCase();const url=new URL(value);return `${url.protocol}//${url.hostname.replace(/^www\./,"").toLowerCase()}${decodeURIComponent(url.pathname).replace(/\/+$/,"")||"/"}`;}catch{return value.trim().replace(/\/+$/,"").toLowerCase();}};
export const propertyMatchesDomain=(property:string,publicUrl:string)=>{const normalized=normalizeSearchConsoleUrl(publicUrl);if(property.startsWith("sc-domain:")){try{return new URL(normalized).hostname.replace(/^www\./,"").toLowerCase()===property.slice(10).replace(/^www\./,"").toLowerCase();}catch{return false;}}return normalized.startsWith(normalizeSearchConsoleUrl(property));};
export async function refreshSearchConsoleAccessToken(refreshToken:string){const {clientId,clientSecret}=credentials();if(!clientId||!clientSecret)throw new Error("Google Search Console OAuth is not configured.");const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({refresh_token:refreshToken,client_id:clientId,client_secret:clientSecret,grant_type:"refresh_token"})});const body=await response.json() as {access_token?:string;error?:string};if(!response.ok||!body.access_token)throw new Error(body.error||"Google authorization needs to be reconnected.");return body.access_token;}
export async function syncSearchConsole(input:{businessId:string;force?:boolean}){const db=getSupabaseAdmin();if(!db)return {status:"error" as const};const {data:connection}=await db.from("business_google_search_console_connections").select("refresh_token,property_url,last_synced_at").eq("business_id",input.businessId).maybeSingle();if(!connection?.property_url||!connection.refresh_token)return {status:"not_ready" as const};if(!input.force&&connection.last_synced_at&&Date.now()-new Date(connection.last_synced_at).getTime()<6*60*60*1000)return {status:"fresh" as const};try{const token=await refreshSearchConsoleAccessToken(connection.refresh_token);const end=new Date(),start=new Date(Date.now()-28*86400000);const response=await fetch(`https://www.googleapis.com/webmasters/v3/sites/${encodeURIComponent(connection.property_url)}/searchAnalytics/query`,{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({startDate:start.toISOString().slice(0,10),endDate:end.toISOString().slice(0,10),dimensions:["page","query"],rowLimit:25000})});const body=await response.json() as {rows?:Array<{keys?:string[];clicks?:number;impressions?:number;ctr?:number;position?:number}>;error?:{code?:number}};if(!response.ok)throw new Error(String(body.error?.code??"api_error"));const today=end.toISOString().slice(0,10),rows=(body.rows??[]).map(row=>({business_id:input.businessId,property_url:connection.property_url,report_date:today,page_url:normalizeSearchConsoleUrl(row.keys?.[0]??""),query:(row.keys?.[1]??"").slice(0,500),clicks:Math.round(row.clicks??0),impressions:Math.round(row.impressions??0),ctr:row.ctr??0,position:row.position??0,synced_at:end.toISOString()})).filter(row=>row.page_url);await db.from("business_google_search_console_rows").delete().eq("business_id",input.businessId).eq("property_url",connection.property_url);if(rows.length)await db.from("business_google_search_console_rows").upsert(rows,{onConflict:"business_id,property_url,report_date,page_url,query"});await db.from("business_google_search_console_connections").update({status:"connected",last_synced_at:end.toISOString(),last_error_code:null,last_error_message:null,updated_at:end.toISOString()}).eq("business_id",input.businessId);return {status:"synced" as const};}catch(error){const message=error instanceof Error?error.message:"Search Console sync failed.";await db.from("business_google_search_console_connections").update({status:/invalid_grant|unauthorized/i.test(message)?"disconnected":"error",last_error_message:message.slice(0,200),last_error_code:"sync_failed",updated_at:new Date().toISOString()}).eq("business_id",input.businessId);return {status:"error" as const};}}

/** Backfills property discovery for connections created before the property cache existed. */
export async function ensureSearchConsoleProperties(businessId:string){const db=getSupabaseAdmin();if(!db)return {status:"error" as const,properties:[] as Array<{siteUrl:string;permissionLevel:string}>};const {data:connection}=await db.from("business_google_search_console_connections").select("refresh_token,available_properties,status").eq("business_id",businessId).maybeSingle();const cached=Array.isArray(connection?.available_properties)?connection.available_properties as Array<{siteUrl:string;permissionLevel:string}>:[];if(cached.length)return {status:"cached" as const,properties:cached};if(!connection?.refresh_token)return {status:"error" as const,properties:[] as Array<{siteUrl:string;permissionLevel:string}>};try{const token=await refreshSearchConsoleAccessToken(connection.refresh_token),properties=await listSearchConsoleProperties(token);const message=properties.length?null:"No Search Console properties found for this Google account.";const {error}=await db.from("business_google_search_console_connections").update({available_properties:properties,status:properties.length?"property_selection_required":"error",last_error_code:properties.length?null:"no_properties",last_error_message:message,updated_at:new Date().toISOString()}).eq("business_id",businessId);if(error)throw error;return {status:properties.length?"discovered" as const:"empty" as const,properties};}catch(error){const reason=error instanceof Error?error.message:"Property discovery failed.";console.error("google_search_console_property_discovery_failed",{businessId,reason:reason.slice(0,200)});await db.from("business_google_search_console_connections").update({status:"error",last_error_code:"property_discovery_failed",last_error_message:"Search Console properties could not be loaded. Try again shortly.",updated_at:new Date().toISOString()}).eq("business_id",businessId);return {status:"error" as const,properties:[] as Array<{siteUrl:string;permissionLevel:string}>};}}
