import type {SupabaseClient} from "@supabase/supabase-js";
import {sendTwilioMessage} from "@/lib/communications/twilioMessage";

type Lead={id:string;business_id:string;customer_id:string|null;job_id:string|null;from_phone_e164:string;to_phone_e164:string;lead_status:string;conversation_status:string;customer_name:string|null;service_address:string|null;issue_summary:string|null;urgency:string;requested_start_at:string|null;extracted_data:Record<string,unknown>;alerted_at:string|null};
type Settings={ai_enabled:boolean;ai_instructions:string;booking_enabled:boolean;alert_phone_e164:string|null};
type AiDecision={reply:string;customer_name:string|null;service_address:string|null;issue_summary:string|null;urgency:"unknown"|"low"|"normal"|"high"|"emergency";requested_start_at:string|null;service_query:string|null;booking_confirmed:boolean;qualified:boolean;lost:boolean};

const emergencyPattern=/\b(gas leak|fire|smoke|carbon monoxide|co alarm|flooding|burst pipe|sparks|electrical fire|no heat|medical emergency|emergency)\b/i;
const optOutPattern=/^(STOP|STOPALL|UNSUBSCRIBE|CANCEL|END|QUIT)([\s.,!?]|$)/i;

function fallbackDecision(lead:Lead,latest:string):AiDecision{
 const emergency=emergencyPattern.test(latest),name=lead.customer_name,address=lead.service_address,issue=lead.issue_summary||latest;
 const reply=emergency?"This may be urgent. If anyone is in immediate danger, call 911 or the appropriate emergency service now. We’re alerting the service team. What is the service address?":!name?"Thanks for replying. What is your full name?":!address?`Thanks, ${name.split(" ")[0]}. What is the service address?`:!lead.issue_summary?"Please briefly describe the problem and tell us whether it is urgent.":"Thanks—we have the details and a team member will follow up. What day and time works best for service?";
 return {reply,customer_name:name,service_address:address,issue_summary:issue,urgency:emergency?"emergency":lead.urgency as AiDecision["urgency"],requested_start_at:lead.requested_start_at,service_query:null,booking_confirmed:false,qualified:Boolean(name&&address&&issue),lost:false};
}

async function aiDecision(settings:Settings,lead:Lead,messages:{direction:string;body:string}[],businessName:string,timeZone:string){
 const key=process.env.OPENAI_API_KEY;if(!settings.ai_enabled||!key)return fallbackDecision(lead,messages.at(-1)?.body??"");
 const model=process.env.OPENAI_MISSED_CALL_MODEL||"gpt-4.1-mini";
 const prompt=`You handle missed-call recovery by SMS for ${businessName}, a service business. ${settings.ai_instructions}\nCurrent business timezone: ${timeZone}.\nCollect name, full service address, issue, urgency, and preferred appointment time. Ask only one concise question at a time. Never claim an appointment is booked unless the customer explicitly confirms a specific offered/known time. Treat extracted facts as unconfirmed. For emergencies, tell them to contact emergency services if anyone is in danger and say staff is being alerted. Reply STOP must never receive a message.`;
 try{
  const response=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model,temperature:0.2,messages:[{role:"system",content:prompt},{role:"user",content:JSON.stringify({known:{name:lead.customer_name,address:lead.service_address,issue:lead.issue_summary,urgency:lead.urgency,requested_start_at:lead.requested_start_at},conversation:messages.slice(-12)})}],response_format:{type:"json_schema",json_schema:{name:"missed_call_intake",strict:true,schema:{type:"object",additionalProperties:false,properties:{reply:{type:"string"},customer_name:{type:["string","null"]},service_address:{type:["string","null"]},issue_summary:{type:["string","null"]},urgency:{type:"string",enum:["unknown","low","normal","high","emergency"]},requested_start_at:{type:["string","null"],description:"ISO 8601 timestamp with timezone, or null"},service_query:{type:["string","null"]},booking_confirmed:{type:"boolean"},qualified:{type:"boolean"},lost:{type:"boolean"}},required:["reply","customer_name","service_address","issue_summary","urgency","requested_start_at","service_query","booking_confirmed","qualified","lost"]}}}})});
  const result=await response.json() as {choices?:{message?:{content?:string}}[];error?:{message?:string}};
  if(!response.ok)throw new Error(result.error?.message||`OpenAI HTTP ${response.status}`);
  return JSON.parse(result.choices?.[0]?.message?.content||"") as AiDecision;
 }catch(error){console.error("Missed-call AI intake failed",{leadId:lead.id,message:error instanceof Error?error.message:"Unknown error"});return fallbackDecision(lead,messages.at(-1)?.body??"");}
}

async function tryBook(db:SupabaseClient,lead:Lead,decision:AiDecision,timeZone:string){
 if(!decision.booking_confirmed||!decision.requested_start_at||!decision.service_address)return null;
 const start=new Date(decision.requested_start_at);if(!Number.isFinite(start.getTime())||start.getTime()<Date.now())return null;
 const {data:services}=await db.from("services").select("id,name,duration_minutes,price_amount").eq("business_id",lead.business_id).eq("active",true).eq("is_deleted",false).order("name");
 const query=(decision.service_query||decision.issue_summary||"").toLowerCase();const service=services?.find(item=>query.includes(item.name.toLowerCase()))??(services?.length===1?services[0]:null);if(!service)return null;
 const parts=new Intl.DateTimeFormat("en-US",{timeZone,weekday:"short",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(start),weekday=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].indexOf(parts.find(part=>part.type==="weekday")?.value??""),localTime=`${parts.find(part=>part.type==="hour")?.value}:${parts.find(part=>part.type==="minute")?.value}:00`;
 const {data:hours}=await db.from("booking_availability").select("start_time,end_time").eq("business_id",lead.business_id).eq("weekday",weekday).eq("active",true);if(!hours?.some(row=>localTime>=row.start_time&&localTime<row.end_time))return null;
 const end=new Date(start.getTime()+Number(service.duration_minutes||60)*60_000),{count}=await db.from("jobs").select("id",{head:true,count:"exact"}).eq("business_id",lead.business_id).lt("starts_at",end.toISOString()).gt("ends_at",start.toISOString()).not("status","in",'(canceled,declined)');if(count)return null;
 let locationId:string|null=null;const {data:existing}=await db.from("service_locations").select("id,street_address,city,state,postal_code").eq("business_id",lead.business_id).eq("customer_id",lead.customer_id!).eq("is_deleted",false);const normalized=decision.service_address.toLowerCase();locationId=existing?.find(row=>[row.street_address,row.city,row.state,row.postal_code].filter(Boolean).join(" ").toLowerCase()===normalized)?.id??null;
 if(!locationId){const {data:created}=await db.from("service_locations").insert({business_id:lead.business_id,customer_id:lead.customer_id,location_name:"Missed-call service address",street_address:decision.service_address,city:"Needs verification",state:"N/A",postal_code:"N/A",country:"US",property_notes:"AI-collected address; staff verification required.",is_primary:!(existing?.length),is_active:true}).select("id").single();locationId=created?.id??null;}
 if(!locationId)return null;
 const {data:job,error}=await db.from("jobs").insert({business_id:lead.business_id,customer_id:lead.customer_id,service_location_id:locationId,service_id:service.id,title:service.name,status:"pending",starts_at:start.toISOString(),ends_at:end.toISOString(),service_address:decision.service_address,description:decision.issue_summary||"Missed-call recovery request",priority:["high","emergency"].includes(decision.urgency)?"urgent":"normal",subtotal:service.price_amount||0,tax_amount:0,booking_source:"missed_call_recovery"}).select("id,job_number").single();
 if(error){console.error("Missed-call booking failed",{leadId:lead.id,code:error.code});return null;}return job;
}

export async function advanceMissedCallConversation(db:SupabaseClient,{businessId,customerId,providerMessageId,body}:{businessId:string;customerId:string;providerMessageId:string;body:string}){
 const {data:lead}=await db.from("missed_call_recovery_leads").select("*").eq("business_id",businessId).eq("customer_id",customerId).in("conversation_status",["active","staff_review"]).order("created_at",{ascending:false}).limit(1).maybeSingle() as {data:Lead|null};if(!lead)return null;
 const duplicate=await db.from("missed_call_recovery_messages").select("id").eq("provider","twilio").eq("provider_message_id",providerMessageId).maybeSingle();if(duplicate.data)return {duplicate:true};
 await db.from("missed_call_recovery_messages").insert({business_id:businessId,lead_id:lead.id,customer_id:customerId,job_id:lead.job_id,direction:"inbound",provider_message_id:providerMessageId,body,delivery_status:"received"});
 if(optOutPattern.test(body)){await db.from("missed_call_recovery_leads").update({conversation_status:"opted_out",lead_status:lead.lead_status==="new"?"lost":lead.lead_status,last_message_at:new Date().toISOString()}).eq("id",lead.id);return {suppressed:true};}
 const [{data:settings},{data:business},{data:history}]=await Promise.all([db.from("business_missed_call_settings").select("ai_enabled,ai_instructions,booking_enabled,alert_phone_e164").eq("business_id",businessId).single(),db.from("businesses").select("name,timezone,slug").eq("id",businessId).single(),db.from("missed_call_recovery_messages").select("direction,body").eq("business_id",businessId).eq("lead_id",lead.id).order("created_at").limit(30)]);
 if(!settings||!business)return null;const decision=await aiDecision(settings as Settings,lead,history??[],business.name,business.timezone);if(emergencyPattern.test(body))decision.urgency="emergency";
 const job=settings.booking_enabled?await tryBook(db,lead,decision,business.timezone):null,now=new Date().toISOString(),leadStatus=job?"booked":decision.lost?"lost":decision.qualified?"qualified":"contacted",conversationStatus=job?"booked":decision.urgency==="emergency"?"staff_review":"active";
 await db.from("missed_call_recovery_leads").update({customer_name:decision.customer_name,service_address:decision.service_address,issue_summary:decision.issue_summary,urgency:decision.urgency,requested_start_at:decision.requested_start_at,lead_status:leadStatus,conversation_status:conversationStatus,job_id:job?.id??lead.job_id,extracted_data:{name:decision.customer_name,address:decision.service_address,issue:decision.issue_summary,urgency:decision.urgency,requested_start_at:decision.requested_start_at,verification:"unconfirmed"},last_message_at:now}).eq("id",lead.id);
 await db.from("customers").update({intake_data:{name:decision.customer_name,address:decision.service_address,issue:decision.issue_summary,urgency:decision.urgency,verification:"unconfirmed"},intake_data_verified:false}).eq("id",customerId).eq("business_id",businessId);
 if(decision.customer_name){const current=await db.from("customers").select("first_name").eq("id",customerId).eq("business_id",businessId).maybeSingle();if(["Missed Call","SMS Lead"].includes(current.data?.first_name??"")){const parts=decision.customer_name.trim().split(/\s+/);await db.from("customers").update({first_name:parts.shift()||"Customer",last_name:parts.join(" ")}).eq("id",customerId).eq("business_id",businessId);}}
 const reply=job?`You’re booked for ${new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short",timeZone:business.timezone}).format(new Date(decision.requested_start_at!))}. Your job number is ${job.job_number}.`:decision.reply.slice(0,1500);
 const outbound=await db.from("missed_call_recovery_messages").insert({business_id:businessId,lead_id:lead.id,customer_id:customerId,job_id:job?.id??lead.job_id,direction:"outbound",body:reply,ai_generated:settings.ai_enabled,delivery_status:"pending"}).select("id").single();
 try{const sent=await sendTwilioMessage({to:lead.from_phone_e164,from:lead.to_phone_e164,body:reply});await db.from("missed_call_recovery_messages").update({provider_message_id:sent.sid,delivery_status:"sent"}).eq("id",outbound.data?.id);}catch(error){await db.from("missed_call_recovery_messages").update({delivery_status:"failed",error_message:(error instanceof Error?error.message:"Delivery failed").slice(0,1000)}).eq("id",outbound.data?.id);}
 if(["high","emergency"].includes(decision.urgency)&&settings.alert_phone_e164&&!lead.alerted_at){const alert=`${decision.urgency.toUpperCase()} missed-call lead: ${decision.customer_name||lead.from_phone_e164} — ${decision.issue_summary||body} — ${decision.service_address||"address pending"}`.slice(0,1500);try{const sent=await sendTwilioMessage({to:settings.alert_phone_e164,from:lead.to_phone_e164,body:alert});await db.from("missed_call_recovery_messages").insert({business_id:businessId,lead_id:lead.id,customer_id:customerId,job_id:job?.id??null,direction:"alert",provider_message_id:sent.sid,body:alert,delivery_status:"sent"});await db.from("missed_call_recovery_leads").update({alerted_at:now}).eq("id",lead.id);}catch(error){console.error("Missed-call emergency alert failed",{leadId:lead.id,message:error instanceof Error?error.message:"Unknown"});}}
 return {leadId:lead.id,jobId:job?.id??null};
}
