export const websiteFirstSources=["pest-control-website","car-detailing-website"] as const;
export type WebsiteFirstSource=(typeof websiteFirstSources)[number];
export type WebsiteFirstConfig={source:WebsiteFirstSource;industryLabel:string;businessHeading:string;businessDescription:string;servicesLegend:string;services:string[];defaultHero:string;defaultSubheading:string;defaultAbout:string;styleLabels:[string,string,string];defaultPrimary:string;defaultSecondary:string;progressiveActions:string[]};
const configs:Record<WebsiteFirstSource,WebsiteFirstConfig>={
 "pest-control-website":{source:"pest-control-website",industryLabel:"pest-control",businessHeading:"Tell us about your business.",businessDescription:"Just the details needed to prepare your first website preview. You can fine-tune everything later.",servicesLegend:"Pest-control services offered",services:["General Pest Control","Residential Pest Control","Commercial Pest Control","Termite Control","Rodent Control","Mosquito Control","Bed Bugs","Ants","Spiders","Roaches","Wasps","Other Pest Control"],defaultHero:"Protect Your Home From Unwanted Guests",defaultSubheading:"Reliable local pest control with clear communication and convenient service.",defaultAbout:"provides dependable local pest-control service and a straightforward customer experience.",styleLabels:["Modern","Bold","Premium"],defaultPrimary:"#1769f5",defaultSecondary:"#0b1733",progressiveActions:["Add services & pricing","Configure business hours","Enable online booking","Connect payments","Invite employees","Set up customer texting"]},
 "car-detailing-website":{source:"car-detailing-website",industryLabel:"car-detailing",businessHeading:"Tell us about your detailing business.",businessDescription:"Share the essentials and your service packages so Servonas can prepare your first detailing website preview.",servicesLegend:"Detailing services offered",services:["Interior Detail","Exterior Detail","Full Detail","Mobile Detailing","Ceramic Coating","Paint Correction","Headlight Restoration","Engine Bay Cleaning","Maintenance Detail","Fleet Detailing","Other Detailing"],defaultHero:"Your Car Deserves More Than a Wash",defaultSubheading:"Professional detailing, paint correction, and ceramic protection that makes every vehicle look its best.",defaultAbout:"provides meticulous vehicle care, straightforward packages, and convenient scheduling.",styleLabels:["Clean","Performance","Premium"],defaultPrimary:"#1677ff",defaultSecondary:"#111827",progressiveActions:["Add package pricing","Configure business hours","Set availability & service area","Enable online booking","Connect payments","Set up customer texting"]},
};
export function getWebsiteFirstConfig(value:unknown):WebsiteFirstConfig|null{return typeof value==="string"&&value in configs?configs[value as WebsiteFirstSource]:null;}
export function isWebsiteFirstSource(value:unknown):value is WebsiteFirstSource{return getWebsiteFirstConfig(value)!==null;}
