import Link from "next/link";
import {WorkspaceNav} from "../../../WorkspaceNav";
import {requireWorkspace} from "@/lib/workspace";
import {canManageCustomers} from "@/lib/access";
import {createCustomerCampaign} from "../actions";

export default async function NewCampaignPage({params,searchParams}:{params:Promise<{businessSlug:string}>;searchParams:Promise<{customers?:string;error?:string}>}){
 const {businessSlug}=await params,q=await searchParams,{supabase,business,role}=await requireWorkspace(businessSlug),canEdit=canManageCustomers(role);
 const ids=[...new Set((q.customers??"").split(",").filter(id=>/^[0-9a-f-]{36}$/i.test(id)))].slice(0,500);
 const {data:customers}=ids.length?await supabase.from("customers").select("id,first_name,last_name,company_name,email,phone,sms_consent_status").eq("business_id",business.id).eq("is_deleted",false).eq("is_active",true).in("id",ids):{data:[]};
 const selected=customers??[];
 return <main className="epic3-shell"><WorkspaceNav slug={businessSlug} name={business.name} industry={business.industry_profile}/><section className="epic3-content campaign-page"><header className="employee-page-header"><div><nav><Link href={`/app/${businessSlug}/customers`}>Customers</Link><b>›</b><Link href={`/app/${businessSlug}/customers/campaigns`}>Campaigns</Link><b>›</b><span>New</span></nav><h1>Create campaign</h1><p>Compose a message for the {selected.length} selected customer{selected.length===1?"":"s"}.</p></div></header>{q.error&&<div className="workspace-notice error">{q.error}</div>}{!selected.length?<div className="workspace-panel dashboard-empty"><strong>Select customers first</strong><p>Return to the customer list and choose the people who should receive this campaign.</p><Link className="sv-button" href={`/app/${businessSlug}/customers`}>Select customers</Link></div>:<form className="workspace-panel campaign-compose" action={createCustomerCampaign.bind(null,businessSlug)}>{selected.map(customer=><input type="hidden" name="customerIds" value={customer.id} key={customer.id}/>) }<div className="campaign-audience"><div><span>Audience</span><strong>{selected.length} selected customers</strong></div><details><summary>Review recipients</summary>{selected.map(customer=><p key={customer.id}><strong>{customer.company_name||`${customer.first_name} ${customer.last_name}`.trim()}</strong><span>{customer.email||"No email"} · {customer.phone||"No phone"} · SMS {customer.sms_consent_status.replaceAll("_"," ")}</span></p>)}</details></div><label>Campaign name<input name="name" required maxLength={160} placeholder="Fall service reminder"/></label><label>Channel<select name="channel" defaultValue="email"><option value="email">Email</option><option value="sms">Text message</option></select><small>Text campaigns only send to customers with explicit SMS consent.</small></label><label>Email subject<input name="subject" maxLength={200} placeholder="Time to schedule your fall service"/><small>Required for email campaigns; ignored for text messages.</small></label><label className="wide">Message<textarea name="body" required maxLength={5000} rows={10} placeholder={`Hi {first_name},\n\nIt’s time to schedule your next service with {business_name}.`}/><small>Personalization: {`{first_name}, {last_name}, {customer_name}, {business_name}`}. URLs are click-tracked. Email opens are tracked when the recipient allows images.</small></label>{canEdit&&<button className="sv-button">Create campaign draft</button>}</form>}</section></main>;
}
