import {NextResponse} from "next/server";
import {searchBusinessPhoneNumbers} from "@/lib/twilio/phoneNumbers";
import {getBusinessAreaCodeSuggestion} from "@/lib/twilio/areaCodeSuggestions";
import {requireTwilioPlatformAdmin,uuidPattern} from "@/lib/twilio/adminRoute";
import {requireBusinessTwilioEnabled} from "@/lib/twilio/access";

export async function GET(request:Request){const unauthorized=await requireTwilioPlatformAdmin();if(unauthorized)return unauthorized;const businessId=new URL(request.url).searchParams.get("businessId")??"";if(!uuidPattern.test(businessId))return NextResponse.json({error:"A valid businessId is required."},{status:400});try{return NextResponse.json({suggestion:await getBusinessAreaCodeSuggestion(businessId)});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Area-code suggestion failed."},{status:409});}}

export async function POST(request:Request){const unauthorized=await requireTwilioPlatformAdmin();if(unauthorized)return unauthorized;let body:{businessId?:string;areaCode?:string;fallbackAreaCodes?:string[];mms?:boolean;voice?:boolean};try{body=await request.json();}catch{return NextResponse.json({error:"A JSON request body is required."},{status:400});}if(!body.businessId||!uuidPattern.test(body.businessId))return NextResponse.json({error:"A valid businessId is required."},{status:400});try{await requireBusinessTwilioEnabled(body.businessId);const suggestion=await getBusinessAreaCodeSuggestion(body.businessId),areaCode=body.areaCode?.trim()||suggestion.preferredAreaCode;if(!areaCode||!/^\d{3}$/.test(areaCode))return NextResponse.json({error:"Choose a valid US area code before searching.",suggestion},{status:400});const fallbackAreaCodes=body.fallbackAreaCodes??(body.areaCode?[]:suggestion.fallbackAreaCodes);return NextResponse.json({suggestion,selectedAreaCode:areaCode,selectionSource:body.areaCode?"override":suggestion.source,numbers:await searchBusinessPhoneNumbers(body.businessId,{areaCode,fallbackAreaCodes,mms:body.mms,voice:body.voice})});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Number search failed."},{status:409});}}
