import Link from "next/link";
import {notFound} from "next/navigation";
import {canManageBusiness} from "@/lib/access";
import {EmployeeForm} from "@/components/EmployeeForm";
import {EmployeeAvailability} from "@/components/EmployeeAvailability";
import {EmployeeQualifications} from "@/components/EmployeeQualifications";
import {EmployeeTerritories} from "@/components/EmployeeTerritories";
import {EmployeeAssets} from "@/components/EmployeeAssets";
import {EmployeePreferences} from "@/components/EmployeePreferences";
import {requireWorkspace} from "@/lib/workspace";
import {WorkspaceNav} from "../../WorkspaceNav";
import {addEmployeeAvailabilityException,addEmployeeQualification,assignEmployeeTerritory,assignWorkforceAsset,createEmployeeTerritory,createWorkforceAsset,deleteEmployeeAvailabilityException,endEmployeeQualification,endEmployeeTerritory,returnWorkforceAsset,saveEmployeeAvailability,saveEmployeePreferences,updateEmployee} from "../workforceActions";
import {disableTechnician,enableTechnician,inviteTeamMember,resendInvitation,revokeInvitation,updateTeamMemberRole} from "../actions";

export default async function EmployeePage({params,searchParams}:{params:Promise<{businessSlug:string;employeeId:string}>;searchParams:Promise<Record<string,string|undefined>>}){
 const {businessSlug,employeeId}=await params,q=await searchParams,{supabase,business,role}=await requireWorkspace(businessSlug),canEdit=canManageBusiness(role);
 const [{data:employee},{data:roles},{data:assignments},{data:managers},{data:availability},{data:intervals},{data:exceptions},{data:qualifications},{data:qualificationDefinitions},{data:territories},{data:territoryAssignments},{data:assets},{data:assetAssignments},{data:preferences,error:preferencesError}]=await Promise.all([
  supabase.from("employees").select("*").eq("business_id",business.id).eq("id",employeeId).maybeSingle(),
  supabase.from("workforce_roles").select("id,name").eq("business_id",business.id).eq("is_active",true).order("name"),
  supabase.from("employee_role_assignments").select("workforce_role_id").eq("business_id",business.id).eq("employee_id",employeeId).eq("is_active",true),
  supabase.from("employees").select("id,preferred_name").eq("business_id",business.id).eq("is_active",true).neq("id",employeeId).order("preferred_name"),
  supabase.from("employee_availability_profiles").select("time_zone,maximum_daily_jobs,maximum_daily_minutes,overtime_preference").eq("business_id",business.id).eq("employee_id",employeeId).maybeSingle(),
  supabase.from("employee_weekly_intervals").select("id,weekday,interval_type,starts_at,ends_at").eq("business_id",business.id).eq("employee_id",employeeId).order("weekday").order("starts_at"),
  supabase.from("employee_availability_exceptions").select("id,exception_type,starts_at,ends_at,availability_effect,approval_status,reason").eq("business_id",business.id).eq("employee_id",employeeId).neq("approval_status","cancelled").gte("ends_at",new Date().toISOString()).order("starts_at"),
  supabase.from("employee_qualifications").select("id,status,proficiency_level,credential_number,issuing_authority,issued_on,expires_on,notes,workforce_qualifications!employee_qualifications_definition_tenant_fk(id,qualification_type,name)").eq("business_id",business.id).eq("employee_id",employeeId).order("assigned_at",{ascending:false}),
  supabase.from("workforce_qualifications").select("id,qualification_type,name").eq("business_id",business.id).eq("is_active",true).order("name"),
  supabase.from("workforce_territories").select("id,name,territory_type,postal_codes,neighborhoods,color").eq("business_id",business.id).eq("is_active",true).order("name"),
  supabase.from("employee_territory_assignments").select("id,assignment_type,effective_from,effective_through,notes,workforce_territories!employee_territories_territory_fk(id,name,territory_type,postal_codes,neighborhoods)").eq("business_id",business.id).eq("employee_id",employeeId).is("ended_at",null).order("assignment_type"),
  supabase.from("workforce_assets").select("id,asset_type,name,asset_number,serial_number,manufacturer,model,condition,status").eq("business_id",business.id).eq("status","available").order("name"),
  supabase.from("employee_asset_assignments").select("id,assigned_at,expected_return_at,assignment_condition,assignment_notes,workforce_assets!employee_assets_asset_fk(id,asset_type,name,asset_number,serial_number,manufacturer,model,condition,status)").eq("business_id",business.id).eq("employee_id",employeeId).is("returned_at",null).order("assigned_at",{ascending:false}),
  supabase.from("employee_scheduling_preferences").select("preferred_work_types,avoided_work_types,preferred_start_time,preferred_end_time,workload_preference,customer_interaction_preference,notes").eq("business_id",business.id).eq("employee_id",employeeId).maybeSingle(),
 ]);
 if(!employee)notFound();
 const [{data:membership},{data:technician},{data:invitation}]=await Promise.all([
  employee.auth_user_id?supabase.from("business_members").select("user_id,role").eq("business_id",business.id).eq("user_id",employee.auth_user_id).maybeSingle():Promise.resolve({data:null}),
  employee.auth_user_id?supabase.from("technician_directory").select("id,is_active,is_technician,can_be_assigned_jobs").eq("business_id",business.id).eq("member_user_id",employee.auth_user_id).maybeSingle():Promise.resolve({data:null}),
  employee.email?supabase.from("business_invitations").select("id,role,expires_at").eq("business_id",business.id).ilike("email",employee.email).is("accepted_at",null).gt("expires_at",new Date().toISOString()).order("created_at",{ascending:false}).limit(1).maybeSingle():Promise.resolve({data:null}),
 ]);
 const technicianEnabled=Boolean(technician?.is_active&&technician.is_technician&&technician.can_be_assigned_jobs);
 const selectedRoleIds=(assignments??[]).map(item=>item.workforce_role_id),selectedRoles=(roles??[]).filter(item=>selectedRoleIds.includes(item.id));
 const manager=(managers??[]).find(item=>item.id===employee.manager_employee_id),workingDays=new Set((intervals??[]).filter(item=>item.interval_type==="working").map(item=>item.weekday)).size;
 const activeQualifications=(qualifications??[]).filter(item=>item.status==="active").length;
 const status=employee.is_active?String(employee.employment_status??"active"):"inactive";
 const employeeAddress=[employee.address_line_1,employee.address_line_2,employee.city,[employee.state,employee.postal_code].filter(Boolean).join(" "),employee.country&&employee.country!=="US"?employee.country:null].filter(Boolean).join(", ");
 return <main className="epic3-shell"><WorkspaceNav slug={businessSlug} name={business.name} industry={business.industry_profile}/><section className="epic3-content customer-record-page employee-record-page">
  <header className="customer-record-header"><div><small><Link href={`/app/${businessSlug}/team`}>Team</Link> › {employee.preferred_name}</small><h1>{employee.preferred_name} <span className={`customer-record-status ${employee.is_active?"active":"inactive"}`}>{status.replaceAll("_"," ")}</span></h1><p>{employee.job_title||employee.employee_type?.replaceAll("_"," ")||"Team member"}{employee.employee_number?` · Employee #${employee.employee_number}`:""}</p></div><div className="crm-header-actions">{employee.phone&&<a className="sv-button sv-secondary" href={`tel:${employee.phone}`}>Call</a>}{employee.email&&<a className="sv-button sv-secondary" href={`mailto:${employee.email}`}>Email</a>}<Link className="sv-button sv-secondary" href={`/app/${businessSlug}/team`}>Back to team</Link></div></header>
  {q.success&&<div className="workspace-notice success">{q.success}</div>}{q.error&&<div className="workspace-notice error">{q.error}</div>}
  <section className="customer-record-metrics employee-record-metrics"><article><span>Workforce roles</span><strong>{selectedRoles.length}</strong><small>{selectedRoles[0]?.name??"No role assigned"}</small></article><article><span>Working days</span><strong>{workingDays}</strong><small>Days configured weekly</small></article><article><span>Qualifications</span><strong>{activeQualifications}</strong><small>Active skills and credentials</small></article><article><span>Territories</span><strong>{territoryAssignments?.length??0}</strong><small>Current assignments</small></article><article><span>Assets</span><strong>{assetAssignments?.length??0}</strong><small>Vehicles and equipment</small></article><article><span>Exceptions</span><strong>{exceptions?.length??0}</strong><small>Upcoming availability changes</small></article></section>
  <nav className="customer-record-tabs"><span>Overview</span><a href="#availability">Availability</a><a href="#qualifications">Qualifications <b>{activeQualifications}</b></a><a href="#territories">Territories <b>{territoryAssignments?.length??0}</b></a><a href="#assets">Assets <b>{assetAssignments?.length??0}</b></a><a href="#preferences">Preferences</a></nav>
  <div className="customer-record-columns employee-record-columns"><div className="customer-record-main">
   {canEdit?<details className="workspace-panel employee-profile-editor"><summary><span><strong>Employee profile</strong><small>Contact details, employment information, manager, and roles</small></span><b>Edit profile</b></summary><EmployeeForm action={updateEmployee.bind(null,businessSlug,employeeId)} roles={roles??[]} managers={managers??[]} employee={employee} selectedRoleIds={selectedRoleIds} submitLabel="Save employee"/></details>:<section className="workspace-panel"><div className="panel-title"><h2>Employee profile</h2></div><dl className="crm-summary"><div><dt>Legal name</dt><dd>{employee.legal_name||"Not provided"}</dd></div><div><dt>Email</dt><dd>{employee.email||"Not provided"}</dd></div><div><dt>Phone</dt><dd>{employee.phone||"Not provided"}</dd></div><div><dt>Employee number</dt><dd>{employee.employee_number||"Not provided"}</dd></div></dl></section>}
   <div id="availability">{availability?<EmployeeAvailability profile={availability} intervals={intervals??[]} exceptions={exceptions??[]} canEdit={canEdit} saveAction={saveEmployeeAvailability.bind(null,businessSlug,employeeId)} addExceptionAction={addEmployeeAvailabilityException.bind(null,businessSlug,employeeId)} deleteExceptionAction={deleteEmployeeAvailabilityException.bind(null,businessSlug,employeeId)}/>:<section className="workspace-panel"><div className="workspace-notice error">Apply the Epic 8 Checkpoint 2 migration to configure employee availability.</div></section>}</div>
   <div id="qualifications">{qualifications&&qualificationDefinitions?<EmployeeQualifications assignments={qualifications} definitions={qualificationDefinitions} canEdit={canEdit} addAction={addEmployeeQualification.bind(null,businessSlug,employeeId)} endAction={endEmployeeQualification.bind(null,businessSlug,employeeId)}/>:<section className="workspace-panel"><div className="workspace-notice error">Apply the Epic 8 Checkpoint 3 migration to manage skills and credentials.</div></section>}</div>
  </div><aside className="customer-record-aside employee-record-aside">
   <section className="workspace-panel customer-side-card"><div className="panel-title"><h2>Employee information</h2><span className={`employee-state ${employee.is_active?"active":"inactive"}`}>{status.replaceAll("_"," ")}</span></div><dl className="employee-record-facts"><div><dt>Email</dt><dd>{employee.email||"Not provided"}</dd></div><div><dt>Phone</dt><dd>{employee.phone||"Not provided"}</dd></div>{employee.secondary_phone&&<div><dt>Secondary phone</dt><dd>{employee.secondary_phone}</dd></div>}{employeeAddress&&<div className="employee-address-fact"><dt>Home address</dt><dd>{employeeAddress}</dd></div>}<div><dt>Type</dt><dd>{employee.employee_type?.replaceAll("_"," ")||"Not provided"}</dd></div><div><dt>Manager</dt><dd>{manager?.preferred_name||"No manager"}</dd></div><div><dt>Hire date</dt><dd>{employee.hire_date||"Not provided"}</dd></div><div><dt>Time zone</dt><dd>{availability?.time_zone||business.timezone}</dd></div>{employee.emergency_contact_name&&<div><dt>Emergency contact</dt><dd>{employee.emergency_contact_name}{employee.emergency_contact_relationship?` · ${employee.emergency_contact_relationship}`:""}{employee.emergency_contact_phone?<><br/>{employee.emergency_contact_phone}</>:null}</dd></div>}</dl></section>
   <section className="workspace-panel customer-side-card"><div className="panel-title"><h2>Workforce roles</h2><span>{selectedRoles.length}</span></div><div className="employee-record-role-list">{selectedRoles.length?selectedRoles.map(item=><span key={item.id}>{item.name}</span>):<p>No workforce roles assigned.</p>}</div></section>
   <section className="workspace-panel customer-side-card employee-access-controls"><div className="panel-title"><h2>Workspace access</h2><span className={`employee-state ${membership?"active":invitation?"invited":"inactive"}`}>{membership?"Active":invitation?"Invited":"No access"}</span></div>{membership?<><dl className="employee-record-facts"><div><dt>Workspace role</dt><dd>{membership.role}</dd></div><div><dt>Technician access</dt><dd>{technicianEnabled?"Enabled":"Off"}</dd></div></dl>{canEdit&&<div className="employee-access-actions">{membership.role!=="owner"&&<form action={updateTeamMemberRole.bind(null,businessSlug)}><input type="hidden" name="memberUserId" value={membership.user_id}/><label>Workspace role<select name="role" defaultValue={membership.role}><option value="staff">Staff</option><option value="manager">Manager</option><option value="admin">Administrator</option></select></label><button className="sv-button sv-secondary">Save role</button></form>}<form action={(technicianEnabled?disableTechnician:enableTechnician).bind(null,businessSlug)}><input type="hidden" name="memberUserId" value={membership.user_id}/><button className={`sv-button ${technicianEnabled?"danger":""}`}>{technicianEnabled?"Disable technician access":"Enable technician access"}</button></form></div>}</>:invitation?<><p>A {invitation.role} invitation is pending until {new Date(invitation.expires_at).toLocaleDateString()}.</p>{canEdit&&<div className="employee-access-actions inline"><form action={resendInvitation.bind(null,businessSlug)}><input type="hidden" name="invitationId" value={invitation.id}/><button className="sv-button sv-secondary">Resend invitation</button></form><form action={revokeInvitation.bind(null,businessSlug)}><input type="hidden" name="invitationId" value={invitation.id}/><button className="sv-button danger">Revoke</button></form></div>}</>:<><p>This employee does not have login access.</p>{canEdit&&employee.email&&<form action={inviteTeamMember.bind(null,businessSlug)} className="employee-access-invite"><input type="hidden" name="email" value={employee.email}/><label>Workspace role<select name="role" defaultValue="staff"><option value="staff">Staff</option><option value="manager">Manager</option><option value="admin">Administrator</option></select></label><button className="sv-button">Invite to workspace</button></form>}</>}</section>
   <div id="territories">{territories&&territoryAssignments?<EmployeeTerritories territories={territories} assignments={territoryAssignments} canEdit={canEdit} createAction={createEmployeeTerritory.bind(null,businessSlug,employeeId)} assignAction={assignEmployeeTerritory.bind(null,businessSlug,employeeId)} endAction={endEmployeeTerritory.bind(null,businessSlug,employeeId)}/>:<section className="workspace-panel"><div className="workspace-notice error">Apply the Epic 8 Checkpoint 4 migration to manage territories.</div></section>}</div>
   <div id="assets">{assets&&assetAssignments?<EmployeeAssets assets={assets} assignments={assetAssignments} canEdit={canEdit} createAction={createWorkforceAsset.bind(null,businessSlug,employeeId)} assignAction={assignWorkforceAsset.bind(null,businessSlug,employeeId)} returnAction={returnWorkforceAsset.bind(null,businessSlug,employeeId)}/>:<section className="workspace-panel"><div className="workspace-notice error">Apply the Epic 8 Checkpoint 5 migration to manage vehicles and equipment.</div></section>}</div>
   <div id="preferences">{!preferencesError?<EmployeePreferences preferences={preferences} canEdit={canEdit} action={saveEmployeePreferences.bind(null,businessSlug,employeeId)}/>:<section className="workspace-panel"><div className="workspace-notice error">Apply the Epic 8 Checkpoint 7 migration to manage workforce preferences.</div></section>}</div>
  </aside></div>
 </section></main>;
}
