import Link from "next/link";
import {WorkspaceNav} from "../../WorkspaceNav";
import {requireWorkspace} from "@/lib/workspace";
import {canManageCustomers} from "@/lib/access";

export default async function CampaignsPage({params,searchParams}:{params:Promise<{businessSlug:string}>;searchParams:Promise<{error?:string}>}){
 const {businessSlug}=await params,q=await searchParams,{supabase,business,role}=await requireWorkspace(businessSlug),canEdit=canManageCustomers(role);
 const {data:campaigns,error}=await supabase.from("customer_campaigns").select("id,name,channel,status,recipient_count,sent_count,delivered_count,opened_count,clicked_count,failed_count,skipped_count,created_at,completed_at").eq("business_id",business.id).order("created_at",{ascending:false}).limit(100);
 return <main className="epic3-shell"><WorkspaceNav slug={businessSlug} name={business.name} industry={business.industry_profile}/><section className="epic3-content campaign-page"><header className="employee-page-header"><div><nav><Link href={`/app/${businessSlug}/customers`}>Customers</Link><b>›</b><span>Campaigns</span></nav><h1>Customer campaigns</h1><p>Send targeted email or text campaigns and follow delivery and engagement.</p></div>{canEdit&&<Link className="sv-button" href={`/app/${businessSlug}/customers`}>Select customers</Link>}</header>{q.error&&<div className="workspace-notice error">{q.error}</div>}{error&&<div className="workspace-notice error">Campaigns could not be loaded. Apply the campaign migration.</div>}<section className="campaign-summary"><article><span>Campaigns</span><strong>{campaigns?.length??0}</strong></article><article><span>Recipients</span><strong>{(campaigns??[]).reduce((sum,row)=>sum+row.recipient_count,0)}</strong></article><article><span>Delivered</span><strong>{(campaigns??[]).reduce((sum,row)=>sum+row.delivered_count,0)}</strong></article><article><span>Clicks</span><strong>{(campaigns??[]).reduce((sum,row)=>sum+row.clicked_count,0)}</strong></article></section><section className="workspace-panel campaign-list"><div className="campaign-list-head"><span>Campaign</span><span>Channel</span><span>Recipients</span><span>Results</span><span>Status</span></div>{campaigns?.map(campaign=><Link href={`/app/${businessSlug}/customers/campaigns/${campaign.id}`} key={campaign.id}><span><strong>{campaign.name}</strong><small>{new Date(campaign.created_at).toLocaleDateString()}</small></span><b>{campaign.channel}</b><span>{campaign.recipient_count}</span><span>{campaign.sent_count} sent · {campaign.delivered_count} delivered · {campaign.clicked_count} clicked</span><em className={`campaign-status ${campaign.status}`}>{campaign.status.replaceAll("_"," ")}</em></Link>)}{!campaigns?.length&&!error&&<div className="dashboard-empty"><strong>No campaigns yet</strong><p>Select customers from the customer list to create your first campaign.</p><Link className="sv-button" href={`/app/${businessSlug}/customers`}>Open customer list</Link></div>}</section></section></main>;
}
