import Link from "next/link";
import {canManageBusiness} from "@/lib/access";
import {requireWorkspaceCapability} from "@/lib/workspace";
import {WorkspaceNav} from "../WorkspaceNav";
import {addMaintenanceEvent,assignEquipment,createEquipment,returnEquipment,updateEquipment} from "./actions";

const relation=<T,>(value:T|T[]|null)=>Array.isArray(value)?value[0]??null:value;
const label=(value:string)=>value.replaceAll("_"," ");
const date=(value:string|null|undefined)=>value?new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeZone:"UTC"}).format(new Date(`${value.slice(0,10)}T12:00:00Z`)):"—";

export default async function EquipmentPage({params,searchParams}:{params:Promise<{businessSlug:string}>;searchParams:Promise<Record<string,string|undefined>>}){
 const {businessSlug}=await params,q=await searchParams,{supabase,business,role}=await requireWorkspaceCapability(businessSlug,"team_management"),canEdit=canManageBusiness(role);
 const [{data:assets,error},{data:assignments},{data:employees},{data:maintenance}]=await Promise.all([
  supabase.from("workforce_assets").select("id,asset_type,name,asset_number,serial_number,manufacturer,model,model_year,license_plate,vin,status,condition,notes,odometer_miles,registration_expires_on,insurance_expires_on,last_service_on,next_service_on,next_service_odometer_miles,gps_device_id,created_at").eq("business_id",business.id).order("name"),
  supabase.from("employee_asset_assignments").select("id,asset_id,employee_id,assigned_at,expected_return_at,assignment_notes,employees!employee_assets_employee_fk(id,preferred_name)").eq("business_id",business.id).is("returned_at",null),
  supabase.from("employees").select("id,preferred_name").eq("business_id",business.id).eq("is_active",true).order("preferred_name"),
  supabase.from("workforce_asset_maintenance_events").select("id,asset_id,event_type,status,title,description,service_provider,scheduled_for,completed_on,odometer_miles,cost,created_at").eq("business_id",business.id).order("created_at",{ascending:false}).limit(500),
 ]);
 const search=(q.q??"").trim().toLowerCase(),type=q.type??"all",status=q.status??"all",soon=new Date(Date.now()+30*86_400_000).toISOString().slice(0,10);
 const rows=(assets??[]).filter(asset=>(type==="all"||asset.asset_type===type)&&(status==="all"||asset.status===status)&&(!search||[asset.name,asset.asset_number,asset.license_plate,asset.vin,asset.manufacturer,asset.model].some(value=>String(value??"").toLowerCase().includes(search))));
 const selected=(assets??[]).find(asset=>asset.id===q.asset)??null,selectedAssignment=selected?assignments?.find(item=>item.asset_id===selected.id):null,selectedEmployee=relation(selectedAssignment?.employees??null),selectedMaintenance=(maintenance??[]).filter(item=>item.asset_id===selected?.id);
 const fleet=(assets??[]).filter(asset=>["vehicle","trailer"].includes(asset.asset_type)),maintenanceDue=(assets??[]).filter(asset=>asset.status==="maintenance"||Boolean(asset.next_service_on&&asset.next_service_on<=soon)||Boolean(asset.registration_expires_on&&asset.registration_expires_on<=soon)||Boolean(asset.insurance_expires_on&&asset.insurance_expires_on<=soon));
 if(error)console.error("Equipment directory failed",{businessId:business.id,code:error.code});
 const href=(assetId:string)=>`/app/${businessSlug}/equipment?asset=${assetId}${search?`&q=${encodeURIComponent(search)}`:""}`;
 return <main className="epic3-shell"><WorkspaceNav slug={businessSlug} name={business.name} industry={business.industry_profile}/><section className="epic3-content equipment-page">
  <header className="employee-page-header"><div><nav aria-label="Breadcrumb"><span>Assets</span><b aria-hidden="true">›</b><span>Equipment &amp; Fleet</span></nav><h1>Equipment &amp; fleet</h1><p>Track vehicles, trailers, tools, custody, mileage, compliance dates, and maintenance.</p></div>{canEdit&&<details className="equipment-create"><summary className="sv-button">＋ Add equipment</summary><form action={createEquipment.bind(null,businessSlug)}><label>Name<input required name="name"/></label><label>Type<select name="assetType" defaultValue="vehicle"><option value="vehicle">Vehicle</option><option value="trailer">Trailer</option><option value="equipment">Equipment</option><option value="tablet">Tablet</option><option value="key">Key</option><option value="safety_equipment">Safety equipment</option><option value="other">Other</option></select></label><label>Asset number<input name="assetNumber"/></label><label>Manufacturer<input name="manufacturer"/></label><label>Model<input name="model"/></label><label>Year<input name="modelYear" type="number" min="1900" max="2200"/></label><label>License plate<input name="licensePlate"/></label><label>VIN<input name="vin"/></label><label>Serial number<input name="serialNumber"/></label><label>Current mileage<input name="odometerMiles" type="number" min="0"/></label><label>Condition<select name="condition" defaultValue="good"><option value="new">New</option><option value="good">Good</option><option value="fair">Fair</option><option value="poor">Poor</option><option value="out_of_service">Out of service</option></select></label><label>Registration expires<input name="registrationExpiresOn" type="date"/></label><label>Insurance expires<input name="insuranceExpiresOn" type="date"/></label><label>Next service date<input name="nextServiceOn" type="date"/></label><label>Service due mileage<input name="nextServiceOdometerMiles" type="number" min="0"/></label><label className="wide">Notes<textarea name="notes"/></label><button className="sv-button">Add equipment</button></form></details>}</header>
  {q.error&&<div className="workspace-notice error">{q.error}</div>}{q.success&&<div className="workspace-notice success">{q.success}</div>}
  <section className="equipment-metrics"><article><span>Total equipment</span><strong>{assets?.length??0}</strong><small>All operational assets</small></article><article><span>Fleet units</span><strong>{fleet.length}</strong><small>Vehicles and trailers</small></article><article><span>Assigned</span><strong>{assets?.filter(asset=>asset.status==="assigned").length??0}</strong><small>Currently in employee custody</small></article><article className={maintenanceDue.length?"warning":""}><span>Needs attention</span><strong>{maintenanceDue.length}</strong><small>Service, documents, or condition</small></article></section>
  <section className={`equipment-workspace${selected?" selected":""}`}><div className="workspace-panel equipment-directory"><form className="equipment-filters"><label className="employee-search"><input name="q" defaultValue={q.q??""} placeholder="Search name, plate, VIN, asset number..."/><b aria-hidden="true">⌕</b></label><label>Type<select name="type" defaultValue={type}><option value="all">All types</option><option value="vehicle">Vehicles</option><option value="trailer">Trailers</option><option value="equipment">Equipment</option><option value="tablet">Tablets</option><option value="safety_equipment">Safety equipment</option><option value="other">Other</option></select></label><label>Status<select name="status" defaultValue={status}><option value="all">All statuses</option><option value="available">Available</option><option value="assigned">Assigned</option><option value="maintenance">Maintenance</option><option value="retired">Retired</option><option value="lost">Lost</option></select></label><button className="sv-button sv-secondary">Filter</button></form><div className="equipment-grid">{rows.map(asset=>{const assignment=assignments?.find(item=>item.asset_id===asset.id),employee=relation(assignment?.employees??null),due=maintenanceDue.some(item=>item.id===asset.id);return <Link href={href(asset.id)} className={`${asset.status}${selected?.id===asset.id?" active":""}`} key={asset.id}><div className="equipment-card-icon">{asset.asset_type==="vehicle"?"▰":asset.asset_type==="trailer"?"▱":"◇"}</div><div><span>{label(asset.asset_type)}</span><strong>{asset.name}</strong><small>{[asset.model_year,asset.manufacturer,asset.model].filter(Boolean).join(" ")||asset.asset_number||"No vehicle details"}</small><small>{asset.license_plate?`Plate ${asset.license_plate}`:asset.vin?`VIN …${asset.vin.slice(-6)}`:"No plate or VIN"}</small></div><aside><b className={`employee-state ${asset.status}`}>{label(asset.status)}</b>{due&&<em>Needs attention</em>}<small>{employee?`Assigned to ${employee.preferred_name}`:"Unassigned"}</small></aside></Link>})}{!rows.length&&<div className="dashboard-empty"><strong>No matching equipment.</strong><p>Add an asset or adjust the filters.</p></div>}</div></div>
   {selected&&<aside className="workspace-panel equipment-detail"><header><div><span>{label(selected.asset_type)}</span><h2>{selected.name}</h2><p>{[selected.model_year,selected.manufacturer,selected.model].filter(Boolean).join(" ")}</p></div><Link href={`/app/${businessSlug}/equipment`}>×</Link></header><dl><div><dt>Status</dt><dd>{label(selected.status)}</dd></div><div><dt>Condition</dt><dd>{label(selected.condition)}</dd></div><div><dt>Mileage</dt><dd>{selected.odometer_miles?.toLocaleString()??"—"}</dd></div><div><dt>Plate</dt><dd>{selected.license_plate||"—"}</dd></div><div><dt>VIN</dt><dd>{selected.vin||"—"}</dd></div><div><dt>Assigned to</dt><dd>{selectedEmployee?.preferred_name||"Unassigned"}</dd></div><div><dt>Registration</dt><dd>{date(selected.registration_expires_on)}</dd></div><div><dt>Insurance</dt><dd>{date(selected.insurance_expires_on)}</dd></div><div><dt>Next service</dt><dd>{date(selected.next_service_on)}{selected.next_service_odometer_miles?` or ${selected.next_service_odometer_miles.toLocaleString()} mi`:""}</dd></div></dl>
    {canEdit&&<details><summary>Edit fleet details</summary><form action={updateEquipment.bind(null,businessSlug,selected.id)}><label>Status<select name="status" defaultValue={selected.status}><option value="available">Available</option><option value="assigned">Assigned</option><option value="maintenance">Maintenance</option><option value="retired">Retired</option><option value="lost">Lost</option></select></label><label>Condition<select name="condition" defaultValue={selected.condition}><option value="new">New</option><option value="good">Good</option><option value="fair">Fair</option><option value="poor">Poor</option><option value="out_of_service">Out of service</option></select></label><label>Mileage<input name="odometerMiles" type="number" min="0" defaultValue={selected.odometer_miles??""}/></label><label>Registration expires<input name="registrationExpiresOn" type="date" defaultValue={selected.registration_expires_on??""}/></label><label>Insurance expires<input name="insuranceExpiresOn" type="date" defaultValue={selected.insurance_expires_on??""}/></label><label>Last service<input name="lastServiceOn" type="date" defaultValue={selected.last_service_on??""}/></label><label>Next service<input name="nextServiceOn" type="date" defaultValue={selected.next_service_on??""}/></label><label>Service due mileage<input name="nextServiceOdometerMiles" type="number" min="0" defaultValue={selected.next_service_odometer_miles??""}/></label><label>GPS device ID<input name="gpsDeviceId" defaultValue={selected.gps_device_id??""}/></label><label>Notes<textarea name="notes" defaultValue={selected.notes??""}/></label><button className="sv-button">Save details</button></form></details>}
    {canEdit&&!selectedAssignment&&selected.status==="available"&&<details><summary>Assign to employee</summary><form action={assignEquipment.bind(null,businessSlug,selected.id)}><label>Employee<select required name="employeeId" defaultValue=""><option value="" disabled>Choose employee</option>{employees?.map(employee=><option key={employee.id} value={employee.id}>{employee.preferred_name}</option>)}</select></label><label>Expected return<input name="expectedReturnAt" type="datetime-local"/></label><label>Notes<input name="assignmentNotes"/></label><button className="sv-button">Assign equipment</button></form></details>}
    {canEdit&&selectedAssignment&&<form action={returnEquipment.bind(null,businessSlug)} className="equipment-return"><input type="hidden" name="assignmentId" value={selectedAssignment.id}/><label>Return condition<select name="returnCondition" defaultValue={selected.condition}><option value="new">New</option><option value="good">Good</option><option value="fair">Fair</option><option value="poor">Poor</option><option value="out_of_service">Out of service</option></select></label><label>Return notes<input name="returnNotes"/></label><button className="sv-button sv-secondary">Record return</button></form>}
    <section className="equipment-maintenance"><div className="panel-title"><h3>Maintenance history</h3><span>{selectedMaintenance.length}</span></div>{canEdit&&<details><summary>＋ Add maintenance</summary><form action={addMaintenanceEvent.bind(null,businessSlug,selected.id)}><label>Title<input required name="title" placeholder="Oil change"/></label><label>Type<select name="eventType"><option value="preventive_service">Preventive service</option><option value="inspection">Inspection</option><option value="repair">Repair</option><option value="tire_service">Tire service</option><option value="registration">Registration</option><option value="insurance">Insurance</option><option value="other">Other</option></select></label><label>Status<select name="maintenanceStatus"><option value="completed">Completed</option><option value="scheduled">Scheduled</option><option value="in_progress">In progress</option><option value="canceled">Canceled</option></select></label><label>Scheduled<input name="scheduledFor" type="date"/></label><label>Completed<input name="completedOn" type="date"/></label><label>Mileage<input name="maintenanceOdometer" type="number" min="0"/></label><label>Cost<input name="cost" type="number" min="0" step=".01"/></label><label>Provider<input name="serviceProvider"/></label><label>Description<textarea name="description"/></label><button className="sv-button">Save maintenance</button></form></details>}<div>{selectedMaintenance.slice(0,8).map(item=><article key={item.id}><span>{label(item.event_type)}</span><strong>{item.title}</strong><small>{date(item.completed_on??item.scheduled_for)} · {label(item.status)}{item.cost!==null?` · $${Number(item.cost).toFixed(2)}`:""}</small></article>)}{!selectedMaintenance.length&&<p>No maintenance recorded.</p>}</div></section>
   </aside>}
  </section>
 </section></main>;
}
