import Link from "next/link";
import {redirect} from "next/navigation";
import {createSupabaseServerClient} from "@/lib/supabaseServer";
import {getSupabaseAdmin} from "@/lib/supabaseAdmin";
import {isServonasPlatformAdmin} from "@/lib/platformAccess";

const title=(value:string|null)=>value?.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase())??"Unknown";

export default async function DomainRequestsAdmin(){
 const session=await createSupabaseServerClient(),{data:{user}}=await session.auth.getUser();
 if(!isServonasPlatformAdmin(user))redirect("/app");
 const admin=getSupabaseAdmin();
 if(!admin)return <main className="admin-entitlements"><div className="workspace-notice error">Private admin access is not configured.</div></main>;
 const {data:requests,error}=await admin.from("business_website_onboarding_states").select("business_id,source,requested_domain,domain_request_status,domain_requested_at").not("requested_domain","is",null).order("domain_requested_at",{ascending:false});
 const businessIds=(requests??[]).map(row=>row.business_id),[{data:businesses},{data:websites}]=businessIds.length?await Promise.all([admin.from("businesses").select("id,name,slug,email,phone").in("id",businessIds),admin.from("business_website_settings").select("business_id,public_slug,custom_domain,domain_status").in("business_id",businessIds)]):[{data:[]},{data:[]}],businessById=new Map((businesses??[]).map(row=>[row.id,row])),websiteByBusiness=new Map((websites??[]).map(row=>[row.business_id,row]));
 return <main className="admin-entitlements domain-request-admin"><header><div><span className="sv-kicker">Internal administration</span><h1>Website domain requests</h1><p>Manual first-year pilot requests. A request does not mean the domain is available or registered.</p></div><div className="crm-header-actions"><Link className="sv-button sv-secondary" href="/app/admin/customers">Customers</Link><Link className="sv-button sv-secondary" href="/app">Workspaces</Link></div></header>{error&&<div className="workspace-notice error">Domain requests could not be loaded. Apply the website-first domain-request migration.</div>}<section className="workspace-panel admin-domain-grid"><div className="admin-domain-grid-row head"><span>Business</span><span>Requested domain</span><span>Status</span><span>Website</span><span>Contact</span><span>Requested</span></div>{(requests??[]).map(request=>{const business=businessById.get(request.business_id),website=websiteByBusiness.get(request.business_id);return <div className="admin-domain-grid-row" key={request.business_id}><span><strong>{business?.name??"Unknown business"}</strong><small>{request.business_id}</small><small>{title(request.source)}</small></span><span><strong>{request.requested_domain}</strong><small>Availability not guaranteed</small></span><span><b className={`estimate-status ${request.domain_request_status}`}>{title(request.domain_request_status)}</b></span><span>{website?.domain_status==="connected"&&website.custom_domain?<a href={`https://${website.custom_domain}`} target="_blank" rel="noreferrer">{website.custom_domain}</a>:<a href={`https://servonas.com/sites/${website?.public_slug??business?.slug}`} target="_blank" rel="noreferrer">servonas.com/sites/{website?.public_slug??business?.slug}</a>}</span><span><a href={`mailto:${business?.email??""}`}>{business?.email??"No email"}</a><small>{business?.phone??"No phone"}</small></span><span>{request.domain_requested_at?new Date(request.domain_requested_at).toLocaleString():"Unknown"}</span></div>})}{!error&&!requests?.length&&<div className="dashboard-empty"><strong>No domain requests yet</strong><p>Qualifying website-first pilot requests will appear here.</p></div>}</section></main>;
}
