import Link from "next/link";
import {WorkspaceNav} from "../../WorkspaceNav";
import {requireWorkspace} from "@/lib/workspace";
import {canManageBusiness} from "@/lib/access";
import {createDiscount,toggleDiscount,updateDiscount} from "./actions";

const money=(v:number|null)=>v==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(v/100);

function Fields({discount,inventory,selected=[]}:{discount?:any;inventory:any[];selected?:string[]}){
 return <div className="discount-form-grid"><label>Name <input required name="name" maxLength={160} defaultValue={discount?.name}/></label><label>Promo code <input required name="code" pattern="[A-Za-z0-9_-]{2,40}" defaultValue={discount?.code}/></label><label>Type <select name="discountType" defaultValue={discount?.discount_type??"percentage"}><option value="percentage">Percentage</option><option value="fixed">Fixed dollar amount</option></select></label><label>Value <input required name="value" type="number" min="0.01" step="0.01" defaultValue={discount?discount.discount_type==="percentage"?discount.discount_value/100:discount.discount_value/100:""}/></label><label>Applies to <select name="appliesTo" defaultValue={discount?.applies_to??"order"}><option value="order">Entire order</option><option value="selected_items">Selected rental items</option></select><small>Choose Selected rental items to limit this offer to specific inventory.</small></label><label>Minimum subtotal <input name="minimumSubtotal" type="number" min="0" step="0.01" defaultValue={discount?.minimum_subtotal_cents!=null?discount.minimum_subtotal_cents/100:""}/></label><label>Starts <input name="startsAt" type="datetime-local" defaultValue={discount?.starts_at?.slice(0,16)}/></label><label>Expires <input name="expiresAt" type="datetime-local" defaultValue={discount?.expires_at?.slice(0,16)}/></label><label>Total usage limit <input name="usageLimit" type="number" min="1" defaultValue={discount?.usage_limit??""}/></label><label>Limit per customer <input name="perCustomerLimit" type="number" min="1" defaultValue={discount?.per_customer_limit??""}/></label><fieldset className="wide discount-item-picker"><legend>Eligible rental items</legend><small>Select these only when “Applies to” is set to “Selected rental items.”</small>{inventory.length?<div>{inventory.map(item=><label key={item.id}><input type="checkbox" name="inventoryItemIds" value={item.id} defaultChecked={selected.includes(item.id)}/><span>{item.name}</span></label>)}</div>:<p>No active rental items are available.</p>}</fieldset><label className="settings-check"><input type="checkbox" name="firstTime" defaultChecked={discount?.first_time_customer_only}/>First-time customers only</label><label className="settings-check"><input type="checkbox" name="active" defaultChecked={discount?.is_active??true}/>Active</label><label className="settings-check"><input type="checkbox" name="announcementEnabled" defaultChecked={discount?.announcement_enabled}/>Show website announcement</label><label className="wide">Announcement text <input name="announcementText" maxLength={240} defaultValue={discount?.announcement_text??""} placeholder="Save 20% with code BOUNCE20"/></label></div>;
}

export default async function DiscountsPage({params,searchParams}:{params:Promise<{businessSlug:string}>;searchParams:Promise<{error?:string;success?:string}>}){
 const {businessSlug}=await params,q=await searchParams,{supabase,business,role}=await requireWorkspace(businessSlug);
 const canEdit=canManageBusiness(role);
 if(!canEdit)return <main className="epic3-shell"><WorkspaceNav slug={businessSlug} name={business.name} industry={business.industry_profile}/><section className="epic3-content marketing-page"><div className="workspace-notice error">Only owners and administrators can view marketing analytics.</div></section></main>;
 const [{data:discounts,error},{data:inventory},{data:targets},{data:redemptions}]=await Promise.all([supabase.from("discounts").select("*").eq("business_id",business.id).order("created_at",{ascending:false}),supabase.from("inventory_items").select("id,name").eq("business_id",business.id).eq("active",true).order("name"),supabase.from("discount_items").select("discount_id,inventory_item_id").eq("business_id",business.id),supabase.from("discount_redemptions").select("discount_id,amount_discounted_cents,status").eq("business_id",business.id).eq("status","redeemed")]);
 const usage=new Map<string,{count:number;saved:number}>();
 for(const row of redemptions??[]){const value=usage.get(row.discount_id)??{count:0,saved:0};value.count++;value.saved+=row.amount_discounted_cents;usage.set(row.discount_id,value);}
 return <main className="epic3-shell"><WorkspaceNav slug={businessSlug} name={business.name} industry={business.industry_profile}/><section className="epic3-content marketing-page discounts-page">
  <header className="marketing-analytics-header"><div><span className="sv-kicker">Marketing</span><h1>Discounts</h1><p>Create and manage promo codes customers can use during checkout.</p>{business.name&&<small>{business.name}</small>}</div></header>
  <nav className="marketing-subnav" aria-label="Marketing sections"><Link href={`/app/${businessSlug}/marketing/funnel`}>Funnel</Link><Link href={`/app/${businessSlug}/marketing/discounts`} aria-current="page">Discounts</Link><Link href={`/app/${businessSlug}/marketing/google-ads`}>Google Ads</Link><Link href={`/app/${businessSlug}/marketing/meta-ads`}>Meta Ads</Link><Link href={`/app/${businessSlug}/marketing/seo`}>Local SEO</Link></nav>
  {q.error&&<div className="workspace-notice error">{q.error}</div>}{q.success&&<div className="workspace-notice success">{q.success}</div>}{error&&<div className="workspace-notice error">Discounts are not installed. Apply the discounts migration.</div>}
  {canEdit&&<details className="workspace-panel discount-editor marketing-discount-editor" open={!discounts?.length}><summary>Create discount</summary><form action={createDiscount.bind(null,businessSlug)}><Fields inventory={inventory??[]}/><button className="sv-button">Create discount</button></form></details>}
  <section className="discount-grid">{discounts?.map(discount=>{const stats=usage.get(discount.id)??{count:0,saved:0},selected=(targets??[]).filter(row=>row.discount_id===discount.id).map(row=>row.inventory_item_id).filter(Boolean);return <article className="workspace-panel" key={discount.id}><header><div><strong>{discount.name}</strong><code>{discount.code}</code></div><span className={`campaign-status ${discount.is_active?"sent":"draft"}`}>{discount.is_active?"Active":"Inactive"}</span></header><dl><div><dt>Offer</dt><dd>{discount.discount_type==="percentage"?`${discount.discount_value/100}%`:money(discount.discount_value)}</dd></div><div><dt>Uses</dt><dd>{stats.count}{discount.usage_limit?` / ${discount.usage_limit}`:""}</dd></div><div><dt>Customer savings</dt><dd>{money(stats.saved)}</dd></div></dl><form action={toggleDiscount.bind(null,businessSlug,discount.id)}><input type="hidden" name="active" value={String(!discount.is_active)}/><button className="sv-button sv-secondary">{discount.is_active?"Deactivate":"Activate"}</button></form><details><summary>Edit</summary><form action={updateDiscount.bind(null,businessSlug,discount.id)}><Fields discount={discount} inventory={inventory??[]} selected={selected}/><button className="sv-button">Save changes</button></form></details></article>})}</section>
 </section></main>;
}
