import { WorkspaceNav } from "../WorkspaceNav";
import { requireWorkspace } from "@/lib/workspace";
import { canManageCustomers } from "@/lib/access";
import { archiveCustomer, createCustomer } from "./actions";
export default async function Customers({params,searchParams}:{params:Promise<{businessSlug:string}>;searchParams:Promise<Record<string,string|undefined>>}){
 const {businessSlug}=await params,q=await searchParams,{supabase,business,role}=await requireWorkspace(businessSlug); const search=(q.q??"").trim();
 let query=supabase.from("customers").select("id,first_name,last_name,email,phone,notes,created_at").eq("business_id",business.id).eq("is_deleted",false).order("created_at",{ascending:false});
 if(search) query=query.or(`first_name.ilike.%${search}%,last_name.ilike.%${search}%,email.ilike.%${search}%,phone.ilike.%${search}%`);
 const {data:customers,error}=await query; if(error) throw new Error(error.message); const canEdit=canManageCustomers(role);
 return <main className="epic3-shell"><WorkspaceNav slug={businessSlug} name={business.name}/><section className="epic3-content"><header className="epic3-header"><div><small>Customer management</small><h1>Customers</h1></div><a href={`/app/${businessSlug}`}>Dashboard</a></header>{q.error&&<div className="workspace-notice error">{q.error}</div>}{q.success&&<div className="workspace-notice success">{q.success}</div>}<form className="customer-search"><input name="q" defaultValue={search} placeholder="Search name, email, or phone"/><button className="sv-button sv-secondary">Search</button></form>{canEdit&&<section className="workspace-panel"><h2>Add customer</h2><form action={createCustomer.bind(null,businessSlug)} className="customer-form"><label>First name<input name="firstName" required/></label><label>Last name<input name="lastName"/></label><label>Email<input name="email" type="email"/></label><label>Phone<input name="phone"/></label><label className="wide">Notes<textarea name="notes" rows={3}/></label><button className="sv-button">Add customer</button></form></section>}<section className="workspace-panel"><div className="panel-title"><h2>Customer list</h2><span>{customers?.length??0} shown</span></div><div className="customer-list">{customers?.length?customers.map(c=><article key={c.id}><div><strong>{c.first_name} {c.last_name}</strong><span>{c.email||"No email"} · {c.phone||"No phone"}</span>{c.notes&&<p>{c.notes}</p>}</div>{canEdit&&<form action={archiveCustomer.bind(null,businessSlug)}><input type="hidden" name="customerId" value={c.id}/><button className="text-button">Archive</button></form>}</article>):<div className="sv-empty"><h3>No customers yet</h3><p>Add the first customer above.</p></div>}</div></section></section></main>
}
