import {randomUUID} from "crypto";
import {cookies} from "next/headers";
import {NextResponse} from "next/server";
import {createSupabaseServerClient} from "@/lib/supabaseServer";
import {getSupabaseAdmin} from "@/lib/supabaseAdmin";
import {canManageBusiness,managementAuthorizationSource} from "@/lib/access";
import {isServonasPlatformAdmin,platformAdminRole} from "@/lib/platformAccess";
import {googleSearchConsoleRedirectUri} from "@/lib/googleSearchConsole";

const appUrl=()=>process.env.NEXT_PUBLIC_APP_URL||"https://servonas.com";
const isPrefetch=(request:Request)=>request.headers.get("next-router-prefetch")==="1"||request.headers.get("purpose")==="prefetch"||request.headers.get("x-middleware-prefetch")==="1";
export async function GET(request:Request,{params}:{params:Promise<{businessSlug:string}>}){const {businessSlug}=await params,prefetch=isPrefetch(request);if(prefetch)return new NextResponse(null,{status:204,headers:{"cache-control":"no-store"}});const db=await createSupabaseServerClient(),{data:{user}}=await db.auth.getUser(),platformAdminAccess=isServonasPlatformAdmin(user),workspaceDb=platformAdminAccess?getSupabaseAdmin():db,{data:business}=workspaceDb?await workspaceDb.from("businesses").select("id,owner_user_id").eq("slug",businessSlug).eq("is_deleted",false).maybeSingle():{data:null},{data:membership}=user&&business&&!platformAdminAccess?await db.from("business_members").select("role").eq("business_id",business.id).eq("user_id",user.id).maybeSingle():{data:null};const role=platformAdminAccess?platformAdminRole:business?.owner_user_id===user?.id?"owner":membership?.role??null,authorized=Boolean(user&&business&&canManageBusiness(role)),clientId=process.env.GOOGLE_SEARCH_CONSOLE_CLIENT_ID?.trim()||process.env.GOOGLE_BUSINESS_CLIENT_ID?.trim(),configured=Boolean(clientId);if(!authorized){console.info("google_search_console_connect_denied",{actorUserId:user?.id??null,businessId:business?.id??null,businessSlug,membershipAuthorized:Boolean(membership&&canManageBusiness(membership.role)),platformAdminAccess,oauthConfigured:configured,prefetch:false,reason:!user?"missing_user":!business?"business_not_found":"role_not_permitted"});return NextResponse.redirect(new URL(`/app/${businessSlug}/marketing/seo?error=${encodeURIComponent("Search Console authorization is not permitted.")}`,appUrl()));}const actor=user!,tenant=business!,oauthClient=clientId!;if(!configured){console.info("google_search_console_connect_denied",{actorUserId:actor.id,businessId:tenant.id,businessSlug,membershipAuthorized:true,platformAdminAccess,oauthConfigured:false,prefetch:false,reason:"oauth_not_configured"});return NextResponse.redirect(new URL(`/app/${businessSlug}/marketing/seo?error=${encodeURIComponent("Google Search Console OAuth is not configured.")}`,appUrl()));}const state=randomUUID();(await cookies()).set("servonas_search_console_oauth",JSON.stringify({state,businessId:tenant.id,businessSlug}),{httpOnly:true,secure:true,sameSite:"lax",maxAge:600,path:"/"});const url=new URL("https://accounts.google.com/o/oauth2/v2/auth");url.searchParams.set("client_id",oauthClient);url.searchParams.set("redirect_uri",googleSearchConsoleRedirectUri());url.searchParams.set("response_type","code");url.searchParams.set("scope","https://www.googleapis.com/auth/webmasters.readonly");url.searchParams.set("access_type","offline");url.searchParams.set("prompt","consent");url.searchParams.set("state",state);console.info("google_search_console_connect_started",{actorUserId:actor.id,businessId:tenant.id,businessSlug,membershipAuthorized:true,authorizationSource:managementAuthorizationSource(role,platformAdminAccess),oauthConfigured:true,prefetch:false});return NextResponse.redirect(url);}
