import Link from "next/link";
import {canManageBusiness} from "@/lib/access";
import {requireWorkspace} from "@/lib/workspace";
import {WorkspaceNav} from "../../WorkspaceNav";
import {summarizeScenario} from "@/lib/territoryScenarios";
import {createScenario,deleteScenario,duplicateScenario,renameScenario,setScenarioStatus} from "./actions";
export default async function ScenarioPlannerPage({params,searchParams}:{params:Promise<{businessSlug:string}>;searchParams:Promise<{scenario?:string;success?:string;error?:string}>}){
 const {businessSlug}=await params,q=await searchParams,{supabase,business,role}=await requireWorkspace(businessSlug),canEdit=canManageBusiness(role);
 const [{data:scenarios,error},{count:liveCount}]=await Promise.all([
  supabase.from("territory_scenarios").select("id,name,description,status,version,source_scenario_id,created_at,updated_at,archived_at").eq("business_id",business.id).is("deleted_at",null).order("updated_at",{ascending:false}),
  supabase.from("workforce_territories").select("id",{count:"exact",head:true}).eq("business_id",business.id).eq("is_active",true),
 ]);
 const selected=(scenarios??[]).find(item=>item.id===(q.scenario??scenarios?.[0]?.id));
 const {data:scenarioTerritories}=selected?await supabase.from("territory_scenario_territories").select("id,name,color,territory_type,change_type,source_territory_id").eq("business_id",business.id).eq("scenario_id",selected.id).order("name"):{data:[]};
 if(error)console.error("Territory scenarios load failed",{businessId:business.id,code:error.code});
 const comparison=summarizeScenario(liveCount??0,scenarioTerritories??[]);
 return <main className="epic3-shell"><WorkspaceNav slug={businessSlug} name={business.name}/><section className="epic3-content scenario-planner">
  <header className="scenario-header"><div><span className="sv-kicker">Territory intelligence</span><h1>Scenario planner</h1><p>Explore operating changes without affecting live customers or territories.</p></div><Link className="sv-button sv-secondary" href={`/app/${businessSlug}/territories`}>Back to territories</Link></header>
  {q.success&&<div className="workspace-notice success">{q.success}</div>}{q.error&&<div className="workspace-notice error">{q.error}</div>}
  {error?<div className="workspace-notice error">Apply the Epic 8.5 Checkpoint 10 migration to use scenario planning.</div>:<div className="scenario-workspace">
   <aside className="scenario-directory"><header><strong>Scenarios</strong><span>{scenarios?.length??0}</span></header>{canEdit&&<form action={createScenario.bind(null,businessSlug)}><input required name="name" maxLength={150} placeholder="Scenario name"/><textarea name="description" maxLength={2000} placeholder="What are you testing?"/><button className="sv-button">Create scenario</button></form>}<nav>{scenarios?.map(item=><Link key={item.id} className={selected?.id===item.id?"active":""} href={`?scenario=${item.id}`}><i className={item.status}/><span><strong>{item.name}</strong><small>{item.status} · {new Intl.DateTimeFormat("en-US",{dateStyle:"medium"}).format(new Date(item.updated_at))}</small></span></Link>)}</nav></aside>
   <section className="scenario-detail">{selected?<><header><div><span>{selected.status} scenario</span><h2>{selected.name}</h2><p>{selected.description||"No planning notes yet."}</p></div><strong>Version {selected.version}</strong></header><div className="scenario-comparison"><article><span>Current</span><strong>{comparison.liveCount}</strong><small>active territories</small></article><b>→</b><article><span>Proposed</span><strong>{comparison.proposedCount}</strong><small>scenario territories</small></article><article><span>Changes</span><strong>{comparison.changedCount}</strong><small>proposed modifications</small></article></div><div className="scenario-territory-list">{scenarioTerritories?.length?scenarioTerritories.map(item=><article key={item.id}><i style={{background:item.color}}/><div><strong>{item.name}</strong><span>{item.territory_type.replaceAll("_"," ")}</span></div><b className={item.change_type}>{item.change_type}</b></article>):<p>No territories were present when this scenario was created.</p>}</div>{canEdit&&<section className="scenario-actions"><form action={renameScenario.bind(null,businessSlug)}><input type="hidden" name="scenarioId" value={selected.id}/><input type="hidden" name="version" value={selected.version}/><label>Name<input required name="name" defaultValue={selected.name} maxLength={150}/></label><label>Planning notes<textarea name="description" defaultValue={selected.description??""} maxLength={2000}/></label><button className="sv-button sv-secondary">Save details</button></form><form action={duplicateScenario.bind(null,businessSlug)}><input type="hidden" name="scenarioId" value={selected.id}/><input required name="name" defaultValue={`${selected.name} copy`} maxLength={150}/><button className="sv-button sv-secondary">Duplicate</button></form><form action={setScenarioStatus.bind(null,businessSlug)}><input type="hidden" name="scenarioId" value={selected.id}/><input type="hidden" name="status" value={selected.status==="archived"?"draft":"archived"}/><button className="sv-button sv-secondary">{selected.status==="archived"?"Restore":"Archive"}</button></form>{selected.status==="archived"&&<form action={deleteScenario.bind(null,businessSlug)}><input type="hidden" name="scenarioId" value={selected.id}/><button className="scenario-delete">Delete archived scenario</button></form>}</section>}</>:<div className="scenario-empty"><strong>No scenario selected</strong><p>Create a scenario to snapshot the current territory plan safely.</p></div>}</section>
  </div>}
 </section></main>;
}
