begin;

-- Apply the same customer/business billing preferences to every completed job,
-- not only jobs generated by recurring service plans.
create or replace function public.create_completed_job_invoice(p_job_id uuid)
returns table(invoice_id uuid,billing_method text,auto_send boolean)
language plpgsql
security definer
set search_path=public
as $$
declare
  j public.jobs%rowtype;
  s public.job_pricing_snapshots%rowtype;
  b public.business_billing_settings%rowtype;
  cb public.customer_billing_profiles%rowtype;
  v_invoice public.invoices%rowtype;
  v_invoice_id uuid;
  v_number text;
  v_value bigint;
  v_prefix text;
  v_digits integer;
  v_method text;
  v_terms integer;
  v_send boolean;
  v_sub bigint;
  v_discount bigint;
  v_fee bigint;
  v_tax bigint;
  v_total bigint;
  v_issue date;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_job_id::text,0));

  select *
  into j
  from public.jobs
  where id=p_job_id
    and not is_deleted
  for update;

  if not found or j.status<>'completed' then
    raise exception 'Only a completed job can be billed'
      using errcode='23514';
  end if;

  insert into public.business_billing_settings(business_id)
  values(j.business_id)
  on conflict(business_id) do nothing;

  select * into b
  from public.business_billing_settings
  where business_id=j.business_id;

  select * into cb
  from public.customer_billing_profiles
  where business_id=j.business_id
    and customer_id=j.customer_id;

  select * into s
  from public.job_pricing_snapshots
  where business_id=j.business_id
    and job_id=j.id;

  if found then
    v_method:=s.billing_method;
    v_terms:=s.payment_terms_days;
    v_send:=s.auto_send_invoice;
  elsif cb.id is not null and not cb.use_business_defaults then
    v_method:=coalesce(cb.billing_method,b.default_billing_method,'invoice_after_completion');
    v_terms:=coalesce(cb.payment_terms_days,b.default_payment_terms_days,30);
    v_send:=coalesce(cb.auto_send_invoice,not coalesce(b.review_before_processing,true));
  else
    v_method:=coalesce(b.default_billing_method,'invoice_after_completion');
    v_terms:=coalesce(b.default_payment_terms_days,30);
    v_send:=not coalesce(b.review_before_processing,true);
  end if;

  select *
  into v_invoice
  from public.invoices
  where business_id=j.business_id
    and job_id=j.id
    and not is_deleted
  for update;

  if found then
    update public.invoices
    set billing_method_snapshot=coalesce(billing_method_snapshot,v_method),
        due_date=coalesce(due_date,issue_date+v_terms)
    where id=v_invoice.id;
    invoice_id:=v_invoice.id;
    billing_method:=coalesce(v_invoice.billing_method_snapshot,v_method);
    auto_send:=v_send;
    return next;
    return;
  end if;

  -- Recurring jobs retain their immutable price snapshot. One-time jobs use
  -- the amounts approved on the job as the immutable completion source.
  if s.id is not null then
    v_sub:=round(s.quantity*s.unit_price_cents);
    v_discount:=least(v_sub,s.discount_cents);
    v_fee:=s.fee_cents;
    v_tax:=round(
      (case when s.taxable then v_sub-v_discount+v_fee else 0 end)
      * s.tax_rate_basis_points/10000.0
    );
  else
    v_sub:=round(coalesce(j.subtotal,0)*100);
    v_discount:=least(v_sub,round(coalesce(j.discount_amount,0)*100));
    v_fee:=0;
    v_tax:=round(coalesce(j.tax_amount,0)*100);
  end if;
  v_total:=greatest(v_sub-v_discount+v_fee+v_tax,0);
  v_issue:=(now() at time zone coalesce(
    (select timezone from public.businesses where id=j.business_id),
    'UTC'
  ))::date;

  v_prefix:=coalesce(b.invoice_prefix,'INV-');
  v_digits:=coalesce(b.invoice_minimum_digits,4);
  update public.business_billing_settings
  set invoice_next_number=invoice_next_number+1,
      updated_at=now()
  where business_id=j.business_id
  returning invoice_next_number-1 into v_value;
  v_number:=v_prefix||lpad(v_value::text,v_digits,'0');

  insert into public.invoices(
    business_id,invoice_number,customer_id,service_location_id,job_id,
    service_plan_id,job_pricing_snapshot_id,billing_method_snapshot,status,
    title,currency,subtotal_cents,discount_total_cents,tax_total_cents,
    fee_total_cents,grand_total_cents,balance_due_cents,issue_date,due_date,
    source_key,created_by,updated_by
  )
  values(
    j.business_id,v_number,j.customer_id,j.service_location_id,j.id,
    s.service_plan_id,s.id,v_method,'draft',
    coalesce(s.service_description,j.title,'Service'),'USD',
    v_sub,v_discount,v_tax,v_fee,v_total,v_total,v_issue,v_issue+v_terms,
    j.id,auth.uid(),auth.uid()
  )
  returning id into v_invoice_id;

  insert into public.invoice_line_items(
    business_id,invoice_id,service_id,name_snapshot,description_snapshot,
    quantity,unit_type_snapshot,unit_price_cents,discount_type,discount_value,
    line_discount_cents,is_taxable,tax_rate_basis_points,line_subtotal_cents,
    tax_amount_cents,line_total_cents
  )
  values(
    j.business_id,v_invoice_id,coalesce(s.service_id,j.service_id),
    coalesce(s.service_description,j.title,'Service'),j.description,
    coalesce(s.quantity,1),'visit',
    case when s.id is not null then s.unit_price_cents else v_sub end,
    case when v_discount>0 then 'fixed' else 'none' end,
    v_discount,v_discount,coalesce(s.taxable,v_tax>0),
    coalesce(s.tax_rate_basis_points,0),v_sub,v_tax,v_total-v_fee
  );

  insert into public.invoice_fees(
    business_id,invoice_id,name_snapshot,amount_cents,sort_order
  )
  select j.business_id,v_invoice_id,'Service fee',v_fee,0
  where v_fee>0;

  insert into public.invoice_events(
    business_id,invoice_id,event_type,actor_user_id,metadata
  )
  values(
    j.business_id,v_invoice_id,'created',auth.uid(),
    jsonb_build_object(
      'source','completed_job',
      'pricing_source',case when s.id is null then 'job' else 'service_plan_snapshot' end
    )
  );

  insert into public.billing_audit_events(
    business_id,customer_id,service_plan_id,job_id,invoice_id,event_type,
    actor_user_id,metadata
  )
  values(
    j.business_id,j.customer_id,s.service_plan_id,j.id,v_invoice_id,
    'completed_job_invoice_created',auth.uid(),
    jsonb_build_object('billing_method',v_method,'auto_send',v_send)
  );

  invoice_id:=v_invoice_id;
  billing_method:=v_method;
  auto_send:=v_send;
  return next;
end
$$;

revoke all on function public.create_completed_job_invoice(uuid) from public;
grant execute on function public.create_completed_job_invoice(uuid)
  to authenticated,service_role;

comment on function public.create_completed_job_invoice(uuid) is
  'Idempotently creates or resolves an invoice for any completed job using the effective service-plan, customer, or business billing preferences.';

commit;

notify pgrst, 'reload schema';
