import {getSupabaseAdmin} from "@/lib/supabaseAdmin";
import {stripeClient} from "@/lib/stripeConnect";
import type Stripe from "stripe";
import {sendTenantTwilioMessage} from "@/lib/twilio/messageUsage";
import {rentalEmailDeliveryIsLive} from "@/lib/emailDeliveryMode";
import {createBookingPaymentRequestToken} from "@/lib/bookingManage/tokens";
import {resolveCurrentSmsConsent} from "@/lib/smsConsent";

const first=<T,>(value:T|T[]|null)=>Array.isArray(value)?value[0]??null:value;
const money=(cents:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(cents/100);
export const rentalPaymentRequestSmsBody=(businessName:string,bookingNumber:number,depositCents:number,url:string)=>`${businessName}: your rental booking #${bookingNumber} is being held while you pay the required ${money(depositCents)} deposit. Pay securely here: ${url} Reply STOP to opt out.`;
export type RentalPaymentRequestResult={url:string;expiresAt:string;phone:string|null;paymentLinkCreated:true;smsAttempted:boolean;smsAccepted:boolean;smsMessageSid:string|null;smsStatus:"accepted"|"skipped"|"failed";smsFailureReason:string|null;emailAttempted:boolean;emailAccepted:boolean;emailFailureReason:string|null;smsSent:boolean;emailSent:boolean};

/** Creates a customer-facing Checkout Session. Staff never receive card details. */
export async function createRentalDepositPaymentRequest(bookingId:string){
 const db=getSupabaseAdmin();if(!db)throw new Error("Supabase is unavailable.");
 const {data:booking,error}=await db.from("bookings").select("id,business_id,job_id,booking_number,status,deposit_cents,amount_paid_cents,total_cents,stripe_checkout_session_id,payment_request_expires_at,sms_consent,customers(email,phone_normalized,sms_consent_status),businesses(name,email)").eq("id",bookingId).maybeSingle();
 if(error||!booking||!booking.job_id)throw new Error("Booking details are unavailable.");
 if(booking.status!=="pending_payment")throw new Error("Only a booking awaiting its deposit can receive this payment request.");
 const depositCents=Math.max(0,Number(booking.deposit_cents)-Number(booking.amount_paid_cents??0));if(!depositCents)throw new Error("This booking does not have a deposit due.");
 const {data:account}=await db.from("business_payment_accounts").select("provider_account_id,charges_enabled,onboarding_status,payouts_enabled").eq("business_id",booking.business_id).eq("provider","stripe").maybeSingle();
 if(!account?.provider_account_id||!account.charges_enabled||account.onboarding_status!=="complete"||!account.payouts_enabled)throw new Error("Stripe payments are not available for this business.");
 const site=(process.env.NEXT_PUBLIC_SITE_URL||"http://localhost:3000").replace(/\/$/,"");const customer=first(booking.customers),business=first(booking.businesses),stripe=stripeClient();if(booking.payment_request_expires_at&&new Date(booking.payment_request_expires_at)<=new Date())throw new Error("This payment request has expired.");const deadline=booking.payment_request_expires_at?new Date(booking.payment_request_expires_at):new Date(Date.now()+24*60*60*1000);let session:Stripe.Checkout.Session|null=null;
 if(booking.stripe_checkout_session_id)try{const existing=await stripe.checkout.sessions.retrieve(booking.stripe_checkout_session_id,{}, {stripeAccount:account.provider_account_id});if(existing.status==="open"&&existing.url&&Number(existing.expires_at)*1000>Date.now())session=existing;}catch{/* Create a replacement only when the previous session cannot be used. */}
 if(!session)session=await stripe.checkout.sessions.create({mode:"payment",customer_email:customer?.email||undefined,payment_method_types:["card"],line_items:[{quantity:1,price_data:{currency:"usd",unit_amount:depositCents,product_data:{name:`Required rental deposit · Booking #${booking.booking_number}`}}}],success_url:`${site}/success?session_id={CHECKOUT_SESSION_ID}`,cancel_url:`${site}/manage-booking`,expires_at:Math.floor(Date.now()/1000)+30*60,metadata:{booking_id:booking.id,business_id:booking.business_id,booking_number:String(booking.booking_number),payment_kind:"rental_deposit_request",deposit_cents:String(depositCents),total_cents:String(booking.total_cents),payment_request_expires_at:deadline.toISOString()}},{stripeAccount:account.provider_account_id});
 if(!session.url)throw new Error("Stripe did not return a payment link.");const {error:updateError}=await db.from("bookings").update({stripe_checkout_session_id:session.id,payment_request_expires_at:deadline.toISOString()}).eq("id",booking.id).eq("business_id",booking.business_id);if(updateError)throw new Error("The payment request could not be saved.");const token=await createBookingPaymentRequestToken(booking.id,booking.business_id,deadline),paymentUrl=`${site}/manage-booking/${token}`;
 const {data:phoneConsent}=customer?.phone_normalized?await db.from("customer_sms_consents").select("status").eq("business_id",booking.business_id).eq("phone_e164",customer.phone_normalized).maybeSingle():{data:null};
 // Transactional booking messages use the current customer consent ledger. A later
 // booking record must not erase an existing explicit consent; an opt-out wins.
 const consent=resolveCurrentSmsConsent({phone:customer?.phone_normalized,customerStatus:customer?.sms_consent_status,ledgerStatus:phoneConsent?.status}),eventKey=`deposit-request:${session.id}:${Date.now()}`,smsAllowed=consent.canSendSms;let smsAttempted=false,smsAccepted=false,smsMessageSid:string|null=null,smsStatus:"accepted"|"skipped"|"failed"="skipped",smsFailureReason:string|null=consent.reason==="phone_missing"?"No valid SMS phone number.":consent.reason==="opted_out"?"Customer has opted out of SMS.":consent.reason==="ledger_not_express"?"Current explicit SMS consent is not recorded in the consent ledger.":consent.reason==="customer_not_express"?"Current explicit SMS consent is incomplete on the customer record.":null,emailAttempted=false,emailAccepted=false,emailFailureReason:string|null=customer?.email?null:"No customer email address.";
 if(smsAllowed){smsFailureReason=null;const {data:event,error:eventError}=await db.from("job_communication_events").insert({job_id:booking.job_id,channel:"sms",template_key:"payment_request",event_key:eventKey,recipient_phone:customer!.phone_normalized,status:"queued"}).select("id").single();if(eventError||!event){smsStatus="failed";smsFailureReason="SMS communication could not be recorded.";}else{smsAttempted=true;try{const sent=await sendTenantTwilioMessage({businessId:booking.business_id,to:customer!.phone_normalized!,body:rentalPaymentRequestSmsBody(business?.name||"Your rental business",Number(booking.booking_number),depositCents,paymentUrl),sourceType:"rental_payment_request",sourceId:event.id});smsAccepted=true;smsStatus="accepted";smsMessageSid=sent.sid;await db.from("job_communication_events").update({status:"sent",provider_message_id:sent.sid,sent_at:new Date().toISOString()}).eq("id",event.id);}catch(sendError){const acceptedSid=typeof sendError==="object"&&sendError!==null&&"messageSid" in sendError&&typeof (sendError as {messageSid?:unknown}).messageSid==="string"?(sendError as {messageSid:string}).messageSid:null;smsMessageSid=acceptedSid;if(acceptedSid){smsAccepted=true;smsStatus="accepted";smsFailureReason="Twilio accepted the message; delivery status will reconcile shortly.";await db.from("job_communication_events").update({status:"sent",provider_message_id:acceptedSid,sent_at:new Date().toISOString()}).eq("id",event.id);}else{smsStatus="failed";smsFailureReason=(sendError instanceof Error?sendError.message:"SMS send failed").slice(0,1000);await db.from("job_communication_events").update({status:"failed",error_message:smsFailureReason}).eq("id",event.id);}}}}
 if(customer?.email){const {data:event,error:eventError}=await db.from("job_communication_events").insert({job_id:booking.job_id,channel:"email",template_key:"payment_request",event_key:eventKey,recipient_email:customer.email,status:rentalEmailDeliveryIsLive()?"queued":"stubbed"}).select("id").single();if(eventError||!event)emailFailureReason="Email communication could not be recorded.";else if(rentalEmailDeliveryIsLive()&&process.env.RESEND_API_KEY&&process.env.EMAIL_FROM)try{emailAttempted=true;const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({from:process.env.EMAIL_FROM,to:[customer.email],reply_to:business?.email||undefined,subject:`Pay your deposit for booking #${booking.booking_number}`,text:`${business?.name||"Your rental business"}: pay your required ${money(depositCents)} deposit securely: ${paymentUrl}`})});if(!response.ok)throw new Error(`Email provider HTTP ${response.status}`);await db.from("job_communication_events").update({status:"sent",sent_at:new Date().toISOString()}).eq("id",event.id);emailAccepted=true;emailFailureReason=null;}catch(sendError){emailFailureReason=(sendError instanceof Error?sendError.message:"Email send failed").slice(0,1000);await db.from("job_communication_events").update({status:"failed",error_message:emailFailureReason}).eq("id",event.id);}else emailFailureReason="Email delivery is not configured.";}
 return {url:paymentUrl,expiresAt:deadline.toISOString(),phone:customer?.phone_normalized??null,paymentLinkCreated:true,smsAttempted,smsAccepted,smsMessageSid,smsStatus,smsFailureReason,emailAttempted,emailAccepted,emailFailureReason,smsSent:smsAccepted,emailSent:emailAccepted} satisfies RentalPaymentRequestResult;
}
