import { WorkspaceNav } from "../WorkspaceNav";
import { requireWorkspace } from "@/lib/workspace";
import { canManageBusiness } from "@/lib/access";
import { connectStripe,disconnectStripe,refreshStripeStatus,updateBusinessSettings } from "./actions";
import { stripePaymentsReady } from "@/lib/stripeConnect";
export default async function Settings({params,searchParams}:{params:Promise<{businessSlug:string}>;searchParams:Promise<Record<string,string|undefined>>}){
 const {businessSlug}=await params,q=await searchParams,{supabase,business,role}=await requireWorkspace(businessSlug),editable=canManageBusiness(role);
 const {data:paymentAccount,error:paymentAccountError}=await supabase.from("business_payment_accounts").select("provider_account_id,onboarding_status,charges_enabled,payouts_enabled,details_submitted,requirements_currently_due,requirements_eventually_due,requirements_past_due,disabled_reason,last_provider_sync_at,last_provider_error,disconnected_at").eq("business_id",business.id).eq("provider","stripe").maybeSingle();
 const restrictions=[...(paymentAccount?.requirements_past_due??[]),...(paymentAccount?.requirements_currently_due??[])];
 const ready=Boolean(paymentAccount?.provider_account_id&&stripePaymentsReady(paymentAccount));
 return <main className="epic3-shell"><WorkspaceNav slug={businessSlug} name={business.name}/><section className="epic3-content"><header className="epic3-header"><div><small>Workspace configuration</small><h1>Business settings</h1></div></header>{q.error&&<div className="workspace-notice error">{q.error}</div>}{q.success&&<div className="workspace-notice success">{q.success}</div>}<section className="workspace-panel"><form action={updateBusinessSettings.bind(null,businessSlug)} className="settings-form"><fieldset disabled={!editable}><label>Business name<input name="name" defaultValue={business.name}/></label><label>Business email<input name="email" type="email" defaultValue={business.email??""}/></label><label>Phone<input name="phone" defaultValue={business.phone??""}/></label><label>Website<input name="websiteUrl" type="url" defaultValue={business.website_url??""}/></label><label>Time zone<select name="timezone" defaultValue={business.timezone??"America/Phoenix"}><option>America/Phoenix</option><option>America/Denver</option><option>America/Chicago</option><option>America/New_York</option><option>America/Los_Angeles</option></select></label><label>Brand color<input name="primaryColor" type="color" defaultValue={business.primary_color??"#2563eb"}/></label><label>Address<input name="addressLine1" defaultValue={business.address_line1??""}/></label><label>City<input name="city" defaultValue={business.city??""}/></label><label>State<input name="state" defaultValue={business.state??""}/></label><label>Postal code<input name="postalCode" defaultValue={business.postal_code??""}/></label><label>Default tax rate (%)<input name="taxRate" type="number" min="0" max="100" step="0.01" defaultValue={business.tax_rate??0}/></label>{editable&&<button className="sv-button">Save settings</button>}</fieldset></form>{!editable&&<p>Only owners and admins can edit these settings.</p>}</section>
 <section className="workspace-panel" id="payments"><div className="panel-title"><div><span className="sv-kicker">Payments</span><h2>Stripe Connect</h2><p>Connect a tenant-specific Express account for future invoice payments and payouts.</p></div><span className={`estimate-status ${ready?"paid":paymentAccount?.onboarding_status||"draft"}`}>{ready?"ready":(paymentAccount?.onboarding_status||"not connected").replaceAll("_"," ")}</span></div>
  {paymentAccountError&&<div className="workspace-notice error">Stripe account status could not be loaded. Apply the Checkpoint 8 migration.</div>}
  {!paymentAccount?.provider_account_id?<div className="payment-connect-empty"><p>Payment collection is unavailable until Stripe onboarding is complete.</p>{editable&&<form action={connectStripe.bind(null,businessSlug)}><button className="sv-button">Connect Stripe</button></form>}</div>:<div className="payment-account-status">
   <dl><div><dt>Charges</dt><dd>{paymentAccount.charges_enabled?"Enabled":"Unavailable"}</dd></div><div><dt>Payouts</dt><dd>{paymentAccount.payouts_enabled?"Enabled":"Unavailable"}</dd></div><div><dt>Details submitted</dt><dd>{paymentAccount.details_submitted?"Yes":"No"}</dd></div><div><dt>Last provider sync</dt><dd>{paymentAccount.last_provider_sync_at?new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short",timeZone:business.timezone}).format(new Date(paymentAccount.last_provider_sync_at)):"Never"}</dd></div></dl>
   {ready?<div className="workspace-notice success">Stripe onboarding is complete. Payment collection remains disabled until the Checkpoint 9 invoice-payment flow is enabled.</div>:<div className="workspace-notice error"><strong>Payments unavailable</strong><p>{paymentAccount.disabled_reason?paymentAccount.disabled_reason.replaceAll("_"," "):"Stripe onboarding or verification is incomplete."}</p>{restrictions.length>0&&<ul>{[...new Set(restrictions)].map((item:string)=><li key={item}>{item.replaceAll("."," → ").replaceAll("_"," ")}</li>)}</ul>}</div>}
   {paymentAccount.last_provider_error&&<details><summary>Latest provider diagnostic</summary><p>{paymentAccount.last_provider_error}</p></details>}
   {editable&&<div className="crm-header-actions"><form action={connectStripe.bind(null,businessSlug)}><button className="sv-button">{ready?"Update Stripe details":"Resume onboarding"}</button></form><form action={refreshStripeStatus.bind(null,businessSlug)}><button className="sv-button sv-secondary">Refresh status</button></form></div>}
   {editable&&<details className="payment-disconnect"><summary>Disconnect Stripe</summary><p>Disconnecting disables future payment collection. Existing Stripe records and Servonas payment history are retained.</p><form action={disconnectStripe.bind(null,businessSlug)}><label>Type DISCONNECT<input required name="confirmation" pattern="DISCONNECT" autoComplete="off"/></label><button className="sv-button sv-danger">Disconnect Stripe</button></form></details>}
  </div>}
 </section></section></main>
}
