import Link from "next/link";
import {redirect} from "next/navigation";
import {createSupabaseServerClient} from "@/lib/supabaseServer";
import {isServonasPlatformAdmin} from "@/lib/platformAccess";
import {getAdminUsageReport,type AdminUsageView} from "@/lib/admin/usageReporting";

const periodPattern=/^\d{4}-(0[1-9]|1[0-2])$/;
const money=(value:number,currency="USD")=>new Intl.NumberFormat("en-US",{style:"currency",currency,minimumFractionDigits:value>0&&value<0.01?4:2,maximumFractionDigits:value>0&&value<0.01?6:2}).format(value);
const number=(value:number)=>new Intl.NumberFormat("en-US").format(value);
const viewOf=(value:string|undefined):AdminUsageView=>value==="twilio"||value==="ai"?value:"overview";
const attention=(view:AdminUsageView,row:{twilio:{unfinalized:number};ai:{unpriced:number}})=>view==="twilio"?row.twilio.unfinalized:view==="ai"?row.ai.unpriced:row.twilio.unfinalized+row.ai.unpriced;

export default async function UsageAdmin({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const query=await searchParams,session=await createSupabaseServerClient(),{data:{user}}=await session.auth.getUser();if(!isServonasPlatformAdmin(user))redirect("/app");
 const period=periodPattern.test(query.period??"")?query.period!:new Date().toISOString().slice(0,7),view=viewOf(query.view),report=await getAdminUsageReport(period),rows=report.businesses;
 return <main className="admin-entitlements usage-admin"><header><div><span className="sv-kicker">Internal administration</span><h1>Customer usage &amp; spend</h1><p>Provider cost by Servonas business. These totals do not create customer charges.</p></div><div className="crm-header-actions"><Link className="sv-button sv-secondary" href="/app/admin/ai">AI access</Link><Link className="sv-button sv-secondary" href="/app/admin/twilio">Twilio setup</Link><Link className="sv-button sv-secondary" href="/app">Workspaces</Link></div></header>
  <section className="usage-service-links" aria-label="Usage provider views"><Link className={view==="overview"?"active":""} href={`/app/admin/usage?period=${period}`}><span>▦</span><div><strong>All usage</strong><small>Twilio and AI together</small></div></Link><Link className={view==="twilio"?"active":""} href={`/app/admin/usage?view=twilio&period=${period}`}><span>✆</span><div><strong>Twilio</strong><small>Messages, segments, and cost</small></div></Link><Link className={view==="ai"?"active":""} href={`/app/admin/usage?view=ai&period=${period}`}><span>✦</span><div><strong>AI</strong><small>Requests, tokens, and cost</small></div></Link></section>
  <section className="workspace-panel usage-period-panel"><form method="get"><input type="hidden" name="view" value={view}/><label>Billing month<input type="month" name="period" defaultValue={period}/></label><button className="sv-button">View month</button></form><p>Costs are provider spend, not customer invoices or overage charges.</p></section>
  <section className="usage-summary-grid">{view!=="ai"&&<><article><span>Twilio spend</span><strong>{money(report.totals.twilioCost)}</strong><small>{number(report.totals.twilioMessages)} messages · {number(report.totals.twilioSegments)} outbound SMS segments</small></article><article><span>Pending Twilio cost</span><strong>{number(report.totals.twilioUnfinalized)}</strong><small>Messages waiting for final provider pricing</small></article></>}{view!=="twilio"&&<><article><span>AI spend</span><strong>{money(report.totals.aiCost)}</strong><small>{number(report.totals.aiRequests)} requests · {number(report.totals.aiTokens)} tokens</small></article><article><span>Unpriced AI requests</span><strong>{number(report.totals.aiUnpriced)}</strong><small>Requests using a model without a configured rate</small></article></>}</section>
  <section className="workspace-panel usage-table-panel"><div className="panel-title"><div><h2>{view==="overview"?"Spend by customer":view==="twilio"?"Twilio spend by customer":"AI spend by customer"}</h2><p>{new Date(`${period}-01T12:00:00Z`).toLocaleDateString("en-US",{month:"long",year:"numeric",timeZone:"UTC"})}</p></div><span>{rows.length} customers</span></div><div className="usage-table"><div className="usage-table-head"><span>Customer</span>{view!=="ai"&&<><span>Twilio usage</span><span>Twilio cost</span></>}{view!=="twilio"&&<><span>AI usage</span><span>AI cost</span></>}<span>Needs attention</span></div>{rows.map(row=><div key={row.id}><span><strong>{row.name}</strong><small>{row.slug}</small></span>{view!=="ai"&&<><span><strong>{number(row.twilio.segments)} segments</strong><small>{number(row.twilio.messageCount)} messages</small></span><span><strong>{money(row.twilio.cost,row.twilio.currency||"USD")}</strong></span></>}{view!=="twilio"&&<><span><strong>{number(row.ai.totalTokens)} tokens</strong><small>{number(row.ai.requestCount)} requests</small></span><span><strong>{money(row.ai.cost)}</strong></span></>}<span>{attention(view,row)?<><strong>{number(attention(view,row))} pending</strong><small>{view!=="ai"&&row.twilio.unfinalized?`${number(row.twilio.unfinalized)} Twilio`:""}{view==="overview"&&row.twilio.unfinalized&&row.ai.unpriced?" · ":""}{view!=="twilio"&&row.ai.unpriced?`${number(row.ai.unpriced)} AI`:""}</small></>:<small className="usage-complete">Up to date</small>}</span></div>)}{!rows.length&&<div className="usage-empty">No {view==="overview"?"provider":view} usage was recorded for this month.</div>}</div></section>
 </main>;
}
